#include "game/ui/pc_settings.h"

#include <array>
#include <utility>
#include "engine/core/localized_text.h"

namespace pt::game {
namespace {

constexpr int kLanguages = 7;

struct Entry {
    std::string_view key;
    std::array<std::string_view, kLanguages> text;

};

// English; the other languages are in engine/core/<language>_text.h (localized::Menu)
constexpr Entry kTexts[] = {
    {"pc_microphone_trigger_assign", {"Assign {input} for the microphone trigger"}},
    {"pc_note_microphone_trigger", {"Optional input alternative to the microphone. Keyboard and both controller triggers activate it only while the game is listening."}},
    {"pc_note_microphone_test", {"Tests your microphone and recognition result."}},
    {"pc_fps_limit", {"Frame limit"}},
    {"pc_unlimited", {"Unlimited"}},
    {"pc_note_fps_limit", {"Caps rendered frames. Menus remain capped at 60 FPS. V-sync may impose a lower limit."}},
    {"pc_hdr", {"Native HDR"}},
    {"pc_note_hdr_restart", {"Applies after restarting. Requires HDR enabled on a compatible display; otherwise uses SDR."}},
    {"pc_surround", {"Surround output"}},
    {"pc_note_surround", {"Uses the output deviceâ€™s 5.1 or 7.1 layout after restarting. Stereo devices stay stereo."}},
    {"pc_rumble_profile", {"Rumble mode"}},
    {"pc_rumble_original", {"Original"}},
    {"pc_rumble_enhanced", {"Enhanced"}},
    {"pc_note_rumble_profile", {"Original preserves the game’s standard motor vibration. Enhanced adds supported trigger vibration and, on supported USB DualSense controllers on Windows, filtered cry haptics derived from Lisa’s crying. The master rumble setting disables both; controller-speaker audio remains independent."}},
    {"pc_controller_speaker", {"Controller speaker"}},
    {"pc_note_controller_speaker", {"Plays Lisa’s authored cry voices through supported Sony controller speakers. Windows requires USB; unsupported devices and Bluetooth stay silent. Independent of haptics; off by default."}},
    {"pc_controller_speaker_volume", {"Controller speaker volume"}},
    {"pc_note_controller_speaker_volume", {"Changes only the controller speaker output. It does not change game audio or DualSense haptic strength. Available for supported wired Sony controllers on Windows."}},
    {"pc_vr_height", {"Height adjustment"}},
    {"pc_note_vr_height", {"Moves your tracked viewpoint up or down without changing the playerâ€™s game position."}},
    {"pc_vr_world_scale", {"World scale"}},
    {"pc_note_vr_world_scale", {"Scales tracked head, eye and controller movement from 50% to 200%; larger values make the world feel smaller. Default is 100%."}},
    {"pc_photo_focal_length", {"Focal length"}},
    {"pc_note_photo_focal_length", {"Lens focal length in millimetres. Focus blur uses the same lens and sensor as the camera."}},
    {"pc_photo_aspect", {"Aspect ratio"}},
    {"pc_note_photo_aspect", {"Frames a centred crop of the photograph."}},
    {"pc_photo_resolution", {"Photo resolution"}},
    {"pc_note_photo_resolution", {"Native saves the framed pixels. 4K renders the scene again with a 3840-pixel long edge."}},
    {"pc_photo_resolution_native", {"Native"}},
    {"pc_photo_resolution_4k", {"4K"}},
    {"pc_photo_save_failed", {"Photo could not be saved. See pt.log."}},
    {"pc_photo_filter", {"Colour filter"}},
    {"pc_note_photo_filter", {"Applies only to the photo view and saved photograph."}},
    {"pc_photo_filter_bw", {"Black and white"}},
    {"pc_photo_filter_warm", {"Warm"}},
    {"pc_photo_filter_cool", {"Cool"}},
    {"pc_photo_filter_muted", {"Muted"}},

    {"pc_loop_browser", {"Loop Browser"}},
    {"pc_note_loop_browser_entry", {"Start any loop without replacing your save."}},
    {"pc_loop_choose", {"Choose a loop"}},
    {"pc_loop_preview", {"Preview"}},
    {"pc_loop_start_hint", {"Enter / X / A: start loop"}},
    {"pc_loop_f000", {"Start room: the opening"}},
    {"pc_loop_f010", {"Loop 1: the radio"}},
    {"pc_loop_f005", {"Loop 2: the lobby door opens"}},
    {"pc_loop_f020", {"Loop 3: crying in the bathroom"}},
    {"pc_loop_f030", {"Loop 4: the bathroom door"}},
    {"pc_loop_f040", {"Loop 5: Lisa down the hall"}},
    {"pc_loop_f060", {"Loop 6: the bathroom, the flashlight"}},
    {"pc_loop_f050a", {"Loop 7: Lisa follows you"}},
    {"pc_loop_f050b", {"Loop 8: the X mark photo"}},
    {"pc_loop_f070", {"Loop 9: the window breaks"}},
    {"pc_loop_f080", {"Loop 10: the bleeding fridge"}},
    {"pc_loop_f090", {"Loop 11: HELLO"}},
    {"pc_loop_f100", {"Loop 12: the red hallway"}},
    {"pc_loop_f110", {"Loop 13: the maze and the peephole"}},
    {"pc_loop_f120", {"Loop 14: 204863, the bug screen"}},
    {"pc_loop_f160", {"Loop 15: the final loop"}},
    {"pc_loop_ending", {"Ending cinematic and credits"}},
    {"pc_loop_street", {"Street walk (after the ending)"}},
    {"pc_note_loop_opening", {"Starts the opening in the start room, as a new game does. Your save is kept."}},
    {"pc_note_loop_hallway", {"Starts in the start room just before this loop, with the puzzles before it solved. Walk through the door. Your save is kept; saving resumes at the next checkpoint."}},
    {"pc_note_loop_ending", {"Plays the ending cinematic and the credits, then offers the street walk. Your save is kept."}},
    {"pc_note_loop_street", {"Puts you in the street from the ending, in first person. Leave it from Extras. Your save is kept."}},
    {"pc_note_loop_locked", {"Locked. Finish the game once; then every loop you reached in play opens."}},
    {"pc_note_loop_browser_locked", {"Finish the game once to unlock the loop browser."}},
    {"pc_street_title", {"The street"}},
    {"pc_street_question", {"Explore the street?"}},
    {"pc_street_walk", {"Yes, walk the street"}},
    {"pc_credit_version", {"P.T. PC Port {1} by LoreanXavier"}},
    {"pc_update_available", {"Version {1} is available (this is {2})"}},
    {"pc_credits_by", {"by LoreanXavier"}},
    {"pc_credits_dlss", {"This game uses NVIDIA DLSS."}},
    {"pc_credits_licenses", {"The full license texts are in the licenses folder next to pt.exe."}},
    {"pc_credits_konami", {"P.T. belongs to Konami Digital Entertainment and Kojima Productions."}},
    {"pc_credits_fan", {"This port is an unofficial fan project, not affiliated with or endorsed by Konami, NVIDIA, AMD or Intel."}},
    {"pc_note_street_walk", {"Walk the street from the ending in first person. Leave it from Extras."}},
    {"pc_street_restart", {"No, return to the start"}},
    {"pc_note_street_restart", {"Restart from the start room, as the original does after the credits."}},
    {"pc_street_leave", {"Leave the street"}},
    {"pc_note_street_leave", {"Ends the street walk and returns to the start room."}},
    {"pc_street_return", {"Return to the house"}},
    {"pc_street_return_confirm", {"Return to the house?"}},
    {"pc_speedrun", {"Speedrun timer"}},
    {"pc_note_speedrun", {"An on-screen timer with a split at every loop and a results screen after the credits. Real time counts everything; game time leaves out pauses and loads. Not in the original."}},
    {"pc_speedrun_real_time", {"Real time"}},
    {"pc_speedrun_game_time", {"Game time"}},
    {"pc_livesplit", {"LiveSplit server"}},
    {"pc_note_livesplit", {"Sends the timer's start, splits and game time to LiveSplit (Control > Start TCP Server, port {1}). The host and port are in pt.ini."}},
    {"pc_speedrun_results", {"RUN COMPLETE"}},
    {"pc_speedrun_run", {"Run"}},
    {"pc_speedrun_splits", {"Splits"}},
    {"pc_speedrun_menu", {"Return to menu"}},
    {"pc_note_speedrun_menu", {"Restarts from the start as the original does after the ending, with the options screen first. The next run starts when you get control."}},
    {"pc_speedrun_outside", {"Explore outside"}},
    {"pc_note_speedrun_outside", {"Walk the street from the ending. Return to the house from the pause menu."}},
    {"pc_note_speedrun_real", {"Wall clock from getting control to the ending: pauses, loads and cutscenes included."}},
    {"pc_note_speedrun_game", {"Unpaused play only: the pause menu and the stage loads after a game over are left out."}},
    {"pc_speedrun_best", {"Personal best"}},
    {"pc_note_speedrun_best", {"Previous best: {1}. Records are in speedrun.ini, speedrun_history.txt and speedrun_pb.lss (LiveSplit) in the user folder."}},
    {"pc_speedrun_new_best", {"New best!"}},
    {"pc_speedrun_partial", {"Not from the start"}},
    {"pc_speedrun_start_room", {"Start room"}},
    {"pc_speedrun_loop", {"Loop {1}"}},
    {"pc_loop_lock", {"Lock the loop browser"}},
    {"pc_note_loop_lock", {"Locks every loop browser entry again, as before your first finished game. Your save is not changed."}},
    {"pc_extras", {"Extras"}},
    {"pc_note_extras", {"Loop browser, free camera and photo mode."}},
    {"pc_freecam", {"Free camera"}},
    {"pc_note_freecam", {"Fly the camera away from the player (F6). Space / Ctrl or the triggers rise and sink, Shift or L3 is faster. Esc ends it."}},
    {"pc_photo_mode", {"Photo mode"}},
    {"pc_note_photo_mode", {"Pause and frame a shot with the free camera (F7). P or Square saves to Pictures/PT Photos, H or Triangle hides the panel."}},
    {"pc_third_person", {"Third person (experimental)"}},
    {"pc_fast_walk", {"Fast walk"}},
    {"pc_note_fast_walk", {"Hold either Shift key or the controller's bottom face button (Xbox A / PlayStation X) to walk 50% faster. Release for normal speed. Interactions and puzzle timers keep their original behavior."}},
    {"pc_note_third_person", {"Experimental, not in the original: the camera follows the player over the shoulder. The zoom and the cutscenes return to first person; events play out as in first person."}},
    {"pc_extras_start", {"Start"}},
    {"pc_vr", {"VR (experimental)"}},
    {"pc_note_vr", {"Play in a VR headset through OpenXR. Experimental: not tested on real hardware."}},
    {"pc_vr_mode", {"VR mode"}},
    {"pc_note_vr_mode", {"Untested on real hardware. Needs an OpenXR runtime and a headset. Applies at the next start; without a headset the game starts as usual."}},
    {"pc_vr_flashlight", {"Flashlight"}},
    {"pc_note_vr_flashlight", {"The flashlight follows your head, as in the original, or the controller in your hand."}},
    {"pc_vr_head", {"Head"}},
    {"pc_vr_controller", {"Controller"}},
    {"pc_vr_turn", {"Turning"}},
    {"pc_note_vr_turn", {"The right stick turns in steps or smoothly. Steps are easier on the stomach."}},
    {"pc_vr_snap", {"Steps"}},
    {"pc_vr_smooth", {"Smooth"}},
    {"pc_photo_title", {"PHOTO MODE"}},
    {"pc_photo_section_camera", {"Camera"}},
    {"pc_photo_section_lens", {"Lens"}},
    {"pc_photo_section_image", {"Image"}},
    {"pc_photo_take", {"Take photo"}},
    {"pc_photo_capture", {"Capture"}},
    {"pc_photo_fov", {"Field of view"}},
    {"pc_photo_roll", {"Camera roll"}},
    {"pc_photo_speed", {"Camera speed"}},
    {"pc_photo_speed_slow", {"Slow"}},
    {"pc_photo_speed_normal", {"Normal"}},
    {"pc_photo_speed_fast", {"Fast"}},
    {"pc_photo_reset", {"Reset camera"}},
    {"pc_photo_focus", {"Focus distance"}},
    {"pc_photo_aperture", {"Aperture"}},
    {"pc_photo_exposure", {"Exposure"}},
    {"pc_photo_grading", {"Colour grading"}},
    {"pc_photo_letterbox", {"Letterbox"}},
    {"pc_photo_body", {"Player body"}},
    {"pc_photo_flashlight", {"Flashlight"}},
    {"pc_photo_shown", {"Shown"}},
    {"pc_photo_hidden", {"Hidden"}},
    {"pc_photo_auto", {"Auto"}},
    {"pc_photo_metres", {"{value} m"}},
    {"pc_photo_saved", {"Saved to Pictures/PT Photos: {file}"}},
    {"pc_photo_hint", {"Arrows / D-pad: choose and change. P / Square: photo. H / Triangle: hide panel. Right mouse: look. Esc / Circle: leave."}},
    {"pc_note_photo_take", {"Saves the current view to Pictures/PT Photos. The panel is never in the photo."}},
    {"pc_note_photo_fov", {"Vertical field of view in degrees. Lower values zoom in."}},
    {"pc_note_photo_roll", {"Tilts the camera sideways for a Dutch angle."}},
    {"pc_note_photo_speed", {"How fast the camera moves. Shift or L3 is still faster."}},
    {"pc_note_photo_reset", {"Returns the camera to where the photo mode started."}},
    {"pc_note_photo_dof", {"Blurs what is nearer or farther than the focus distance."}},
    {"pc_note_photo_focus", {"Auto focuses on what is at the centre of the frame."}},
    {"pc_note_photo_aperture", {"Lower f-numbers blur more. Auto keeps the game's own lens."}},
    {"pc_note_photo_exposure", {"Brightens or darkens the image, in steps of half a stop."}},
    {"pc_note_photo_grain", {"The original film grain. Off gives a cleaner image."}},
    {"pc_note_photo_grading", {"The original colour look. Off shows neutral colours."}},
    {"pc_note_photo_letterbox", {"Cinematic black bars. They are part of the photo."}},
    {"pc_note_photo_body", {"Shows or hides the player's body."}},
    {"pc_note_photo_flashlight", {"Turns the flashlight's light off while the photo mode runs."}},
    {"pc_extras_stop", {"Stop"}},
    {"pc_note_loop_generating", {"Generating previews... Your save is kept. Saving resumes at the next checkpoint: leaving the basement, or reaching the final loop."}},
    {"pc_title", {"PC SETTINGS"}},
    {"pc_entry", {"PC Settings"}},
    {"pc_back", {"Back"}},
    {"pc_quit", {"Quit"}},
    {"pc_nav_columns", {"Tab / L1 / R1: switch column"}},
    {"pc_quit_confirm", {"Quit?"}},
    // the save dialogs (game_ui.cpp): the PS4 shows its own system dialog when the storage is full, the PC this text
    {"pc_save_no_space", {"There is not enough free space to save the game.\nFree some space, then close this message to try again."}},
    {"pc_ok", {"OK"}},
    {"pc_note_quit", {"Exit the game."}},
    {"pc_note_quit_confirm", {"Press {accept} again to quit. Back cancels."}},
    {"pc_section_display", {"Display"}},
    {"pc_section_upscaling", {"Upscaling"}},
    {"pc_section_sound", {"Sound"}},
    {"pc_section_controls", {"Controls"}},
    {"pc_section_progress", {"Progress"}},
    {"pc_section_ray_tracing", {"Ray tracing"}},
    {"pc_section_textures", {"Textures"}},
    {"pc_display_mode", {"Display mode"}},
    {"pc_resolution", {"Resolution"}},
    {"pc_vsync", {"V-sync"}},
    {"pc_focus_pause", {"Pause in background"}},
    {"pc_focus_mute", {"Mute in background"}},
    {"pc_upscaler", {"Upscaler"}},
    {"pc_quality", {"Quality"}},
    {"pc_sharpness", {"Sharpness"}},
    {"pc_frame_generation", {"Frame generation"}},
    {"pc_volume", {"Volume"}},
    {"pc_microphone", {"Microphone"}},
    {"pc_microphone_test", {"Microphone test"}},
    {"pc_mic_level", {"Input level"}},
    {"pc_mic_heard", {"Recognized words"}},
    {"pc_mic_monitor", {"Hear my voice"}},
    {"pc_mic_no_word", {"None yet"}},
    {"pc_mic_waiting", {"Waiting for the selected microphone."}},
    {"pc_mic_unavailable", {"Could not open the selected microphone. Check recording permissions and device selection."}},
    {"pc_mic_st_loading", {"Loading..."}},
    {"pc_mic_st_nomic", {"No microphone"}},
    {"pc_mic_st_files", {"Speech files missing"}},
    {"pc_mic_st_runtime", {"Speech engine failed"}},
    {"pc_mic_st_cpu", {"CPU not supported"}},
    {"pc_mic_st_model", {"Speech model failed"}},
    {"pc_mic_st_silent", {"No sound"}},
    {"pc_mic_err_files", {"The speech recognition files are missing. Reinstall or repair the game."}},
    {"pc_mic_err_runtime", {"The speech engine could not be loaded. See pt.log for the cause."}},
    {"pc_mic_err_cpu", {"This processor cannot run the speech engine."}},
    {"pc_mic_err_model", {"The speech model could not be loaded. See pt.log for the cause."}},
    {"pc_mic_err_silent", {"The microphone is open but sends no sound. Check that it is not muted and that the right device is selected."}},
    {"pc_mic_say_jack", {"Say Jack into the selected microphone. This test does not advance the puzzle."}},
    {"pc_mic_monitor_note", {"Listen to your microphone. Headphones prevent feedback. Monitoring stops when you leave this test."}},
    {"pc_mouse", {"Mouse sensitivity"}},
    {"pc_gamepad_sensitivity", {"Gamepad look sensitivity"}},
    {"pc_camera_tilt", {"Camera tilt"}},
    {"pc_vibration", {"Vibration"}},
    {"pc_dead_zone", {"Stick dead zone"}},
    {"pc_reset", {"Reset progress"}},
    {"pc_graphics", {"Graphics"}},
    {"pc_graphics_value", {"More"}},
    {"pc_rt_shadows", {"Ray-traced shadows"}},
    {"pc_rt_contact", {"Contact shadows"}},
    {"pc_shadows", {"Shadows"}},
    {"pc_reflections", {"Reflections"}},
    {"pc_standard", {"Standard"}},
    {"pc_ray_traced", {"Ray traced"}},
    {"pc_rt_sharp_long", {"Ray traced, sharp"}},
    {"pc_rt_soft_long", {"Ray traced, soft"}},
    {"pc_note_shadows", {"Low to Original are the original's shadow maps (512, 1024 or 2048 px). Ray traced replaces them: sharp as the original, or soft from each light's size."}},
    {"pc_note_ao", {"Standard is the original's screen-space shading. Ray traced darkens corners and the space under objects from the scene itself. Not in the original."}},
    {"pc_note_reflections", {"Standard is the original's screen-space floor reflections. Ray traced also reflects what is off screen. Experimental."}},
    {"pc_rt_ao", {"Ambient occlusion"}},
    {"pc_anisotropy", {"Anisotropic filtering"}},
    {"pc_enhanced_textures", {"Enhanced textures"}},
    {"pc_texture_preparing", {"Preparing"}},
    {"pc_note_texture_tools_missing", {"The enhanced texture tools or model files are missing. Restore texture-tools from the portable package, then try again. Original textures are preserved."}},
    {"pc_note_texture_busy", {"Another game instance is preparing this texture cache. Wait until it finishes, then try again. Original textures are preserved."}},
    {"pc_note_texture_failed", {"Texture preparation failed; original textures are preserved. Check free disk space and pt.log for the cause, then try again."}},
    {"pc_note_texture_preparing", {"Preparing enhanced textures. Original textures stay visible until ready; then they change here without restarting. Off cancels preparation."}},
    {"pc_note_enhanced_textures", {"Generates sharper colour textures once from your game files, walls and people included (4096 px with 10 GB of video memory, else 2048). Switch Off to cancel; original textures stay available."}},
    {"pc_rt_sharp", {"Sharp"}},
    {"pc_rt_soft", {"Soft"}},
    {"pc_on", {"On"}},
    {"pc_off", {"Off"}},
    {"pc_window", {"Window"}},
    {"pc_borderless", {"Borderless"}},
    {"pc_fullscreen", {"Fullscreen"}},
    {"pc_native", {"Native"}},
    {"pc_quality_quality", {"Quality"}},
    {"pc_quality_balanced", {"Balanced"}},
    {"pc_quality_performance", {"Performance"}},
    {"pc_quality_ultra", {"Ultra performance"}},
    {"pc_quality_custom", {"Custom"}},
    {"pc_system_default", {"System default"}},
    {"pc_reset_value", {"Reset"}},
    {"pc_reset_confirm", {"Confirm"}},
    {"pc_reset_done", {"Done"}},
    {"pc_note_vsync", {"Applies immediately. Synchronizes presentation with the monitor refresh rate."}},
    {"pc_note_vsync_off", {"Applies immediately. Off shows each frame as soon as it is ready: the frame rate is not held to the refresh rate, and the picture can tear."}},
    {"pc_note_restart", {"Takes effect at the next start."}},
    {"pc_note_display_mode", {"Alt+Enter also switches between window and fullscreen."}},
    {"pc_note_resolution", {"Window size."}},
    {"pc_note_resolution_fullscreen", {"Borderless uses the selected size; exclusive uses a supported display size."}},
    {"pc_note_upscaler_off", {"Off renders at the display resolution, as the original."}},
    {"pc_note_render_size", {"{1} rendered, {2} shown."}},
    {"pc_note_needs_upscaler", {"Needs an upscaler."}},
    {"pc_note_sharpness_fsr", {"Only FSR has its own sharpening. Image clarity on the Graphics page sharpens with any upscaler."}},
    {"pc_note_reset", {"Resets progression and restarts the game now. Your language and PC settings are preserved."}},
    {"pc_note_reset_confirm", {"Press {accept} again to delete the save."}},
    {"pc_note_reset_done", {"Progress restarted in this session."}},
    {"pc_note_camera_tilt", {"The camera leans with the head, as in the original."}},
    {"pc_note_voice", {"The microphone listens only where the original game does."}},
    {"pc_note_focus_pause", {"Opens this menu when the window goes to the background."}},
    {"pc_note_focus_mute", {"Silences the game while the window is in the background."}},
    {"pc_note_frame_generation_missing", {"Not in this build."}},
    {"pc_note_frame_generation", {"AMD FSR 3 shows a generated frame between two rendered frames."}},
    {"pc_note_fsr4_vulkan", {"AMD releases FSR 4 for DirectX 12 only; this game renders with Vulkan, so FSR 4 cannot run here."}},
    {"pc_dlss_model", {"DLSS model"}},
    {"pc_dlss_model_auto", {"Auto"}},
    {"pc_note_dlss_model", {"Auto follows NVIDIA: K up to Balanced, M for Performance, L for Ultra performance. L and M cost about twice as much on RTX 20 and 30."}},
    {"pc_note_frame_generation_dlss", {"Experimental. NVIDIA DLSS Frame Generation shows a generated frame between two rendered frames. Takes effect at the next start."}},
    {"pc_note_dlssg_gpu", {"DLSS Frame Generation needs an NVIDIA GeForce RTX 40 series or newer GPU."}},
    {"pc_note_fsr_fg_gpu", {"FSR 3 frame generation needs an AMD Radeon RX 5000 series or newer GPU."}},
    {"pc_note_dlssg_driver", {"DLSS Frame Generation needs a newer NVIDIA driver."}},
    {"pc_note_dlssg_hags", {"DLSS Frame Generation needs hardware-accelerated GPU scheduling (Windows graphics settings)."}},
    {"pc_note_dlssg_missing", {"DLSS Frame Generation is not in this build."}},
    {"pc_note_dlssg_failed", {"DLSS Frame Generation could not start and was turned off."}},
    {"pc_note_dlssg_restart", {"Restart the game to start DLSS Frame Generation."}},
    {"pc_note_vsync_dlssg", {"DLSS Frame Generation runs without v-sync on Vulkan; the setting applies again when frame generation is off."}},
    {"pc_note_fsr_fg_restart", {"Restart the game to switch from DLSS Frame Generation to FSR 3."}},
    {"pc_note_dead_zone", {"0.10 is the DualShock 4's own."}},
    {"pc_note_gamepad_sensitivity", {"Multiplies turn speed after the original stick response. 1 keeps it unchanged."}},
    {"pc_note_rt_shadows", {"Shadows traced against the scene instead of shadow maps, as sharp as the original's. Not in the original."}},
    {"pc_note_rt_soft", {"Traced shadows with soft edges from each light's size. Not in the original."}},
    {"pc_note_rt_unsupported", {"Needs a GPU with Vulkan ray tracing."}},
    {"pc_note_graphics", {"Choose a graphics preset, or fine-tune lighting, textures and image effects. Resolution and upscaling stay separate."}},
    {"pc_note_rt_contact", {"Objects cast short traced shadows from every light, also the ones the original leaves unshadowed."}},
    {"pc_note_rt_ao", {"Traced shading darkens corners and the space under and behind objects. Not in the original."}},
    {"pc_rt_reflections", {"Reflections"}},
    {"pc_note_rt_reflections", {"Floors reflect the scene beyond the screen edges. Experimental; appearance may differ from the original."}},
    {"pc_note_anisotropy", {"Sharper floors and walls seen at a slant. Off is the original's filtering."}},
    {"pc_graphics_quality", {"Quality"}},
    {"pc_graphics_preset", {"Preset"}},
    {"pc_preset_low", {"Low"}},
    {"pc_preset_medium", {"Medium"}},
    {"pc_preset_original", {"Original (PS4)"}},
    {"pc_preset_high", {"High"}},
    {"pc_preset_ultra", {"Ultra"}},
    {"pc_preset_custom", {"Custom"}},
    {"pc_ray_tracing", {"Ray tracing"}},
    {"pc_clarity", {"Image clarity"}},
    {"pc_graphics_advanced", {"Advanced"}},
    {"pc_graphics_lighting", {"Lighting"}},
    {"pc_graphics_effects", {"Image effects"}},
    {"pc_graphics_image", {"Image detail"}},
    {"pc_lighting_standard", {"Standard lighting"}},
    {"pc_shadow_quality", {"Shadow maps"}},
    {"pc_standard_ao", {"Ambient occlusion"}},
    {"pc_standard_reflections", {"Screen reflections"}},
    {"pc_ray_quality", {"Ray quality"}},
    {"pc_ray_balanced", {"Balanced"}},
    {"pc_texture_detail", {"Texture detail"}},
    {"pc_detail_reduced", {"Reduced"}},
    {"pc_detail_fine", {"Fine"}},
    {"pc_dof", {"Depth of field"}},
    {"pc_motion_blur", {"Motion blur"}},
    {"pc_bloom", {"Bloom"}},
    {"pc_lens_ghosts", {"Lens flare ghosts"}},
    {"pc_note_lens_ghosts", {"The large lens flare reflections across the screen when looking near a lamp, as in the original (PS4). Off removes them."}},
    {"pc_film_grain", {"Film grain"}},
    {"pc_note_preset", {"Changes graphics only; keeps your resolution and upscaler. Manual adjustments show Custom. Ultra uses ray tracing when supported."}},
    {"pc_note_ray_master", {"Enable or disable traced shadows, contact shadows, ambient occlusion and reflections together. Individual controls are in Lighting."}},
    {"pc_lens_distortion", {"Lens effect"}},
    {"pc_note_lens_distortion", {"Original curved lens and colour fringing. Off gives sharper edges and a wider unobstructed image."}},
    {"pc_note_clarity", {"Adds restrained local-contrast sharpening at output resolution. Zero preserves the original image."}},
    {"pc_note_letterbox", {"Black bars over and under the picture in play and in cutscenes. Subtitles stay inside the picture. Not in the original."}},
    {"pc_note_advanced", {"Fine-tune this category. Back returns to Graphics; changes automatically show Custom."}},
    {"pc_note_shadow_quality", {"512, 1024 or original 2048 px shadow maps. Ray-traced shadows replace maps when enabled. Resolution scale is unchanged."}},
    {"pc_note_standard_ao", {"Original screen-space ambient shading. Turn off to reduce cost on slower GPUs."}},
    {"pc_note_standard_reflections", {"Original screen-space floor reflections. Traced reflections replace them when enabled."}},
    {"pc_note_ray_quality", {"Balanced: 2 rays. High: 4 rays. Ultra: 8 rays for softer shadows and less noisy traced ambient shading."}},
    {"pc_note_texture_detail", {"Reduced uses coarser texture mips. Fine preserves more texture detail at a distance; may shimmer. Output resolution stays unchanged."}},
    {"pc_note_dof", {"Original camera focus blur. Off keeps nearby surfaces and the background sharp."}},
    {"pc_note_motion_blur", {"Original blur while turning and moving. Off gives a clearer moving image."}},
    {"pc_note_bloom", {"Original light bloom. Off reduces glow and post-processing cost."}},
    {"pc_note_film_grain", {"Original film grain strength. Zero reveals a cleaner image; 100% retains the original effect."}},
    {"pc_mods", {"Mods"}},
    {"pc_section_mods", {"Installed mods"}},
    {"pc_note_mods", {"Turning a mod on or off takes effect at the next start. Mods are not part of the original game."}},
    {"pc_archive", {"Museum"}},
    {"pc_note_archive", {"The game's own pictures, voices, photo pieces, cutscenes and models, as you reach them in play. Your game is not changed."}},
    {"pc_note_archive_locked", {"Finish the game once to unlock the museum."}},
    {"pc_note_extras_archive", {"Loop browser, museum, free camera and photo mode."}},
    {"pc_archive_sections", {"Halls"}},
    {"pc_archive_images", {"Subliminal images"}},
    {"pc_archive_voices", {"Voices and radio"}},
    {"pc_archive_photos", {"Photo pieces"}},
    {"pc_archive_cutscenes", {"Cutscenes"}},
    {"pc_archive_models", {"Models"}},
    {"pc_archive_unused", {"Unused content"}},
    {"pc_note_archive_images", {"The texts the subliminal flashes show, the noise of the flashes and the peephole's view."}},
    {"pc_note_archive_voices", {"The radio broadcasts and every spoken line, with the transcript in your subtitle language."}},
    {"pc_note_archive_photos", {"The torn pieces of the photograph, and the photo they make in the frame."}},
    {"pc_note_archive_cutscenes", {"Every cutscene from its start, with its sound and subtitles."}},
    {"pc_note_archive_models", {"Lisa and the hallway's other figures and objects, in the light of the start room."}},
    {"pc_note_archive_unused_section", {"Content in the game's files that the game never shows. It opens once you finish the game."}},
    {"pc_note_archive_image", {"Enter / Cross: view full screen."}},
    {"pc_note_archive_voice", {"Enter / Cross: play or stop."}},
    {"pc_note_archive_photo", {"Enter / Cross: view full screen."}},
    {"pc_note_archive_demo", {"Enter / Cross: play from the start. Esc / Circle stops it."}},
    {"pc_note_archive_model", {"Enter / Cross: view the model. Esc / Circle returns."}},
    {"pc_note_archive_unused", {"Never shown in the game. Enter / Cross: view the model."}},
    {"pc_note_archive_locked", {"Locked. Reach it in play to open it."}},
    {"pc_note_archive_playing", {"Playing. Enter / Cross stops it."}},
    {"pc_archive_lock", {"Lock the museum"}},
    {"pc_note_archive_lock", {"Locks every exhibit of the museum again, as before you played. Your save is not changed."}},
    {"pc_archive_hint", {"Enter / X / A: open"}},
    {"pc_archive_view_hint", {"Left / Right: previous / next. Esc / Circle: back."}},
    {"pc_archive_demo_hint", {"Esc / Circle / Enter / Cross: stop"}},
    {"pc_archive_model_hint", {"WASD / left stick: pan. Arrows / right stick: turn. Triggers: zoom. Esc / Circle: back."}},
    {"pc_archive_sub", {"Subliminal text {1}"}},
    {"pc_archive_noise", {"Noise"}},
    {"pc_archive_noise_normal", {"Noise distortion"}},
    {"pc_archive_peephole_mask", {"The peephole's view"}},
    {"pc_archive_radio_news", {"Radio: the news broadcast"}},
    {"pc_archive_radio_news2", {"Radio: the broadcast again"}},
    {"pc_archive_radio_voice", {"Radio voice {1}"}},
    {"pc_archive_riddle", {"Radio riddle {1}"}},
    {"pc_archive_sermon", {"Radio: the sermon"}},
    {"pc_archive_phone", {"The phone call"}},
    {"pc_archive_peephole_voice", {"Through the peephole"}},
    {"pc_archive_bag", {"The talking bag"}},
    {"pc_archive_fetus", {"The fetus speaks {1}"}},
    {"pc_archive_photo_lisa", {"Piece: Lisa"}},
    {"pc_archive_photo_tree", {"Piece: the tree"}},
    {"pc_archive_photo_gap", {"Piece: the gap"}},
    {"pc_archive_photo_bath", {"Piece: the bathroom"}},
    {"pc_archive_photo_stair", {"Piece: the stairs"}},
    {"pc_archive_photo_option", {"Piece: the options screen"}},
    {"pc_archive_photo_complete", {"The completed photo"}},
    {"pc_archive_preface", {"The preface"}},
    {"pc_archive_awakening", {"The first awakening"}},
    {"pc_archive_opening", {"Waking up"}},
    {"pc_archive_first_exit", {"The first door"}},
    {"pc_archive_door", {"Through the door"}},
    {"pc_archive_clock", {"Midnight"}},
    {"pc_archive_kill", {"Caught by Lisa"}},
    {"pc_archive_ending", {"The ending"}},
    {"pc_archive_teaser", {"The teaser"}},
    {"pc_archive_lisa_stand", {"Lisa, standing"}},
    {"pc_archive_lisa_walk", {"Lisa, walking"}},
    {"pc_archive_lisa_dash", {"Lisa, rushing"}},
    {"pc_archive_lisa_door", {"Lisa behind the door"}},
    {"pc_archive_baby", {"The fetus in the sink"}},
    {"pc_archive_fridge", {"The fridge"}},
    {"pc_archive_bag_model", {"The paper bag"}},
    {"pc_archive_lamp", {"The ceiling lamp"}},
    {"pc_archive_roach", {"Cockroach"}},
    {"pc_archive_flashlight", {"The flashlight"}},
    {"pc_archive_radio", {"The radio"}},
    {"pc_archive_phone_model", {"The telephone"}},
    {"pc_archive_xmark_photo", {"The X mark photo"}},
    {"pc_archive_clock_model", {"The clock"}},
    {"pc_archive_man", {"The man"}},
    {"pc_archive_bathtub", {"The body in the bathtub"}},
};

}

std::vector<std::string_view> PcDescriptionKeys() {
    std::vector<std::string_view> keys;
    for (const Entry& entry : kTexts) if (entry.key.find("note") != std::string_view::npos || entry.key == "pc_mic_say_jack") keys.push_back(entry.key);
    return keys;
}

std::string PcNoteText(std::string_view note, int language) {
    const size_t split = note.find(kPcNoteArgument);
    if (split == std::string_view::npos) return std::string(PcText(note, language));
    std::string text(PcText(note.substr(0, split), language));
    std::string_view rest = note.substr(split + 1);
    for (int n = 1; ; ++n) {
        const size_t end = rest.find(kPcNoteArgument);
        const std::string token = "{" + std::to_string(n) + "}";
        if (const size_t at = text.find(token); at != std::string::npos) text.replace(at, token.size(), rest.substr(0, end));
        if (end == std::string_view::npos) break;
        rest = rest.substr(end + 1);
    }
    return text;
}

std::string_view PcText(std::string_view key, int language) {
    if (language >= 1) {
        const auto text = localized::Menu(key, language);
        if (!text.empty()) return text;
    }
    for (const Entry& e : kTexts) {
        if (e.key == key) {
            const std::string_view text = language > 0 && language < kLanguages ? e.text[language] : std::string_view();
            return text.empty() ? e.text[0] : text;
        }
    }
    return key;
}

}
