Mod.Log("started", Mod.Floor(), Mod.Loop(), Mod.Step())
Mod.On("FloorEnter", function(floor, loop)
    Mod.Log("FloorEnter", floor, loop)
end)
Mod.On("StepChange", function(old, new)
    Mod.Log("StepChange", old, new)
end)
Mod.On("Message", function(name, sender)
    Mod.Log("Message", name, sender)
end)
