#pragma once
#include <cstdint>
#include <initializer_list>
#include <string_view>

namespace pt::chinese {
struct Text { std::string_view key, text; };
inline constexpr Text kMenu[] = {
    {"pc_controller_speaker","控制器扬声器"},
    {"pc_note_controller_speaker","通过受支持的 Sony 控制器扬声器播放游戏中为 Lisa 录制的哭喊声。Windows 需要 USB 连接；不支持的设备和蓝牙连接不会播放声音。此功能与触觉反馈独立，默认关闭。"},
    {"pc_controller_speaker_volume","控制器扬声器音量"},
    {"pc_note_controller_speaker_volume","仅以 5% 为步进调整控制器扬声器音量，不会改变游戏主音频或 DualSense 触觉强度。仅适用于 Windows 上通过 USB 连接的受支持 Sony 控制器。"},
    {"pc_microphone_trigger_assign","将 {input} 设为麦克风触发键"},
    {"pc_note_microphone_trigger","可选的麦克风替代输入。游戏正在聆听时，键盘和手柄的两个扳机都可触发。"},
    {"pc_note_microphone_test","测试麦克风和识别结果。"},
    {"pc_fps_limit","帧率上限"},
    {"pc_unlimited","不限制"},
    {"pc_note_fps_limit","限制渲染帧数。菜单仍限制为 60 FPS。垂直同步可能会施加更低的上限。"},
    {"pc_hdr","原生 HDR"},
    {"pc_note_hdr_restart","下次启动时生效。需要在兼容显示器上启用 HDR；否则使用 SDR。"},
    {"pc_surround","环绕声输出"},
    {"pc_note_surround","重启后使用输出设备的 5.1 或 7.1 声道布局。立体声设备仍使用立体声。"},
    {"pc_rumble_profile","振动模式"},
    {"pc_rumble_original","原版"},
    {"pc_rumble_enhanced","增强"},
    {"pc_note_rumble_profile","原版仅使用游戏原有的马达振动。增强模式会增加受支持的扳机振动，并在 Windows 上受支持的 USB DualSense 手柄上加入由 Lisa 过滤后哭喊音频生成的触觉反馈。关闭主振动选项会同时关闭这两项。手柄扬声器音频单独设置。"},
    {"pc_vr_height","高度调整"},
    {"pc_note_vr_height","上下移动跟踪视点，不改变玩家在游戏中的位置。"},
    {"pc_vr_world_scale","世界缩放比例"},
    {"pc_note_vr_world_scale","将头部、眼睛和控制器的跟踪移动缩放至 50%–200%。数值越大，世界看起来越小。默认值：100%。"},
    {"pc_photo_focal_length","焦距"},
    {"pc_note_photo_focal_length","镜头的焦距，单位为毫米。对焦模糊使用与相机相同的镜头和传感器。"},
    {"pc_photo_aspect","宽高比"},
    {"pc_note_photo_aspect","从照片中央进行裁剪。"},
    {"pc_photo_resolution","照片分辨率"},
    {"pc_note_photo_resolution","原生模式保存取景范围内的像素。4K 会重新渲染场景，长边为 3840 像素。"},
    {"pc_photo_resolution_native","原生"},
    {"pc_photo_resolution_4k","4K"},
    {"pc_photo_filter","色彩滤镜"},
    {"pc_note_photo_filter","仅应用于照片预览和保存的照片。"},
    {"pc_photo_filter_bw","黑白"},
    {"pc_photo_filter_warm","暖色"},
    {"pc_photo_filter_cool","冷色"},
    {"pc_photo_filter_muted","柔和"},
    {"pc_archive_model_hint","WASD / 左摇杆：平移取景。方向键 / 右摇杆：旋转。扳机：缩放。Esc / 圆圈键：返回。"},
    {"pc_note_resolution_fullscreen","无边框模式使用所选尺寸；独占全屏使用受支持的显示尺寸。"},
    {"op_options","选项"},
    {"op_back","返回"},
    {"op_brightness_setting","亮度"},
    {"op_britness_tip","请调整亮度，直到只能看到左侧的图像。"},
    {"op_subtitles_setting","字幕"},
    {"op_sub_none","关闭"},
    {"op_sub_english","英语"},
    {"op_sub_french","法语"},
    {"op_sub_german","德语"},
    {"op_sub_spanish","西班牙语"},
    {"op_sub_japanese","日语"},
    {"op_sub_itlian","意大利语"},
    {"op_sub_portuguese","葡萄牙语"},
    {"op_sub_turkish","土耳其语"},
    {"op_sub_chinese","简体中文"},
    {"op_sub_arabic","阿拉伯语"},
    {"op_sub_russian","俄语"},
    {"op_sub_ukrainian","乌克兰语"},
    {"op_sub_czech","捷克语"},
    {"op_sub_polish","波兰语"},
    {"op_camera_setting","镜头"},
    {"op_camera_y_axis","垂直方向"},
    {"op_camera_x_axis","水平方向"},
    {"op_camera_normal","标准"},
    {"op_camera_reversed","反转"},
    {"pc_loop_browser","循环选择"},
    {"pc_note_loop_browser_entry","从任意一个循环开始游戏，不会覆盖你的存档。"},
    {"pc_loop_choose","选择循环"},
    {"pc_loop_preview","预览"},
    {"pc_loop_start_hint","Enter / X / A：开始"},
    {"pc_loop_f000","起始房间：开场"},
    {"pc_loop_f010","循环 1：收音机"},
    {"pc_loop_f005","循环 2：门厅的门打开了"},
    {"pc_loop_f020","循环 3：浴室里的哭声"},
    {"pc_loop_f030","循环 4：浴室门"},
    {"pc_loop_f040","循环 5：走廊尽头的丽莎"},
    {"pc_loop_f060","循环 6：浴室与手电筒"},
    {"pc_loop_f050a","循环 7：丽莎跟在身后"},
    {"pc_loop_f050b","循环 8：打叉的照片"},
    {"pc_loop_f070","循环 9：窗户破碎"},
    {"pc_loop_f080","循环 10：流血的冰箱"},
    {"pc_loop_f090","循环 11：HELLO"},
    {"pc_loop_f100","循环 12：红色走廊"},
    {"pc_loop_f110","循环 13：迷宫与猫眼"},
    {"pc_loop_f120","循环 14：204863 与故障画面"},
    {"pc_loop_f160","循环 15：最后的循环"},
    {"pc_loop_ending","结局动画与制作人员名单"},
    {"pc_loop_street","漫步街道（结局之后）"},
    {"pc_note_loop_opening","与新游戏一样，在起始房间开始开场。你的存档会保留。"},
    {"pc_note_loop_hallway","从此循环之前的起始房间开始，之前的谜题均已解开。穿过门即可。你的存档会保留，到达下一个检查点后恢复存档。"},
    {"pc_note_loop_ending","播放结局动画和制作人员名单，之后可选择漫步街道。你的存档会保留。"},
    {"pc_note_loop_street","以第一人称置身于结局中的街道。可从“附加功能”中离开。你的存档会保留。"},
    {"pc_note_loop_locked","未解锁。通关一次后，游戏中到达过的所有循环都会开放。"},
    {"pc_note_loop_browser_locked","通关一次即可解锁循环选择。"},
    {"pc_street_title","街道"},
    {"pc_street_question","要探索这条街道吗？"},
    {"pc_street_walk","是，漫步街道"},
    {"pc_credit_version","P.T. PC Port {1}，制作：LoreanXavier"},
    {"pc_update_available","新版本 {1} 已发布 (当前为 {2})"},
    {"pc_credits_by","制作：LoreanXavier"},
    {"pc_credits_dlss","本游戏使用 NVIDIA DLSS。"},
    {"pc_credits_licenses","完整的许可证文本位于 pt.exe 旁边的 licenses 文件夹中。"},
    {"pc_credits_konami","P.T. 归 Konami Digital Entertainment 与 Kojima Productions 所有。"},
    {"pc_credits_fan","本移植版是非官方的粉丝项目，与 Konami、NVIDIA、AMD 和 Intel 无关，也未获得其认可。"},
    {"pc_note_street_walk","以第一人称漫步结局中的街道。可从“附加功能”中离开。"},
    {"pc_street_restart","否，回到起点"},
    {"pc_note_street_restart","与原版制作人员名单之后一样，从起始房间重新开始。"},
    {"pc_street_leave","离开街道"},
    {"pc_note_street_leave","结束街道漫步，回到起始房间。"},
    {"pc_street_return","回到房子"},
    {"pc_street_return_confirm","回到房子？"},
    {"pc_loop_lock","锁定循环选择"},
    {"pc_note_loop_lock","重新锁定循环选择的所有条目，如同首次通关之前。你的存档不会改变。"},
    {"pc_extras","附加功能"},
    {"pc_vr","VR（实验性）"},
    {"pc_note_vr","通过 OpenXR 使用 VR 头显游玩。实验性功能：未在真实硬件上测试。"},
    {"pc_vr_mode","VR 模式"},
    {"pc_note_vr_mode","未在真实硬件上测试。需要 OpenXR 运行时和头显。下次启动时生效；没有头显时游戏照常启动。"},
    {"pc_vr_flashlight","手电筒"},
    {"pc_note_vr_flashlight","手电筒像原版一样跟随头部，或跟随你手中的控制器。"},
    {"pc_vr_head","头部"},
    {"pc_vr_controller","控制器"},
    {"pc_vr_turn","转向"},
    {"pc_note_vr_turn","右摇杆按固定角度或平滑转向。固定角度转向更不容易晕。"},
    {"pc_vr_snap","固定角度"},
    {"pc_vr_smooth","平滑"},
    {"pc_note_extras","循环选择、自由镜头和拍照模式。"},
    {"pc_freecam","自由镜头"},
    {"pc_note_freecam","让镜头脱离玩家自由移动（F6）。空格 / Ctrl 或扳机键控制升降，Shift 或 L3 加速。按 Esc 退出。"},
    {"pc_photo_mode","拍照模式"},
    {"pc_note_photo_mode","暂停游戏并用自由镜头取景（F7）。按 P 或方块键保存到 Pictures/PT Photos，按 H 或三角键隐藏面板。"},
    {"pc_speedrun","速通计时器"},
    {"pc_note_speedrun","屏幕计时器，每个循环记录一次分段，并在片尾字幕后显示结果。真实时间计算一切；游戏时间不计暂停和加载。原版无此功能。"},
    {"pc_speedrun_real_time","真实时间"},
    {"pc_speedrun_game_time","游戏时间"},
    {"pc_livesplit","LiveSplit 服务器"},
    {"pc_note_livesplit","将计时器的开始、分段和游戏时间发送到 LiveSplit（Control > Start TCP Server，端口 {1}）。主机和端口在 pt.ini 中。"},
    {"pc_speedrun_results","通关"},
    {"pc_speedrun_run","本次"},
    {"pc_speedrun_splits","分段"},
    {"pc_speedrun_menu","返回菜单"},
    {"pc_note_speedrun_menu","像原版在结局后那样从头开始，先显示选项画面。下一次计时在你获得控制时开始。"},
    {"pc_speedrun_outside","探索外面"},
    {"pc_note_speedrun_outside","在结局的街道上行走。可从暂停菜单回到房子。"},
    {"pc_note_speedrun_real","从获得控制到结局的真实时间：包括暂停、加载和过场。"},
    {"pc_note_speedrun_game","仅计未暂停的游玩：不计暂停菜单和游戏结束后的加载。"},
    {"pc_speedrun_best","个人最佳"},
    {"pc_note_speedrun_best","之前的最佳：{1}。记录保存在用户文件夹的 speedrun.ini、speedrun_history.txt 和 speedrun_pb.lss（LiveSplit）中。"},
    {"pc_speedrun_new_best","新纪录！"},
    {"pc_speedrun_partial","不是从头开始"},
    {"pc_speedrun_start_room","起始房间"},
    {"pc_speedrun_loop","循环 {1}"},
    {"pc_third_person","第三人称（实验性）"},
    {"pc_note_third_person","实验性功能，原版没有：镜头从肩后跟随玩家。缩放和过场动画时切回第一人称；事件的发生与第一人称完全相同。"},
    {"pc_extras_start","开始"},
    {"pc_photo_title","拍照模式"},
    {"pc_photo_section_camera","相机"},
    {"pc_photo_section_lens","镜头"},
    {"pc_photo_section_image","画面"},
    {"pc_photo_take","拍照"},
    {"pc_photo_capture","拍摄"},
    {"pc_photo_fov","视野"},
    {"pc_photo_roll","画面倾斜"},
    {"pc_photo_speed","相机速度"},
    {"pc_photo_speed_slow","慢"},
    {"pc_photo_speed_normal","正常"},
    {"pc_photo_speed_fast","快"},
    {"pc_photo_reset","重置相机"},
    {"pc_photo_focus","对焦距离"},
    {"pc_photo_aperture","光圈"},
    {"pc_photo_exposure","曝光"},
    {"pc_photo_grading","调色"},
    {"pc_photo_letterbox","电影黑边"},
    {"pc_photo_body","玩家身体"},
    {"pc_photo_flashlight","手电筒"},
    {"pc_photo_shown","显示"},
    {"pc_photo_hidden","隐藏"},
    {"pc_photo_auto","自动"},
    {"pc_photo_metres","{value} 米"},
    {"pc_photo_saved","已保存到 Pictures/PT Photos：{file}"},
    {"pc_photo_save_failed","无法保存照片。请查看 pt.log。"},
    {"pc_photo_hint","方向键 / 十字键：选择和调整。P / 方块键：拍照。H / 三角键：隐藏面板。鼠标右键：转动视角。Esc / 圆圈键：退出。"},
    {"pc_note_photo_take","将当前画面保存到 Pictures/PT Photos。照片中不会出现面板。"},
    {"pc_note_photo_fov","垂直视野角度。数值越小，画面放大得越多。"},
    {"pc_note_photo_roll","让相机向一侧倾斜，形成倾斜构图。"},
    {"pc_note_photo_speed","相机的移动速度。按住 Shift 或 L3 仍可加速。"},
    {"pc_note_photo_reset","让相机回到进入拍照模式时的位置。"},
    {"pc_note_photo_dof","让比对焦距离更近或更远的物体变得模糊。"},
    {"pc_note_photo_focus","“自动”会对焦于画面中央的物体。"},
    {"pc_note_photo_aperture","f 值越小，虚化越强。“自动”沿用游戏本身的镜头设置。"},
    {"pc_note_photo_exposure","以半档为单位调亮或调暗画面。"},
    {"pc_note_photo_grain","原版的胶片颗粒。关闭后画面更干净。"},
    {"pc_note_photo_grading","原版的色调风格。关闭后显示中性色彩。"},
    {"pc_note_photo_letterbox","电影感的上下黑边，会保留在照片中。"},
    {"pc_note_photo_body","显示或隐藏玩家的身体。"},
    {"pc_note_photo_flashlight","拍照模式期间关闭手电筒的光。"},
    {"pc_extras_stop","停止"},
    {"pc_note_loop_generating","正在生成预览……你的存档会保留。到达下一个检查点时恢复存档：离开地下室，或进入最后的循环。"},
    {"pc_title","PC 设置"},
    {"pc_entry","PC 设置"},
    {"pc_back","返回"},
    {"pc_quit","退出"},
    {"pc_nav_columns","Tab / L1 / R1：切换列"},
    {"pc_quit_confirm","确定退出？"},
    {"pc_save_no_space","剩余空间不足，无法保存游戏。\n请释放一些空间，然后关闭此消息重试。"},
    {"pc_ok","确定"},
    {"pc_note_quit","退出游戏。"},
    {"pc_note_quit_confirm","再次按 {accept} 退出游戏，按返回键取消。"},
    {"pc_section_display","显示"},
    {"pc_section_upscaling","超分辨率"},
    {"pc_section_sound","声音"},
    {"pc_section_controls","操作"},
    {"pc_section_progress","进度"},
    {"pc_section_ray_tracing","光线追踪"},
    {"pc_section_textures","纹理"},
    {"pc_display_mode","显示模式"},
    {"pc_resolution","分辨率"},
    {"pc_vsync","垂直同步"},
    {"pc_focus_pause","后台时暂停"},
    {"pc_focus_mute","后台时静音"},
    {"pc_upscaler","超分辨率技术"},
    {"pc_quality","模式"},
    {"pc_sharpness","锐化"},
    {"pc_frame_generation","帧生成"},
    {"pc_volume","音量"},
    {"pc_microphone","麦克风"},
    {"pc_microphone_test","麦克风测试"},
    {"pc_mic_level","输入电平"},
    {"pc_mic_heard","识别结果"},
    {"pc_mic_monitor","监听麦克风"},
    {"pc_mic_no_word","暂无"},
    {"pc_mic_waiting","正在等待所选麦克风……"},
    {"pc_mic_unavailable","无法打开所选麦克风。请检查录音权限和所选设备。"},
    {"pc_mic_st_loading","加载中…"},
    {"pc_mic_st_nomic","无麦克风"},
    {"pc_mic_st_files","缺少语音文件"},
    {"pc_mic_st_runtime","语音引擎失败"},
    {"pc_mic_st_cpu","CPU 不受支持"},
    {"pc_mic_st_model","语音模型失败"},
    {"pc_mic_st_silent","无声音"},
    {"pc_mic_err_files","缺少语音识别文件。请重新安装或修复游戏。"},
    {"pc_mic_err_runtime","无法加载语音引擎。原因见 pt.log。"},
    {"pc_mic_err_cpu","此处理器无法运行语音引擎。"},
    {"pc_mic_err_model","无法加载语音模型。原因见 pt.log。"},
    {"pc_mic_err_silent","麦克风已打开但没有声音。请检查是否被静音以及所选设备是否正确。"},
    {"pc_mic_say_jack","对着所选麦克风说“Jack”。此测试不会推进谜题。"},
    {"pc_mic_monitor_note","监听自己的麦克风声音。佩戴耳机可避免啸叫。离开此测试后自动停止监听。"},
    {"pc_mouse","鼠标灵敏度"},
    {"pc_gamepad_sensitivity","手柄转向灵敏度"},
    {"pc_camera_tilt","镜头倾斜"},
    {"pc_vibration","振动"},
    {"pc_dead_zone","摇杆死区"},
    {"pc_reset","重置进度"},
    {"pc_graphics","画面"},
    {"pc_graphics_value","更多"},
    {"pc_rt_shadows","光线追踪阴影"},
    {"pc_rt_contact","接触阴影"},
    {"pc_shadows","阴影"},
    {"pc_reflections","反射"},
    {"pc_standard","标准"},
    {"pc_ray_traced","光线追踪"},
    {"pc_rt_sharp_long","光追（锐利）"},
    {"pc_rt_soft_long","光追（柔和）"},
    {"pc_note_shadows","“低”到“原版”为原版的阴影贴图（512、1024 或 2048 像素）。光线追踪阴影会取代阴影贴图：可与原版一样锐利，或按各光源大小呈现柔和边缘。"},
    {"pc_note_ao","“标准”为原版的屏幕空间环境光遮蔽。光线追踪会根据场景本身加深角落和物体下方的阴影。原版无此效果。"},
    {"pc_note_reflections","“标准”为原版的屏幕空间地面反射。光线追踪还能反射屏幕外的物体。实验性功能。"},
    {"pc_rt_ao","环境光遮蔽"},
    {"pc_anisotropy","各向异性过滤"},
    {"pc_enhanced_textures","增强纹理"},
    {"pc_texture_preparing","生成中"},
    {"pc_note_texture_tools_missing","缺少增强纹理工具或模型文件。请从便携版安装包中恢复 texture-tools 文件夹后重试。原始纹理不受影响。"},
    {"pc_note_texture_busy","另一个游戏进程正在生成此纹理缓存。请等待其完成后重试。原始纹理不受影响。"},
    {"pc_note_texture_failed","纹理生成失败，原始纹理不受影响。请检查磁盘剩余空间，并查看 pt.log 了解原因，然后重试。"},
    {"pc_note_texture_preparing","正在生成增强纹理。完成前继续显示原始纹理，完成后无需重启即可自动替换。选择“关闭”可取消。"},
    {"pc_note_enhanced_textures","根据你的游戏文件一次性生成更清晰的颜色纹理。包括墙面和人物；显存 10 GB 以上为 4096 像素，否则为 2048。选择“关闭”可取消，原始纹理始终保留。"},
    {"pc_rt_sharp","锐利"},
    {"pc_rt_soft","柔和"},
    {"pc_on","开启"},
    {"pc_off","关闭"},
    {"pc_window","窗口化"},
    {"pc_borderless","无边框窗口"},
    {"pc_fullscreen","全屏"},
    {"pc_native","原生"},
    {"pc_quality_quality","质量"},
    {"pc_quality_balanced","平衡"},
    {"pc_quality_performance","性能"},
    {"pc_quality_ultra","超高性能"},
    {"pc_quality_custom","自定义"},
    {"pc_system_default","系统默认"},
    {"pc_reset_value","重置"},
    {"pc_reset_confirm","确认"},
    {"pc_reset_done","已完成"},
    {"pc_note_vsync","立即生效。使画面输出与显示器刷新率同步。"},
    {"pc_note_vsync_off","立即生效。关闭时每帧一完成就显示：帧率不受刷新率限制，画面可能出现撕裂。"},
    {"pc_note_restart","下次启动游戏时生效。"},
    {"pc_note_display_mode","也可按 Alt+Enter 在窗口和全屏之间切换。"},
    {"pc_note_resolution","窗口大小。"},
    {"pc_note_resolution_fullscreen","全屏模式使用桌面分辨率。"},
    {"pc_note_upscaler_off","关闭时以显示分辨率渲染，与原版相同。"},
    {"pc_note_render_size","渲染分辨率 {1}，输出分辨率 {2}。"},
    {"pc_note_needs_upscaler","需先启用超分辨率技术。"},
    {"pc_note_sharpness_fsr","只有 FSR 自带锐化。“画面”页面中的“画面清晰度”适用于任何超分辨率技术。"},
    {"pc_note_reset","清除游戏进度并立即重新开始。语言和 PC 设置会保留。"},
    {"pc_note_reset_confirm","再次按 {accept} 删除存档。"},
    {"pc_note_reset_done","进度已重置，游戏已重新开始。"},
    {"pc_note_camera_tilt","镜头随头部动作倾斜，与原版相同。"},
    {"pc_note_voice","麦克风只在原版游戏会监听的地方监听。"},
    {"pc_note_focus_pause","游戏窗口切换到后台时打开此菜单。"},
    {"pc_note_focus_mute","游戏窗口在后台时静音。"},
    {"pc_note_frame_generation_missing","此版本不包含该功能。"},
    {"pc_note_frame_generation","AMD FSR 3 会在两帧渲染画面之间插入一帧生成画面。"},
    {"pc_note_fsr4_vulkan","AMD 仅为 DirectX 12 提供 FSR 4；本游戏使用 Vulkan 渲染，因此无法在此运行 FSR 4。"},
    {"pc_dlss_model","DLSS 模型"},
    {"pc_dlss_model_auto","自动"},
    {"pc_note_dlss_model","自动即 NVIDIA 的选择：平衡及以上用 K，性能用 M，超高性能用 L。在 RTX 20 和 30 上，L 和 M 的开销约为两倍。"},
    {"pc_note_frame_generation_dlss","实验性功能。NVIDIA DLSS 帧生成会在两帧渲染画面之间插入一帧生成画面。下次启动时生效。"},
    {"pc_note_dlssg_gpu","DLSS 帧生成需要 NVIDIA GeForce RTX 40 系列或更新的显卡。"},
    {"pc_note_fsr_fg_gpu","FSR 3 帧生成需要 AMD Radeon RX 5000 系列或更新的显卡。"},
    {"pc_note_dlssg_driver","DLSS 帧生成需要更新的 NVIDIA 驱动程序。"},
    {"pc_note_dlssg_hags","DLSS 帧生成需要开启硬件加速 GPU 计划（Windows 图形设置）。"},
    {"pc_note_dlssg_missing","此版本不包含 DLSS 帧生成。"},
    {"pc_note_dlssg_failed","DLSS 帧生成无法启动，已关闭。"},
    {"pc_note_dlssg_restart","请重新启动游戏以开启 DLSS 帧生成。"},
    {"pc_note_vsync_dlssg","在 Vulkan 下，DLSS 帧生成在不开启垂直同步的情况下运行；关闭帧生成后此设置重新生效。"},
    {"pc_note_fsr_fg_restart","请重新启动游戏以从 DLSS 帧生成切换到 FSR 3。"},
    {"pc_note_dead_zone","0.10 为 DualShock 4 的原始数值。"},
    {"pc_note_gamepad_sensitivity","在原始摇杆响应曲线后调整转向速度。1 表示保持原样。"},
    {"pc_note_rt_shadows","以光线追踪代替阴影贴图生成阴影，锐利程度与原版一致。原版无此效果。"},
    {"pc_note_rt_soft","光线追踪阴影，边缘柔和程度取决于各光源的大小。原版无此效果。"},
    {"pc_note_rt_unsupported","需要支持 Vulkan 光线追踪的显卡。"},
    {"pc_note_graphics","选择画面预设，或分别细调光照、纹理和画面效果。分辨率和超分辨率需单独设置。"},
    {"pc_note_rt_contact","所有光源都会让物体投下短距离的光线追踪阴影，包括原版中不产生阴影的光源。"},
    {"pc_note_rt_ao","以光线追踪加深角落以及物体下方和后方的阴影。原版无此效果。"},
    {"pc_rt_reflections","反射"},
    {"pc_note_rt_reflections","地面可反射屏幕边缘以外的场景。实验性功能，效果可能与原版不同。"},
    {"pc_note_anisotropy","让倾斜视角下的地面和墙面更清晰。关闭时使用原版的纹理过滤。"},
    {"pc_graphics_quality","画质"},
    {"pc_graphics_preset","画面预设"},
    {"pc_preset_low","低"},
    {"pc_preset_medium","中"},
    {"pc_preset_original","原版（PS4）"},
    {"pc_preset_high","高"},
    {"pc_preset_ultra","极高"},
    {"pc_preset_custom","自定义"},
    {"pc_ray_tracing","光线追踪"},
    {"pc_clarity","画面清晰度"},
    {"pc_graphics_advanced","高级"},
    {"pc_graphics_lighting","光照"},
    {"pc_graphics_effects","画面效果"},
    {"pc_graphics_image","画面细节"},
    {"pc_lighting_standard","标准光照"},
    {"pc_shadow_quality","阴影贴图"},
    {"pc_standard_ao","环境光遮蔽"},
    {"pc_standard_reflections","屏幕空间反射"},
    {"pc_ray_quality","光线追踪质量"},
    {"pc_ray_balanced","平衡"},
    {"pc_texture_detail","纹理细节"},
    {"pc_detail_reduced","降低"},
    {"pc_detail_fine","精细"},
    {"pc_dof","景深"},
    {"pc_motion_blur","动态模糊"},
    {"pc_bloom","泛光"},
    {"pc_lens_ghosts","镜头光晕鬼影"},
    {"pc_note_lens_ghosts","看向灯具附近时遍布整个画面的大型镜头光晕反射，与原版（PS4）相同。关闭后不再绘制。"},
    {"pc_film_grain","胶片颗粒"},
    {"pc_note_preset","只更改画面设置，不影响分辨率和超分辨率技术。手动调整后显示为“自定义”。“极高”在支持时启用光线追踪。"},
    {"pc_note_ray_master","同时开启或关闭光线追踪阴影、接触阴影、环境光遮蔽和反射。各项可在“光照”中单独设置。"},
    {"pc_lens_distortion","镜头效果"},
    {"pc_note_lens_distortion","原版的镜头畸变和色散效果。关闭后边缘更清晰，画面更开阔、无遮挡。"},
    {"pc_note_clarity","在输出分辨率下适度增强局部对比度，使画面更锐利。设为 0 则保持原版画面。"},
    {"pc_note_letterbox","游戏和过场动画中画面上下的黑边。字幕保持在画面内。原版无此效果。"},
    {"pc_note_advanced","细调此类设置。按返回键回到“画面”；做出更改后预设自动显示为“自定义”。"},
    {"pc_note_shadow_quality","使用 512、1024 或原版 2048 像素的阴影贴图。启用光线追踪阴影后将取代阴影贴图。不影响分辨率缩放。"},
    {"pc_note_standard_ao","原版的屏幕空间环境光遮蔽。性能较弱的显卡可关闭此项以降低开销。"},
    {"pc_note_standard_reflections","原版的屏幕空间地面反射。启用光线追踪反射后将取代此效果。"},
    {"pc_note_ray_quality","平衡：2 条光线。高：4 条光线。极高：8 条光线，阴影更柔和，光线追踪环境光遮蔽的噪点更少。"},
    {"pc_note_texture_detail","“降低”使用更粗糙的纹理层级。“精细”保留更多远处的纹理细节，但可能出现闪烁。不影响输出分辨率。"},
    {"pc_note_dof","原版的镜头对焦模糊。关闭后近处物体和背景都保持清晰。"},
    {"pc_note_motion_blur","原版转身和移动时的模糊效果。关闭后运动画面更清晰。"},
    {"pc_note_bloom","原版的光晕效果。关闭可减弱泛光，并降低后期处理开销。"},
    {"pc_note_film_grain","原版的胶片颗粒强度。关闭后画面更干净；100% 保留原版效果。"},
    {"pc_mods","模组"},
    {"pc_section_mods","已安装的模组"},
    {"pc_note_mods","启用或停用模组将在下次启动时生效。模组不属于原版游戏内容。"},
    {"pc_archive","博物馆"},
    {"pc_note_archive","游戏本身的图片、语音、照片碎片、过场动画和模型，在游戏中到达后开放。不会改变你的游戏进度。"},
    {"pc_note_extras_archive","循环选择、博物馆、自由镜头和拍照模式。"},
    {"pc_archive_sections","展厅"},
    {"pc_archive_images","潜意识图像"},
    {"pc_archive_voices","语音与广播"},
    {"pc_archive_photos","照片碎片"},
    {"pc_archive_cutscenes","过场动画"},
    {"pc_archive_models","模型"},
    {"pc_archive_unused","未使用内容"},
    {"pc_note_archive_images","潜意识闪现的文字、闪现时的噪点和猫眼中的视野。"},
    {"pc_note_archive_voices","广播节目和所有台词，附带字幕语言的文本。"},
    {"pc_note_archive_photos","照片的碎片，以及它们在相框中拼成的照片。"},
    {"pc_note_archive_cutscenes","从头播放每段过场动画，带有声音和字幕。"},
    {"pc_note_archive_models","丽莎以及走廊中的其他人物和物品，处在起始房间的灯光下。"},
    {"pc_note_archive_unused_section","游戏文件中存在、但游戏从未展示的内容。通关后开放。"},
    {"pc_note_archive_image","Enter / 叉键：全屏查看。"},
    {"pc_note_archive_voice","Enter / 叉键：播放或停止。"},
    {"pc_note_archive_photo","Enter / 叉键：全屏查看。"},
    {"pc_note_archive_demo","Enter / 叉键：从头播放。Esc / 圆圈键停止。"},
    {"pc_note_archive_model","Enter / 叉键：查看模型。Esc / 圆圈键：返回。"},
    {"pc_note_archive_unused","游戏中从未出现。Enter / 叉键：查看模型。"},
    {"pc_note_archive_locked","未解锁。在游戏中到达后开放。"},
    {"pc_note_archive_playing","正在播放。Enter / 叉键停止。"},
    {"pc_archive_lock","锁定博物馆"},
    {"pc_note_archive_lock","将博物馆的所有展品重新锁定，如同游玩之前。存档不会改变。"},
    {"pc_archive_hint","Enter / X / A：打开"},
    {"pc_archive_view_hint","左 / 右：上一个 / 下一个。Esc / 圆圈键：返回。"},
    {"pc_archive_demo_hint","Esc / 圆圈键 / Enter / 叉键：停止"},
    {"pc_archive_model_hint","方向键 / 摇杆：旋转。W / S / 扳机键：拉近 / 拉远。Esc / 圆圈键：返回。"},
    {"pc_archive_sub","潜意识文字 {1}"},
    {"pc_archive_noise","噪点"},
    {"pc_archive_noise_normal","噪点扭曲"},
    {"pc_archive_peephole_mask","猫眼中的视野"},
    {"pc_archive_radio_news","广播：新闻节目"},
    {"pc_archive_radio_news2","广播：再次播报"},
    {"pc_archive_radio_voice","广播语音 {1}"},
    {"pc_archive_riddle","广播谜语 {1}"},
    {"pc_archive_sermon","广播：布道"},
    {"pc_archive_phone","电话"},
    {"pc_archive_peephole_voice","透过猫眼"},
    {"pc_archive_bag","会说话的袋子"},
    {"pc_archive_fetus","胎儿的话语 {1}"},
    {"pc_archive_photo_lisa","碎片：丽莎"},
    {"pc_archive_photo_tree","碎片：树"},
    {"pc_archive_photo_gap","碎片：缝隙"},
    {"pc_archive_photo_bath","碎片：浴室"},
    {"pc_archive_photo_stair","碎片：楼梯"},
    {"pc_archive_photo_option","碎片：选项画面"},
    {"pc_archive_photo_complete","完整的照片"},
    {"pc_archive_preface","序章"},
    {"pc_archive_awakening","初次醒来"},
    {"pc_archive_opening","醒来"},
    {"pc_archive_first_exit","第一扇门"},
    {"pc_archive_door","穿过门"},
    {"pc_archive_clock","午夜"},
    {"pc_archive_kill","被丽莎抓住"},
    {"pc_archive_ending","结局"},
    {"pc_archive_teaser","预告"},
    {"pc_archive_lisa_stand","丽莎（站立）"},
    {"pc_archive_lisa_walk","丽莎（行走）"},
    {"pc_archive_lisa_dash","丽莎（扑来）"},
    {"pc_archive_lisa_door","门后的丽莎"},
    {"pc_archive_baby","水槽里的胎儿"},
    {"pc_archive_fridge","冰箱"},
    {"pc_archive_bag_model","纸袋"},
    {"pc_archive_lamp","吊灯"},
    {"pc_archive_roach","蟑螂"},
    {"pc_archive_flashlight","手电筒"},
    {"pc_archive_radio","收音机"},
    {"pc_archive_phone_model","电话机"},
    {"pc_archive_xmark_photo","画着X的照片"},
    {"pc_archive_clock_model","时钟"},
    {"pc_archive_man","男人"},
    {"pc_archive_bathtub","浴缸里的尸体"},
};
inline std::string_view Menu(std::string_view key) {
    for (const auto& e : kMenu) if(e.key==key) return e.text;
    return {};
}
struct Subtitle { uint32_t key; std::initializer_list<std::string_view> lines; };
inline const Subtitle kSubtitles[] = {
    {0x54E4EFDE,{
        "国会围绕枪支管制的争论再度升温之际，",
        "我们遗憾地报道，一名女子和她的两个孩子|遭到身为丈夫和父亲的男子杀害。",
        "两天前，这名父亲在当地枪店|购买了作案所用的步枪。",
        "这起残忍的凶杀案发生在周日下午，|当时一家人正聚在家中。",
        "案发当天，父亲从汽车后备箱中取出步枪，|开枪射杀了午饭后正在收拾厨房的妻子。",
        "十岁的儿子闻声前来查看，|也被父亲开枪打死。",
        "六岁的女儿机灵地躲进了浴室，|但据报道，父亲谎称这只是个游戏，把她骗了出来。",
        "女孩被发现时胸部中了一枪，是近距离射击。",
        "腹部中枪的母亲当时正怀有身孕。",
        "邻居拨打 911 报警，警方赶到时，|发现这名父亲正坐在车里听收音机。",
        "据邻居说，案发前几天，|他们曾听见这名父亲大声反复念着一串数字。",
        "他们说，那听起来就像在念某种诡异的咒语。",
        "上个月，同一州还有一家人遭枪杀身亡；|去年十二月，",
        "一名男子用步枪和剁肉刀杀害了全家。",
        "这些案件的凶手都是父亲。",
        "州警方表示，这一连串家庭凶杀案似乎彼此无关，",
        "但它们可能反映出一个更大的趋势，与就业、|育儿以及普通家庭面临的其他社会问题有关。"}},
    {0xB91F5727,{
        "我走着。",
        "除了走，我什么也做不了。",
        "然后，我看到自己走在我的前面。",
        "但那其实不是我。",
        "小心。",
        "门缝……是另一重现实。",
        "只有我才是我。",
        "你确定只有你才是你吗？"}},
    {0x72E1954B,{
        "你丢了工作，于是借酒浇愁。",
        "她只好去杂货店当兼职收银员。",
        "她能挣到工资，唯一的原因|是经理喜欢看她穿裙子的样子。",
        "你还记得吧？",
        "整整十个月前。"}},
    {0x7D33E7DF,{
        "爸爸是个无趣的人。",
        "每天吃同样的饭菜，|穿同样的衣服，",
        "坐在同样的游戏前……",
        "没错，他就是那种人。",
        "可是有一天，他竟然把我们全杀了！",
        "连杀人的方式都毫无新意。",
        "我可没在抱怨……反正我早就无聊得要死了。",
        "不过你猜怎么着？我会回来的，",
        "还会带上我的新玩具。"}},
    {0xFBCD1565,{
        "是时候行动了。",
        "我们的社会已经烂到了根子里。",
        "我要对所有善良正直的人说，|你们的救济金被削减，饭碗被夺走。",
        "对，就是你！你知道该怎么做！",
        "就是现在！动手吧！"}},
    {0xDF405E61,{
        "你被选中了。"}},
    {0x40D69C3A,{
        "别换台，我们才刚刚开始。"}},
    {0x0AD16A8E,{
        "自来水不可信。"}},
    {0xC5EB59AA,{
        "看看你身后。",
        "我说，看看你身后。"}},
    {0x879FF72D,{
        "杀害家人后，这名父亲|用车库里的一根浇花水管上吊自尽。"}},
    {0x01E674E7,{
        "204863",
        "204863"}},
    {0x30DE6EF0,{
        "你的儿子……"}},
    {0x4926CF3C,{
        "送他去天堂吧……|……用你自己的手。",
        "现在动手还来得及。"}},
    {0x7AC3E25E,{
        "你……你干了什么？！",
        "当着所有人的面！",
        "我要把这件事捅到新闻上去，你这个疯子！",
        "杀人犯！"}},
    {0x7980630B,{
        "杀害家人后，这名父亲|用车库里的一根脐带上吊自尽。"}},
    {0xCE86DEBA,{
        "我的声音，你听得见吗？|这个标记，你看得懂吗？|只要你来找我，我会永远等下去。"}},
    {0x3E6F2ED2,{
        "我的声音，你听得见吗？|这个标记，你看得懂吗？"}},
    {0xD925B7BD,{
        "我的声音，你听得见吗？"}},
    {0x4AF4F3D4,{
        "原谅我，丽莎|我的身体里有一个怪物"}},
    {0x4FA7C4BD,{
        "我听见他们在地狱里呼唤我"}},
    {0xF124B2D3,{
        "已经回不了头了"}},
    {0x5D5A2A13,{
        "爸爸是个无趣的人。|每天吃同样的饭菜，穿同样的衣服，坐在同样的游戏前……|没错，他就是那种人。"}},
    {0x3FB2DE6F,{
        "对，就是你！你知道该怎么做！",
        "就是现在！",
        "动手吧！"}},
    {0xBF6D9A27,{
        "别换台，我们才刚刚开始。",
        "自来水不可信。",
        "204863",
        "看看你身后。",
        "我说，看看你身后。",
        "204863"}},
    {0xC52AE206,{
        "小心。门缝……|是另一重现实。"}},
    {0xD62FBBDA,{
        "只有我才是我。|你确定只有你才是你吗？"}},
    {0x99242989,{
        "本游戏为预告作品，|与正式作品没有直接关联。"}},
};
}
