#pragma once
#include <cstdint>
#include <initializer_list>
#include <string_view>

namespace pt::czech {
struct Text { std::string_view key, text; };
inline constexpr Text kMenu[] = {
    {"pc_controller_speaker","Reproduktor ovladače"},
    {"pc_note_controller_speaker","Přehrává nahrané výkřiky Lisy z podporovaných reproduktorů ovladačů Sony. Ve Windows je nutné připojení USB; nepodporovaná zařízení a Bluetooth zůstávají potichu. Nezávislé na haptice; ve výchozím stavu vypnuté."},
    {"pc_controller_speaker_volume","Hlasitost reproduktoru ovladače"},
    {"pc_note_controller_speaker_volume","Mění pouze hlasitost reproduktoru ovladače v krocích po 5 %. Nemění zvuk hry ani sílu haptiky DualSense. Dostupné jen pro podporované kabelové ovladače Sony ve Windows."},
    {"pc_microphone_trigger_assign","Přiřadit {input} ke spuštění mikrofonu"},
    {"pc_note_microphone_trigger","Volitelná alternativa k mikrofonu. Klávesnice a obě spouště ovladače ji aktivují jen tehdy, když hra naslouchá."},
    {"pc_note_microphone_test","Otestuje mikrofon a výsledek rozpoznávání."},
    {"pc_fps_limit","Omezení snímkové frekvence"},
    {"pc_unlimited","Bez omezení"},
    {"pc_note_fps_limit","Omezuje vykreslené snímky. Nabídky zůstávají omezené na 60 FPS. Vertikální synchronizace může nastavit nižší limit."},
    {"pc_hdr","Nativní HDR"},
    {"pc_note_hdr_restart","Použije se při příštím spuštění. Vyžaduje zapnuté HDR na kompatibilním displeji; jinak se použije SDR."},
    {"pc_surround","Prostorový zvuk"},
    {"pc_note_surround","Po restartu použije rozložení 5.1 nebo 7.1 výstupního zařízení. Stereofonní zařízení zůstávají stereofonní."},
    {"pc_rumble_profile","Režim vibrací"},
    {"pc_rumble_original","Původní"},
    {"pc_rumble_enhanced","Vylepšený"},
    {"pc_note_rumble_profile","Původní používá jen vibrace motorů podle původní hry. Vylepšený přidá podporované vibrace spouští a u podporovaných ovladačů DualSense přes USB ve Windows také haptiku odvozenou z filtrovaných výkřiků Lisy. Hlavní nastavení vibrací vypne obojí. Zvuk reproduktoru ovladače je nezávislý."},
    {"pc_vr_height","Nastavení výšky"},
    {"pc_note_vr_height","Posune sledovaný pohled nahoru nebo dolů, aniž by změnilo pozici hráče ve hře."},
    {"pc_vr_world_scale","Měřítko světa"},
    {"pc_note_vr_world_scale","Mění měřítko sledovaného pohybu hlavy, očí a ovladačů v rozsahu 50–200 %. Čím vyšší hodnota, tím menší se svět jeví. Výchozí hodnota: 100 %."},
    {"pc_photo_focal_length","Ohnisková vzdálenost"},
    {"pc_note_photo_focal_length","Ohnisková vzdálenost objektivu v milimetrech. Rozostření používá stejný objektiv a snímač jako kamera."},
    {"pc_photo_aspect","Poměr stran"},
    {"pc_note_photo_aspect","Ořízne fotografii od středu."},
    {"pc_photo_resolution","Rozlišení fotografie"},
    {"pc_note_photo_resolution","Nativní ukládá obrazové body v záběru. 4K znovu vykreslí scénu s delší stranou o 3840 obrazových bodech."},
    {"pc_photo_resolution_native","Nativní"},
    {"pc_photo_resolution_4k","4K"},
    {"pc_photo_filter","Barevný filtr"},
    {"pc_note_photo_filter","Použije se pouze v náhledu fotografie a v uloženém snímku."},
    {"pc_photo_filter_bw","Černobílý"},
    {"pc_photo_filter_warm","Teplý"},
    {"pc_photo_filter_cool","Studený"},
    {"pc_photo_filter_muted","Tlumený"},
    {"pc_archive_model_hint","WASD / levá páčka: posun záběru. Šipky / pravá páčka: otáčení. Spouště: zoom. Esc / kruh: zpět."},
    {"pc_note_resolution_fullscreen","Bezrámový režim používá zvolenou velikost; exkluzivní celá obrazovka používá podporované rozlišení displeje."},
    {"op_options","NASTAVENÍ"},
    {"op_back","Zpět"},
    {"op_brightness_setting","Jas"},
    {"op_britness_tip","Nastavte jas tak, aby byl vidět pouze obrázek vlevo."},
    {"op_subtitles_setting","Titulky"},
    {"op_sub_none","Vyp."},
    {"op_sub_english","Angličtina"},
    {"op_sub_french","Francouzština"},
    {"op_sub_german","Němčina"},
    {"op_sub_spanish","Španělština"},
    {"op_sub_japanese","Japonština"},
    {"op_sub_itlian","Italština"},
    {"op_sub_portuguese","Portugalština"},
    {"op_sub_turkish","Turečtina"},
    {"op_sub_chinese","Čínština (zjedn.)"},
    {"op_sub_arabic","Arabština"},
    {"op_sub_russian","Ruština"},
    {"op_sub_ukrainian","Ukrajinština"},
    {"op_sub_czech","Čeština"},
    {"op_sub_polish","Polština"},
    {"op_camera_setting","Kamera"},
    {"op_camera_y_axis","Svislá osa"},
    {"op_camera_x_axis","Vodorovná osa"},
    {"op_camera_normal","Normální"},
    {"op_camera_reversed","Obrácená"},
    {"pc_loop_browser","Výběr smyčky"},
    {"pc_note_loop_browser_entry","Začněte kteroukoli smyčkou, aniž by se změnila vaše uložená hra."},
    {"pc_loop_choose","Vyberte smyčku"},
    {"pc_loop_preview","Náhled"},
    {"pc_loop_start_hint","Enter / X / A: spustit"},
    {"pc_loop_f000","Úvodní místnost: prolog"},
    {"pc_loop_f010","Smyčka 1: rádio"},
    {"pc_loop_f005","Smyčka 2: otevírají se dveře do chodby"},
    {"pc_loop_f020","Smyčka 3: pláč v koupelně"},
    {"pc_loop_f030","Smyčka 4: dveře koupelny"},
    {"pc_loop_f040","Smyčka 5: Lisa na konci chodby"},
    {"pc_loop_f060","Smyčka 6: koupelna a svítilna"},
    {"pc_loop_f050a","Smyčka 7: Lisa jde za vámi"},
    {"pc_loop_f050b","Smyčka 8: fotografie s křížkem"},
    {"pc_loop_f070","Smyčka 9: rozbité okno"},
    {"pc_loop_f080","Smyčka 10: zakrvácená lednice"},
    {"pc_loop_f090","Smyčka 11: HELLO"},
    {"pc_loop_f100","Smyčka 12: rudá chodba"},
    {"pc_loop_f110","Smyčka 13: labyrint a kukátko"},
    {"pc_loop_f120","Smyčka 14: 204863, chybová obrazovka"},
    {"pc_loop_f160","Smyčka 15: poslední smyčka"},
    {"pc_loop_ending","Závěrečná scéna a titulky"},
    {"pc_loop_street","Procházka ulicí (po dohrání)"},
    {"pc_note_loop_opening","Spustí prolog v úvodní místnosti jako nová hra. Uložená hra se nezmění."},
    {"pc_note_loop_hallway","Začnete v úvodní místnosti před touto smyčkou, dřívější hádanky jsou vyřešené. Projděte dveřmi. Uložená hra se nezmění a obnoví se u další kontrolní pozice."},
    {"pc_note_loop_ending","Přehraje závěrečnou scénu a titulky, poté nabídne procházku ulicí. Uložená hra se nezmění."},
    {"pc_note_loop_street","Přenese vás na ulici z finále, pohled z první osoby. Odejít můžete v části „Bonusy“. Uložená hra se nezmění."},
    {"pc_note_loop_locked","Zamčeno. Dohrajte hru jednou a odemknou se všechny smyčky, ke kterým jste se dostali."},
    {"pc_note_loop_browser_locked","Dohrajte hru jednou a odemkne se výběr smyčky."},
    {"pc_street_title","Ulice"},
    {"pc_street_question","Prozkoumat ulici?"},
    {"pc_street_walk","Ano, projít se ulicí"},
    {"pc_credit_version","P.T. PC Port {1} od LoreanXavier"},
    {"pc_update_available","K dispozici je verze {1} (nyní {2})"},
    {"pc_credits_by","od LoreanXavier"},
    {"pc_credits_dlss","Tato hra používá NVIDIA DLSS."},
    {"pc_credits_licenses","Plná znění licencí jsou ve složce licenses vedle pt.exe."},
    {"pc_credits_konami","P.T. patří společnostem Konami Digital Entertainment a Kojima Productions."},
    {"pc_credits_fan","Tento port je neoficiální fanouškovský projekt, nijak nespojený se společnostmi Konami, NVIDIA, AMD ani Intel a jimi neschválený."},
    {"pc_note_street_walk","Procházka ulicí z finále z pohledu první osoby. Odejít můžete v části „Bonusy“."},
    {"pc_street_restart","Ne, vrátit se na začátek"},
    {"pc_note_street_restart","Začít znovu v úvodní místnosti, jako v originále po titulcích."},
    {"pc_street_leave","Opustit ulici"},
    {"pc_note_street_leave","Ukončí procházku a vrátí vás do úvodní místnosti."},
    {"pc_street_return","Vrátit se do domu"},
    {"pc_street_return_confirm","Vrátit se do domu?"},
    {"pc_loop_lock","Zamknout výběr smyčky"},
    {"pc_note_loop_lock","Znovu zamkne všechny smyčky ve výběru, jako před prvním dohráním. Uložená hra se nezmění."},
    {"pc_extras","Bonusy"},
    {"pc_vr","VR (experimentální)"},
    {"pc_note_vr","Hra ve VR headsetu přes OpenXR. Experimentální: neověřeno na skutečném zařízení."},
    {"pc_vr_mode","Režim VR"},
    {"pc_note_vr_mode","Neověřeno na skutečném zařízení. Vyžaduje prostředí OpenXR a headset. Projeví se od příštího spuštění; bez headsetu se hra spustí jako obvykle."},
    {"pc_vr_flashlight","Svítilna"},
    {"pc_note_vr_flashlight","Svítilna sleduje hlavu jako v originále, nebo ovladač v ruce."},
    {"pc_vr_head","Hlava"},
    {"pc_vr_controller","Ovladač"},
    {"pc_vr_turn","Otáčení"},
    {"pc_note_vr_turn","Pravá páčka otáčí po krocích, nebo plynule. Po krocích se méně dělá nevolno."},
    {"pc_vr_snap","Po krocích"},
    {"pc_vr_smooth","Plynule"},
    {"pc_note_extras","Výběr smyčky, volná kamera a fotorežim."},
    {"pc_freecam","Volná kamera"},
    {"pc_note_freecam","Kamera se oddělí od postavy a volně létá (F6). Mezerník / Ctrl nebo triggery: nahoru a dolů, Shift nebo L3: rychleji. Esc: konec."},
    {"pc_photo_mode","Fotorežim"},
    {"pc_note_photo_mode","Pauza a focení volnou kamerou (F7). P nebo „čtverec“: uložit do Pictures/PT Photos, H nebo „trojúhelník“: skrýt panel."},
    {"pc_speedrun","Časovač speedrunu"},
    {"pc_note_speedrun","Časovač na obrazovce se splituje u každé smyčky a obrazovkou s výsledky po titulcích. Reálný čas počítá všechno; herní čas nezahrnuje pauzy a načítání. V originále nic takového není."},
    {"pc_speedrun_real_time","Reálný čas"},
    {"pc_speedrun_game_time","Herní čas"},
    {"pc_livesplit","Server LiveSplit"},
    {"pc_note_livesplit","Odesílá start, splity a herní čas do LiveSplitu (Control > Start TCP Server, port {1}). Adresa a port jsou uvedeny v pt.ini."},
    {"pc_speedrun_results","RUN DOKONČEN"},
    {"pc_speedrun_run","Run"},
    {"pc_speedrun_splits","Splity"},
    {"pc_speedrun_menu","Zpět do nabídky"},
    {"pc_note_speedrun_menu","Začne od začátku jako originál po finále, nejprve s obrazovkou nastavení. Další run začne, jakmile získáte ovládání."},
    {"pc_speedrun_outside","Prozkoumat ulici"},
    {"pc_note_speedrun_outside","Projděte se ulicí z finále. Do domu se můžete vrátit z nabídky pauzy."},
    {"pc_note_speedrun_real","Reálný čas od získání ovládání do finále: včetně pauz, načítání a animací."},
    {"pc_note_speedrun_game","Pouze hra bez pauzy: nabídka pauzy a načítání po smrti se nezapočítávají."},
    {"pc_speedrun_best","Osobní rekord"},
    {"pc_note_speedrun_best","Předchozí rekord: {1}. Rekordy se ukládají do speedrun.ini, speedrun_history.txt a speedrun_pb.lss (LiveSplit) ve složce uživatele."},
    {"pc_speedrun_new_best","Nový rekord!"},
    {"pc_speedrun_partial","Ne od začátku"},
    {"pc_speedrun_start_room","Úvodní místnost"},
    {"pc_speedrun_loop","Smyčka {1}"},
    {"pc_third_person","Pohled z třetí osoby (experiment)"},
    {"pc_note_third_person","Experimentální funkce, která v originále není: kamera sleduje postavu přes rameno. Přiblížení a cutscény vrátí pohled z první osoby; události probíhají stejně jako z první osoby."},
    {"pc_extras_start","Zapnout"},
    {"pc_photo_title","FOTOREŽIM"},
    {"pc_photo_section_camera","Kamera"},
    {"pc_photo_section_lens","Objektiv"},
    {"pc_photo_section_image","Obraz"},
    {"pc_photo_take","Pořídit snímek"},
    {"pc_photo_capture","Vyfotit"},
    {"pc_photo_fov","Zorné pole"},
    {"pc_photo_roll","Náklon kamery"},
    {"pc_photo_speed","Rychlost kamery"},
    {"pc_photo_speed_slow","Nízká"},
    {"pc_photo_speed_normal","Normální"},
    {"pc_photo_speed_fast","Vysoká"},
    {"pc_photo_reset","Obnovit kameru"},
    {"pc_photo_focus","Zaostřovací vzdálenost"},
    {"pc_photo_aperture","Clona"},
    {"pc_photo_exposure","Expozice"},
    {"pc_photo_grading","Barevné ladění"},
    {"pc_photo_letterbox","Filmový formát"},
    {"pc_photo_body","Tělo postavy"},
    {"pc_photo_flashlight","Světlo"},
    {"pc_photo_shown","Zobrazit"},
    {"pc_photo_hidden","Skrýt"},
    {"pc_photo_auto","Auto"},
    {"pc_photo_metres","{value} m"},
    {"pc_photo_saved","Uloženo do Pictures/PT Photos: {file}"},
    {"pc_photo_save_failed","Fotografii se nepodařilo uložit. Viz pt.log."},
    {"pc_photo_hint","Šipky: výběr a změna. P / „čtverec“: snímek. H / „trojúhelník“: skrýt panel. Pravé tlačítko myši: rozhlížení. Esc / „kolečko“: konec."},
    {"pc_note_photo_take","Uloží aktuální záběr do Pictures/PT Photos. Panel se na snímku neobjeví."},
    {"pc_note_photo_fov","Vertikální zorný úhel ve stupních. Čím menší hodnota, tím větší přiblížení."},
    {"pc_note_photo_roll","Nakloní kameru na stranu a vytvoří „holandský úhel“."},
    {"pc_note_photo_speed","Rychlost pohybu kamery. Shift nebo L3 ji stále zrychlují."},
    {"pc_note_photo_reset","Vrátí kameru na místo, kde byl fotorežim zapnut."},
    {"pc_note_photo_dof","Rozostří vše, co je blíž nebo dál než zaostřovací vzdálenost."},
    {"pc_note_photo_focus","„Auto“: zaostří na to, co je uprostřed záběru."},
    {"pc_note_photo_aperture","Čím menší clonové číslo, tím silnější rozostření. „Auto“ ponechá objektiv hry."},
    {"pc_note_photo_exposure","Zesvětlí nebo ztmaví obraz po půlstupních."},
    {"pc_note_photo_grain","Filmové zrnění jako v originále. „Vyp.“ dává čistší obraz."},
    {"pc_note_photo_grading","Barevné ladění originálu. „Vyp.“ zobrazí neutrální barvy."},
    {"pc_note_photo_letterbox","Černé pruhy jako v kině. Na snímku zůstanou."},
    {"pc_note_photo_body","Zobrazí nebo skryje tělo postavy."},
    {"pc_note_photo_flashlight","Vypne světlo svítilny po dobu fotorežimu."},
    {"pc_extras_stop","Vypnout"},
    {"pc_note_loop_generating","Vytváří se náhled... Uložená hra se nezmění a obnoví se u další kontrolní pozice: po odchodu ze sklepa nebo v poslední smyčce."},
    {"pc_title","NASTAVENÍ PC"},
    {"pc_entry","Nastavení PC"},
    {"pc_back","Zpět"},
    {"pc_quit","Ukončit"},
    {"pc_nav_columns","Tab / L1 / R1: další sloupec"},
    {"pc_quit_confirm","Ukončit hru?"},
    {"pc_save_no_space","Není dost volného místa pro uložení hry.\nUvolněte místo a zavřete toto hlášení, abyste to mohli zkusit znovu."},
    {"pc_ok","OK"},
    {"pc_note_quit","Ukončí hru."},
    {"pc_note_quit_confirm","Stiskněte {accept} ještě jednou pro ukončení, nebo „Zpět“ pro zrušení."},
    {"pc_section_display","Obraz"},
    {"pc_section_upscaling","Upscaling"},
    {"pc_section_sound","Zvuk"},
    {"pc_section_controls","Ovládání"},
    {"pc_section_progress","Postup"},
    {"pc_section_ray_tracing","Ray tracing"},
    {"pc_section_textures","Textury"},
    {"pc_display_mode","Režim zobrazení"},
    {"pc_resolution","Rozlišení"},
    {"pc_vsync","V-Sync"},
    {"pc_focus_pause","Pauza na pozadí"},
    {"pc_focus_mute","Ztlumit na pozadí"},
    {"pc_upscaler","Metoda"},
    {"pc_quality","Režim"},
    {"pc_sharpness","Ostrost"},
    {"pc_frame_generation","Generování snímků"},
    {"pc_volume","Hlasitost"},
    {"pc_microphone","Mikrofon"},
    {"pc_microphone_test","Test mikrofonu"},
    {"pc_mic_level","Úroveň signálu"},
    {"pc_mic_heard","Rozpoznáno"},
    {"pc_mic_monitor","Slyšet sám sebe"},
    {"pc_mic_no_word","Zatím nic"},
    {"pc_mic_waiting","Čekání na vybraný mikrofon..."},
    {"pc_mic_unavailable","Vybraný mikrofon se nepodařilo otevřít. Zkontrolujte oprávnění k nahrávání a výběr zařízení."},
    {"pc_mic_st_loading","Načítání..."},
    {"pc_mic_st_nomic","Žádný mikrofon"},
    {"pc_mic_st_files","Chybí soubory řeči"},
    {"pc_mic_st_runtime","Selhání řečového modulu"},
    {"pc_mic_st_cpu","Nepodporovaný procesor"},
    {"pc_mic_st_model","Selhání řečového modelu"},
    {"pc_mic_st_silent","Žádný zvuk"},
    {"pc_mic_err_files","Chybí soubory pro rozpoznávání řeči. Přeinstalujte nebo opravte hru."},
    {"pc_mic_err_runtime","Řečový modul se nepodařilo načíst. Důvod je uveden v pt.log."},
    {"pc_mic_err_cpu","Tento procesor nedokáže spustit řečový modul."},
    {"pc_mic_err_model","Řečový model se nepodařilo načíst. Důvod je uveden v pt.log."},
    {"pc_mic_err_silent","Mikrofon je otevřený, ale nepřichází žádný zvuk. Zkontrolujte, že není ztlumený a že je vybráno správné zařízení."},
    {"pc_mic_say_jack","Řekněte do mikrofonu „Jack“. Test nemá vliv na řešení hádanky."},
    {"pc_mic_monitor_note","Slyšíte svůj mikrofon. Použijte sluchátka, aby nevznikalo pískání. Poslech se po opuštění testu vypne."},
    {"pc_mouse","Citlivost myši"},
    {"pc_gamepad_sensitivity","Citlivost otáčení ovladačem"},
    {"pc_camera_tilt","Náklon kamery"},
    {"pc_vibration","Vibrace"},
    {"pc_dead_zone","Mrtvá zóna páčky"},
    {"pc_reset","Smazat postup"},
    {"pc_graphics","Grafika"},
    {"pc_graphics_value","Otevřít"},
    {"pc_rt_shadows","Stíny (ray tracing)"},
    {"pc_rt_contact","Kontaktní stíny"},
    {"pc_shadows","Stíny"},
    {"pc_reflections","Odrazy"},
    {"pc_standard","Standardní"},
    {"pc_ray_traced","Ray tracing"},
    {"pc_rt_sharp_long","Ray tracing, ostré"},
    {"pc_rt_soft_long","Ray tracing, měkké"},
    {"pc_note_shadows","Od „Nízké“ po „Jako PS4“: stínové mapy originálu (512, 1024 nebo 2048 px). Ray tracing je nahrazuje: stíny jsou ostré jako v originále, nebo měkké."},
    {"pc_note_ao","„Standardní“: okolní zastínění v obrazovém prostoru z originálu. Ray tracing ztmavuje rohy a prostor pod předměty v celé scéně. V originále nic takového není."},
    {"pc_note_reflections","„Standardní“: odrazy na podlaze v obrazovém prostoru jako v originále. Ray tracing odráží i to, co je mimo obraz. Experimentální."},
    {"pc_rt_ao","Okolní zastínění"},
    {"pc_anisotropy","Anizotropní filtrování"},
    {"pc_enhanced_textures","Vylepšené textury"},
    {"pc_texture_preparing","Příprava"},
    {"pc_note_texture_tools_missing","Chybí nástroje nebo model pro vylepšení textur. Obnovte složku texture-tools z přenosné verze a zkuste to znovu. Původní textury nebyly změněny."},
    {"pc_note_texture_busy","Tuto mezipaměť textur právě vytváří jiná kopie hry. Počkejte na dokončení a zkuste to znovu. Původní textury nebyly změněny."},
    {"pc_note_texture_failed","Textury se nepodařilo připravit; původní zůstaly beze změny. Zkontrolujte volné místo na disku a příčinu v pt.log, poté to zkuste znovu."},
    {"pc_note_texture_preparing","Probíhá příprava vylepšených textur. Zatím jsou vidět původní; poté se textury změní bez restartu. „Vyp.“ přípravu zruší."},
    {"pc_note_enhanced_textures","Jednorázově vytvoří ostřejší barevné textury ze souborů hry. Včetně zdí a postav; 4096 px při 10 GB videopaměti, jinak 2048. „Vyp.“ je zruší; původní textury zůstanou."},
    {"pc_rt_sharp","Ostré"},
    {"pc_rt_soft","Měkké"},
    {"pc_on","Zap."},
    {"pc_off","Vyp."},
    {"pc_window","V okně"},
    {"pc_borderless","Bez rámečku"},
    {"pc_fullscreen","Celá obrazovka"},
    {"pc_native","Nativní"},
    {"pc_quality_quality","Kvalita"},
    {"pc_quality_balanced","Vyvážený"},
    {"pc_quality_performance","Výkon"},
    {"pc_quality_ultra","Max. výkon"},
    {"pc_quality_custom","Vlastní"},
    {"pc_system_default","Podle systému"},
    {"pc_reset_value","Smazat"},
    {"pc_reset_confirm","Potvrdit"},
    {"pc_reset_done","Hotovo"},
    {"pc_note_vsync","Použije se ihned. Synchronizuje výstup snímků s obnovovací frekvencí monitoru."},
    {"pc_note_vsync_off","Použije se ihned. Když je vypnuto, každý snímek se zobrazí, jakmile je hotový: snímková frekvence není omezena obnovovací frekvencí a může docházet k trhání obrazu."},
    {"pc_note_restart","Projeví se po restartu hry."},
    {"pc_note_display_mode","Mezi oknem a celou obrazovkou lze přepínat také klávesami Alt+Enter."},
    {"pc_note_resolution","Velikost okna."},
    {"pc_note_resolution_fullscreen","Na celé obrazovce se používá rozlišení plochy."},
    {"pc_note_upscaler_off","„Vyp.“: vykreslování v rozlišení obrazovky jako v originále."},
    {"pc_note_render_size","Vykreslování: {1}, výstup: {2}."},
    {"pc_note_needs_upscaler","Nejprve zapněte upscaling."},
    {"pc_note_sharpness_fsr","Vlastní zostření má pouze FSR. „Zřetelnost“ na stránce „Grafika“ funguje s libovolnou metodou upscalingu."},
    {"pc_note_reset","Smaže postup a okamžitě restartuje hru. Jazyk a nastavení PC zůstanou zachovány."},
    {"pc_note_reset_confirm","Stiskněte {accept} ještě jednou pro smazání uložené hry."},
    {"pc_note_reset_done","Postup byl smazán, hra začala znovu."},
    {"pc_note_camera_tilt","Kamera se naklání spolu s hlavou jako v originále."},
    {"pc_note_voice","Mikrofon poslouchá jen tam, kde to dělá původní hra."},
    {"pc_note_focus_pause","Otevře tuto nabídku, když okno hry přejde do pozadí."},
    {"pc_note_focus_mute","Vypne zvuk, dokud je okno hry na pozadí."},
    {"pc_note_frame_generation_missing","V tomto sestavení není dostupné."},
    {"pc_note_frame_generation","AMD FSR 3 vloží vygenerovaný snímek mezi dva vykreslené."},
    {"pc_note_fsr4_vulkan","AMD vydává FSR 4 pouze pro DirectX 12; tato hra běží na Vulkanu, takže FSR 4 zde není dostupné."},
    {"pc_dlss_model","Model DLSS"},
    {"pc_dlss_model_auto","Auto"},
    {"pc_note_dlss_model","Auto používá volbu NVIDIA: K do „Vyváženého“, M pro „Výkon“, L pro „Max. výkon“. Na RTX 20 a 30 jsou L a M zhruba dvakrát náročnější."},
    {"pc_note_frame_generation_dlss","Experimentální. NVIDIA DLSS Frame Generation vloží vygenerovaný snímek mezi dva vykreslené. Zapne se při příštím spuštění."},
    {"pc_note_dlssg_gpu","DLSS Frame Generation vyžaduje grafickou kartu NVIDIA GeForce RTX 40 nebo novější."},
    {"pc_note_fsr_fg_gpu","Generování snímků FSR 3 vyžaduje grafickou kartu AMD Radeon RX 5000 nebo novější."},
    {"pc_note_dlssg_driver","DLSS Frame Generation vyžaduje novější ovladač NVIDIA."},
    {"pc_note_dlssg_hags","DLSS Frame Generation vyžaduje hardwarově akcelerované plánování GPU (nastavení grafiky ve Windows)."},
    {"pc_note_dlssg_missing","V tomto sestavení DLSS Frame Generation není."},
    {"pc_note_dlssg_failed","DLSS Frame Generation se nepodařilo spustit, funkce byla vypnuta."},
    {"pc_note_dlssg_restart","Restartujte hru, aby se zapnulo DLSS Frame Generation."},
    {"pc_note_vsync_dlssg","Na Vulkanu DLSS Frame Generation běží bez vertikální synchronizace; nastavení opět platí, když je generování snímků vypnuto."},
    {"pc_note_fsr_fg_restart","Restartujte hru, aby se přešlo z DLSS Frame Generation na FSR 3."},
    {"pc_note_dead_zone","0,10: standardní hodnota DualShocku 4."},
    {"pc_note_gamepad_sensitivity","Mění rychlost otáčení až za původní odezvou páčky. Hodnota 1 ji zachová."},
    {"pc_note_rt_shadows","Stíny se počítají sledováním paprsků v celé scéně místo stínových map, s ostrostí originálu. V originále nic takového není."},
    {"pc_note_rt_soft","Stíny se sledováním paprsků a měkkými okraji závislými na velikosti zdroje světla. V originále nic takového není."},
    {"pc_note_rt_unsupported","Vyžaduje grafickou kartu s podporou ray tracingu ve Vulkanu."},
    {"pc_note_graphics","Vyberte grafický profil, nebo jemně upravte osvětlení, textury a efekty. Rozlišení a upscaling se nastavují zvlášť."},
    {"pc_note_rt_contact","Krátké stíny se sledováním paprsků od každého zdroje světla, včetně těch, které v originále stíny nevrhají."},
    {"pc_note_rt_ao","Okolní zastínění se sledováním paprsků ztmavuje rohy a prostor pod předměty i za nimi. V originále nic takového není."},
    {"pc_rt_reflections","Odrazy"},
    {"pc_note_rt_reflections","Podlaha odráží scénu za okraji obrazovky. Experimentální funkce; obraz se může lišit od originálu."},
    {"pc_note_anisotropy","Podlahy a stěny v ostrém úhlu vypadají ostřeji. „Vyp.“: filtrování jako v originále."},
    {"pc_graphics_quality","Kvalita"},
    {"pc_graphics_preset","Profil"},
    {"pc_preset_low","Nízká"},
    {"pc_preset_medium","Střední"},
    {"pc_preset_original","Jako PS4"},
    {"pc_preset_high","Vysoká"},
    {"pc_preset_ultra","Ultra"},
    {"pc_preset_custom","Vlastní"},
    {"pc_ray_tracing","Ray tracing"},
    {"pc_clarity","Zřetelnost"},
    {"pc_graphics_advanced","Pokročilé"},
    {"pc_graphics_lighting","Osvětlení"},
    {"pc_graphics_effects","Efekty"},
    {"pc_graphics_image","Obraz"},
    {"pc_lighting_standard","Standardní osvětlení"},
    {"pc_shadow_quality","Stínové mapy"},
    {"pc_standard_ao","Okolní zastínění"},
    {"pc_standard_reflections","Odrazy v obrazovém prostoru"},
    {"pc_ray_quality","Kvalita ray tracingu"},
    {"pc_ray_balanced","Vyvážená"},
    {"pc_texture_detail","Detail textur"},
    {"pc_detail_reduced","Snížený"},
    {"pc_detail_fine","Vysoký"},
    {"pc_dof","Hloubka ostrosti"},
    {"pc_motion_blur","Rozmazání pohybem"},
    {"pc_bloom","Záře"},
    {"pc_lens_ghosts","Odlesky objektivu"},
    {"pc_note_lens_ghosts","Velké odrazy odlesků objektivu přes celou obrazovku při pohledu poblíž lampy, jako v originále (PS4). „Vyp.“ je odstraní."},
    {"pc_film_grain","Filmová zrnitost"},
    {"pc_note_preset","Mění pouze grafiku, rozlišení a upscaling zůstávají beze změny. Ruční úpravy znamenají „Vlastní“. „Ultra“ zapne ray tracing, pokud je dostupný."},
    {"pc_note_ray_master","Společně zapíná nebo vypíná stíny se sledováním paprsků, kontaktní stíny, okolní zastínění a odrazy. Jednotlivě je najdete v části „Osvětlení“."},
    {"pc_lens_distortion","Efekt objektivu"},
    {"pc_note_lens_distortion","Zkreslení objektivu a barevné lemování jako v originále. „Vyp.“ dává ostřejší okraje a širší záběr bez ztmavených rohů."},
    {"pc_note_clarity","Mírně zvyšuje ostrost pomocí lokálního kontrastu ve výstupním rozlišení. 0: obraz jako v originále."},
    {"pc_note_letterbox","Černé pruhy nahoře a dole v záběru ve hře i v animacích. Titulky zůstávají v záběru. V originále nic takového není."},
    {"pc_note_advanced","Jemné nastavení této kategorie. „Zpět“ vrátí do části „Grafika“; po změnách se profil změní na „Vlastní“."},
    {"pc_note_shadow_quality","Stínové mapy 512, 1024 nebo původních 2048 px. Stíny se sledováním paprsků je v případě zapnutí nahrazují. Škálování rozlišení se nemění."},
    {"pc_note_standard_ao","Okolní zastínění v obrazovém prostoru z originálu. Vypněte, pokud chcete snížit zátěž slabší grafické karty."},
    {"pc_note_standard_reflections","Odrazy na podlaze v obrazovém prostoru z originálu. Jsou-li zapnuty odrazy se sledováním paprsků, nahradí tyto."},
    {"pc_note_ray_quality","Vyvážená: 2 paprsky. Vysoká: 4 paprsky. Ultra: 8 paprsků; stíny jsou měkčí a okolní zastínění se sledováním paprsků má méně šumu."},
    {"pc_note_texture_detail","„Snížený“: hrubší úrovně MIP. „Vysoký“: více detailů v dálce, možné blikání. Výstupní rozlišení se nemění."},
    {"pc_note_dof","Rozostření mimo ohnisko jako v originále. „Vyp.“ ponechá ostré blízké plochy i pozadí."},
    {"pc_note_motion_blur","Rozmazání při otáčení a pohybu jako v originále. „Vyp.“ zostří obraz v pohybu."},
    {"pc_note_bloom","Záře zdrojů světla jako v originále. „Vyp.“ odstraní svatozáře a sníží zátěž následného zpracování."},
    {"pc_note_film_grain","Síla filmového zrnění jako v originále. „Vyp.“: čistý obraz; 100 %: efekt jako v originále."},
    {"pc_mods","Módy"},
    {"pc_section_mods","Nainstalované módy"},
    {"pc_note_mods","Zapnutí nebo vypnutí módu se projeví po restartu. Módy nejsou součástí původní hry."},
    {"pc_archive","Muzeum"},
    {"pc_note_archive","Obrázky, hlasy, útržky fotografie, animace a modely samotné hry; odemykají se postupem hrou. Vaše hra se nemění."},
    {"pc_note_extras_archive","Výběr smyčky, muzeum, volná kamera a fotorežim."},
    {"pc_archive_sections","Sály"},
    {"pc_archive_images","Podprahové obrazy"},
    {"pc_archive_voices","Hlasy a rádio"},
    {"pc_archive_photos","Útržky fotografie"},
    {"pc_archive_cutscenes","Animace"},
    {"pc_archive_models","Modely"},
    {"pc_archive_unused","Nepoužité"},
    {"pc_note_archive_images","Texty podprahových záblesků, šum záblesků a pohled skrz kukátko."},
    {"pc_note_archive_voices","Rozhlasové relace a všechny repliky s textem v jazyce titulků."},
    {"pc_note_archive_photos","Roztrhané útržky fotografie a snímek, který dohromady tvoří, v rámečku."},
    {"pc_note_archive_cutscenes","Každá animace od začátku, se zvukem a titulky."},
    {"pc_note_archive_models","Lisa a další postavy a předměty z chodby ve světle úvodní místnosti."},
    {"pc_note_archive_unused_section","Obsah herních souborů, který hra nikdy neukazuje. Odemkne se po dohrání hry."},
    {"pc_note_archive_image","Enter / „křížek“: na celou obrazovku."},
    {"pc_note_archive_voice","Enter / „křížek“: přehrát nebo zastavit."},
    {"pc_note_archive_photo","Enter / „křížek“: na celou obrazovku."},
    {"pc_note_archive_demo","Enter / „křížek“: přehrát od začátku. Esc / „kolečko“ zastaví."},
    {"pc_note_archive_model","Enter / „křížek“: zobrazit model. Esc / „kolečko“: zpět."},
    {"pc_note_archive_unused","Ve hře se nezobrazuje. Enter / „křížek“: zobrazit model."},
    {"pc_note_archive_locked","Zamčeno. Dostaňte se k tomu ve hře a odemkne se."},
    {"pc_note_archive_playing","Přehrává se. Enter / „křížek“ zastaví."},
    {"pc_archive_lock","Zamknout muzeum"},
    {"pc_note_archive_lock","Znovu zamkne všechny exponáty muzea jako před začátkem hry. Uložená hra se nemění."},
    {"pc_archive_hint","Enter / X / A: otevřít"},
    {"pc_archive_view_hint","Vlevo / vpravo: předchozí / další. Esc / „kolečko“: zpět."},
    {"pc_archive_demo_hint","Esc / „kolečko“ / Enter / „křížek“: zastavit"},
    {"pc_archive_model_hint","Šipky / páčky: otáčet. W / S / spouště: blíž / dál. Esc / „kolečko“: zpět."},
    {"pc_archive_sub","Podprahový text {1}"},
    {"pc_archive_noise","Šum"},
    {"pc_archive_noise_normal","Zkreslení šumu"},
    {"pc_archive_peephole_mask","Pohled skrz kukátko"},
    {"pc_archive_radio_news","Rádio: zprávy"},
    {"pc_archive_radio_news2","Rádio: zprávy podruhé"},
    {"pc_archive_radio_voice","Hlas rádia {1}"},
    {"pc_archive_riddle","Hádanka rádia {1}"},
    {"pc_archive_sermon","Rádio: kázání"},
    {"pc_archive_phone","Telefonní hovor"},
    {"pc_archive_peephole_voice","Skrz kukátko"},
    {"pc_archive_bag","Taška, která mluví"},
    {"pc_archive_fetus","Hlas plodu {1}"},
    {"pc_archive_photo_lisa","Útržek: Lisa"},
    {"pc_archive_photo_tree","Útržek: strom"},
    {"pc_archive_photo_gap","Útržek: škvíra"},
    {"pc_archive_photo_bath","Útržek: koupelna"},
    {"pc_archive_photo_stair","Útržek: schody"},
    {"pc_archive_photo_option","Útržek: obrazovka nastavení"},
    {"pc_archive_photo_complete","Složená fotografie"},
    {"pc_archive_preface","Prolog"},
    {"pc_archive_awakening","První probuzení"},
    {"pc_archive_opening","Probuzení"},
    {"pc_archive_first_exit","První dveře"},
    {"pc_archive_door","Skrz dveře"},
    {"pc_archive_clock","Půlnoc"},
    {"pc_archive_kill","V Lisiných rukou"},
    {"pc_archive_ending","Závěr"},
    {"pc_archive_teaser","Teaser"},
    {"pc_archive_lisa_stand","Lisa stojí"},
    {"pc_archive_lisa_walk","Lisa jde"},
    {"pc_archive_lisa_dash","Lisa se vrhá"},
    {"pc_archive_lisa_door","Lisa za dveřmi"},
    {"pc_archive_baby","Plod v umyvadle"},
    {"pc_archive_fridge","Lednice"},
    {"pc_archive_bag_model","Papírová taška"},
    {"pc_archive_lamp","Stropní lampa"},
    {"pc_archive_roach","Šváb"},
    {"pc_archive_flashlight","Svítilna"},
    {"pc_archive_radio","Rádio"},
    {"pc_archive_phone_model","Telefon"},
    {"pc_archive_xmark_photo","Fotografie s křížkem"},
    {"pc_archive_clock_model","Hodiny"},
    {"pc_archive_man","Muž"},
    {"pc_archive_bathtub","Tělo ve vaně"},
};
inline std::string_view Menu(std::string_view key) {
    for (const auto& e : kMenu) if(e.key==key) return e.text;
    return {};
}
struct Subtitle { uint32_t key; std::initializer_list<std::string_view> lines; };
inline const Subtitle kSubtitles[] = {
    {0x54E4EFDE,{
        "Zatím co se v Kongresu debatuje o omezení držení zbraní,",
        "s hlubokým zármutkem oznamujeme: ženu a její dvě děti|zavraždil její vlastní manžel a jejich otec.",
        "Pušku, kterou byl čin spáchán, koupil otec|v místní prodejně zbraní dva dny před vraždou.",
        "K brutální vraždě došlo v neděli odpoledne,|kdy byla celá rodina doma.",
        "Otec toho dne vyndal pušku z kufru svého auta|a zastřelil manželku, která po obědě uklízela v kuchyni.",
        "Když jeho desetiletý syn přiběhl|zjistit co to bylo za ránu, zastřelil otec i jeho.",
        "Šestiletá dcera měla dost rozumu na to, schovat se v koupelně,|ale podle dostupných informací ji otec vylákal tím, že řekl, že je to jen hra.",
        "Dívku našli se střelnou ranou do hrudi z bezprostřední blízkosti.",
        "Matka, kterou střelil do břicha, byla těhotná.",
        "Policie, která přijela po tom co sousedi zavolali na 911,|našla otce v autě: poslouchal rádio.",
        "Podle sousedů slyšeli několik dní před vraždou,|jak otec nahlas opakuje stále stejnou posloupnost čísel.",
        "Prý to znělo jako nějaké podivné zaklínadlo.",
        "Minulý měsíc byla ve stejném státě zastřelena další rodina,|a loni v prosinci",
        "muž zabil celou svou rodinu puškou a řeznickým sekáčkem.",
        "Ve všech případech byli vrahy otcové.",
        "Státní policie se domnívá, že tyto rodinné vraždy spolu nesouvisejí,",
        "ale mohou být součástí širšího trendu spojeného s prací,|péčí o děti a dalšími sociálními problémy běžných rodin."}},
    {0xB91F5727,{
        "Kráčel jsem.",
        "Nemohl jsem dělat nic jiného než kráčet.",
        "A pak jsem před sebou uviděl sám sebe, jak kráčím.",
        "Ale nebyl jsem to opravdu já.",
        "Dávej pozor.",
        "Ta škvíra ve dveřích... je jiná realita.",
        "Jediné já jsem já.",
        "Jsi si jistý, že jediné ty jsi ty?"}},
    {0x72E1954B,{
        "Dostal jsi padáka a začal jsi utápět žal v alkoholu.",
        "Musela si najít brigádu jako pokladní v potravinách.",
        "Platili jí jen proto že se|manažérovi líbilo, jak vypadá v sukni.",
        "Vždyť si to pamatuješ? Ne?",
        "Přesně před deseti měsíci."}},
    {0x7D33E7DF,{
        "Táta byl fakt otrava.",
        "Každý den jedl totéž,|oblékal se stejně,",
        "seděl furt u stejných her...",
        "Jo, takový prostě byl.",
        "A pak nás jednoho dne všechny zabil!",
        "Ani zabít nás nedokázal originálně.",
        "Nestěžuju si... stejně jsem se k smrti nudil.",
        "Ale víš co? Vrátím se",
        "a přinesu si sebou své nové hračky."}},
    {0xFBCD1565,{
        "Je čas jednat.",
        "Naše společnost je shnilá skrz naskrz.",
        "Obracím se na všechny poctivé, slušné lidi,|kterým snížili dávky a vzali práci.",
        "Ano, ty! Ty víš, co máš dělat!",
        "Čas nadešel! Udělej to!"}},
    {0xDF405E61,{
        "Byl jsi vybrán."}},
    {0x40D69C3A,{
        "Nepřepínejte, teprve začínáme."}},
    {0x0AD16A8E,{
        "Vodě z kohoutku se nedá věřit."}},
    {0xC5EB59AA,{
        "Koukni se za sebe.",
        "Řekl jsem, koukni se za sebe."}},
    {0x879FF72D,{
        "Poté, co zabil rodinu, se otec oběsil|na zahradní hadici v garáži."}},
    {0x01E674E7,{
        "204863",
        "204863"}},
    {0x30DE6EF0,{
        "Tvůj syn..."}},
    {0x4926CF3C,{
        "Pošli ho do nebe...|...vlastní rukou.",
        "Ještě není pozdě, pokud si pospíšíš."}},
    {0x7AC3E25E,{
        "Ty... cos to provedl?!",
        "Před všemi!",
        "Řeknu to ve zprávách, ty cvoku!",
        "VRAHU!"}},
    {0x7980630B,{
        "Poté, co zabil rodinu, se otec oběsil|na pupeční šňůře v garáži."}},
    {0xCE86DEBA,{
        "Můj hlas, slyšíš ho?|Tento vzkaz, dokážeš ho přečíst?|Budu čekat věčně, jestli za mnou přijdeš."}},
    {0x3E6F2ED2,{
        "Můj hlas, slyšíš ho?|Tento vzkaz, dokážeš ho přečíst?"}},
    {0xD925B7BD,{
        "Můj hlas, slyšíš ho?"}},
    {0x4AF4F3D4,{
        "Odpusť mi, Liso|Uvnitř mě je nestvůra"}},
    {0x4FA7C4BD,{
        "Slyším, jak na mě volají z pekla"}},
    {0xF124B2D3,{
        "Není cesty zpět"}},
    {0x5D5A2A13,{
        "Táta byl fakt otrava.|Každý den jedl totéž, oblékal se stejně, seděl furt u stejných her...|Jo, takový prostě byl."}},
    {0x3FB2DE6F,{
        "Ano, ty! Ty víš, co máš dělat!",
        "Čas nadešel!",
        "Udělej to!"}},
    {0xBF6D9A27,{
        "Nepřepínejte, teprve začínáme.",
        "Vodě z kohoutku se nedá věřit.",
        "204863",
        "Koukni se za sebe.",
        "Řekl jsem, koukni se za sebe.",
        "204863"}},
    {0xC52AE206,{
        "Dávej pozor. Ta škvíra ve dveřích...|je jiná realita."}},
    {0xD62FBBDA,{
        "Jediné já jsem já.|Jsi si jistý, že jediné ty jsi ty?"}},
    {0x99242989,{
        "Tato hra je upoutávka.|Nesouvisí přímo s hlavní hrou."}},
};
}

