#pragma once
#include <string_view>

// French for the port's own menus (PC settings, extras, photo mode, loop browser, notes and prompts) and the added
// languages' names on the option screen. The options screen's other texts and the subtitles are the game's own.
namespace pt::french {
struct Text { std::string_view key, text; };
inline constexpr Text kMenu[] = {
    {"pc_controller_speaker","Haut-parleur de la manette"},
    {"pc_note_controller_speaker","Diffuse les cris enregistrés de Lisa sur les haut-parleurs compatibles des manettes Sony. Sous Windows, une connexion USB est requise ; les appareils non pris en charge et Bluetooth restent silencieux. Indépendant du retour haptique ; désactivé par défaut."},
    {"pc_controller_speaker_volume","Volume du haut-parleur de la manette"},
    {"pc_note_controller_speaker_volume","Règle uniquement le volume du haut-parleur de la manette, par pas de 5 %. Ne modifie ni le son du jeu ni la force haptique de DualSense. Disponible uniquement avec une manette Sony filaire prise en charge sous Windows."},
    {"pc_microphone_trigger_assign","Assigner {input} au déclencheur du micro"},
    {"pc_note_microphone_trigger","Entrée facultative en remplacement du microphone. Le clavier et les deux gâchettes de la manette l’activent uniquement quand le jeu écoute."},
    {"pc_note_microphone_test","Teste le microphone et le résultat de la reconnaissance."},
    {"pc_fps_limit","Limite d’images par seconde"},
    {"pc_unlimited","Illimité"},
    {"pc_note_fps_limit","Limite les images rendues. Les menus restent limités à 60 i/s. La synchronisation verticale peut imposer une limite plus basse."},
    {"pc_hdr","HDR natif"},
    {"pc_note_hdr_restart","Prend effet au prochain démarrage. Nécessite le HDR activé sur un écran compatible ; sinon, le mode SDR est utilisé."},
    {"pc_surround","Sortie surround"},
    {"pc_note_surround","Utilise la configuration 5.1 ou 7.1 de la sortie après redémarrage. Les appareils stéréo restent en stéréo."},
    {"pc_rumble_profile","Mode de vibration"},
    {"pc_rumble_original","Original"},
    {"pc_rumble_enhanced","Amélioré"},
    {"pc_note_rumble_profile","Original conserve la vibration des moteurs prévue par le jeu. Amélioré ajoute la vibration des gâchettes compatibles et, sur les manettes DualSense USB prises en charge sous Windows, l’haptique tirée des cris filtrés de Lisa. Le réglage principal de vibration désactive les deux. Le son du haut-parleur de la manette reste indépendant."},
    {"pc_vr_height","Réglage de la hauteur"},
    {"pc_note_vr_height","Déplace le point de vue suivi vers le haut ou le bas sans changer la position du joueur dans le jeu."},
    {"pc_vr_world_scale","Échelle du monde"},
    {"pc_note_vr_world_scale","Met à l’échelle les mouvements suivis de la tête, des yeux et des manettes de 50 à 200 %. Plus la valeur est élevée, plus le monde semble petit. Valeur par défaut : 100 %."},
    {"pc_photo_focal_length","Longueur focale"},
    {"pc_note_photo_focal_length","Longueur focale de l’objectif en millimètres. Le flou de mise au point utilise le même objectif et le même capteur que la caméra."},
    {"pc_photo_aspect","Format d’image"},
    {"pc_note_photo_aspect","Recadre la photo au centre."},
    {"pc_photo_resolution","Résolution photo"},
    {"pc_note_photo_resolution","Le mode natif enregistre les pixels cadrés. Le mode 4K restitue la scène avec un grand côté de 3840 pixels."},
    {"pc_photo_resolution_native","Natif"},
    {"pc_photo_resolution_4k","4K"},
    {"pc_photo_filter","Filtre couleur"},
    {"pc_note_photo_filter","S’applique uniquement à l’aperçu photo et à la photo enregistrée."},
    {"pc_photo_filter_bw","Noir et blanc"},
    {"pc_photo_filter_warm","Chaud"},
    {"pc_photo_filter_cool","Froid"},
    {"pc_photo_filter_muted","Atténué"},
    {"pc_archive_model_hint","WASD / stick gauche : déplacer le cadrage. Flèches / stick droit : tourner. Gâchettes : zoom. Échap / Rond : retour."},
    {"pc_note_resolution_fullscreen","Le mode sans bordure utilise la taille choisie ; le plein écran exclusif utilise une taille d’écran prise en charge."},
    {"op_sub_turkish","Turc"},
    {"op_sub_chinese","Chinois simplifié"},
    {"op_sub_arabic","Arabe"},
    {"op_sub_russian","Russe"},
    {"op_sub_ukrainian","Ukrainien"},
    {"op_sub_czech","Tchèque"},
    {"op_sub_polish","Polonais"},
    {"pc_loop_browser","Sélection de boucle"},
    {"pc_note_loop_browser_entry","Démarrez n'importe quelle boucle sans remplacer votre sauvegarde."},
    {"pc_loop_choose","Choisissez une boucle"},
    {"pc_loop_preview","Aperçu"},
    {"pc_loop_start_hint","Entrée / X / A : démarrer la boucle"},
    {"pc_loop_f000","Pièce de départ : l'ouverture"},
    {"pc_loop_f010","Boucle 1 : la radio"},
    {"pc_loop_f005","Boucle 2 : la porte de l'entrée s'ouvre"},
    {"pc_loop_f020","Boucle 3 : des pleurs dans la salle de bain"},
    {"pc_loop_f030","Boucle 4 : la porte de la salle de bain"},
    {"pc_loop_f040","Boucle 5 : Lisa au bout du couloir"},
    {"pc_loop_f060","Boucle 6 : la salle de bain, la lampe torche"},
    {"pc_loop_f050a","Boucle 7 : Lisa vous suit"},
    {"pc_loop_f050b","Boucle 8 : la photo marquée d'une croix"},
    {"pc_loop_f070","Boucle 9 : la fenêtre se brise"},
    {"pc_loop_f080","Boucle 10 : le frigo qui saigne"},
    {"pc_loop_f090","Boucle 11 : HELLO"},
    {"pc_loop_f100","Boucle 12 : le couloir rouge"},
    {"pc_loop_f110","Boucle 13 : le labyrinthe et le judas"},
    {"pc_loop_f120","Boucle 14 : 204863, l'écran de plantage"},
    {"pc_loop_f160","Boucle 15 : la dernière boucle"},
    {"pc_loop_ending","Cinématique de fin et générique"},
    {"pc_loop_street","Balade dans la rue (après la fin)"},
    {"pc_note_loop_opening","Lance l'ouverture dans la pièce de départ, comme une nouvelle partie. Votre sauvegarde est conservée."},
    {"pc_note_loop_hallway","Démarre dans la pièce de départ juste avant cette boucle, énigmes précédentes résolues. Franchissez la porte. Votre sauvegarde est conservée ; l'enregistrement reprend au prochain point de contrôle."},
    {"pc_note_loop_ending","Lance la cinématique de fin et le générique, puis propose la balade dans la rue. Votre sauvegarde est conservée."},
    {"pc_note_loop_street","Vous place dans la rue de la fin, à la première personne. Quittez-la depuis Bonus. Votre sauvegarde est conservée."},
    {"pc_note_loop_locked","Verrouillé. Terminez le jeu une fois : chaque boucle atteinte en jouant s'ouvre alors."},
    {"pc_note_loop_browser_locked","Terminez le jeu une fois pour déverrouiller la sélection de boucle."},
    {"pc_street_title","La rue"},
    {"pc_street_question","Explorer la rue ?"},
    {"pc_street_walk","Oui, marcher dans la rue"},
    {"pc_credit_version","P.T. PC Port {1} par LoreanXavier"},
    {"pc_update_available","Version {1} disponible (celle-ci est la {2})"},
    {"pc_credits_by","par LoreanXavier"},
    {"pc_credits_dlss","Ce jeu utilise NVIDIA DLSS."},
    {"pc_credits_licenses","Les textes complets des licences se trouvent dans le dossier licenses, à côté de pt.exe."},
    {"pc_credits_konami","P.T. appartient à Konami Digital Entertainment et à Kojima Productions."},
    {"pc_credits_fan","Ce portage est un projet de fan non officiel, sans lien avec Konami, NVIDIA, AMD ou Intel et sans leur approbation."},
    {"pc_note_street_walk","Parcourez à la première personne la rue de la fin. Quittez-la depuis Bonus."},
    {"pc_street_restart","Non, revenir au début"},
    {"pc_note_street_restart","Recommence dans la pièce de départ, comme l'original après le générique."},
    {"pc_street_leave","Quitter la rue"},
    {"pc_note_street_leave","Termine la balade et ramène à la pièce de départ."},
    {"pc_street_return","Retourner à la maison"},
    {"pc_street_return_confirm","Retourner à la maison ?"},
    {"pc_loop_lock","Verrouiller la sélection de boucle"},
    {"pc_note_loop_lock","Verrouille de nouveau toutes les boucles, comme avant votre première partie terminée. Votre sauvegarde ne change pas."},
    {"pc_extras","Bonus"},
    {"pc_vr","VR (expérimental)"},
    {"pc_note_vr","Jouer avec un casque VR via OpenXR. Expérimental : non testé sur du vrai matériel."},
    {"pc_vr_mode","Mode VR"},
    {"pc_note_vr_mode","Non testé sur du vrai matériel. Nécessite un runtime OpenXR et un casque. S'applique au prochain lancement ; sans casque, le jeu démarre normalement."},
    {"pc_vr_flashlight","Lampe torche"},
    {"pc_note_vr_flashlight","La lampe suit votre tête, comme dans l'original, ou la manette dans votre main."},
    {"pc_vr_head","Tête"},
    {"pc_vr_controller","Manette"},
    {"pc_vr_turn","Rotation"},
    {"pc_note_vr_turn","Le stick droit tourne par paliers ou en continu. Les paliers sont plus doux pour l'estomac."},
    {"pc_vr_snap","Par paliers"},
    {"pc_vr_smooth","Continue"},
    {"pc_note_extras","Sélection de boucle, caméra libre et mode photo."},
    {"pc_freecam","Caméra libre"},
    {"pc_note_freecam","Détache la caméra du joueur (F6). Espace / Ctrl ou les gâchettes : monter et descendre, Maj ou L3 : plus vite. Échap : quitter."},
    {"pc_photo_mode","Mode photo"},
    {"pc_note_photo_mode","Met le jeu en pause pour cadrer avec la caméra libre (F7). P ou Carré : enregistrer dans Pictures/PT Photos, H ou Triangle : masquer le panneau."},
    {"pc_speedrun","Chronomètre speedrun"},
    {"pc_note_speedrun","Un chronomètre à l'écran avec un temps intermédiaire à chaque boucle et un écran de résultats après le générique. Le temps réel compte tout ; le temps de jeu exclut les pauses et les chargements. Absent de l'original."},
    {"pc_speedrun_real_time","Temps réel"},
    {"pc_speedrun_game_time","Temps de jeu"},
    {"pc_livesplit","Serveur LiveSplit"},
    {"pc_note_livesplit","Envoie le départ, les temps intermédiaires et le temps de jeu à LiveSplit (Control > Start TCP Server, port {1}). L'hôte et le port sont dans pt.ini."},
    {"pc_speedrun_results","PARTIE TERMINÉE"},
    {"pc_speedrun_run","Partie"},
    {"pc_speedrun_splits","Temps intermédiaires"},
    {"pc_speedrun_menu","Retour au menu"},
    {"pc_note_speedrun_menu","Recommence depuis le début comme l'original après la fin, avec d'abord l'écran des options. La partie suivante démarre quand vous reprenez le contrôle."},
    {"pc_speedrun_outside","Explorer dehors"},
    {"pc_note_speedrun_outside","Marcher dans la rue de la fin. Retournez à la maison depuis le menu pause."},
    {"pc_note_speedrun_real","Horloge réelle de la prise de contrôle à la fin : pauses, chargements et cinématiques compris."},
    {"pc_note_speedrun_game","Jeu hors pause seulement : le menu pause et les chargements après un game over sont exclus."},
    {"pc_speedrun_best","Record personnel"},
    {"pc_note_speedrun_best","Record précédent : {1}. Les records sont dans speedrun.ini, speedrun_history.txt et speedrun_pb.lss (LiveSplit) dans le dossier utilisateur."},
    {"pc_speedrun_new_best","Nouveau record !"},
    {"pc_speedrun_partial","Pas depuis le début"},
    {"pc_speedrun_start_room","Pièce de départ"},
    {"pc_speedrun_loop","Boucle {1}"},
    {"pc_third_person","Troisième personne (expérimental)"},
    {"pc_note_third_person","Expérimental, absent de l'original : la caméra suit le joueur par-dessus l'épaule. Le zoom et les cinématiques repassent à la première personne ; les événements se déroulent comme en première personne."},
    {"pc_extras_start","Démarrer"},
    {"pc_photo_title","MODE PHOTO"},
    {"pc_photo_section_camera","Caméra"},
    {"pc_photo_section_lens","Objectif"},
    {"pc_photo_section_image","Image"},
    {"pc_photo_take","Prendre une photo"},
    {"pc_photo_capture","Capturer"},
    {"pc_photo_fov","Champ de vision"},
    {"pc_photo_roll","Roulis de la caméra"},
    {"pc_photo_speed","Vitesse de la caméra"},
    {"pc_photo_speed_slow","Lente"},
    {"pc_photo_speed_normal","Normale"},
    {"pc_photo_speed_fast","Rapide"},
    {"pc_photo_reset","Réinitialiser la caméra"},
    {"pc_photo_focus","Distance de mise au point"},
    {"pc_photo_aperture","Ouverture"},
    {"pc_photo_exposure","Exposition"},
    {"pc_photo_grading","Étalonnage"},
    {"pc_photo_letterbox","Bandes noires"},
    {"pc_photo_body","Corps du joueur"},
    {"pc_photo_flashlight","Lampe torche"},
    {"pc_photo_shown","Affiché"},
    {"pc_photo_hidden","Masqué"},
    {"pc_photo_auto","Auto"},
    {"pc_photo_metres","{value} m"},
    {"pc_photo_saved","Enregistrée dans Pictures/PT Photos : {file}"},
    {"pc_photo_save_failed","Impossible d’enregistrer la photo. Consultez pt.log."},
    {"pc_photo_hint","Flèches / croix directionnelle : choisir et modifier. P / Carré : photo. H / Triangle : masquer le panneau. Clic droit : regarder. Échap / Rond : quitter."},
    {"pc_note_photo_take","Enregistre la vue actuelle dans Pictures/PT Photos. Le panneau n'apparaît jamais sur la photo."},
    {"pc_note_photo_fov","Champ de vision vertical en degrés. Une valeur plus basse rapproche l'image."},
    {"pc_note_photo_roll","Incline la caméra sur le côté pour un plan débullé."},
    {"pc_note_photo_speed","Vitesse de déplacement de la caméra. Maj ou L3 accélèrent toujours."},
    {"pc_note_photo_reset","Ramène la caméra à l'endroit où le mode photo a commencé."},
    {"pc_note_photo_dof","Floute ce qui est plus proche ou plus loin que la distance de mise au point."},
    {"pc_note_photo_focus","Auto fait la mise au point sur ce qui est au centre de l'image."},
    {"pc_note_photo_aperture","Plus le nombre f est bas, plus le flou est fort. Auto conserve l'objectif du jeu."},
    {"pc_note_photo_exposure","Éclaircit ou assombrit l'image par demi-diaphragme."},
    {"pc_note_photo_grain","Le grain de film d'origine. Désactivé donne une image plus propre."},
    {"pc_note_photo_grading","Les couleurs d'origine. Désactivé affiche des couleurs neutres."},
    {"pc_note_photo_letterbox","Bandes noires cinéma. Elles apparaissent sur la photo."},
    {"pc_note_photo_body","Affiche ou masque le corps du joueur."},
    {"pc_note_photo_flashlight","Éteint la lampe torche pendant le mode photo."},
    {"pc_extras_stop","Arrêter"},
    {"pc_note_loop_generating","Création des aperçus... Votre sauvegarde est conservée. L'enregistrement reprend au prochain point de contrôle : en quittant le sous-sol ou en atteignant la dernière boucle."},
    {"pc_title","PARAMÈTRES PC"},
    {"pc_entry","Paramètres PC"},
    {"pc_back","Retour"},
    {"pc_quit","Quitter"},
    {"pc_nav_columns","Tab / L1 / R1 : changer de colonne"},
    {"pc_quit_confirm","Quitter ?"},
    {"pc_save_no_space","Espace disque insuffisant pour sauvegarder la partie.\nLibérez de l'espace, puis fermez ce message pour réessayer."},
    {"pc_ok","OK"},
    {"pc_note_quit","Quitter le jeu."},
    {"pc_note_quit_confirm","Appuyez de nouveau sur {accept} pour quitter. Retour pour annuler."},
    {"pc_section_display","Affichage"},
    {"pc_section_upscaling","Mise à l'échelle"},
    {"pc_section_sound","Son"},
    {"pc_section_controls","Commandes"},
    {"pc_section_progress","Progression"},
    {"pc_section_ray_tracing","Ray tracing"},
    {"pc_section_textures","Textures"},
    {"pc_display_mode","Mode d'affichage"},
    {"pc_resolution","Résolution"},
    {"pc_vsync","Synchro verticale"},
    {"pc_focus_pause","Pause en arrière-plan"},
    {"pc_focus_mute","Muet en arrière-plan"},
    {"pc_upscaler","Méthode"},
    {"pc_quality","Mode"},
    {"pc_sharpness","Netteté"},
    {"pc_frame_generation","Génération d'images"},
    {"pc_volume","Volume"},
    {"pc_microphone","Microphone"},
    {"pc_microphone_test","Test du microphone"},
    {"pc_mic_level","Niveau d'entrée"},
    {"pc_mic_heard","Mots reconnus"},
    {"pc_mic_monitor","Écouter ma voix"},
    {"pc_mic_no_word","Aucun pour l'instant"},
    {"pc_mic_waiting","En attente du microphone sélectionné..."},
    {"pc_mic_unavailable","Impossible d'ouvrir le microphone sélectionné. Vérifiez l'autorisation d'enregistrement et le choix du périphérique."},
    {"pc_mic_st_loading","Chargement..."},
    {"pc_mic_st_nomic","Aucun microphone"},
    {"pc_mic_st_files","Fichiers vocaux absents"},
    {"pc_mic_st_runtime","Moteur vocal en échec"},
    {"pc_mic_st_cpu","Processeur non pris en charge"},
    {"pc_mic_st_model","Modèle vocal en échec"},
    {"pc_mic_st_silent","Aucun son"},
    {"pc_mic_err_files","Les fichiers de reconnaissance vocale sont absents. Réinstallez ou réparez le jeu."},
    {"pc_mic_err_runtime","Le moteur vocal n'a pas pu être chargé. Consultez pt.log pour la cause."},
    {"pc_mic_err_cpu","Ce processeur ne peut pas exécuter le moteur vocal."},
    {"pc_mic_err_model","Le modèle vocal n'a pas pu être chargé. Consultez pt.log pour la cause."},
    {"pc_mic_err_silent","Le microphone est ouvert mais n'envoie aucun son. Vérifiez qu'il n'est pas coupé et que le bon périphérique est sélectionné."},
    {"pc_mic_say_jack","Dites « Jack » dans le microphone sélectionné. Ce test ne fait pas avancer l'énigme."},
    {"pc_mic_monitor_note","Vous entendez votre microphone. Un casque évite le larsen. L'écoute s'arrête quand vous quittez ce test."},
    {"pc_mouse","Sensibilité de la souris"},
    {"pc_gamepad_sensitivity","Sensibilité de rotation à la manette"},
    {"pc_camera_tilt","Inclinaison de la caméra"},
    {"pc_vibration","Vibrations"},
    {"pc_dead_zone","Zone morte du stick"},
    {"pc_reset","Réinitialiser la progression"},
    {"pc_graphics","Graphismes"},
    {"pc_graphics_value","Ouvrir"},
    {"pc_rt_shadows","Ombres en ray tracing"},
    {"pc_rt_contact","Ombres de contact"},
    {"pc_shadows","Ombres"},
    {"pc_reflections","Réflexions"},
    {"pc_standard","Standard"},
    {"pc_ray_traced","Ray tracing"},
    {"pc_rt_sharp_long","Ray tracing, nettes"},
    {"pc_rt_soft_long","Ray tracing, douces"},
    {"pc_note_shadows","De Bas à Original : les cartes d'ombres d'origine (512, 1024 ou 2048 px). Le ray tracing les remplace : ombres nettes comme l'original, ou douces selon la taille de chaque lumière."},
    {"pc_note_ao","Standard : l'occlusion en espace écran d'origine. Le ray tracing assombrit les coins et le dessous des objets à partir de la scène. Absent de l'original."},
    {"pc_note_reflections","Standard : les reflets au sol en espace écran d'origine. Le ray tracing reflète aussi ce qui est hors de l'écran. Expérimental."},
    {"pc_rt_ao","Occlusion ambiante"},
    {"pc_anisotropy","Filtrage anisotrope"},
    {"pc_enhanced_textures","Textures améliorées"},
    {"pc_texture_preparing","Préparation"},
    {"pc_note_texture_tools_missing","Les outils ou les fichiers de modèle des textures améliorées sont absents. Restaurez texture-tools depuis la version portable, puis réessayez. Les textures d'origine sont conservées."},
    {"pc_note_texture_busy","Une autre instance du jeu prépare ce cache de textures. Attendez la fin, puis réessayez. Les textures d'origine sont conservées."},
    {"pc_note_texture_failed","Échec de la préparation des textures ; les textures d'origine sont conservées. Vérifiez l'espace disque et pt.log, puis réessayez."},
    {"pc_note_texture_preparing","Préparation des textures améliorées. Les textures d'origine restent affichées, puis sont remplacées sans redémarrage. Désactivé annule."},
    {"pc_note_enhanced_textures","Crée une fois des textures couleur plus nettes à partir de vos fichiers de jeu. Murs et personnages compris ; 4096 px avec 10 Go de mémoire vidéo, sinon 2048. Désactivé annule ; les textures d'origine restent disponibles."},
    {"pc_rt_sharp","Nettes"},
    {"pc_rt_soft","Douces"},
    {"pc_on","Activé"},
    {"pc_off","Désactivé"},
    {"pc_window","Fenêtré"},
    {"pc_borderless","Sans bordure"},
    {"pc_fullscreen","Plein écran"},
    {"pc_native","Native"},
    {"pc_quality_quality","Qualité"},
    {"pc_quality_balanced","Équilibré"},
    {"pc_quality_performance","Performance"},
    {"pc_quality_ultra","Ultra performance"},
    {"pc_quality_custom","Personnalisé"},
    {"pc_system_default","Par défaut (système)"},
    {"pc_reset_value","Réinitialiser"},
    {"pc_reset_confirm","Confirmer"},
    {"pc_reset_done","Terminé"},
    {"pc_note_vsync","Effet immédiat. Synchronise l'affichage avec la fréquence de rafraîchissement de l'écran."},
    {"pc_note_vsync_off","S'applique immédiatement. Désactivée, chaque image s'affiche dès qu'elle est prête : la fréquence n'est pas limitée par l'écran et l'image peut se déchirer."},
    {"pc_note_restart","Prend effet au prochain lancement."},
    {"pc_note_display_mode","Alt+Entrée bascule aussi entre fenêtre et plein écran."},
    {"pc_note_resolution","Taille de la fenêtre."},
    {"pc_note_resolution_fullscreen","Le plein écran utilise la résolution du bureau."},
    {"pc_note_upscaler_off","Désactivé : rendu à la résolution de l'écran, comme l'original."},
    {"pc_note_render_size","Rendu en {1}, affiché en {2}."},
    {"pc_note_needs_upscaler","Nécessite une méthode de mise à l'échelle."},
    {"pc_note_sharpness_fsr","Seul FSR a sa propre netteté. Clarté de l'image, dans Graphismes, accentue l'image avec toutes les méthodes."},
    {"pc_note_reset","Réinitialise la progression et relance le jeu immédiatement. La langue et les paramètres PC sont conservés."},
    {"pc_note_reset_confirm","Appuyez de nouveau sur {accept} pour supprimer la sauvegarde."},
    {"pc_note_reset_done","Progression réinitialisée dans cette session."},
    {"pc_note_camera_tilt","La caméra s'incline avec la tête, comme dans l'original."},
    {"pc_note_voice","Le microphone n'écoute qu'aux moments où le jeu original le fait."},
    {"pc_note_focus_pause","Ouvre ce menu quand la fenêtre passe en arrière-plan."},
    {"pc_note_focus_mute","Coupe le son du jeu tant que la fenêtre est en arrière-plan."},
    {"pc_note_frame_generation_missing","Absent de cette version."},
    {"pc_note_frame_generation","AMD FSR 3 affiche une image générée entre deux images rendues."},
    {"pc_note_fsr4_vulkan","AMD ne publie FSR 4 que pour DirectX 12 ; ce jeu utilise Vulkan, FSR 4 ne peut donc pas fonctionner ici."},
    {"pc_dlss_model","Modèle DLSS"},
    {"pc_dlss_model_auto","Auto"},
    {"pc_note_dlss_model","Auto suit le choix de NVIDIA : K jusqu'à Équilibré, M en Performance, L en Ultra performance. L et M coûtent environ deux fois plus sur RTX 20 et 30."},
    {"pc_note_frame_generation_dlss","Expérimental. NVIDIA DLSS Frame Generation affiche une image générée entre deux images rendues. Prend effet au prochain lancement."},
    {"pc_note_dlssg_gpu","DLSS Frame Generation nécessite une carte NVIDIA GeForce RTX 40 ou plus récente."},
    {"pc_note_fsr_fg_gpu","La génération d'images FSR 3 nécessite une carte AMD Radeon RX 5000 ou plus récente."},
    {"pc_note_dlssg_driver","DLSS Frame Generation nécessite un pilote NVIDIA plus récent."},
    {"pc_note_dlssg_hags","DLSS Frame Generation nécessite la planification GPU à accélération matérielle (paramètres graphiques de Windows)."},
    {"pc_note_dlssg_missing","DLSS Frame Generation n'est pas inclus dans cette version."},
    {"pc_note_dlssg_failed","DLSS Frame Generation n'a pas pu démarrer et a été désactivé."},
    {"pc_note_dlssg_restart","Relancez le jeu pour démarrer DLSS Frame Generation."},
    {"pc_note_vsync_dlssg","DLSS Frame Generation fonctionne sans synchro verticale sous Vulkan ; le réglage s'applique de nouveau sans génération d'images."},
    {"pc_note_fsr_fg_restart","Relancez le jeu pour passer de DLSS Frame Generation à FSR 3."},
    {"pc_note_dead_zone","0.10 est la valeur de la DualShock 4."},
    {"pc_note_gamepad_sensitivity","Modifie la vitesse de rotation après la réponse d'origine du stick. 1 conserve le réglage d'origine."},
    {"pc_note_rt_shadows","Ombres calculées par ray tracing à la place des cartes d'ombres, aussi nettes que dans l'original. Absent de l'original."},
    {"pc_note_rt_soft","Ombres en ray tracing aux bords adoucis selon la taille de chaque lumière. Absent de l'original."},
    {"pc_note_rt_unsupported","Nécessite un GPU compatible ray tracing Vulkan."},
    {"pc_note_graphics","Choisissez un préréglage ou affinez éclairage, textures et effets d'image. Résolution et mise à l'échelle se règlent à part."},
    {"pc_note_rt_contact","Les objets projettent de courtes ombres en ray tracing depuis chaque lumière, même celles qui n'en projettent pas dans l'original."},
    {"pc_note_rt_ao","Assombrit par ray tracing les coins et l'espace sous et derrière les objets. Absent de l'original."},
    {"pc_rt_reflections","Réflexions"},
    {"pc_note_rt_reflections","Le sol reflète la scène au-delà des bords de l'écran. Expérimental ; le rendu peut différer de l'original."},
    {"pc_note_anisotropy","Sols et murs plus nets vus de biais. Désactivé conserve le filtrage d'origine."},
    {"pc_graphics_quality","Qualité"},
    {"pc_graphics_preset","Préréglage"},
    {"pc_preset_low","Bas"},
    {"pc_preset_medium","Moyen"},
    {"pc_preset_original","Original (PS4)"},
    {"pc_preset_high","Élevé"},
    {"pc_preset_ultra","Ultra"},
    {"pc_preset_custom","Personnalisé"},
    {"pc_ray_tracing","Ray tracing"},
    {"pc_clarity","Clarté de l'image"},
    {"pc_graphics_advanced","Avancé"},
    {"pc_graphics_lighting","Éclairage"},
    {"pc_graphics_effects","Effets d'image"},
    {"pc_graphics_image","Image"},
    {"pc_lighting_standard","Éclairage standard"},
    {"pc_shadow_quality","Cartes d'ombres"},
    {"pc_standard_ao","Occlusion ambiante"},
    {"pc_standard_reflections","Réflexions en espace écran"},
    {"pc_ray_quality","Qualité des rayons"},
    {"pc_ray_balanced","Équilibrée"},
    {"pc_texture_detail","Détail des textures"},
    {"pc_detail_reduced","Réduit"},
    {"pc_detail_fine","Fin"},
    {"pc_dof","Profondeur de champ"},
    {"pc_motion_blur","Flou de mouvement"},
    {"pc_bloom","Bloom"},
    {"pc_lens_ghosts","Reflets de lens flare"},
    {"pc_note_lens_ghosts","Les grands reflets de lens flare sur tout l'écran quand on regarde près d'une lampe, comme dans l'original (PS4). Désactivé les supprime."},
    {"pc_film_grain","Grain de film"},
    {"pc_note_preset","Ne change que les graphismes : résolution et mise à l'échelle sont conservées. Un réglage manuel affiche Personnalisé. Ultra utilise le ray tracing si possible."},
    {"pc_note_ray_master","Active ou désactive ensemble ombres en ray tracing, ombres de contact, occlusion ambiante et réflexions. Les réglages séparés sont dans Éclairage."},
    {"pc_lens_distortion","Effet d'objectif"},
    {"pc_note_lens_distortion","La courbure d'objectif et les franges colorées d'origine. Désactivé donne des bords plus nets et une image plus large."},
    {"pc_note_clarity","Ajoute une légère accentuation du contraste local à la résolution de sortie. Zéro conserve l'image d'origine."},
    {"pc_note_letterbox","Bandes noires en haut et en bas de l'image, en jeu et dans les cinématiques. Les sous-titres restent dans l'image. Absent de l'original."},
    {"pc_note_advanced","Affinez cette catégorie. Retour revient à Graphismes ; toute modification affiche Personnalisé."},
    {"pc_note_shadow_quality","Cartes d'ombres de 512, 1024 ou 2048 px (original). Les ombres en ray tracing les remplacent si activées. L'échelle de résolution ne change pas."},
    {"pc_note_standard_ao","L'occlusion ambiante en espace écran d'origine. Désactivez-la pour alléger les GPU modestes."},
    {"pc_note_standard_reflections","Les reflets au sol en espace écran d'origine. Les réflexions en ray tracing les remplacent si activées."},
    {"pc_note_ray_quality","Équilibrée : 2 rayons. Élevé : 4 rayons. Ultra : 8 rayons, pour des ombres plus douces et une occlusion en ray tracing moins bruitée."},
    {"pc_note_texture_detail","Réduit utilise des mips plus grossiers. Fin garde plus de détails au loin, avec un possible scintillement. La résolution de sortie ne change pas."},
    {"pc_note_dof","Le flou de mise au point d'origine. Désactivé garde nets les surfaces proches et l'arrière-plan."},
    {"pc_note_motion_blur","Le flou d'origine en tournant et en se déplaçant. Désactivé donne une image plus nette en mouvement."},
    {"pc_note_bloom","Le halo lumineux d'origine. Désactivé réduit la lueur et le coût du post-traitement."},
    {"pc_note_film_grain","L'intensité du grain de film d'origine. Désactivé donne une image plus propre ; 100 % garde l'effet d'origine."},
    {"pc_mods","Mods"},
    {"pc_section_mods","Mods installés"},
    {"pc_note_mods","Activer ou désactiver un mod prend effet au prochain lancement. Les mods ne font pas partie du jeu original."},
    {"pc_archive","Musée"},
    {"pc_note_archive","Les images, voix, morceaux de photo, cinématiques et modèles du jeu, à mesure que vous les atteignez en jouant. Votre partie n'est pas modifiée."},
    {"pc_note_extras_archive","Sélection de boucle, musée, caméra libre et mode photo."},
    {"pc_archive_sections","Salles"},
    {"pc_archive_images","Images subliminales"},
    {"pc_archive_voices","Voix et radio"},
    {"pc_archive_photos","Morceaux de photo"},
    {"pc_archive_cutscenes","Cinématiques"},
    {"pc_archive_models","Modèles"},
    {"pc_archive_unused","Contenu inutilisé"},
    {"pc_note_archive_images","Les textes des flashs subliminaux, le bruit de ces flashs et la vue par le judas."},
    {"pc_note_archive_voices","Les émissions de radio et toutes les répliques, avec leur transcription dans votre langue de sous-titres."},
    {"pc_note_archive_photos","Les morceaux déchirés de la photographie, et la photo qu'ils forment dans le cadre."},
    {"pc_note_archive_cutscenes","Chaque cinématique depuis son début, avec son son et ses sous-titres."},
    {"pc_note_archive_models","Lisa et les autres silhouettes et objets du couloir, dans la lumière de la pièce de départ."},
    {"pc_note_archive_unused_section","Du contenu présent dans les fichiers du jeu que le jeu ne montre jamais. Il s'ouvre une fois le jeu terminé."},
    {"pc_note_archive_image","Entrée / Croix : afficher en plein écran."},
    {"pc_note_archive_voice","Entrée / Croix : lire ou arrêter."},
    {"pc_note_archive_photo","Entrée / Croix : afficher en plein écran."},
    {"pc_note_archive_demo","Entrée / Croix : lire depuis le début. Échap / Rond l'arrête."},
    {"pc_note_archive_model","Entrée / Croix : voir le modèle. Échap / Rond : retour."},
    {"pc_note_archive_unused","Jamais montré dans le jeu. Entrée / Croix : voir le modèle."},
    {"pc_note_archive_locked","Verrouillé. Atteignez-le en jouant pour l'ouvrir."},
    {"pc_note_archive_playing","Lecture en cours. Entrée / Croix l'arrête."},
    {"pc_archive_lock","Verrouiller le musée"},
    {"pc_note_archive_lock","Verrouille de nouveau chaque pièce du musée, comme avant de jouer. Votre sauvegarde n'est pas modifiée."},
    {"pc_archive_hint","Entrée / X / A : ouvrir"},
    {"pc_archive_view_hint","Gauche / Droite : précédent / suivant. Échap / Rond : retour."},
    {"pc_archive_demo_hint","Échap / Rond / Entrée / Croix : arrêter"},
    {"pc_archive_model_hint","Flèches / sticks : tourner. W / S / gâchettes : plus près / plus loin. Échap / Rond : retour."},
    {"pc_archive_sub","Texte subliminal {1}"},
    {"pc_archive_noise","Bruit"},
    {"pc_archive_noise_normal","Distorsion du bruit"},
    {"pc_archive_peephole_mask","La vue par le judas"},
    {"pc_archive_radio_news","Radio : le bulletin d'informations"},
    {"pc_archive_radio_news2","Radio : le bulletin, encore"},
    {"pc_archive_radio_voice","Voix de la radio {1}"},
    {"pc_archive_riddle","Énigme de la radio {1}"},
    {"pc_archive_sermon","Radio : le sermon"},
    {"pc_archive_phone","L'appel téléphonique"},
    {"pc_archive_peephole_voice","Par le judas"},
    {"pc_archive_bag","Le sac qui parle"},
    {"pc_archive_fetus","Le fœtus parle {1}"},
    {"pc_archive_photo_lisa","Morceau : Lisa"},
    {"pc_archive_photo_tree","Morceau : l'arbre"},
    {"pc_archive_photo_gap","Morceau : la fente"},
    {"pc_archive_photo_bath","Morceau : la salle de bain"},
    {"pc_archive_photo_stair","Morceau : l'escalier"},
    {"pc_archive_photo_option","Morceau : l'écran des options"},
    {"pc_archive_photo_complete","La photo complète"},
    {"pc_archive_preface","La préface"},
    {"pc_archive_awakening","Le premier réveil"},
    {"pc_archive_opening","Le réveil"},
    {"pc_archive_first_exit","La première porte"},
    {"pc_archive_door","Par la porte"},
    {"pc_archive_clock","Minuit"},
    {"pc_archive_kill","Prisonnier de Lisa"},
    {"pc_archive_ending","La fin"},
    {"pc_archive_teaser","Le teaser"},
    {"pc_archive_lisa_stand","Lisa, debout"},
    {"pc_archive_lisa_walk","Lisa, qui marche"},
    {"pc_archive_lisa_dash","Lisa, qui se précipite"},
    {"pc_archive_lisa_door","Lisa derrière la porte"},
    {"pc_archive_baby","Le fœtus dans le lavabo"},
    {"pc_archive_fridge","Le réfrigérateur"},
    {"pc_archive_bag_model","Le sac en papier"},
    {"pc_archive_lamp","Le plafonnier"},
    {"pc_archive_roach","Cafard"},
    {"pc_archive_flashlight","La lampe torche"},
    {"pc_archive_radio","La radio"},
    {"pc_archive_phone_model","Le téléphone"},
    {"pc_archive_xmark_photo","La photo à la croix"},
    {"pc_archive_clock_model","L'horloge"},
    {"pc_archive_man","L'homme"},
    {"pc_archive_bathtub","Le corps dans la baignoire"},
};
inline std::string_view Menu(std::string_view key) {
    for (const auto& e : kMenu) if (e.key == key) return e.text;
    return {};
}
}
