#pragma once
#include <string_view>

// German for the port's own menus (PC settings, extras, photo mode, loop browser, notes and prompts) and the added
// languages' names on the option screen. The options screen's other texts and the subtitles are the game's own.
namespace pt::german {
struct Text { std::string_view key, text; };
inline constexpr Text kMenu[] = {
    {"pc_controller_speaker","Controller-Lautsprecher"},
    {"pc_note_controller_speaker","Gibt Lisas aufgezeichnete Schreie über unterstützte Sony-Controller-Lautsprecher wieder. Unter Windows ist USB erforderlich; nicht unterstützte Geräte und Bluetooth bleiben stumm. Unabhängig von der Haptik; standardmäßig aus."},
    {"pc_controller_speaker_volume","Lautstärke des Controller-Lautsprechers"},
    {"pc_note_controller_speaker_volume","Ändert nur die Lautstärke des Controller-Lautsprechers in 5%-Schritten. Spielaudio und DualSense-Haptik bleiben unverändert. Nur mit unterstützten kabelgebundenen Sony-Controllern unter Windows verfügbar."},
    {"pc_microphone_trigger_assign","{input} als Mikrofon-Auslöser festlegen"},
    {"pc_note_microphone_trigger","Optionale Alternative zum Mikrofon. Tastatur und beide Controller-Trigger aktivieren sie nur, wenn das Spiel zuhört."},
    {"pc_note_microphone_test","Testet das Mikrofon und das Erkennungsergebnis."},
    {"pc_fps_limit","Bildratenlimit"},
    {"pc_unlimited","Unbegrenzt"},
    {"pc_note_fps_limit","Begrenzt gerenderte Bilder. Menüs bleiben auf 60 FPS begrenzt. V-Sync kann ein niedrigeres Limit erzwingen."},
    {"pc_hdr","Nativer HDR-Modus"},
    {"pc_note_hdr_restart","Wird beim nächsten Start übernommen. Erfordert aktiviertes HDR auf einem kompatiblen Display; andernfalls wird SDR verwendet."},
    {"pc_surround","Raumklangausgabe"},
    {"pc_note_surround","Verwendet nach einem Neustart das 5.1- oder 7.1-Layout des Ausgabegeräts. Stereo-Geräte bleiben bei Stereo."},
    {"pc_rumble_profile","Vibrationsmodus"},
    {"pc_rumble_original","Original"},
    {"pc_rumble_enhanced","Erweitert"},
    {"pc_note_rumble_profile","Original nutzt nur die vom Spiel vorgesehene Motorvibration. Erweitert ergänzt unterstützte Trigger-Vibration und auf unterstützten DualSense-Controllern per USB unter Windows Haptik aus Lisas gefilterten Schreien. Die Hauptoption für Vibration schaltet beides aus. Controller-Lautsprecher sind davon unabhängig."},
    {"pc_vr_height","Höhenanpassung"},
    {"pc_note_vr_height","Verschiebt den getrackten Blickpunkt nach oben oder unten, ohne die Position des Spielers zu ändern."},
    {"pc_vr_world_scale","Weltmaßstab"},
    {"pc_note_vr_world_scale","Skaliert die erfassten Bewegungen von Kopf, Augen und Controllern auf 50 bis 200 %. Je höher der Wert, desto kleiner wirkt die Welt. Standard: 100 %."},
    {"pc_photo_focal_length","Brennweite"},
    {"pc_note_photo_focal_length","Brennweite des Objektivs in Millimetern. Die Fokusunschärfe verwendet dasselbe Objektiv und denselben Sensor wie die Kamera."},
    {"pc_photo_aspect","Bildformat"},
    {"pc_note_photo_aspect","Schneidet das Foto mittig zu."},
    {"pc_photo_resolution","Fotoauflösung"},
    {"pc_note_photo_resolution","Native speichert die zugeschnittenen Pixel. 4K rendert die Szene erneut mit 3840 Pixeln an der langen Seite."},
    {"pc_photo_resolution_native","Native"},
    {"pc_photo_resolution_4k","4K"},
    {"pc_photo_filter","Farbfilter"},
    {"pc_note_photo_filter","Wirkt sich nur auf die Fotoansicht und das gespeicherte Foto aus."},
    {"pc_photo_filter_bw","Schwarzweiß"},
    {"pc_photo_filter_warm","Warm"},
    {"pc_photo_filter_cool","Kühl"},
    {"pc_photo_filter_muted","Gedämpft"},
    {"pc_archive_model_hint","WASD / linker Stick: Bildausschnitt verschieben. Pfeile / rechter Stick: drehen. Trigger: zoomen. Esc / Kreis: zurück."},
    {"pc_note_resolution_fullscreen","Randlos verwendet die gewählte Größe; exklusives Vollbild verwendet eine unterstützte Bildschirmgröße."},
    {"op_sub_turkish","Türkisch"},
    {"op_sub_chinese","Chinesisch (vereinf.)"},
    {"op_sub_arabic","Arabisch"},
    {"op_sub_russian","Russisch"},
    {"op_sub_ukrainian","Ukrainisch"},
    {"op_sub_czech","Tschechisch"},
    {"op_sub_polish","Polnisch"},
    {"pc_loop_browser","Schleifenauswahl"},
    {"pc_note_loop_browser_entry","Beliebige Schleife starten, ohne Ihren Spielstand zu ersetzen."},
    {"pc_loop_choose","Schleife wählen"},
    {"pc_loop_preview","Vorschau"},
    {"pc_loop_start_hint","Enter / X / A: Schleife starten"},
    {"pc_loop_f000","Startraum: der Anfang"},
    {"pc_loop_f010","Schleife 1: das Radio"},
    {"pc_loop_f005","Schleife 2: die Dielentür öffnet sich"},
    {"pc_loop_f020","Schleife 3: Weinen im Bad"},
    {"pc_loop_f030","Schleife 4: die Badezimmertür"},
    {"pc_loop_f040","Schleife 5: Lisa am Ende des Flurs"},
    {"pc_loop_f060","Schleife 6: das Bad, die Taschenlampe"},
    {"pc_loop_f050a","Schleife 7: Lisa folgt Ihnen"},
    {"pc_loop_f050b","Schleife 8: das Foto mit dem X"},
    {"pc_loop_f070","Schleife 9: das Fenster zerbricht"},
    {"pc_loop_f080","Schleife 10: der blutende Kühlschrank"},
    {"pc_loop_f090","Schleife 11: HELLO"},
    {"pc_loop_f100","Schleife 12: der rote Flur"},
    {"pc_loop_f110","Schleife 13: das Labyrinth und der Türspion"},
    {"pc_loop_f120","Schleife 14: 204863, der Fehlerbildschirm"},
    {"pc_loop_f160","Schleife 15: die letzte Schleife"},
    {"pc_loop_ending","Abschlusssequenz und Abspann"},
    {"pc_loop_street","Spaziergang auf der Straße (nach dem Ende)"},
    {"pc_note_loop_opening","Startet den Anfang im Startraum wie ein neues Spiel. Ihr Spielstand bleibt erhalten."},
    {"pc_note_loop_hallway","Beginnt im Startraum direkt vor dieser Schleife, alle Rätsel davor gelöst. Gehen Sie durch die Tür. Ihr Spielstand bleibt erhalten; gespeichert wird wieder ab dem nächsten Kontrollpunkt."},
    {"pc_note_loop_ending","Zeigt die Abschlusssequenz und den Abspann und bietet danach den Spaziergang auf der Straße an. Ihr Spielstand bleibt erhalten."},
    {"pc_note_loop_street","Versetzt Sie auf die Straße aus dem Ende, aus der Ich-Perspektive. Verlassen über Extras. Ihr Spielstand bleibt erhalten."},
    {"pc_note_loop_locked","Gesperrt. Beenden Sie das Spiel einmal; danach öffnet sich jede Schleife, die Sie im Spiel erreicht haben."},
    {"pc_note_loop_browser_locked","Beenden Sie das Spiel einmal, um die Schleifenauswahl freizuschalten."},
    {"pc_street_title","Die Straße"},
    {"pc_street_question","Die Straße erkunden?"},
    {"pc_street_walk","Ja, die Straße entlanggehen"},
    {"pc_credit_version","P.T. PC Port {1} von LoreanXavier"},
    {"pc_update_available","Version {1} ist verfügbar (dies ist {2})"},
    {"pc_credits_by","von LoreanXavier"},
    {"pc_credits_dlss","Dieses Spiel verwendet NVIDIA DLSS."},
    {"pc_credits_licenses","Die vollständigen Lizenztexte liegen im Ordner licenses neben pt.exe."},
    {"pc_credits_konami","P.T. gehört Konami Digital Entertainment und Kojima Productions."},
    {"pc_credits_fan","Diese Portierung ist ein inoffizielles Fanprojekt, weder mit Konami, NVIDIA, AMD oder Intel verbunden noch von ihnen unterstützt."},
    {"pc_note_street_walk","Gehen Sie die Straße aus dem Ende in der Ich-Perspektive entlang. Verlassen über Extras."},
    {"pc_street_restart","Nein, zurück zum Anfang"},
    {"pc_note_street_restart","Neustart im Startraum, wie im Original nach dem Abspann."},
    {"pc_street_leave","Straße verlassen"},
    {"pc_note_street_leave","Beendet den Spaziergang und kehrt in den Startraum zurück."},
    {"pc_street_return","Zurück ins Haus"},
    {"pc_street_return_confirm","Zurück ins Haus?"},
    {"pc_loop_lock","Schleifenauswahl sperren"},
    {"pc_note_loop_lock","Sperrt alle Schleifen der Auswahl wieder, wie vor Ihrem ersten Spielende. Ihr Spielstand bleibt unverändert."},
    {"pc_extras","Extras"},
    {"pc_vr","VR (experimentell)"},
    {"pc_note_vr","Mit einem VR-Headset über OpenXR spielen. Experimentell: nicht auf echter Hardware getestet."},
    {"pc_vr_mode","VR-Modus"},
    {"pc_note_vr_mode","Nicht auf echter Hardware getestet. Benötigt eine OpenXR-Laufzeit und ein Headset. Gilt ab dem nächsten Start; ohne Headset startet das Spiel wie gewohnt."},
    {"pc_vr_flashlight","Taschenlampe"},
    {"pc_note_vr_flashlight","Die Taschenlampe folgt wie im Original deinem Kopf oder dem Controller in deiner Hand."},
    {"pc_vr_head","Kopf"},
    {"pc_vr_controller","Controller"},
    {"pc_vr_turn","Drehen"},
    {"pc_note_vr_turn","Der rechte Stick dreht in Schritten oder stufenlos. Schritte sind magenschonender."},
    {"pc_vr_snap","In Schritten"},
    {"pc_vr_smooth","Stufenlos"},
    {"pc_note_extras","Schleifenauswahl, freie Kamera und Fotomodus."},
    {"pc_freecam","Freie Kamera"},
    {"pc_note_freecam","Löst die Kamera vom Spieler (F6). Leertaste / Strg oder Trigger: hoch und runter, Umschalt oder L3: schneller. Esc: beenden."},
    {"pc_photo_mode","Fotomodus"},
    {"pc_note_photo_mode","Hält das Spiel an, um mit der freien Kamera ein Bild zu gestalten (F7). P oder Quadrat: in Pictures/PT Photos speichern, H oder Dreieck: Leiste ausblenden."},
    {"pc_speedrun","Speedrun-Timer"},
    {"pc_note_speedrun","Ein Timer auf dem Bildschirm mit einer Zwischenzeit pro Schleife und einer Ergebnisanzeige nach dem Abspann. Echtzeit zählt alles; Spielzeit lässt Pausen und Ladezeiten weg. Nicht im Original."},
    {"pc_speedrun_real_time","Echtzeit"},
    {"pc_speedrun_game_time","Spielzeit"},
    {"pc_livesplit","LiveSplit-Server"},
    {"pc_note_livesplit","Sendet Start, Zwischenzeiten und Spielzeit an LiveSplit (Control > Start TCP Server, Port {1}). Host und Port stehen in pt.ini."},
    {"pc_speedrun_results","LAUF BEENDET"},
    {"pc_speedrun_run","Lauf"},
    {"pc_speedrun_splits","Zwischenzeiten"},
    {"pc_speedrun_menu","Zurück zum Menü"},
    {"pc_note_speedrun_menu","Startet wie das Original nach dem Ende von vorn, zuerst mit dem Optionsbildschirm. Der nächste Lauf beginnt, sobald du die Kontrolle hast."},
    {"pc_speedrun_outside","Draußen erkunden"},
    {"pc_note_speedrun_outside","Die Straße aus dem Ende entlanggehen. Zurück ins Haus über das Pausenmenü."},
    {"pc_note_speedrun_real","Echte Uhrzeit von der Kontrolle bis zum Ende: Pausen, Ladezeiten und Zwischensequenzen inklusive."},
    {"pc_note_speedrun_game","Nur Spiel ohne Pause: das Pausenmenü und das Laden nach einem Game Over zählen nicht."},
    {"pc_speedrun_best","Persönliche Bestzeit"},
    {"pc_note_speedrun_best","Vorherige Bestzeit: {1}. Die Rekorde liegen in speedrun.ini, speedrun_history.txt und speedrun_pb.lss (LiveSplit) im Benutzerordner."},
    {"pc_speedrun_new_best","Neue Bestzeit!"},
    {"pc_speedrun_partial","Nicht vom Anfang"},
    {"pc_speedrun_start_room","Startraum"},
    {"pc_speedrun_loop","Schleife {1}"},
    {"pc_third_person","Third-Person-Ansicht (experimentell)"},
    {"pc_note_third_person","Experimentell, nicht im Original: Die Kamera folgt dem Spieler über die Schulter. Zoom und Zwischensequenzen wechseln zurück in die Ich-Perspektive; die Ereignisse laufen ab wie in der Ich-Perspektive."},
    {"pc_extras_start","Starten"},
    {"pc_photo_title","FOTOMODUS"},
    {"pc_photo_section_camera","Kamera"},
    {"pc_photo_section_lens","Objektiv"},
    {"pc_photo_section_image","Bild"},
    {"pc_photo_take","Foto aufnehmen"},
    {"pc_photo_capture","Aufnehmen"},
    {"pc_photo_fov","Sichtfeld"},
    {"pc_photo_roll","Kamerarollen"},
    {"pc_photo_speed","Kamerageschwindigkeit"},
    {"pc_photo_speed_slow","Langsam"},
    {"pc_photo_speed_normal","Normal"},
    {"pc_photo_speed_fast","Schnell"},
    {"pc_photo_reset","Kamera zurücksetzen"},
    {"pc_photo_focus","Fokusentfernung"},
    {"pc_photo_aperture","Blende"},
    {"pc_photo_exposure","Belichtung"},
    {"pc_photo_grading","Farbkorrektur"},
    {"pc_photo_letterbox","Kinobalken"},
    {"pc_photo_body","Spielerkörper"},
    {"pc_photo_flashlight","Taschenlampe"},
    {"pc_photo_shown","Sichtbar"},
    {"pc_photo_hidden","Ausgeblendet"},
    {"pc_photo_auto","Auto"},
    {"pc_photo_metres","{value} m"},
    {"pc_photo_saved","In Pictures/PT Photos gespeichert: {file}"},
    {"pc_photo_save_failed","Foto konnte nicht gespeichert werden. Siehe pt.log."},
    {"pc_photo_hint","Pfeile / Steuerkreuz: wählen und ändern. P / Quadrat: Foto. H / Dreieck: Leiste ausblenden. Rechte Maustaste: umsehen. Esc / Kreis: verlassen."},
    {"pc_note_photo_take","Speichert die aktuelle Ansicht in Pictures/PT Photos. Die Leiste ist nie auf dem Foto."},
    {"pc_note_photo_fov","Vertikales Sichtfeld in Grad. Kleinere Werte zoomen heran."},
    {"pc_note_photo_roll","Neigt die Kamera zur Seite für eine schräge Perspektive."},
    {"pc_note_photo_speed","Wie schnell sich die Kamera bewegt. Umschalt oder L3 beschleunigen weiterhin."},
    {"pc_note_photo_reset","Bringt die Kamera dorthin zurück, wo der Fotomodus begann."},
    {"pc_note_photo_dof","Zeichnet alles unscharf, was näher oder ferner als die Fokusentfernung ist."},
    {"pc_note_photo_focus","Auto stellt auf das scharf, was in der Bildmitte ist."},
    {"pc_note_photo_aperture","Kleinere Blendenzahlen zeichnen stärker unscharf. Auto behält das Objektiv des Spiels."},
    {"pc_note_photo_exposure","Hellt das Bild auf oder dunkelt es ab, in halben Blendenstufen."},
    {"pc_note_photo_grain","Die originale Filmkörnung. Aus ergibt ein saubereres Bild."},
    {"pc_note_photo_grading","Die originale Farbgebung. Aus zeigt neutrale Farben."},
    {"pc_note_photo_letterbox","Schwarze Kinobalken. Sie sind Teil des Fotos."},
    {"pc_note_photo_body","Blendet den Körper des Spielers ein oder aus."},
    {"pc_note_photo_flashlight","Schaltet das Licht der Taschenlampe im Fotomodus aus."},
    {"pc_extras_stop","Beenden"},
    {"pc_note_loop_generating","Vorschauen werden erstellt ... Ihr Spielstand bleibt erhalten. Gespeichert wird wieder ab dem nächsten Kontrollpunkt: beim Verlassen des Kellers oder in der letzten Schleife."},
    {"pc_title","PC-EINSTELLUNGEN"},
    {"pc_entry","PC-Einstellungen"},
    {"pc_back","Zurück"},
    {"pc_quit","Beenden"},
    {"pc_nav_columns","Tab / L1 / R1: Spalte wechseln"},
    {"pc_quit_confirm","Beenden?"},
    {"pc_save_no_space","Nicht genug freier Speicherplatz, um das Spiel zu speichern.\nGeben Sie Speicherplatz frei und schließen Sie diese Meldung, um es erneut zu versuchen."},
    {"pc_ok","OK"},
    {"pc_note_quit","Das Spiel beenden."},
    {"pc_note_quit_confirm","Drücken Sie erneut {accept}, um zu beenden. Zurück bricht ab."},
    {"pc_section_display","Anzeige"},
    {"pc_section_upscaling","Hochskalierung"},
    {"pc_section_sound","Ton"},
    {"pc_section_controls","Steuerung"},
    {"pc_section_progress","Fortschritt"},
    {"pc_section_ray_tracing","Raytracing"},
    {"pc_section_textures","Texturen"},
    {"pc_display_mode","Anzeigemodus"},
    {"pc_resolution","Auflösung"},
    {"pc_vsync","V-Sync"},
    {"pc_focus_pause","Im Hintergrund pausieren"},
    {"pc_focus_mute","Im Hintergrund stumm"},
    {"pc_upscaler","Verfahren"},
    {"pc_quality","Modus"},
    {"pc_sharpness","Schärfe"},
    {"pc_frame_generation","Frame-Generierung"},
    {"pc_volume","Lautstärke"},
    {"pc_microphone","Mikrofon"},
    {"pc_microphone_test","Mikrofontest"},
    {"pc_mic_level","Eingangspegel"},
    {"pc_mic_heard","Erkannte Wörter"},
    {"pc_mic_monitor","Eigene Stimme hören"},
    {"pc_mic_no_word","Noch keine"},
    {"pc_mic_waiting","Warte auf das gewählte Mikrofon ..."},
    {"pc_mic_unavailable","Das gewählte Mikrofon konnte nicht geöffnet werden. Prüfen Sie die Aufnahmeberechtigung und die Geräteauswahl."},
    {"pc_mic_st_loading","Wird geladen..."},
    {"pc_mic_st_nomic","Kein Mikrofon"},
    {"pc_mic_st_files","Sprachdateien fehlen"},
    {"pc_mic_st_runtime","Sprach-Engine fehlgeschlagen"},
    {"pc_mic_st_cpu","CPU nicht unterstützt"},
    {"pc_mic_st_model","Sprachmodell fehlgeschlagen"},
    {"pc_mic_st_silent","Kein Ton"},
    {"pc_mic_err_files","Die Dateien zur Spracherkennung fehlen. Installieren oder reparieren Sie das Spiel neu."},
    {"pc_mic_err_runtime","Die Sprach-Engine konnte nicht geladen werden. Die Ursache steht in pt.log."},
    {"pc_mic_err_cpu","Dieser Prozessor kann die Sprach-Engine nicht ausführen."},
    {"pc_mic_err_model","Das Sprachmodell konnte nicht geladen werden. Die Ursache steht in pt.log."},
    {"pc_mic_err_silent","Das Mikrofon ist geöffnet, liefert aber keinen Ton. Prüfen Sie, ob es stummgeschaltet ist und das richtige Gerät gewählt ist."},
    {"pc_mic_say_jack","Sagen Sie „Jack“ in das gewählte Mikrofon. Dieser Test löst das Rätsel nicht."},
    {"pc_mic_monitor_note","Sie hören Ihr Mikrofon. Kopfhörer verhindern Rückkopplungen. Das Mithören endet, wenn Sie den Test verlassen."},
    {"pc_mouse","Mausempfindlichkeit"},
    {"pc_gamepad_sensitivity","Drehgeschwindigkeit des Controllers"},
    {"pc_camera_tilt","Kameraneigung"},
    {"pc_vibration","Vibration"},
    {"pc_dead_zone","Stick-Totzone"},
    {"pc_reset","Fortschritt zurücksetzen"},
    {"pc_graphics","Grafik"},
    {"pc_graphics_value","Öffnen"},
    {"pc_rt_shadows","Raytracing-Schatten"},
    {"pc_rt_contact","Kontaktschatten"},
    {"pc_shadows","Schatten"},
    {"pc_reflections","Spiegelungen"},
    {"pc_standard","Standard"},
    {"pc_ray_traced","Raytracing"},
    {"pc_rt_sharp_long","Raytracing, scharf"},
    {"pc_rt_soft_long","Raytracing, weich"},
    {"pc_note_shadows","Niedrig bis Original sind die Schattenkarten des Originals (512, 1024 oder 2048 px). Raytracing ersetzt sie: scharf wie das Original oder weich nach der Größe jedes Lichts."},
    {"pc_note_ao","Standard ist die Bildschirmraum-Verdeckung des Originals. Raytracing dunkelt Ecken und den Raum unter Objekten aus der Szene selbst ab. Nicht im Original."},
    {"pc_note_reflections","Standard sind die Bildschirmraum-Bodenspiegelungen des Originals. Raytracing spiegelt auch, was außerhalb des Bildes liegt. Experimentell."},
    {"pc_rt_ao","Umgebungsverdeckung"},
    {"pc_anisotropy","Anisotrope Filterung"},
    {"pc_enhanced_textures","Verbesserte Texturen"},
    {"pc_texture_preparing","Vorbereitung"},
    {"pc_note_texture_tools_missing","Die Werkzeuge oder Modelldateien für verbesserte Texturen fehlen. Stellen Sie texture-tools aus dem portablen Paket wieder her und versuchen Sie es erneut. Die Originaltexturen bleiben erhalten."},
    {"pc_note_texture_busy","Eine andere Instanz des Spiels erstellt gerade diesen Textur-Cache. Warten Sie, bis sie fertig ist, und versuchen Sie es erneut. Die Originaltexturen bleiben erhalten."},
    {"pc_note_texture_failed","Die Texturvorbereitung ist fehlgeschlagen; die Originaltexturen bleiben erhalten. Prüfen Sie den freien Speicherplatz und pt.log und versuchen Sie es erneut."},
    {"pc_note_texture_preparing","Verbesserte Texturen werden vorbereitet. Bis dahin sind die Originaltexturen zu sehen; danach wechseln sie ohne Neustart. Aus bricht ab."},
    {"pc_note_enhanced_textures","Erzeugt einmalig schärfere Farbtexturen aus Ihren Spieldateien. Wände und Figuren eingeschlossen; 4096 px ab 10 GB Videospeicher, sonst 2048. Aus bricht ab; die Originaltexturen bleiben verfügbar."},
    {"pc_rt_sharp","Scharf"},
    {"pc_rt_soft","Weich"},
    {"pc_on","An"},
    {"pc_off","Aus"},
    {"pc_window","Fenster"},
    {"pc_borderless","Randlos"},
    {"pc_fullscreen","Vollbild"},
    {"pc_native","Nativ"},
    {"pc_quality_quality","Qualität"},
    {"pc_quality_balanced","Ausgewogen"},
    {"pc_quality_performance","Leistung"},
    {"pc_quality_ultra","Ultra-Leistung"},
    {"pc_quality_custom","Benutzerdefiniert"},
    {"pc_system_default","Systemstandard"},
    {"pc_reset_value","Zurücksetzen"},
    {"pc_reset_confirm","Bestätigen"},
    {"pc_reset_done","Erledigt"},
    {"pc_note_vsync","Wirkt sofort. Synchronisiert die Bildausgabe mit der Bildwiederholrate des Monitors."},
    {"pc_note_vsync_off","Wirkt sofort. Aus zeigt jedes Bild, sobald es fertig ist: Die Bildrate ist nicht an die Bildwiederholrate gebunden, und das Bild kann reißen."},
    {"pc_note_restart","Wirkt beim nächsten Start."},
    {"pc_note_display_mode","Alt+Enter wechselt auch zwischen Fenster und Vollbild."},
    {"pc_note_resolution","Fenstergröße."},
    {"pc_note_resolution_fullscreen","Im Vollbild gilt die Desktopauflösung."},
    {"pc_note_upscaler_off","Aus rendert in der Bildschirmauflösung, wie das Original."},
    {"pc_note_render_size","{1} gerendert, {2} angezeigt."},
    {"pc_note_needs_upscaler","Erfordert ein Hochskalierungsverfahren."},
    {"pc_note_sharpness_fsr","Nur FSR hat eine eigene Schärfung. Bildklarheit auf der Grafikseite schärft mit jedem Verfahren."},
    {"pc_note_reset","Setzt den Fortschritt zurück und startet das Spiel sofort neu. Sprache und PC-Einstellungen bleiben erhalten."},
    {"pc_note_reset_confirm","Drücken Sie erneut {accept}, um den Spielstand zu löschen."},
    {"pc_note_reset_done","Fortschritt in dieser Sitzung zurückgesetzt."},
    {"pc_note_camera_tilt","Die Kamera neigt sich mit dem Kopf, wie im Original."},
    {"pc_note_voice","Das Mikrofon hört nur dort zu, wo es auch das Originalspiel tut."},
    {"pc_note_focus_pause","Öffnet dieses Menü, wenn das Fenster in den Hintergrund wechselt."},
    {"pc_note_focus_mute","Schaltet das Spiel stumm, solange das Fenster im Hintergrund ist."},
    {"pc_note_frame_generation_missing","In dieser Version nicht enthalten."},
    {"pc_note_frame_generation","AMD FSR 3 zeigt ein erzeugtes Bild zwischen zwei gerenderten Bildern."},
    {"pc_note_fsr4_vulkan","AMD veröffentlicht FSR 4 nur für DirectX 12; dieses Spiel rendert mit Vulkan, daher kann FSR 4 hier nicht laufen."},
    {"pc_dlss_model","DLSS-Modell"},
    {"pc_dlss_model_auto","Automatisch"},
    {"pc_note_dlss_model","Automatisch folgt NVIDIAs Wahl: K bis Ausgewogen, M bei Leistung, L bei Ultra-Leistung. L und M kosten auf RTX 20 und 30 etwa doppelt so viel."},
    {"pc_note_frame_generation_dlss","Experimentell. NVIDIA DLSS Frame Generation zeigt ein erzeugtes Bild zwischen zwei gerenderten Bildern. Wirkt ab dem nächsten Start."},
    {"pc_note_dlssg_gpu","DLSS Frame Generation erfordert eine NVIDIA GeForce RTX 40 oder neuer."},
    {"pc_note_fsr_fg_gpu","FSR 3 Frame-Generierung erfordert eine AMD Radeon RX 5000 oder neuer."},
    {"pc_note_dlssg_driver","DLSS Frame Generation erfordert einen neueren NVIDIA-Treiber."},
    {"pc_note_dlssg_hags","DLSS Frame Generation erfordert die hardwarebeschleunigte GPU-Planung (Windows-Grafikeinstellungen)."},
    {"pc_note_dlssg_missing","DLSS Frame Generation ist in diesem Build nicht enthalten."},
    {"pc_note_dlssg_failed","DLSS Frame Generation konnte nicht starten und wurde ausgeschaltet."},
    {"pc_note_dlssg_restart","Starten Sie das Spiel neu, um DLSS Frame Generation zu starten."},
    {"pc_note_vsync_dlssg","DLSS Frame Generation läuft unter Vulkan ohne V-Sync; die Einstellung gilt wieder, wenn die Frame-Generierung aus ist."},
    {"pc_note_fsr_fg_restart","Starten Sie das Spiel neu, um von DLSS Frame Generation zu FSR 3 zu wechseln."},
    {"pc_note_dead_zone","0.10 ist der Wert des DualShock 4."},
    {"pc_note_gamepad_sensitivity","Passt die Drehgeschwindigkeit nach der ursprünglichen Stick-Kurve an. 1 behält sie bei."},
    {"pc_note_rt_shadows","Schatten per Raytracing statt mit Schattenkarten, so scharf wie im Original. Nicht im Original."},
    {"pc_note_rt_soft","Raytracing-Schatten mit weichen Kanten nach der Größe jedes Lichts. Nicht im Original."},
    {"pc_note_rt_unsupported","Erfordert eine GPU mit Vulkan-Raytracing."},
    {"pc_note_graphics","Wählen Sie eine Grafikvoreinstellung oder passen Sie Beleuchtung, Texturen und Bildeffekte an. Auflösung und Hochskalierung bleiben getrennt."},
    {"pc_note_rt_contact","Objekte werfen kurze Raytracing-Schatten von jedem Licht, auch von denen, die im Original keine werfen."},
    {"pc_note_rt_ao","Raytracing-Schattierung dunkelt Ecken und den Raum unter und hinter Objekten ab. Nicht im Original."},
    {"pc_rt_reflections","Spiegelungen"},
    {"pc_note_rt_reflections","Böden spiegeln die Szene über die Bildränder hinaus. Experimentell; das Aussehen kann vom Original abweichen."},
    {"pc_note_anisotropy","Schärfere Böden und Wände bei schrägem Blick. Aus ist die Filterung des Originals."},
    {"pc_graphics_quality","Qualität"},
    {"pc_graphics_preset","Voreinstellung"},
    {"pc_preset_low","Niedrig"},
    {"pc_preset_medium","Mittel"},
    {"pc_preset_original","Original (PS4)"},
    {"pc_preset_high","Hoch"},
    {"pc_preset_ultra","Ultra"},
    {"pc_preset_custom","Benutzerdefiniert"},
    {"pc_ray_tracing","Raytracing"},
    {"pc_clarity","Bildklarheit"},
    {"pc_graphics_advanced","Erweitert"},
    {"pc_graphics_lighting","Beleuchtung"},
    {"pc_graphics_effects","Bildeffekte"},
    {"pc_graphics_image","Bild"},
    {"pc_lighting_standard","Standardbeleuchtung"},
    {"pc_shadow_quality","Schattenkarten"},
    {"pc_standard_ao","Umgebungsverdeckung"},
    {"pc_standard_reflections","Bildschirmspiegelungen"},
    {"pc_ray_quality","Strahlenqualität"},
    {"pc_ray_balanced","Ausgewogen"},
    {"pc_texture_detail","Texturdetails"},
    {"pc_detail_reduced","Reduziert"},
    {"pc_detail_fine","Fein"},
    {"pc_dof","Tiefenschärfe"},
    {"pc_motion_blur","Bewegungsunschärfe"},
    {"pc_bloom","Bloom"},
    {"pc_lens_ghosts","Lens-Flare-Reflexe"},
    {"pc_note_lens_ghosts","Die großen Lens-Flare-Reflexe über den ganzen Bildschirm beim Blick nahe einer Lampe, wie im Original (PS4). Aus entfernt sie."},
    {"pc_film_grain","Filmkörnung"},
    {"pc_note_preset","Ändert nur die Grafik; Auflösung und Hochskalierung bleiben. Manuelle Änderungen zeigen Benutzerdefiniert. Ultra nutzt Raytracing, wenn unterstützt."},
    {"pc_note_ray_master","Schaltet Raytracing-Schatten, Kontaktschatten, Umgebungsverdeckung und Spiegelungen gemeinsam ein oder aus. Einzeln unter Beleuchtung."},
    {"pc_lens_distortion","Objektiveffekt"},
    {"pc_note_lens_distortion","Die originale Objektivwölbung und Farbsäume. Aus ergibt schärfere Ränder und ein weiteres, freies Bild."},
    {"pc_note_clarity","Fügt eine dezente lokale Kontrastschärfung in der Ausgabeauflösung hinzu. Null behält das Originalbild."},
    {"pc_note_letterbox","Schwarze Balken über und unter dem Bild, im Spiel und in Zwischensequenzen. Untertitel bleiben im Bild. Nicht im Original."},
    {"pc_note_advanced","Diese Kategorie fein einstellen. Zurück führt zur Grafik; Änderungen zeigen automatisch Benutzerdefiniert."},
    {"pc_note_shadow_quality","Schattenkarten mit 512, 1024 oder originalen 2048 px. Raytracing-Schatten ersetzen sie, wenn aktiv. Die Auflösungsskalierung bleibt."},
    {"pc_note_standard_ao","Die originale Umgebungsverdeckung im Bildschirmraum. Ausschalten entlastet langsamere GPUs."},
    {"pc_note_standard_reflections","Die originalen Bodenspiegelungen im Bildschirmraum. Raytracing-Spiegelungen ersetzen sie, wenn aktiv."},
    {"pc_note_ray_quality","Ausgewogen: 2 Strahlen. Hoch: 4 Strahlen. Ultra: 8 Strahlen für weichere Schatten und weniger Rauschen in der Raytracing-Verdeckung."},
    {"pc_note_texture_detail","Reduziert nutzt gröbere Mip-Stufen. Fein behält mehr Details in der Ferne, kann aber flimmern. Die Ausgabeauflösung bleibt."},
    {"pc_note_dof","Die originale Fokusunschärfe der Kamera. Aus hält nahe Flächen und den Hintergrund scharf."},
    {"pc_note_motion_blur","Die originale Unschärfe beim Drehen und Bewegen. Aus ergibt ein klareres Bild in Bewegung."},
    {"pc_note_bloom","Das originale Überstrahlen der Lichter. Aus verringert das Leuchten und die Nachbearbeitungskosten."},
    {"pc_note_film_grain","Die Stärke der originalen Filmkörnung. Aus ergibt ein saubereres Bild; 100 % behält den Originaleffekt."},
    {"pc_mods","Mods"},
    {"pc_section_mods","Installierte Mods"},
    {"pc_note_mods","Das Ein- oder Ausschalten eines Mods wirkt beim nächsten Start. Mods sind nicht Teil des Originalspiels."},
    {"pc_archive","Museum"},
    {"pc_note_archive","Die Bilder, Stimmen, Fotostücke, Zwischensequenzen und Modelle des Spiels, sobald Sie sie im Spiel erreichen. Ihr Spiel wird nicht verändert."},
    {"pc_note_extras_archive","Schleifenauswahl, Museum, freie Kamera und Fotomodus."},
    {"pc_archive_sections","Säle"},
    {"pc_archive_images","Unterschwellige Bilder"},
    {"pc_archive_voices","Stimmen und Radio"},
    {"pc_archive_photos","Fotostücke"},
    {"pc_archive_cutscenes","Zwischensequenzen"},
    {"pc_archive_models","Modelle"},
    {"pc_archive_unused","Ungenutzte Inhalte"},
    {"pc_note_archive_images","Die Texte der unterschwelligen Blitze, das Rauschen der Blitze und der Blick durch das Guckloch."},
    {"pc_note_archive_voices","Die Radiosendungen und jede gesprochene Zeile, mit der Abschrift in Ihrer Untertitelsprache."},
    {"pc_note_archive_photos","Die zerrissenen Stücke der Fotografie und das Foto, das sie im Rahmen ergeben."},
    {"pc_note_archive_cutscenes","Jede Zwischensequenz von Anfang an, mit Ton und Untertiteln."},
    {"pc_note_archive_models","Lisa und die anderen Gestalten und Gegenstände des Flurs, im Licht des Startraums."},
    {"pc_note_archive_unused_section","Inhalte in den Dateien des Spiels, die das Spiel nie zeigt. Sie öffnen sich, sobald Sie das Spiel beendet haben."},
    {"pc_note_archive_image","Enter / Kreuz: im Vollbild ansehen."},
    {"pc_note_archive_voice","Enter / Kreuz: abspielen oder anhalten."},
    {"pc_note_archive_photo","Enter / Kreuz: im Vollbild ansehen."},
    {"pc_note_archive_demo","Enter / Kreuz: von Anfang an abspielen. Esc / Kreis hält an."},
    {"pc_note_archive_model","Enter / Kreuz: Modell ansehen. Esc / Kreis: zurück."},
    {"pc_note_archive_unused","Im Spiel nie zu sehen. Enter / Kreuz: Modell ansehen."},
    {"pc_note_archive_locked","Gesperrt. Erreichen Sie es im Spiel, um es zu öffnen."},
    {"pc_note_archive_playing","Wird abgespielt. Enter / Kreuz hält an."},
    {"pc_archive_lock","Museum sperren"},
    {"pc_note_archive_lock","Sperrt jedes Ausstellungsstück des Museums wieder wie vor dem Spielen. Ihr Spielstand wird nicht verändert."},
    {"pc_archive_hint","Enter / X / A: öffnen"},
    {"pc_archive_view_hint","Links / Rechts: vorheriges / nächstes. Esc / Kreis: zurück."},
    {"pc_archive_demo_hint","Esc / Kreis / Enter / Kreuz: anhalten"},
    {"pc_archive_model_hint","Pfeile / Sticks: drehen. W / S / Trigger: näher / weiter weg. Esc / Kreis: zurück."},
    {"pc_archive_sub","Unterschwelliger Text {1}"},
    {"pc_archive_noise","Rauschen"},
    {"pc_archive_noise_normal","Rauschverzerrung"},
    {"pc_archive_peephole_mask","Der Blick durch das Guckloch"},
    {"pc_archive_radio_news","Radio: die Nachrichtensendung"},
    {"pc_archive_radio_news2","Radio: die Sendung noch einmal"},
    {"pc_archive_radio_voice","Radiostimme {1}"},
    {"pc_archive_riddle","Radiorätsel {1}"},
    {"pc_archive_sermon","Radio: die Predigt"},
    {"pc_archive_phone","Der Anruf"},
    {"pc_archive_peephole_voice","Durch das Guckloch"},
    {"pc_archive_bag","Die sprechende Tüte"},
    {"pc_archive_fetus","Der Fötus spricht {1}"},
    {"pc_archive_photo_lisa","Stück: Lisa"},
    {"pc_archive_photo_tree","Stück: der Baum"},
    {"pc_archive_photo_gap","Stück: der Spalt"},
    {"pc_archive_photo_bath","Stück: das Badezimmer"},
    {"pc_archive_photo_stair","Stück: die Treppe"},
    {"pc_archive_photo_option","Stück: der Optionsbildschirm"},
    {"pc_archive_photo_complete","Das vollständige Foto"},
    {"pc_archive_preface","Das Vorwort"},
    {"pc_archive_awakening","Das erste Erwachen"},
    {"pc_archive_opening","Das Erwachen"},
    {"pc_archive_first_exit","Die erste Tür"},
    {"pc_archive_door","Durch die Tür"},
    {"pc_archive_clock","Mitternacht"},
    {"pc_archive_kill","Von Lisa gefangen"},
    {"pc_archive_ending","Das Ende"},
    {"pc_archive_teaser","Der Teaser"},
    {"pc_archive_lisa_stand","Lisa, stehend"},
    {"pc_archive_lisa_walk","Lisa, gehend"},
    {"pc_archive_lisa_dash","Lisa, stürmend"},
    {"pc_archive_lisa_door","Lisa hinter der Tür"},
    {"pc_archive_baby","Der Fötus im Waschbecken"},
    {"pc_archive_fridge","Der Kühlschrank"},
    {"pc_archive_bag_model","Die Papiertüte"},
    {"pc_archive_lamp","Die Deckenlampe"},
    {"pc_archive_roach","Kakerlake"},
    {"pc_archive_flashlight","Die Taschenlampe"},
    {"pc_archive_radio","Das Radio"},
    {"pc_archive_phone_model","Das Telefon"},
    {"pc_archive_xmark_photo","Das Foto mit dem X"},
    {"pc_archive_clock_model","Die Uhr"},
    {"pc_archive_man","Der Mann"},
    {"pc_archive_bathtub","Die Leiche in der Badewanne"},
};
inline std::string_view Menu(std::string_view key) {
    for (const auto& e : kMenu) if (e.key == key) return e.text;
    return {};
}
}
