#pragma once
#include <string_view>

// Italian for the port's own menus (PC settings, extras, photo mode, loop browser, notes and prompts) and the added
// languages' names on the option screen. The options screen's other texts and the subtitles are the game's own.
namespace pt::italian {
struct Text { std::string_view key, text; };
inline constexpr Text kMenu[] = {
    {"pc_controller_speaker","Altoparlante del controller"},
    {"pc_note_controller_speaker","Riproduce le urla registrate di Lisa dagli altoparlanti supportati dei controller Sony. Su Windows serve una connessione USB; i dispositivi non supportati e Bluetooth restano silenziosi. Indipendente dal feedback aptico; disattivato per impostazione predefinita."},
    {"pc_controller_speaker_volume","Volume altoparlante controller"},
    {"pc_note_controller_speaker_volume","Regola solo il volume dell’altoparlante del controller, a incrementi del 5%. Non modifica l’audio del gioco né la forza aptica di DualSense. Disponibile solo con controller Sony cablati supportati su Windows."},
    {"pc_microphone_trigger_assign","Assegna {input} al comando del microfono"},
    {"pc_note_microphone_trigger","Alternativa facoltativa al microfono. La tastiera e i due grilletti del controller la attivano solo quando il gioco ascolta."},
    {"pc_note_microphone_test","Prova il microfono e il risultato del riconoscimento."},
    {"pc_fps_limit","Limite fotogrammi"},
    {"pc_unlimited","Illimitato"},
    {"pc_note_fps_limit","Limita i fotogrammi renderizzati. I menu restano limitati a 60 FPS. La sincronizzazione verticale può imporre un limite inferiore."},
    {"pc_hdr","HDR nativo"},
    {"pc_note_hdr_restart","Si applica al prossimo avvio. Richiede HDR attivo su uno schermo compatibile; altrimenti viene usato SDR."},
    {"pc_surround","Uscita surround"},
    {"pc_note_surround","Dopo il riavvio usa la configurazione 5.1 o 7.1 dell’uscita. I dispositivi stereo restano in stereo."},
    {"pc_rumble_profile","Modalità vibrazione"},
    {"pc_rumble_original","Originale"},
    {"pc_rumble_enhanced","Migliorata"},
    {"pc_note_rumble_profile","Originale usa solo la vibrazione dei motori prevista dal gioco. Migliorata aggiunge la vibrazione dei grilletti supportati e, su Windows sui controller DualSense USB supportati, aptica ricavata dalle urla filtrate di Lisa. Il comando principale della vibrazione disattiva entrambe. L’audio dell’altoparlante del controller è indipendente."},
    {"pc_vr_height","Regolazione altezza"},
    {"pc_note_vr_height","Sposta il punto di vista tracciato in alto o in basso senza cambiare la posizione del giocatore nel gioco."},
    {"pc_vr_world_scale","Scala del mondo"},
    {"pc_note_vr_world_scale","Ridimensiona i movimenti tracciati di testa, occhi e controller dal 50% al 200%. Più il valore è alto, più il mondo sembra piccolo. Valore predefinito: 100%."},
    {"pc_photo_focal_length","Lunghezza focale"},
    {"pc_note_photo_focal_length","Lunghezza focale dell’obiettivo in millimetri. La sfocatura usa lo stesso obiettivo e sensore della fotocamera."},
    {"pc_photo_aspect","Formato immagine"},
    {"pc_note_photo_aspect","Ritaglia la foto dal centro."},
    {"pc_photo_resolution","Risoluzione foto"},
    {"pc_note_photo_resolution","Nativa salva i pixel inquadrati. 4K esegue di nuovo il rendering della scena con 3840 pixel sul lato lungo."},
    {"pc_photo_resolution_native","Nativa"},
    {"pc_photo_resolution_4k","4K"},
    {"pc_photo_filter","Filtro colore"},
    {"pc_note_photo_filter","Si applica solo all’anteprima e alla foto salvata."},
    {"pc_photo_filter_bw","Bianco e nero"},
    {"pc_photo_filter_warm","Caldo"},
    {"pc_photo_filter_cool","Freddo"},
    {"pc_photo_filter_muted","Tenue"},
    {"pc_archive_model_hint","WASD / stick sinistro: sposta l’inquadratura. Frecce / stick destro: ruota. Grilletti: zoom. Esc / Cerchio: indietro."},
    {"pc_note_resolution_fullscreen","La modalità senza bordi usa la dimensione scelta; lo schermo intero esclusivo usa una modalità supportata."},
    {"op_sub_turkish","Turco"},
    {"op_sub_chinese","Cinese semplificato"},
    {"op_sub_arabic","Arabo"},
    {"op_sub_russian","Russo"},
    {"op_sub_ukrainian","Ucraino"},
    {"op_sub_czech","Ceco"},
    {"op_sub_polish","Polacco"},
    {"pc_loop_browser","Selezione ciclo"},
    {"pc_note_loop_browser_entry","Avvia qualsiasi ciclo senza sostituire il tuo salvataggio."},
    {"pc_loop_choose","Scegli un ciclo"},
    {"pc_loop_preview","Anteprima"},
    {"pc_loop_start_hint","Invio / X / A: avvia il ciclo"},
    {"pc_loop_f000","Stanza iniziale: l'apertura"},
    {"pc_loop_f010","Ciclo 1: la radio"},
    {"pc_loop_f005","Ciclo 2: si apre la porta dell'ingresso"},
    {"pc_loop_f020","Ciclo 3: pianto in bagno"},
    {"pc_loop_f030","Ciclo 4: la porta del bagno"},
    {"pc_loop_f040","Ciclo 5: Lisa in fondo al corridoio"},
    {"pc_loop_f060","Ciclo 6: il bagno, la torcia"},
    {"pc_loop_f050a","Ciclo 7: Lisa ti segue"},
    {"pc_loop_f050b","Ciclo 8: la foto con la croce"},
    {"pc_loop_f070","Ciclo 9: la finestra si rompe"},
    {"pc_loop_f080","Ciclo 10: il frigorifero che sanguina"},
    {"pc_loop_f090","Ciclo 11: HELLO"},
    {"pc_loop_f100","Ciclo 12: il corridoio rosso"},
    {"pc_loop_f110","Ciclo 13: il labirinto e lo spioncino"},
    {"pc_loop_f120","Ciclo 14: 204863, la schermata di errore"},
    {"pc_loop_f160","Ciclo 15: l'ultimo ciclo"},
    {"pc_loop_ending","Filmato finale e titoli di coda"},
    {"pc_loop_street","Passeggiata in strada (dopo il finale)"},
    {"pc_note_loop_opening","Avvia l'apertura nella stanza iniziale, come una nuova partita. Il tuo salvataggio resta invariato."},
    {"pc_note_loop_hallway","Inizia nella stanza iniziale appena prima di questo ciclo, con gli enigmi precedenti risolti. Attraversa la porta. Il salvataggio resta invariato e riprende al prossimo checkpoint."},
    {"pc_note_loop_ending","Riproduce il filmato finale e i titoli di coda, poi propone la passeggiata in strada. Il tuo salvataggio resta invariato."},
    {"pc_note_loop_street","Ti porta nella strada del finale, in prima persona. Esci da Extra. Il tuo salvataggio resta invariato."},
    {"pc_note_loop_locked","Bloccato. Completa il gioco una volta; poi si apre ogni ciclo raggiunto giocando."},
    {"pc_note_loop_browser_locked","Completa il gioco una volta per sbloccare la selezione ciclo."},
    {"pc_street_title","La strada"},
    {"pc_street_question","Esplorare la strada?"},
    {"pc_street_walk","Sì, percorri la strada"},
    {"pc_credit_version","P.T. PC Port {1} di LoreanXavier"},
    {"pc_update_available","Versione {1} disponibile (questa è la {2})"},
    {"pc_credits_by","di LoreanXavier"},
    {"pc_credits_dlss","Questo gioco utilizza NVIDIA DLSS."},
    {"pc_credits_licenses","I testi completi delle licenze si trovano nella cartella licenses accanto a pt.exe."},
    {"pc_credits_konami","P.T. appartiene a Konami Digital Entertainment e Kojima Productions."},
    {"pc_credits_fan","Questo port è un progetto amatoriale non ufficiale, non affiliato né approvato da Konami, NVIDIA, AMD o Intel."},
    {"pc_note_street_walk","Percorri in prima persona la strada del finale. Esci da Extra."},
    {"pc_street_restart","No, torna all'inizio"},
    {"pc_note_street_restart","Ricomincia dalla stanza iniziale, come fa l'originale dopo i titoli di coda."},
    {"pc_street_leave","Lascia la strada"},
    {"pc_note_street_leave","Termina la passeggiata e torna alla stanza iniziale."},
    {"pc_street_return","Torna alla casa"},
    {"pc_street_return_confirm","Tornare alla casa?"},
    {"pc_loop_lock","Blocca la selezione ciclo"},
    {"pc_note_loop_lock","Blocca di nuovo tutti i cicli, come prima del tuo primo finale. Il salvataggio non cambia."},
    {"pc_extras","Extra"},
    {"pc_vr","VR (sperimentale)"},
    {"pc_note_vr","Gioca con un visore VR tramite OpenXR. Sperimentale: non provato su hardware reale."},
    {"pc_vr_mode","Modalità VR"},
    {"pc_note_vr_mode","Non provato su hardware reale. Richiede un runtime OpenXR e un visore. Si applica al prossimo avvio; senza visore il gioco parte come sempre."},
    {"pc_vr_flashlight","Torcia"},
    {"pc_note_vr_flashlight","La torcia segue la tua testa, come nell'originale, o il controller che hai in mano."},
    {"pc_vr_head","Testa"},
    {"pc_vr_controller","Controller"},
    {"pc_vr_turn","Rotazione"},
    {"pc_note_vr_turn","Lo stick destro ruota a scatti o in modo continuo. Gli scatti danno meno nausea."},
    {"pc_vr_snap","A scatti"},
    {"pc_vr_smooth","Continua"},
    {"pc_note_extras","Selezione ciclo, visuale libera e modalità foto."},
    {"pc_freecam","Visuale libera"},
    {"pc_note_freecam","Stacca la visuale dal giocatore (F6). Spazio / Ctrl o i grilletti: sali e scendi, Maiusc o L3: più veloce. Esc: esci."},
    {"pc_photo_mode","Modalità foto"},
    {"pc_note_photo_mode","Metti in pausa e inquadra con la visuale libera (F7). P o Quadrato: salva in Pictures/PT Photos, H o Triangolo: nascondi il pannello."},
    {"pc_speedrun","Timer speedrun"},
    {"pc_note_speedrun","Un timer a schermo con un parziale a ogni ciclo e una schermata dei risultati dopo i titoli di coda. Il tempo reale conta tutto; il tempo di gioco esclude pause e caricamenti. Assente nell'originale."},
    {"pc_speedrun_real_time","Tempo reale"},
    {"pc_speedrun_game_time","Tempo di gioco"},
    {"pc_livesplit","Server LiveSplit"},
    {"pc_note_livesplit","Invia a LiveSplit l'avvio, i parziali e il tempo di gioco (Control > Start TCP Server, porta {1}). Host e porta sono in pt.ini."},
    {"pc_speedrun_results","PARTITA COMPLETATA"},
    {"pc_speedrun_run","Partita"},
    {"pc_speedrun_splits","Parziali"},
    {"pc_speedrun_menu","Torna al menu"},
    {"pc_note_speedrun_menu","Ricomincia dall'inizio come l'originale dopo il finale, prima con la schermata delle opzioni. La partita successiva parte quando riprendi il controllo."},
    {"pc_speedrun_outside","Esplora fuori"},
    {"pc_note_speedrun_outside","Percorri la strada del finale. Torna alla casa dal menu di pausa."},
    {"pc_note_speedrun_real","Orologio reale da quando prendi il controllo al finale: pause, caricamenti e filmati inclusi."},
    {"pc_note_speedrun_game","Solo gioco non in pausa: il menu di pausa e i caricamenti dopo un game over sono esclusi."},
    {"pc_speedrun_best","Record personale"},
    {"pc_note_speedrun_best","Record precedente: {1}. I record sono in speedrun.ini, speedrun_history.txt e speedrun_pb.lss (LiveSplit) nella cartella utente."},
    {"pc_speedrun_new_best","Nuovo record!"},
    {"pc_speedrun_partial","Non dall'inizio"},
    {"pc_speedrun_start_room","Stanza iniziale"},
    {"pc_speedrun_loop","Ciclo {1}"},
    {"pc_third_person","Terza persona (sperimentale)"},
    {"pc_note_third_person","Sperimentale, non presente nell'originale: la visuale segue il giocatore da dietro la spalla. Lo zoom e i filmati tornano in prima persona; gli eventi si svolgono come in prima persona."},
    {"pc_extras_start","Avvia"},
    {"pc_photo_title","MODALITÀ FOTO"},
    {"pc_photo_section_camera","Visuale"},
    {"pc_photo_section_lens","Obiettivo"},
    {"pc_photo_section_image","Immagine"},
    {"pc_photo_take","Scatta foto"},
    {"pc_photo_capture","Scatta"},
    {"pc_photo_fov","Campo visivo"},
    {"pc_photo_roll","Rotazione visuale"},
    {"pc_photo_speed","Velocità visuale"},
    {"pc_photo_speed_slow","Lenta"},
    {"pc_photo_speed_normal","Normale"},
    {"pc_photo_speed_fast","Veloce"},
    {"pc_photo_reset","Ripristina visuale"},
    {"pc_photo_focus","Distanza di messa a fuoco"},
    {"pc_photo_aperture","Apertura"},
    {"pc_photo_exposure","Esposizione"},
    {"pc_photo_grading","Correzione colore"},
    {"pc_photo_letterbox","Bande cinema"},
    {"pc_photo_body","Corpo del giocatore"},
    {"pc_photo_flashlight","Torcia"},
    {"pc_photo_shown","Visibile"},
    {"pc_photo_hidden","Nascosto"},
    {"pc_photo_auto","Auto"},
    {"pc_photo_metres","{value} m"},
    {"pc_photo_saved","Salvata in Pictures/PT Photos: {file}"},
    {"pc_photo_save_failed","Impossibile salvare la foto. Consulta pt.log."},
    {"pc_photo_hint","Frecce / tasti direzionali: scegli e modifica. P / Quadrato: foto. H / Triangolo: nascondi pannello. Tasto destro del mouse: guarda. Esc / Cerchio: esci."},
    {"pc_note_photo_take","Salva la vista attuale in Pictures/PT Photos. Il pannello non compare mai nella foto."},
    {"pc_note_photo_fov","Campo visivo verticale in gradi. Valori più bassi ingrandiscono."},
    {"pc_note_photo_roll","Inclina la visuale di lato per un'inquadratura obliqua."},
    {"pc_note_photo_speed","Velocità della visuale. Maiusc o L3 la aumentano ancora."},
    {"pc_note_photo_reset","Riporta la visuale dove è iniziata la modalità foto."},
    {"pc_note_photo_dof","Sfoca ciò che è più vicino o più lontano della distanza di messa a fuoco."},
    {"pc_note_photo_focus","Auto mette a fuoco ciò che è al centro dell'inquadratura."},
    {"pc_note_photo_aperture","Numeri f più bassi sfocano di più. Auto mantiene l'obiettivo del gioco."},
    {"pc_note_photo_exposure","Schiarisce o scurisce l'immagine a passi di mezzo stop."},
    {"pc_note_photo_grain","La grana pellicola originale. Off dà un'immagine più pulita."},
    {"pc_note_photo_grading","Il colore originale. Off mostra colori neutri."},
    {"pc_note_photo_letterbox","Bande nere cinematografiche. Fanno parte della foto."},
    {"pc_note_photo_body","Mostra o nasconde il corpo del giocatore."},
    {"pc_note_photo_flashlight","Spegne la luce della torcia durante la modalità foto."},
    {"pc_extras_stop","Ferma"},
    {"pc_note_loop_generating","Creazione delle anteprime... Il tuo salvataggio resta invariato. Il salvataggio riprende al prossimo checkpoint: uscendo dal seminterrato o raggiungendo l'ultimo ciclo."},
    {"pc_title","IMPOSTAZIONI PC"},
    {"pc_entry","Impostazioni PC"},
    {"pc_back","Indietro"},
    {"pc_quit","Esci"},
    {"pc_nav_columns","Tab / L1 / R1: cambia colonna"},
    {"pc_quit_confirm","Uscire?"},
    {"pc_save_no_space","Spazio libero insufficiente per salvare la partita.\nLibera spazio, poi chiudi questo messaggio per riprovare."},
    {"pc_ok","OK"},
    {"pc_note_quit","Esci dal gioco."},
    {"pc_note_quit_confirm","Premi di nuovo {accept} per uscire. Indietro annulla."},
    {"pc_section_display","Schermo"},
    {"pc_section_upscaling","Upscaling"},
    {"pc_section_sound","Audio"},
    {"pc_section_controls","Comandi"},
    {"pc_section_progress","Progressi"},
    {"pc_section_ray_tracing","Ray tracing"},
    {"pc_section_textures","Texture"},
    {"pc_display_mode","Modalità schermo"},
    {"pc_resolution","Risoluzione"},
    {"pc_vsync","V-Sync"},
    {"pc_focus_pause","Pausa in background"},
    {"pc_focus_mute","Muto in background"},
    {"pc_upscaler","Metodo"},
    {"pc_quality","Modalità"},
    {"pc_sharpness","Nitidezza"},
    {"pc_frame_generation","Generazione frame"},
    {"pc_volume","Volume"},
    {"pc_microphone","Microfono"},
    {"pc_microphone_test","Test del microfono"},
    {"pc_mic_level","Livello di ingresso"},
    {"pc_mic_heard","Parole riconosciute"},
    {"pc_mic_monitor","Ascolta la mia voce"},
    {"pc_mic_no_word","Ancora nessuna"},
    {"pc_mic_waiting","In attesa del microfono selezionato..."},
    {"pc_mic_unavailable","Impossibile aprire il microfono selezionato. Controlla i permessi di registrazione e il dispositivo scelto."},
    {"pc_mic_st_loading","Caricamento..."},
    {"pc_mic_st_nomic","Nessun microfono"},
    {"pc_mic_st_files","File vocali mancanti"},
    {"pc_mic_st_runtime","Motore vocale non riuscito"},
    {"pc_mic_st_cpu","CPU non supportata"},
    {"pc_mic_st_model","Modello vocale non riuscito"},
    {"pc_mic_st_silent","Nessun suono"},
    {"pc_mic_err_files","I file del riconoscimento vocale mancano. Reinstalla o ripara il gioco."},
    {"pc_mic_err_runtime","Impossibile caricare il motore vocale. La causa è in pt.log."},
    {"pc_mic_err_cpu","Questo processore non può eseguire il motore vocale."},
    {"pc_mic_err_model","Impossibile caricare il modello vocale. La causa è in pt.log."},
    {"pc_mic_err_silent","Il microfono è aperto ma non invia alcun suono. Controlla che non sia disattivato e che sia selezionato il dispositivo giusto."},
    {"pc_mic_say_jack","Pronuncia «Jack» nel microfono selezionato. Questo test non fa avanzare l'enigma."},
    {"pc_mic_monitor_note","Ascolti il tuo microfono. Le cuffie evitano il ritorno. L'ascolto si interrompe quando esci dal test."},
    {"pc_mouse","Sensibilità del mouse"},
    {"pc_gamepad_sensitivity","Sensibilità di rotazione del controller"},
    {"pc_camera_tilt","Inclinazione visuale"},
    {"pc_vibration","Vibrazione"},
    {"pc_dead_zone","Zona morta levetta"},
    {"pc_reset","Azzera progressi"},
    {"pc_graphics","Grafica"},
    {"pc_graphics_value","Apri"},
    {"pc_rt_shadows","Ombre in ray tracing"},
    {"pc_rt_contact","Ombre di contatto"},
    {"pc_shadows","Ombre"},
    {"pc_reflections","Riflessi"},
    {"pc_standard","Standard"},
    {"pc_ray_traced","Ray tracing"},
    {"pc_rt_sharp_long","Ray tracing, nitide"},
    {"pc_rt_soft_long","Ray tracing, morbide"},
    {"pc_note_shadows","Da Basso a Originale sono le shadow map dell'originale (512, 1024 o 2048 px). Il ray tracing le sostituisce: nitide come l'originale o morbide in base alla dimensione di ogni luce."},
    {"pc_note_ao","Standard è l'occlusione in screen space dell'originale. Il ray tracing scurisce angoli e lo spazio sotto gli oggetti dalla scena stessa. Assente nell'originale."},
    {"pc_note_reflections","Standard sono i riflessi del pavimento in screen space dell'originale. Il ray tracing riflette anche ciò che è fuori schermo. Sperimentale."},
    {"pc_rt_ao","Occlusione ambientale"},
    {"pc_anisotropy","Filtro anisotropico"},
    {"pc_enhanced_textures","Texture migliorate"},
    {"pc_texture_preparing","Preparazione"},
    {"pc_note_texture_tools_missing","Mancano gli strumenti o i file del modello per le texture migliorate. Ripristina texture-tools dal pacchetto portatile e riprova. Le texture originali restano intatte."},
    {"pc_note_texture_busy","Un'altra istanza del gioco sta preparando questa cache di texture. Attendi che finisca e riprova. Le texture originali restano intatte."},
    {"pc_note_texture_failed","Preparazione delle texture non riuscita; le texture originali restano intatte. Controlla lo spazio libero e pt.log, poi riprova."},
    {"pc_note_texture_preparing","Preparazione delle texture migliorate. Fino ad allora restano quelle originali; poi cambiano senza riavvio. Off annulla."},
    {"pc_note_enhanced_textures","Crea una volta texture a colori più nitide dai file del gioco. Pareti e personaggi inclusi; 4096 px con 10 GB di memoria video, altrimenti 2048. Off annulla; le texture originali restano disponibili."},
    {"pc_rt_sharp","Nitide"},
    {"pc_rt_soft","Morbide"},
    {"pc_on","On"},
    {"pc_off","Off"},
    {"pc_window","Finestra"},
    {"pc_borderless","Senza bordi"},
    {"pc_fullscreen","Schermo intero"},
    {"pc_native","Nativa"},
    {"pc_quality_quality","Qualità"},
    {"pc_quality_balanced","Bilanciata"},
    {"pc_quality_performance","Prestazioni"},
    {"pc_quality_ultra","Ultra prestazioni"},
    {"pc_quality_custom","Personalizzata"},
    {"pc_system_default","Predefinito di sistema"},
    {"pc_reset_value","Azzera"},
    {"pc_reset_confirm","Conferma"},
    {"pc_reset_done","Fatto"},
    {"pc_note_vsync","Effetto immediato. Sincronizza le immagini con la frequenza di aggiornamento del monitor."},
    {"pc_note_vsync_off","Si applica subito. Disattivata, ogni frame appare appena è pronto: il frame rate non è legato alla frequenza del monitor e l'immagine può strapparsi."},
    {"pc_note_restart","Ha effetto al prossimo avvio."},
    {"pc_note_display_mode","Anche Alt+Invio passa da finestra a schermo intero."},
    {"pc_note_resolution","Dimensione della finestra."},
    {"pc_note_resolution_fullscreen","A schermo intero si usa la risoluzione del desktop."},
    {"pc_note_upscaler_off","Off esegue il rendering alla risoluzione dello schermo, come l'originale."},
    {"pc_note_render_size","Rendering a {1}, mostrato a {2}."},
    {"pc_note_needs_upscaler","Richiede un metodo di upscaling."},
    {"pc_note_sharpness_fsr","Solo FSR ha una nitidezza propria. Nitidezza immagine, nella pagina Grafica, funziona con qualsiasi metodo."},
    {"pc_note_reset","Azzera i progressi e riavvia subito il gioco. La lingua e le impostazioni PC restano."},
    {"pc_note_reset_confirm","Premi di nuovo {accept} per eliminare il salvataggio."},
    {"pc_note_reset_done","Progressi azzerati in questa sessione."},
    {"pc_note_camera_tilt","La visuale si inclina con la testa, come nell'originale."},
    {"pc_note_voice","Il microfono ascolta solo dove lo fa il gioco originale."},
    {"pc_note_focus_pause","Apre questo menu quando la finestra passa in background."},
    {"pc_note_focus_mute","Silenzia il gioco mentre la finestra è in background."},
    {"pc_note_frame_generation_missing","Non presente in questa versione."},
    {"pc_note_frame_generation","AMD FSR 3 mostra un frame generato tra due frame renderizzati."},
    {"pc_note_fsr4_vulkan","AMD pubblica FSR 4 solo per DirectX 12; questo gioco usa Vulkan, quindi FSR 4 non può funzionare qui."},
    {"pc_dlss_model","Modello DLSS"},
    {"pc_dlss_model_auto","Automatico"},
    {"pc_note_dlss_model","Automatico segue la scelta di NVIDIA: K fino a Bilanciata, M in Prestazioni, L in Ultra prestazioni. L e M costano circa il doppio su RTX 20 e 30."},
    {"pc_note_frame_generation_dlss","Sperimentale. NVIDIA DLSS Frame Generation mostra un frame generato tra due frame renderizzati. Si attiva al prossimo avvio."},
    {"pc_note_dlssg_gpu","DLSS Frame Generation richiede una NVIDIA GeForce RTX serie 40 o successiva."},
    {"pc_note_fsr_fg_gpu","La generazione frame FSR 3 richiede una AMD Radeon RX serie 5000 o successiva."},
    {"pc_note_dlssg_driver","DLSS Frame Generation richiede un driver NVIDIA più recente."},
    {"pc_note_dlssg_hags","DLSS Frame Generation richiede la pianificazione GPU con accelerazione hardware (impostazioni grafiche di Windows)."},
    {"pc_note_dlssg_missing","DLSS Frame Generation non è incluso in questa build."},
    {"pc_note_dlssg_failed","DLSS Frame Generation non è riuscito ad avviarsi ed è stato disattivato."},
    {"pc_note_dlssg_restart","Riavvia il gioco per avviare DLSS Frame Generation."},
    {"pc_note_vsync_dlssg","DLSS Frame Generation funziona senza V-Sync su Vulkan; l'impostazione torna valida quando la generazione frame è disattivata."},
    {"pc_note_fsr_fg_restart","Riavvia il gioco per passare da DLSS Frame Generation a FSR 3."},
    {"pc_note_dead_zone","0.10 è il valore del DualShock 4."},
    {"pc_note_gamepad_sensitivity","Modifica la velocità di rotazione dopo la risposta originale dello stick. 1 la mantiene invariata."},
    {"pc_note_rt_shadows","Ombre calcolate in ray tracing invece delle shadow map, nitide come quelle originali. Assente nell'originale."},
    {"pc_note_rt_soft","Ombre in ray tracing con bordi morbidi in base alla dimensione di ogni luce. Assente nell'originale."},
    {"pc_note_rt_unsupported","Richiede una GPU con ray tracing Vulkan."},
    {"pc_note_graphics","Scegli una preimpostazione o regola illuminazione, texture ed effetti immagine. Risoluzione e upscaling restano a parte."},
    {"pc_note_rt_contact","Gli oggetti proiettano brevi ombre in ray tracing da ogni luce, anche da quelle che nell'originale non ne proiettano."},
    {"pc_note_rt_ao","L'ombreggiatura in ray tracing scurisce angoli e lo spazio sotto e dietro gli oggetti. Assente nell'originale."},
    {"pc_rt_reflections","Riflessi"},
    {"pc_note_rt_reflections","I pavimenti riflettono la scena oltre i bordi dello schermo. Sperimentale; l'aspetto può differire dall'originale."},
    {"pc_note_anisotropy","Pavimenti e pareti più nitidi visti di sbieco. Off è il filtro originale."},
    {"pc_graphics_quality","Qualità"},
    {"pc_graphics_preset","Preimpostazione"},
    {"pc_preset_low","Basso"},
    {"pc_preset_medium","Medio"},
    {"pc_preset_original","Originale (PS4)"},
    {"pc_preset_high","Alto"},
    {"pc_preset_ultra","Ultra"},
    {"pc_preset_custom","Personalizzato"},
    {"pc_ray_tracing","Ray tracing"},
    {"pc_clarity","Nitidezza immagine"},
    {"pc_graphics_advanced","Avanzate"},
    {"pc_graphics_lighting","Illuminazione"},
    {"pc_graphics_effects","Effetti immagine"},
    {"pc_graphics_image","Immagine"},
    {"pc_lighting_standard","Illuminazione standard"},
    {"pc_shadow_quality","Shadow map"},
    {"pc_standard_ao","Occlusione ambientale"},
    {"pc_standard_reflections","Riflessi a schermo"},
    {"pc_ray_quality","Qualità dei raggi"},
    {"pc_ray_balanced","Bilanciata"},
    {"pc_texture_detail","Dettaglio texture"},
    {"pc_detail_reduced","Ridotto"},
    {"pc_detail_fine","Fine"},
    {"pc_dof","Profondità di campo"},
    {"pc_motion_blur","Sfocatura di movimento"},
    {"pc_bloom","Bloom"},
    {"pc_lens_ghosts","Riflessi del lens flare"},
    {"pc_note_lens_ghosts","I grandi riflessi del lens flare su tutto lo schermo quando si guarda vicino a una lampada, come nell'originale (PS4). Off li rimuove."},
    {"pc_film_grain","Grana pellicola"},
    {"pc_note_preset","Cambia solo la grafica; risoluzione e upscaling restano. Le modifiche manuali mostrano Personalizzato. Ultra usa il ray tracing se supportato."},
    {"pc_note_ray_master","Attiva o disattiva insieme ombre in ray tracing, ombre di contatto, occlusione ambientale e riflessi. I singoli comandi sono in Illuminazione."},
    {"pc_lens_distortion","Effetto obiettivo"},
    {"pc_note_lens_distortion","La curvatura dell'obiettivo e le frange di colore originali. Off dà bordi più nitidi e un'immagine più ampia."},
    {"pc_note_clarity","Aggiunge una leggera nitidezza del contrasto locale alla risoluzione di uscita. Zero mantiene l'immagine originale."},
    {"pc_note_letterbox","Bande nere sopra e sotto l'immagine, in gioco e nelle scene di intermezzo. I sottotitoli restano nell'immagine. Assente nell'originale."},
    {"pc_note_advanced","Regola questa categoria. Indietro torna a Grafica; le modifiche mostrano Personalizzato."},
    {"pc_note_shadow_quality","Shadow map da 512, 1024 o 2048 px (originale). Le ombre in ray tracing le sostituiscono se attive. La scala di risoluzione non cambia."},
    {"pc_note_standard_ao","L'occlusione ambientale originale in screen space. Disattivala per alleggerire le GPU più lente."},
    {"pc_note_standard_reflections","I riflessi del pavimento originali in screen space. I riflessi in ray tracing li sostituiscono se attivi."},
    {"pc_note_ray_quality","Bilanciata: 2 raggi. Alto: 4 raggi. Ultra: 8 raggi, per ombre più morbide e meno rumore nell'occlusione in ray tracing."},
    {"pc_note_texture_detail","Ridotto usa mip più grossolane. Fine mantiene più dettagli in lontananza; può sfarfallare. La risoluzione di uscita non cambia."},
    {"pc_note_dof","La sfocatura di messa a fuoco originale. Off mantiene nitidi le superfici vicine e lo sfondo."},
    {"pc_note_motion_blur","La sfocatura originale durante rotazioni e movimenti. Off dà un'immagine più chiara in movimento."},
    {"pc_note_bloom","Il bagliore originale delle luci. Off riduce l'alone e il costo della post-elaborazione."},
    {"pc_note_film_grain","L'intensità della grana pellicola originale. Off dà un'immagine più pulita; 100% mantiene l'effetto originale."},
    {"pc_mods","Mod"},
    {"pc_section_mods","Mod installate"},
    {"pc_note_mods","Attivare o disattivare una mod ha effetto al prossimo avvio. Le mod non fanno parte del gioco originale."},
    {"pc_archive","Museo"},
    {"pc_note_archive","Immagini, voci, pezzi di foto, filmati e modelli del gioco stesso, man mano che li raggiungi giocando. La tua partita non cambia."},
    {"pc_note_extras_archive","Selezione ciclo, museo, visuale libera e modalità foto."},
    {"pc_archive_sections","Sale"},
    {"pc_archive_images","Immagini subliminali"},
    {"pc_archive_voices","Voci e radio"},
    {"pc_archive_photos","Pezzi di foto"},
    {"pc_archive_cutscenes","Filmati"},
    {"pc_archive_models","Modelli"},
    {"pc_archive_unused","Contenuti inutilizzati"},
    {"pc_note_archive_images","I testi dei lampi subliminali, il disturbo dei lampi e la vista dallo spioncino."},
    {"pc_note_archive_voices","Le trasmissioni radio e ogni battuta parlata, con la trascrizione nella lingua dei sottotitoli."},
    {"pc_note_archive_photos","I pezzi strappati della fotografia, e la foto che formano nella cornice."},
    {"pc_note_archive_cutscenes","Ogni filmato dall'inizio, con il suo sonoro e i sottotitoli."},
    {"pc_note_archive_models","Lisa e le altre figure e oggetti del corridoio, nella luce della stanza iniziale."},
    {"pc_note_archive_unused_section","Contenuti presenti nei file del gioco che il gioco non mostra mai. Si apre dopo aver completato il gioco."},
    {"pc_note_archive_image","Invio / Croce: visualizza a schermo intero."},
    {"pc_note_archive_voice","Invio / Croce: riproduci o ferma."},
    {"pc_note_archive_photo","Invio / Croce: visualizza a schermo intero."},
    {"pc_note_archive_demo","Invio / Croce: riproduci dall'inizio. Esc / Cerchio lo ferma."},
    {"pc_note_archive_model","Invio / Croce: guarda il modello. Esc / Cerchio: indietro."},
    {"pc_note_archive_unused","Mai mostrato nel gioco. Invio / Croce: guarda il modello."},
    {"pc_note_archive_locked","Bloccato. Raggiungilo giocando per aprirlo."},
    {"pc_note_archive_playing","In riproduzione. Invio / Croce lo ferma."},
    {"pc_archive_lock","Blocca il museo"},
    {"pc_note_archive_lock","Blocca di nuovo ogni pezzo del museo, come prima di giocare. Il salvataggio non cambia."},
    {"pc_archive_hint","Invio / X / A: apri"},
    {"pc_archive_view_hint","Sinistra / Destra: precedente / successivo. Esc / Cerchio: indietro."},
    {"pc_archive_demo_hint","Esc / Cerchio / Invio / Croce: ferma"},
    {"pc_archive_model_hint","Frecce / levette: ruota. W / S / grilletti: più vicino / più lontano. Esc / Cerchio: indietro."},
    {"pc_archive_sub","Testo subliminale {1}"},
    {"pc_archive_noise","Disturbo"},
    {"pc_archive_noise_normal","Distorsione del disturbo"},
    {"pc_archive_peephole_mask","La vista dallo spioncino"},
    {"pc_archive_radio_news","Radio: il notiziario"},
    {"pc_archive_radio_news2","Radio: il notiziario, di nuovo"},
    {"pc_archive_radio_voice","Voce della radio {1}"},
    {"pc_archive_riddle","Indovinello della radio {1}"},
    {"pc_archive_sermon","Radio: il sermone"},
    {"pc_archive_phone","La telefonata"},
    {"pc_archive_peephole_voice","Dallo spioncino"},
    {"pc_archive_bag","La busta che parla"},
    {"pc_archive_fetus","Il feto parla {1}"},
    {"pc_archive_photo_lisa","Pezzo: Lisa"},
    {"pc_archive_photo_tree","Pezzo: l'albero"},
    {"pc_archive_photo_gap","Pezzo: la fessura"},
    {"pc_archive_photo_bath","Pezzo: il bagno"},
    {"pc_archive_photo_stair","Pezzo: le scale"},
    {"pc_archive_photo_option","Pezzo: la schermata delle opzioni"},
    {"pc_archive_photo_complete","La foto completa"},
    {"pc_archive_preface","La prefazione"},
    {"pc_archive_awakening","Il primo risveglio"},
    {"pc_archive_opening","Il risveglio"},
    {"pc_archive_first_exit","La prima porta"},
    {"pc_archive_door","Attraverso la porta"},
    {"pc_archive_clock","Mezzanotte"},
    {"pc_archive_kill","Presa da Lisa"},
    {"pc_archive_ending","Il finale"},
    {"pc_archive_teaser","Il teaser"},
    {"pc_archive_lisa_stand","Lisa, in piedi"},
    {"pc_archive_lisa_walk","Lisa, che cammina"},
    {"pc_archive_lisa_dash","Lisa, che si lancia"},
    {"pc_archive_lisa_door","Lisa dietro la porta"},
    {"pc_archive_baby","Il feto nel lavandino"},
    {"pc_archive_fridge","Il frigorifero"},
    {"pc_archive_bag_model","La busta di carta"},
    {"pc_archive_lamp","La lampada a soffitto"},
    {"pc_archive_roach","Scarafaggio"},
    {"pc_archive_flashlight","La torcia"},
    {"pc_archive_radio","La radio"},
    {"pc_archive_phone_model","Il telefono"},
    {"pc_archive_xmark_photo","La foto con la X"},
    {"pc_archive_clock_model","L'orologio"},
    {"pc_archive_man","L'uomo"},
    {"pc_archive_bathtub","Il corpo nella vasca"},
};
inline std::string_view Menu(std::string_view key) {
    for (const auto& e : kMenu) if (e.key == key) return e.text;
    return {};
}
}
