#pragma once
#include <string_view>

// Japanese for the port's own menus (PC settings, extras, photo mode, loop browser, notes and prompts) and the added
// languages' names on the option screen. The options screen's other texts and the subtitles are the game's own.
namespace pt::japanese {
struct Text { std::string_view key, text; };
inline constexpr Text kMenu[] = {
    {"pc_controller_speaker","コントローラーのスピーカー"},
    {"pc_note_controller_speaker","Lisaのゲーム内の叫び声を、対応するSonyコントローラーのスピーカーから再生します。WindowsではUSB接続が必要です。非対応機器やBluetoothでは音は出ません。ハプティクスとは独立しており、初期設定ではオフです。"},
    {"pc_controller_speaker_volume","コントローラーのスピーカー音量"},
    {"pc_note_controller_speaker_volume","コントローラーのスピーカー音量だけを5%刻みで調整します。ゲーム音声やDualSenseの振動強度は変わりません。Windowsで対応するSony製コントローラーをUSB接続した場合のみ使用できます。"},
    {"pc_microphone_trigger_assign","マイク用トリガーに {input} を割り当て"},
    {"pc_note_microphone_trigger","マイクの代わりに使う任意の入力です。ゲームが聞き取り中のときだけ、キーボードとコントローラーの左右のトリガーで有効になります。"},
    {"pc_note_microphone_test","マイクと音声認識の結果をテストします。"},
    {"pc_fps_limit","フレームレート上限"},
    {"pc_unlimited","上限なし"},
    {"pc_note_fps_limit","描画フレーム数を制限します。メニューは最大60 FPSです。垂直同期により、さらに低い上限になる場合があります。"},
    {"pc_hdr","ネイティブHDR"},
    {"pc_note_hdr_restart","次回起動時に適用されます。対応ディスプレイでHDRを有効にしてください。対応していない場合はSDRで表示します。"},
    {"pc_surround","サラウンド出力"},
    {"pc_note_surround","再起動後、出力機器の5.1または7.1チャンネルを使用します。ステレオ機器ではステレオのままです。"},
    {"pc_rumble_profile","振動モード"},
    {"pc_rumble_original","オリジナル"},
    {"pc_rumble_enhanced","強化"},
    {"pc_note_rumble_profile","オリジナルはゲーム本来のモーター振動のみを使います。強化では対応するトリガー振動と、Windowsで対応するUSB接続DualSenseでLisaのフィルター済みの叫び声から作ったハプティクスを追加します。振動の主設定をオフにすると両方とも無効になります。コントローラーのスピーカー音声は別設定です。"},
    {"pc_vr_height","高さ調整"},
    {"pc_note_vr_height","プレイヤーのゲーム内位置を変えずに、トラッキング中の視点を上下に移動します。"},
    {"pc_vr_world_scale","ワールドスケール"},
    {"pc_note_vr_world_scale","頭、目、コントローラーのトラッキング移動を50～200%に調整します。値が大きいほど世界が小さく感じられます。初期値は100%です。"},
    {"pc_photo_focal_length","焦点距離"},
    {"pc_note_photo_focal_length","レンズの焦点距離（mm）。フォーカスぼけにはカメラと同じレンズとセンサーを使います。"},
    {"pc_photo_aspect","アスペクト比"},
    {"pc_note_photo_aspect","写真の中央を切り抜きます。"},
    {"pc_photo_resolution","写真の解像度"},
    {"pc_note_photo_resolution","ネイティブはフレーム内のピクセルを保存します。4Kは長辺3840ピクセルでシーンを再描画します。"},
    {"pc_photo_resolution_native","ネイティブ"},
    {"pc_photo_resolution_4k","4K"},
    {"pc_photo_filter","カラーフィルター"},
    {"pc_note_photo_filter","写真モードの表示と保存する写真にのみ適用します。"},
    {"pc_photo_filter_bw","白黒"},
    {"pc_photo_filter_warm","あたたかい色"},
    {"pc_photo_filter_cool","寒色"},
    {"pc_photo_filter_muted","色ひかえめ"},
    {"pc_archive_model_hint","WASD / 左スティック：視点を移動。矢印キー / 右スティック：回転。トリガー：ズーム。Esc / 丸：戻る。"},
    {"pc_note_resolution_fullscreen","ボーダーレスは選択したサイズで描画します。排他フルスクリーンは対応する画面サイズを使います。"},
    {"op_sub_turkish","トルコ語"},
    {"op_sub_chinese","中国語（簡体字）"},
    {"op_sub_arabic","アラビア語"},
    {"op_sub_russian","ロシア語"},
    {"op_sub_ukrainian","ウクライナ語"},
    {"op_sub_czech","チェコ語"},
    {"op_sub_polish","ポーランド語"},
    {"pc_loop_browser","ループ選択"},
    {"pc_note_loop_browser_entry","セーブデータを上書きせずに、好きなループから始めます。"},
    {"pc_loop_choose","ループを選択"},
    {"pc_loop_preview","プレビュー"},
    {"pc_loop_start_hint","Enter / X / A：ループを開始"},
    {"pc_loop_f000","最初の部屋：オープニング"},
    {"pc_loop_f010","ループ1：ラジオ"},
    {"pc_loop_f005","ループ2：入口のドアが開く"},
    {"pc_loop_f020","ループ3：バスルームの泣き声"},
    {"pc_loop_f030","ループ4：バスルームのドア"},
    {"pc_loop_f040","ループ5：廊下の先のリサ"},
    {"pc_loop_f060","ループ6：バスルームと懐中電灯"},
    {"pc_loop_f050a","ループ7：ついてくるリサ"},
    {"pc_loop_f050b","ループ8：バツ印の写真"},
    {"pc_loop_f070","ループ9：割れる窓"},
    {"pc_loop_f080","ループ10：血を流す冷蔵庫"},
    {"pc_loop_f090","ループ11：HELLO"},
    {"pc_loop_f100","ループ12：赤い廊下"},
    {"pc_loop_f110","ループ13：迷路とのぞき穴"},
    {"pc_loop_f120","ループ14：204863、バグ画面"},
    {"pc_loop_f160","ループ15：最後のループ"},
    {"pc_loop_ending","エンディングムービーとクレジット"},
    {"pc_loop_street","街を歩く（エンディング後）"},
    {"pc_note_loop_opening","新しいゲームと同じく、最初の部屋でオープニングを始めます。 セーブデータはそのまま残ります。"},
    {"pc_note_loop_hallway","このループの直前の最初の部屋から、それまでの謎を解いた状態で始めます。 ドアを通ってください。 セーブデータはそのまま残り、次のチェックポイントからセーブが再開されます。"},
    {"pc_note_loop_ending","エンディングムービーとクレジットを再生し、そのあと街を歩くかどうかを選べます。 セーブデータはそのまま残ります。"},
    {"pc_note_loop_street","エンディングの街に一人称で立ちます。 エクストラから終了できます。 セーブデータはそのまま残ります。"},
    {"pc_note_loop_locked","ロック中です。 一度クリアすると、プレイで到達したループがすべて開きます。"},
    {"pc_note_loop_browser_locked","一度クリアするとループ選択が使えるようになります。"},
    {"pc_street_title","街"},
    {"pc_street_question","街を探索しますか？"},
    {"pc_street_walk","はい、街を歩く"},
    {"pc_credit_version","P.T. PC Port {1} 制作：LoreanXavier"},
    {"pc_update_available","バージョン {1} があります (現在は {2})"},
    {"pc_credits_by","制作：LoreanXavier"},
    {"pc_credits_dlss","このゲームはNVIDIA DLSSを使用しています。"},
    {"pc_credits_licenses","ライセンスの全文は、pt.exeと同じ場所にあるlicensesフォルダにあります。"},
    {"pc_credits_konami","P.T.はKonami Digital EntertainmentとKojima Productionsの作品です。"},
    {"pc_credits_fan","この移植版は非公式のファンプロジェクトであり、Konami、NVIDIA、AMD、Intelとは関係がなく、承認も受けていません。"},
    {"pc_note_street_walk","エンディングの街を一人称で歩きます。 エクストラから終了できます。"},
    {"pc_street_restart","いいえ、最初に戻る"},
    {"pc_note_street_restart","オリジナルのクレジット後と同じく、最初の部屋からやり直します。"},
    {"pc_street_leave","街を出る"},
    {"pc_note_street_leave","街の散策を終えて最初の部屋に戻ります。"},
    {"pc_street_return","家に戻る"},
    {"pc_street_return_confirm","家に戻りますか？"},
    {"pc_loop_lock","ループ選択をロック"},
    {"pc_note_loop_lock","初めてクリアする前と同じく、ループ選択のすべての項目を再びロックします。 セーブデータは変わりません。"},
    {"pc_extras","エクストラ"},
    {"pc_vr","VR（実験的）"},
    {"pc_note_vr","OpenXR で VR ヘッドセットを使って遊びます。実験的機能：実機では未検証です。"},
    {"pc_vr_mode","VR モード"},
    {"pc_note_vr_mode","実機では未検証です。OpenXR ランタイムとヘッドセットが必要です。次回の起動から有効になり、ヘッドセットがない場合は通常どおり起動します。"},
    {"pc_vr_flashlight","懐中電灯"},
    {"pc_note_vr_flashlight","懐中電灯はオリジナルと同じく頭の向き、または手に持ったコントローラーに従います。"},
    {"pc_vr_head","頭"},
    {"pc_vr_controller","コントローラー"},
    {"pc_vr_turn","回転"},
    {"pc_note_vr_turn","右スティックで段階的またはなめらかに回転します。段階的なほうが酔いにくくなります。"},
    {"pc_vr_snap","段階的"},
    {"pc_vr_smooth","なめらか"},
    {"pc_note_extras","ループ選択、フリーカメラ、フォトモード。"},
    {"pc_freecam","フリーカメラ"},
    {"pc_note_freecam","カメラをプレイヤーから離して自由に動かします（F6）。 Space / Ctrl またはトリガーで上下、Shift または L3 で高速。 Esc で終了。"},
    {"pc_photo_mode","フォトモード"},
    {"pc_note_photo_mode","ゲームを一時停止し、フリーカメラで構図を決めます（F7）。 P または四角ボタンで Pictures/PT Photos に保存、H または三角ボタンでパネルを非表示。"},
    {"pc_speedrun","スピードランタイマー"},
    {"pc_note_speedrun","画面にタイマーを表示し、ループごとに区間を記録して、クレジットの後に結果を表示します。実時間はすべてを数え、ゲーム時間はポーズとロードを除きます。オリジナルにはありません。"},
    {"pc_speedrun_real_time","実時間"},
    {"pc_speedrun_game_time","ゲーム時間"},
    {"pc_livesplit","LiveSplitサーバー"},
    {"pc_note_livesplit","タイマーの開始、区間、ゲーム時間をLiveSplitに送ります（Control > Start TCP Server、ポート{1}）。ホストとポートはpt.iniにあります。"},
    {"pc_speedrun_results","クリア"},
    {"pc_speedrun_run","記録"},
    {"pc_speedrun_splits","区間"},
    {"pc_speedrun_menu","メニューに戻る"},
    {"pc_note_speedrun_menu","エンディングの後のオリジナルと同じく最初からやり直し、まずオプション画面を表示します。次の記録は操作できるようになった時に始まります。"},
    {"pc_speedrun_outside","外を探索"},
    {"pc_note_speedrun_outside","エンディングの街を歩きます。ポーズメニューから家に戻れます。"},
    {"pc_note_speedrun_real","操作できるようになってからエンディングまでの実際の時間です。ポーズ、ロード、ムービーを含みます。"},
    {"pc_note_speedrun_game","ポーズしていないプレイだけです。ポーズメニューとゲームオーバー後のロードは除きます。"},
    {"pc_speedrun_best","自己ベスト"},
    {"pc_note_speedrun_best","前回のベスト：{1}。記録はユーザーフォルダのspeedrun.ini、speedrun_history.txt、speedrun_pb.lss（LiveSplit）にあります。"},
    {"pc_speedrun_new_best","自己ベスト更新！"},
    {"pc_speedrun_partial","最初からではありません"},
    {"pc_speedrun_start_room","最初の部屋"},
    {"pc_speedrun_loop","ループ{1}"},
    {"pc_third_person","三人称視点（実験的）"},
    {"pc_note_third_person","実験的な機能で、オリジナルにはありません。カメラが肩越しにプレイヤーを追います。ズームとムービーでは一人称に戻り、イベントは一人称と同じように起こります。"},
    {"pc_extras_start","開始"},
    {"pc_photo_title","フォトモード"},
    {"pc_photo_section_camera","カメラ"},
    {"pc_photo_section_lens","レンズ"},
    {"pc_photo_section_image","画像"},
    {"pc_photo_take","写真を撮る"},
    {"pc_photo_capture","撮影"},
    {"pc_photo_fov","視野角"},
    {"pc_photo_roll","カメラの回転"},
    {"pc_photo_speed","カメラの速度"},
    {"pc_photo_speed_slow","遅い"},
    {"pc_photo_speed_normal","標準"},
    {"pc_photo_speed_fast","速い"},
    {"pc_photo_reset","カメラをリセット"},
    {"pc_photo_focus","ピント位置"},
    {"pc_photo_aperture","絞り"},
    {"pc_photo_exposure","露出"},
    {"pc_photo_grading","カラーグレーディング"},
    {"pc_photo_letterbox","シネマバー"},
    {"pc_photo_body","プレイヤーの体"},
    {"pc_photo_flashlight","懐中電灯"},
    {"pc_photo_shown","表示"},
    {"pc_photo_hidden","非表示"},
    {"pc_photo_auto","オート"},
    {"pc_photo_metres","{value} m"},
    {"pc_photo_saved","Pictures/PT Photos に保存しました：{file}"},
    {"pc_photo_save_failed","写真を保存できませんでした。pt.log を確認してください。"},
    {"pc_photo_hint","矢印/方向キー：選択と変更 P/四角：撮影 H/三角：パネルを非表示 右クリック：見回す Esc/丸：終了"},
    {"pc_note_photo_take","現在の画面を Pictures/PT Photos に保存します。 パネルは写真に写りません。"},
    {"pc_note_photo_fov","縦方向の視野角（度）。 値を小さくするとズームします。"},
    {"pc_note_photo_roll","カメラを横に傾けて、斜めの構図にします。"},
    {"pc_note_photo_speed","カメラの移動速度です。 Shift または L3 でさらに速くなります。"},
    {"pc_note_photo_reset","フォトモードを始めた位置にカメラを戻します。"},
    {"pc_note_photo_dof","ピント位置より近いものと遠いものをぼかします。"},
    {"pc_note_photo_focus","オートでは画面中央のものにピントを合わせます。"},
    {"pc_note_photo_aperture","F値が小さいほど強くぼけます。 オートではゲーム本来のレンズのままです。"},
    {"pc_note_photo_exposure","画像を1/2段ずつ明るく、または暗くします。"},
    {"pc_note_photo_grain","オリジナルのフィルムグレインです。 オフにすると画像がすっきりします。"},
    {"pc_note_photo_grading","オリジナルの色調です。 オフにすると色味がニュートラルになります。"},
    {"pc_note_photo_letterbox","映画のような黒い帯です。 写真にも写ります。"},
    {"pc_note_photo_body","プレイヤーの体を表示または非表示にします。"},
    {"pc_note_photo_flashlight","フォトモード中は懐中電灯の光を消します。"},
    {"pc_extras_stop","停止"},
    {"pc_note_loop_generating","プレビューを作成しています… セーブデータはそのまま残ります。 次のチェックポイント（地下室を出るか、最後のループに着いたとき）からセーブが再開されます。"},
    {"pc_title","PC設定"},
    {"pc_entry","PC設定"},
    {"pc_back","戻る"},
    {"pc_quit","終了"},
    {"pc_nav_columns","Tab / L1 / R1：列を切り替え"},
    {"pc_quit_confirm","終了しますか？"},
    {"pc_save_no_space","ゲームを保存する空き容量がありません。\n空き容量を確保してから、このメッセージを閉じて再試行してください。"},
    {"pc_ok","OK"},
    {"pc_note_quit","ゲームを終了します。"},
    {"pc_note_quit_confirm","もう一度 {accept} を押すと終了します。 戻るでキャンセル。"},
    {"pc_section_display","ディスプレイ"},
    {"pc_section_upscaling","アップスケーリング"},
    {"pc_section_sound","サウンド"},
    {"pc_section_controls","操作"},
    {"pc_section_progress","進行状況"},
    {"pc_section_ray_tracing","レイトレーシング"},
    {"pc_section_textures","テクスチャ"},
    {"pc_display_mode","表示モード"},
    {"pc_resolution","解像度"},
    {"pc_vsync","垂直同期"},
    {"pc_focus_pause","非アクティブ時に一時停止"},
    {"pc_focus_mute","非アクティブ時に消音"},
    {"pc_upscaler","方式"},
    {"pc_quality","モード"},
    {"pc_sharpness","シャープネス"},
    {"pc_frame_generation","フレーム生成"},
    {"pc_volume","音量"},
    {"pc_microphone","マイク"},
    {"pc_microphone_test","マイクテスト"},
    {"pc_mic_level","入力レベル"},
    {"pc_mic_heard","認識した単語"},
    {"pc_mic_monitor","自分の声を聞く"},
    {"pc_mic_no_word","まだありません"},
    {"pc_mic_waiting","選択したマイクを待っています…"},
    {"pc_mic_unavailable","選択したマイクを開けませんでした。 録音の許可と選択したデバイスを確認してください。"},
    {"pc_mic_st_loading","読み込み中…"},
    {"pc_mic_st_nomic","マイクなし"},
    {"pc_mic_st_files","音声ファイルなし"},
    {"pc_mic_st_runtime","音声エンジン失敗"},
    {"pc_mic_st_cpu","CPU非対応"},
    {"pc_mic_st_model","音声モデル失敗"},
    {"pc_mic_st_silent","音なし"},
    {"pc_mic_err_files","音声認識のファイルが見つかりません。 ゲームを再インストールするか修復してください。"},
    {"pc_mic_err_runtime","音声エンジンを読み込めませんでした。 原因は pt.log を確認してください。"},
    {"pc_mic_err_cpu","このプロセッサでは音声エンジンを実行できません。"},
    {"pc_mic_err_model","音声モデルを読み込めませんでした。 原因は pt.log を確認してください。"},
    {"pc_mic_err_silent","マイクは開いていますが音が届いていません。 ミュートされていないか、正しいデバイスが選ばれているか確認してください。"},
    {"pc_mic_say_jack","選択したマイクに「Jack」と話してください。 このテストでは謎は進みません。"},
    {"pc_mic_monitor_note","マイクの音を聞きます。 ハウリングを防ぐためにヘッドホンを使ってください。 テストを出ると止まります。"},
    {"pc_mouse","マウス感度"},
    {"pc_gamepad_sensitivity","ゲームパッドの視点感度"},
    {"pc_camera_tilt","カメラの傾き"},
    {"pc_vibration","振動"},
    {"pc_dead_zone","デッドゾーン"},
    {"pc_reset","進行状況をリセット"},
    {"pc_graphics","グラフィック"},
    {"pc_graphics_value","開く"},
    {"pc_rt_shadows","レイトレーシングの影"},
    {"pc_rt_contact","コンタクトシャドウ"},
    {"pc_shadows","影"},
    {"pc_reflections","反射"},
    {"pc_standard","標準"},
    {"pc_ray_traced","レイトレーシング"},
    {"pc_rt_sharp_long","レイトレーシング（シャープ）"},
    {"pc_rt_soft_long","レイトレーシング（ソフト）"},
    {"pc_note_shadows","低からオリジナルまではオリジナルのシャドウマップ（512、1024、2048 px）です。 レイトレーシングはこれに代わり、オリジナルと同じくシャープな影か、光源の大きさに応じたソフトな影を作ります。"},
    {"pc_note_ao","標準はオリジナルのスクリーンスペースの陰影です。 レイトレーシングはシーンそのものから角や物の下を暗くします。 オリジナルにはありません。"},
    {"pc_note_reflections","標準はオリジナルのスクリーンスペースの床の反射です。 レイトレーシングは画面の外のものも映します。 試験的な機能です。"},
    {"pc_rt_ao","アンビエントオクルージョン"},
    {"pc_anisotropy","異方性フィルタリング"},
    {"pc_enhanced_textures","高精細テクスチャ"},
    {"pc_texture_preparing","準備中"},
    {"pc_note_texture_tools_missing","高精細テクスチャのツールまたはモデルファイルがありません。 ポータブル版から texture-tools を戻して、もう一度お試しください。 元のテクスチャはそのままです。"},
    {"pc_note_texture_busy","別のゲームがこのテクスチャキャッシュを準備しています。 終わるのを待って、もう一度お試しください。 元のテクスチャはそのままです。"},
    {"pc_note_texture_failed","テクスチャの準備に失敗しました。 元のテクスチャはそのままです。 ディスクの空き容量と pt.log を確認して、もう一度お試しください。"},
    {"pc_note_texture_preparing","高精細テクスチャを準備しています。 完了までは元のテクスチャを表示し、完了すると再起動なしで切り替わります。 オフで中止します。"},
    {"pc_note_enhanced_textures","ゲームのファイルから、より精細なカラーテクスチャを一度だけ作成します。壁や人物も含みます。ビデオメモリ10 GB以上で4096ピクセル、それ以外は2048。オフで中止します。 元のテクスチャも使えます。"},
    {"pc_rt_sharp","シャープ"},
    {"pc_rt_soft","ソフト"},
    {"pc_on","オン"},
    {"pc_off","オフ"},
    {"pc_window","ウィンドウ"},
    {"pc_borderless","ボーダーレス"},
    {"pc_fullscreen","フルスクリーン"},
    {"pc_native","ネイティブ"},
    {"pc_quality_quality","クオリティ"},
    {"pc_quality_balanced","バランス"},
    {"pc_quality_performance","パフォーマンス"},
    {"pc_quality_ultra","ウルトラパフォーマンス"},
    {"pc_quality_custom","カスタム"},
    {"pc_system_default","システムの既定"},
    {"pc_reset_value","リセット"},
    {"pc_reset_confirm","決定"},
    {"pc_reset_done","完了"},
    {"pc_note_vsync","すぐに反映されます。 画面の表示をモニターのリフレッシュレートに合わせます。"},
    {"pc_note_vsync_off","すぐに適用されます。オフでは各フレームを完成しだい表示します。フレームレートはリフレッシュレートに制限されず、画面が裂けることがあります。"},
    {"pc_note_restart","次回の起動時に反映されます。"},
    {"pc_note_display_mode","Alt+Enter でもウィンドウとフルスクリーンを切り替えられます。"},
    {"pc_note_resolution","ウィンドウのサイズです。"},
    {"pc_note_resolution_fullscreen","フルスクリーンではデスクトップの解像度を使います。"},
    {"pc_note_upscaler_off","オフではオリジナルと同じく画面の解像度で描画します。"},
    {"pc_note_render_size","描画 {1}、表示 {2}。"},
    {"pc_note_needs_upscaler","アップスケーリングの方式が必要です。"},
    {"pc_note_sharpness_fsr","独自のシャープネスがあるのは FSR だけです。 グラフィックの「クラリティ」はどの方式でも使えます。"},
    {"pc_note_reset","進行状況をリセットし、すぐにゲームを最初から始めます。 言語とPC設定はそのままです。"},
    {"pc_note_reset_confirm","もう一度 {accept} を押すとセーブデータを削除します。"},
    {"pc_note_reset_done","このセッションで進行状況をリセットしました。"},
    {"pc_note_camera_tilt","オリジナルと同じく、カメラが頭の動きに合わせて傾きます。"},
    {"pc_note_voice","マイクはオリジナルのゲームが声を聞く場面でのみ使われます。"},
    {"pc_note_focus_pause","ウィンドウが非アクティブになると、このメニューを開きます。"},
    {"pc_note_focus_mute","ウィンドウが非アクティブの間、ゲームの音を消します。"},
    {"pc_note_frame_generation_missing","このビルドにはありません。"},
    {"pc_note_frame_generation","AMD FSR 3 が描画した2つのフレームの間に生成したフレームを表示します。"},
    {"pc_note_fsr4_vulkan","AMD は FSR 4 を DirectX 12 向けにのみ提供しています。このゲームは Vulkan で描画するため、FSR 4 は使えません。"},
    {"pc_dlss_model","DLSS モデル"},
    {"pc_dlss_model_auto","自動"},
    {"pc_note_dlss_model","自動は NVIDIA の選択です。バランスまでは K、パフォーマンスは M、ウルトラパフォーマンスは L。L と M は RTX 20/30 では約2倍の負荷がかかります。"},
    {"pc_note_frame_generation_dlss","実験的機能。NVIDIA DLSS フレーム生成が描画した2つのフレームの間に生成したフレームを表示します。次回の起動から有効になります。"},
    {"pc_note_dlssg_gpu","DLSS フレーム生成には NVIDIA GeForce RTX 40 シリーズ以降の GPU が必要です。"},
    {"pc_note_fsr_fg_gpu","FSR 3 フレーム生成には AMD Radeon RX 5000 シリーズ以降の GPU が必要です。"},
    {"pc_note_dlssg_driver","DLSS フレーム生成には新しい NVIDIA ドライバーが必要です。"},
    {"pc_note_dlssg_hags","DLSS フレーム生成にはハードウェア アクセラレータによる GPU スケジューリング（Windows のグラフィックの設定）が必要です。"},
    {"pc_note_dlssg_missing","このビルドには DLSS フレーム生成が含まれていません。"},
    {"pc_note_dlssg_failed","DLSS フレーム生成を開始できなかったため、オフにしました。"},
    {"pc_note_dlssg_restart","DLSS フレーム生成を開始するにはゲームを再起動してください。"},
    {"pc_note_vsync_dlssg","Vulkan では DLSS フレーム生成は垂直同期なしで動作します。フレーム生成をオフにすると設定が再び適用されます。"},
    {"pc_note_fsr_fg_restart","DLSS フレーム生成から FSR 3 に切り替えるにはゲームを再起動してください。"},
    {"pc_note_dead_zone","0.10 は DualShock 4 本来の値です。"},
    {"pc_note_gamepad_sensitivity","元のスティック応答の後に旋回速度を調整します。1 は元の速度です。"},
    {"pc_note_rt_shadows","シャドウマップの代わりにレイトレーシングで影を作ります。 シャープさはオリジナルと同じです。 オリジナルにはありません。"},
    {"pc_note_rt_soft","光源の大きさに応じて縁がやわらかくなるレイトレーシングの影です。 オリジナルにはありません。"},
    {"pc_note_rt_unsupported","Vulkan のレイトレーシングに対応した GPU が必要です。"},
    {"pc_note_graphics","プリセットを選ぶか、ライティング、テクスチャ、画像効果を細かく調整します。 解像度とアップスケーリングは別に設定します。"},
    {"pc_note_rt_contact","すべての光源から、物が短いレイトレーシングの影を落とします。 オリジナルで影のない光源も含みます。"},
    {"pc_note_rt_ao","レイトレーシングの陰影で、角や物の下と後ろを暗くします。 オリジナルにはありません。"},
    {"pc_rt_reflections","反射"},
    {"pc_note_rt_reflections","床が画面の外のシーンも映します。 試験的な機能で、見た目がオリジナルと異なる場合があります。"},
    {"pc_note_anisotropy","斜めから見た床や壁がくっきりします。 オフはオリジナルのフィルタリングです。"},
    {"pc_graphics_quality","品質"},
    {"pc_graphics_preset","プリセット"},
    {"pc_preset_low","低"},
    {"pc_preset_medium","中"},
    {"pc_preset_original","オリジナル（PS4）"},
    {"pc_preset_high","高"},
    {"pc_preset_ultra","最高"},
    {"pc_preset_custom","カスタム"},
    {"pc_ray_tracing","レイトレーシング"},
    {"pc_clarity","クラリティ"},
    {"pc_graphics_advanced","詳細設定"},
    {"pc_graphics_lighting","ライティング"},
    {"pc_graphics_effects","画像効果"},
    {"pc_graphics_image","画像"},
    {"pc_lighting_standard","標準ライティング"},
    {"pc_shadow_quality","シャドウマップ"},
    {"pc_standard_ao","アンビエントオクルージョン"},
    {"pc_standard_reflections","スクリーンスペース反射"},
    {"pc_ray_quality","レイの品質"},
    {"pc_ray_balanced","バランス"},
    {"pc_texture_detail","テクスチャの精細さ"},
    {"pc_detail_reduced","低"},
    {"pc_detail_fine","高精細"},
    {"pc_dof","被写界深度"},
    {"pc_motion_blur","モーションブラー"},
    {"pc_bloom","ブルーム"},
    {"pc_lens_ghosts","レンズフレアのゴースト"},
    {"pc_note_lens_ghosts","ランプの近くを見たときに画面全体へ広がる大きなレンズフレアの反射です。オリジナル（PS4）と同じです。オフにすると消えます。"},
    {"pc_film_grain","フィルムグレイン"},
    {"pc_note_preset","グラフィックだけを変更し、解像度とアップスケーリングはそのままです。 手動で変えるとカスタムになります。 最高は対応していればレイトレーシングを使います。"},
    {"pc_note_ray_master","レイトレーシングの影、コンタクトシャドウ、アンビエントオクルージョン、反射をまとめてオン／オフします。 個別の設定はライティングにあります。"},
    {"pc_lens_distortion","レンズ効果"},
    {"pc_note_lens_distortion","オリジナルのレンズのゆがみと色のにじみです。 オフにすると縁がくっきりし、画面が広く見えます。"},
    {"pc_note_clarity","出力解像度で局所コントラストを控えめに強調します。 0 ではオリジナルの画像のままです。"},
    {"pc_note_letterbox","プレイ中とムービーで画面の上下に黒い帯を表示します。 字幕は画面の中に収まります。 オリジナルにはありません。"},
    {"pc_note_advanced","この項目を細かく調整します。 戻るでグラフィックに戻ります。 変更するとカスタムになります。"},
    {"pc_note_shadow_quality","512、1024、またはオリジナルの 2048 px のシャドウマップです。 レイトレーシングの影がオンならこれに代わります。 解像度スケールは変わりません。"},
    {"pc_note_standard_ao","オリジナルのスクリーンスペースのアンビエントオクルージョンです。 性能の低い GPU ではオフにすると負荷が下がります。"},
    {"pc_note_standard_reflections","オリジナルのスクリーンスペースの床の反射です。 レイトレーシングの反射がオンならこれに代わります。"},
    {"pc_note_ray_quality","バランス：2本。 高：4本。 最高：8本で、影がよりソフトになり、レイトレーシングの陰影のノイズが減ります。"},
    {"pc_note_texture_detail","低は低解像度のミップを使います。 高精細は遠くの細部を多く残しますが、ちらつく場合があります。 出力解像度は変わりません。"},
    {"pc_note_dof","オリジナルのピントのぼけです。 オフにすると近くの面も背景もくっきりします。"},
    {"pc_note_motion_blur","オリジナルの振り向きや移動のぶれです。 オフにすると動きがくっきり見えます。"},
    {"pc_note_bloom","オリジナルの光のにじみです。 オフにすると光が抑えられ、ポストプロセスの負荷も下がります。"},
    {"pc_note_film_grain","オリジナルのフィルムグレインの強さです。 オフで画像がすっきりし、100% でオリジナルの効果になります。"},
    {"pc_mods","MOD"},
    {"pc_section_mods","インストール済みのMOD"},
    {"pc_note_mods","MODのオン／オフは次回の起動時に反映されます。 MODはオリジナルのゲームには含まれません。"},
    {"pc_archive","ミュージアム"},
    {"pc_note_archive","ゲーム内の画像、声、写真の切れ端、ムービー、モデルを、プレイで到達した順に見られます。 ゲームの進行は変わりません。"},
    {"pc_note_extras_archive","ループ選択、ミュージアム、フリーカメラ、フォトモード。"},
    {"pc_archive_sections","展示室"},
    {"pc_archive_images","サブリミナル画像"},
    {"pc_archive_voices","声とラジオ"},
    {"pc_archive_photos","写真の切れ端"},
    {"pc_archive_cutscenes","ムービー"},
    {"pc_archive_models","モデル"},
    {"pc_archive_unused","未使用データ"},
    {"pc_note_archive_images","サブリミナルのフラッシュの文字、フラッシュのノイズ、のぞき穴の視界。"},
    {"pc_note_archive_voices","ラジオ放送とすべてのセリフを、字幕の言語の文字起こしと共に聞けます。"},
    {"pc_note_archive_photos","破れた写真の切れ端と、額の中でそれらが作る写真。"},
    {"pc_note_archive_cutscenes","すべてのムービーを最初から、音と字幕付きで再生します。"},
    {"pc_note_archive_models","リサと廊下のほかの姿や物を、最初の部屋の明かりで見られます。"},
    {"pc_note_archive_unused_section","ゲームのファイルにあるが、ゲームでは見られないデータ。 一度クリアすると開きます。"},
    {"pc_note_archive_image","Enter / バツ：全画面で見る"},
    {"pc_note_archive_voice","Enter / バツ：再生または停止"},
    {"pc_note_archive_photo","Enter / バツ：全画面で見る"},
    {"pc_note_archive_demo","Enter / バツ：最初から再生。 Esc / 丸で停止。"},
    {"pc_note_archive_model","Enter / バツ：モデルを見る。 Esc / 丸で戻る。"},
    {"pc_note_archive_unused","ゲームでは見られません。 Enter / バツ：モデルを見る。"},
    {"pc_note_archive_locked","ロック中です。 プレイで到達すると開きます。"},
    {"pc_note_archive_playing","再生中。 Enter / バツで停止。"},
    {"pc_archive_lock","ミュージアムをロック"},
    {"pc_note_archive_lock","ミュージアムの展示をすべて、プレイ前のように再びロックします。 セーブデータは変わりません。"},
    {"pc_archive_hint","Enter / X / A：開く"},
    {"pc_archive_view_hint","左 / 右：前 / 次  Esc / 丸：戻る"},
    {"pc_archive_demo_hint","Esc / 丸 / Enter / バツ：停止"},
    {"pc_archive_model_hint","矢印 / スティック：回す  W / S / トリガー：近く / 遠く  Esc / 丸：戻る"},
    {"pc_archive_sub","サブリミナル文字 {1}"},
    {"pc_archive_noise","ノイズ"},
    {"pc_archive_noise_normal","ノイズのゆがみ"},
    {"pc_archive_peephole_mask","のぞき穴の視界"},
    {"pc_archive_radio_news","ラジオ：ニュース放送"},
    {"pc_archive_radio_news2","ラジオ：もう一度の放送"},
    {"pc_archive_radio_voice","ラジオの声 {1}"},
    {"pc_archive_riddle","ラジオのなぞなぞ {1}"},
    {"pc_archive_sermon","ラジオ：説教"},
    {"pc_archive_phone","電話"},
    {"pc_archive_peephole_voice","のぞき穴から"},
    {"pc_archive_bag","しゃべる袋"},
    {"pc_archive_fetus","赤ちゃんの声 {1}"},
    {"pc_archive_photo_lisa","切れ端：リサ"},
    {"pc_archive_photo_tree","切れ端：木"},
    {"pc_archive_photo_gap","切れ端：すき間"},
    {"pc_archive_photo_bath","切れ端：浴室"},
    {"pc_archive_photo_stair","切れ端：階段"},
    {"pc_archive_photo_option","切れ端：オプション画面"},
    {"pc_archive_photo_complete","完成した写真"},
    {"pc_archive_preface","序文"},
    {"pc_archive_awakening","最初の目覚め"},
    {"pc_archive_opening","目覚め"},
    {"pc_archive_first_exit","最初のドア"},
    {"pc_archive_door","ドアの向こうへ"},
    {"pc_archive_clock","午前0時"},
    {"pc_archive_kill","リサに捕まる"},
    {"pc_archive_ending","エンディング"},
    {"pc_archive_teaser","ティザー"},
    {"pc_archive_lisa_stand","リサ（立つ）"},
    {"pc_archive_lisa_walk","リサ（歩く）"},
    {"pc_archive_lisa_dash","リサ（迫る）"},
    {"pc_archive_lisa_door","ドアの裏のリサ"},
    {"pc_archive_baby","洗面台の赤ちゃん"},
    {"pc_archive_fridge","冷蔵庫"},
    {"pc_archive_bag_model","紙袋"},
    {"pc_archive_lamp","天井の照明"},
    {"pc_archive_roach","ゴキブリ"},
    {"pc_archive_flashlight","懐中電灯"},
    {"pc_archive_radio","ラジオ"},
    {"pc_archive_phone_model","電話機"},
    {"pc_archive_xmark_photo","バツ印の写真"},
    {"pc_archive_clock_model","時計"},
    {"pc_archive_man","男"},
    {"pc_archive_bathtub","バスタブの死体"},
};
inline std::string_view Menu(std::string_view key) {
    for (const auto& e : kMenu) if (e.key == key) return e.text;
    return {};
}
}
