#pragma once
#include <cstdint>
#include <initializer_list>
#include <string_view>

namespace pt::polish {
struct Text { std::string_view key, text; };
inline constexpr Text kMenu[] = {
    {"pc_controller_speaker","Głośnik kontrolera"},
    {"pc_note_controller_speaker","Odtwarza nagrane krzyki Lisy przez głośniki obsługiwanych kontrolerów Sony. W systemie Windows wymaga połączenia USB; nieobsługiwane urządzenia i Bluetooth pozostają wyciszone. Działa niezależnie od wibracji i jest domyślnie wyłączone."},
    {"pc_controller_speaker_volume","Głośność głośnika kontrolera"},
    {"pc_note_controller_speaker_volume","Zmienia wyłącznie głośność głośnika kontrolera. Nie wpływa na dźwięk gry ani siłę wibracji. Dostępne dla obsługiwanych przewodowych kontrolerów Sony w systemie Windows."},
    {"pc_microphone_trigger_assign","Przypisz {input} do włączania mikrofonu."},
    {"pc_note_microphone_trigger","Opcjonalny sposób włączania mikrofonu. Klawiatura i oba spusty kontrolera działają tylko wtedy, gdy gra nasłuchuje."},
    {"pc_note_microphone_test","Sprawdza działanie mikrofonu i rozpoznawanie mowy."},
    {"pc_fps_limit","Limit klatek na sekundę"},
    {"pc_unlimited","Bez limitu"},
    {"pc_note_fps_limit","Ogranicza liczbę renderowanych klatek na sekundę. W menu zawsze obowiązuje limit 60 FPS. Synchronizacja pionowa może narzucić niższy limit."},
    {"pc_hdr","Natywny HDR"},
    {"pc_note_hdr_restart","Zostanie zastosowane po ponownym uruchomieniu. Wymaga włączonej obsługi HDR na zgodnym ekranie; w przeciwnym razie używany jest SDR."},
    {"pc_surround","Dźwięk przestrzenny"},
    {"pc_note_surround","Po ponownym uruchomieniu korzysta z układu 5.1 lub 7.1 urządzenia wyjściowego. Urządzenia stereo nadal odtwarzają dźwięk dwukanałowy."},
    {"pc_rumble_profile","Tryb wibracji"},
    {"pc_rumble_original","Oryginalny"},
    {"pc_rumble_enhanced","Ulepszony"},
    {"pc_note_rumble_profile","Oryginalny zachowuje standardowe wibracje z gry. Ulepszony dodaje wibracje spustów oraz – na obsługiwanych kontrolerach DualSense podłączonych przez USB w systemie Windows – wibracje haptyczne generowane z przetworzonych krzyków Lisy. Główne ustawienie wibracji wyłącza oba efekty; dźwięk głośnika kontrolera działa niezależnie."},
    {"pc_vr_height","Regulacja wysokości"},
    {"pc_note_vr_height","Przesuwa śledzony punkt widzenia w pionie bez zmiany pozycji gracza w świecie gry."},
    {"pc_vr_world_scale","Skala świata"},
    {"pc_note_vr_world_scale","Skaluje śledzony ruch głowy, oczu i kontrolerów w zakresie od 50% do 200%. Wyższe wartości sprawiają, że otoczenie wydaje się mniejsze. Domyślnie: 100%."},
    {"pc_photo_focal_length","Ogniskowa"},
    {"pc_note_photo_focal_length","Ogniskowa obiektywu w milimetrach. Rozmycie ostrości korzysta z parametrów obiektywu i matrycy wirtualnej kamery."},
    {"pc_photo_aspect","Proporcje obrazu"},
    {"pc_note_photo_aspect","Przycina kadr względem środka obrazu."},
    {"pc_photo_resolution","Rozdzielczość zdjęcia"},
    {"pc_note_photo_resolution","Natywna zapisuje kadr w aktualnej rozdzielczości gry. 4K renderuje scenę ponownie z dłuższą krawędzią o długości 3840 pikseli."},
    {"pc_photo_resolution_native","Natywna"},
    {"pc_photo_resolution_4k","4K"},
    {"pc_photo_filter","Filtr kolorów"},
    {"pc_note_photo_filter","Stosowany wyłącznie w podglądzie kadru oraz na zapisanym zdjęciu."},
    {"pc_photo_filter_bw","Czarno-biały"},
    {"pc_photo_filter_warm","Ciepły"},
    {"pc_photo_filter_cool","Chłodny"},
    {"pc_photo_filter_muted","Stonowany"},
    {"pc_photo_save_failed","Nie udało się zapisać zdjęcia. Szczegóły znajdziesz w pliku pt.log."},
    {"pc_mic_st_loading","Wczytywanie..."},
    {"pc_mic_st_nomic","Brak mikrofonu"},
    {"pc_mic_st_files","Brak plików rozpoznawania mowy"},
    {"pc_mic_st_runtime","Błąd silnika rozpoznawania mowy"},
    {"pc_mic_st_cpu","Nieobsługiwany procesor"},
    {"pc_mic_st_model","Błąd modelu rozpoznawania mowy"},
    {"pc_mic_st_silent","Brak sygnału audio"},
    {"pc_mic_err_files","Brakuje plików rozpoznawania mowy. Zainstaluj grę ponownie lub zweryfikuj spójność plików."},
    {"pc_mic_err_runtime","Nie udało się zainicjować silnika rozpoznawania mowy. Szczegóły znajdziesz w pliku pt.log."},
    {"pc_mic_err_cpu","Ten procesor nie spełnia wymagań silnika rozpoznawania mowy."},
    {"pc_mic_err_model","Nie udało się wczytać modelu rozpoznawania mowy. Szczegóły znajdziesz w pliku pt.log."},
    {"pc_mic_err_silent","Mikrofon jest aktywny, ale nie rejestruje dźwięku. Upewnij się, że urządzenie nie jest wyciszone i wybrano właściwe źródło w systemie."},
    {"pc_gamepad_sensitivity","Czułość rozglądania (kontroler)"},
    {"pc_note_gamepad_sensitivity","Mnożnik prędkości obrotu kamery po zastosowaniu domyślnej charakterystyki gałki. Wartość 1.0 pozostawia oryginalną czułość."},
    {"op_options","OPCJE"},
    {"op_back","Wstecz"},
    {"op_brightness_setting","Jasność"},
    {"op_britness_tip","Dostosuj jasność tak, aby widoczny był wyłącznie obraz po lewej stronie."},
    {"op_subtitles_setting","Napisy"},
    {"op_sub_none","Wył."},
    {"op_sub_english","Angielski"},
    {"op_sub_french","Francuski"},
    {"op_sub_german","Niemiecki"},
    {"op_sub_spanish","Hiszpański"},
    {"op_sub_japanese","Japoński"},
    {"op_sub_itlian","Włoski"},
    {"op_sub_portuguese","Portugalski"},
    {"op_sub_turkish","Turecki"},
    {"op_sub_chinese","Chiński (uproszczony)"},
    {"op_sub_arabic","Arabski"},
    {"op_sub_russian","Rosyjski"},
    {"op_sub_ukrainian","Ukraiński"},
    {"op_sub_czech","Czeski"},
    {"op_sub_polish","Polski"},
    {"op_camera_setting","Kamera"},
    {"op_camera_y_axis","Oś pionowa"},
    {"op_camera_x_axis","Oś pozioma"},
    {"op_camera_normal","Normalna"},
    {"op_camera_reversed","Odwrócona"},
    {"pc_loop_browser","Wybór pętli"},
    {"pc_note_loop_browser_entry","Rozpocznij grę od dowolnego etapu bez nadpisywania aktualnego zapisu gry."},
    {"pc_loop_choose","Wybierz pętlę"},
    {"pc_loop_preview","Podgląd"},
    {"pc_loop_start_hint","Enter / Krzyżyk / A: rozpocznij pętlę"},
    {"pc_loop_f000","Pokój startowy: prolog"},
    {"pc_loop_f010","Pętla 1: radio"},
    {"pc_loop_f005","Pętla 2: otwierają się drzwi do korytarza"},
    {"pc_loop_f020","Pętla 3: płacz w łazience"},
    {"pc_loop_f030","Pętla 4: drzwi do łazienki"},
    {"pc_loop_f040","Pętla 5: Lisa na końcu korytarza"},
    {"pc_loop_f060","Pętla 6: łazienka, latarka"},
    {"pc_loop_f050a","Pętla 7: Lisa idzie za tobą"},
    {"pc_loop_f050b","Pętla 8: zdjęcie ze znakiem krzyżyka"},
    {"pc_loop_f070","Pętla 9: pęka okno"},
    {"pc_loop_f080","Pętla 10: krwawiąca lodówka"},
    {"pc_loop_f090","Pętla 11: HELLO"},
    {"pc_loop_f100","Pętla 12: czerwony korytarz"},
    {"pc_loop_f110","Pętla 13: labirynt i wizjer w drzwiach"},
    {"pc_loop_f120","Pętla 14: 204863, ekran błędu"},
    {"pc_loop_f160","Pętla 15: ostatnia pętla"},
    {"pc_loop_ending","Finałowy przerywnik filmowy i napisy końcowe"},
    {"pc_loop_street","Spacer ulicą (po finale)"},
    {"pc_note_loop_opening","Uruchamia prolog w pokoju startowym, jak przy nowej grze. Twój zapis gry zostanie zachowany."},
    {"pc_note_loop_hallway","Rozpoczyna w pokoju startowym tuż przed tą pętlą, z rozwiązanymi poprzednimi zagadkami. Przejdź przez drzwi. Zapis gry nie ulegnie zmianie i wznowi się od następnego punktu kontrolnego."},
    {"pc_note_loop_ending","Odtwarza finałowy przerywnik filmowy i napisy końcowe, a następnie oferuje spacer ulicą. Twój zapis gry zostanie zachowany."},
    {"pc_note_loop_street","Przenosi cię na ulicę z finału z perspektywy pierwszej osoby. Możesz wyjść przez menu Dodatki. Twój zapis gry zostanie zachowany."},
    {"pc_note_loop_locked","Zablokowane. Ukończ grę przynajmniej raz, aby odblokować osiągnięte pętle."},
    {"pc_note_loop_browser_locked","Ukończ grę raz, aby odblokować wybór pętli."},
    {"pc_street_title","Ulica"},
    {"pc_street_question","Zbadać ulicę?"},
    {"pc_street_walk","Tak, przejdź się ulicą"},
    {"pc_credit_version","P.T. PC Port {1} autorstwa LoreanXavier"},
    {"pc_update_available","Dostępna jest nowa wersja: {1} (obecnie zainstalowana: {2})"},
    {"pc_credits_by","autorstwa LoreanXavier"},
    {"pc_credits_dlss","Ta gra wykorzystuje technologię NVIDIA DLSS."},
    {"pc_credits_licenses","Pełna treść licencji znajduje się w folderze licenses obok pliku pt.exe."},
    {"pc_credits_konami","P.T. jest własnością Konami Digital Entertainment oraz Kojima Productions."},
    {"pc_credits_fan","Ten port jest nieoficjalnym projektem fanowskim i nie jest powiązany ani wspierany przez firmy Konami, NVIDIA, AMD ani Intel."},
    {"pc_note_street_walk","Przejdź się ulicą z finału z perspektywy pierwszej osoby. Wyjście jest możliwe przez menu Dodatki."},
    {"pc_street_restart","Nie, wróć do początku"},
    {"pc_note_street_restart","Rozpoczyna grę od nowa w pokoju startowym, tak jak po napisach końcowych w oryginale."},
    {"pc_street_leave","Opuść ulicę"},
    {"pc_note_street_leave","Kończy spacer i powraca do pokoju startowego."},
    {"pc_street_return","Wróć do domu"},
    {"pc_street_return_confirm","Wrócić do domu?"},
    {"pc_loop_lock","Zablokuj wybór pętli"},
    {"pc_note_loop_lock","Ponownie blokuje wszystkie pętle w menu wyboru, przywracając stan sprzed pierwszego ukończenia gry. Twój zapis gry nie ulegnie zmianie."},
    {"pc_extras","Dodatki"},
    {"pc_vr","VR (eksperymentalne)"},
    {"pc_note_vr","Rozgrywka w goglach VR za pośrednictwem OpenXR. Funkcja eksperymentalna: nieprzetestowana na fizycznym sprzęcie."},
    {"pc_vr_mode","Tryb VR"},
    {"pc_note_vr_mode","Funkcja nieprzetestowana na fizycznym sprzęcie. Wymaga środowiska OpenXR i podłączonych gogli VR. Zostanie zastosowana przy następnym uruchomieniu; bez gogli gra włączy się w standardowym trybie."},
    {"pc_vr_flashlight","Latarka"},
    {"pc_note_vr_flashlight","Określa, czy snop światła latarki podąża za ruchem głowy (jak w oryginale), czy za kontrolerem trzymanym w dłoni."},
    {"pc_vr_head","Głowa"},
    {"pc_vr_controller","Kontroler"},
    {"pc_vr_turn","Obrót"},
    {"pc_note_vr_turn","Prawy drążek obraca widok skokowo lub płynnie. Obrót skokowy w mniejszym stopniu wywołuje chorobę lokomocyjną."},
    {"pc_vr_snap","Skokowy"},
    {"pc_vr_smooth","Płynny"},
    {"pc_note_extras","Wybór pętli, swobodna kamera i tryb fotograficzny."},
    {"pc_freecam","Swobodna kamera"},
    {"pc_note_freecam","Odłącza kamerę od postaci gracza (F6). Spacja / Ctrl lub spusty: góra i dół, Shift lub L3: szybszy ruch. Esc: wyjście."},
    {"pc_photo_mode","Tryb fotograficzny"},
    {"pc_note_photo_mode","Zatrzymuje grę i pozwala skomponować ujęcie za pomocą swobodnej kamery (F7). Klawisz P lub Kwadrat: zapis w Pictures/PT Photos, H lub Trójkąt: ukrycie panelu."},
    {"pc_speedrun","Stoper speedrunu"},
    {"pc_note_speedrun","Wyświetla stoper na ekranie z międzyczasem dla każdej pętli oraz podsumowaniem po napisach końcowych. Czas rzeczywisty mierzy pełny upływ czasu; czas gry pomija pauzy i ekrany ładowania. Opcja nieobecna w oryginale."},
    {"pc_speedrun_real_time","Czas rzeczywisty"},
    {"pc_speedrun_game_time","Czas gry"},
    {"pc_livesplit","Serwer LiveSplit"},
    {"pc_note_livesplit","Przesyła sygnał startu, międzyczasy oraz czas gry do programu LiveSplit (Control > Start TCP Server, port {1}). Konfiguracja hosta i portu znajduje się w pliku pt.ini."},
    {"pc_speedrun_results","PODEJŚCIE ZAKOŃCZONE"},
    {"pc_speedrun_run","Podejście"},
    {"pc_speedrun_splits","Międzyczasy"},
    {"pc_speedrun_menu","Wróć do menu"},
    {"pc_note_speedrun_menu","Rozpoczyna grę od nowa tak jak po finale w oryginale, otwierając najpierw ekran opcji. Następna próba rozpocznie się z chwilą przejęcia kontroli nad postacią."},
    {"pc_speedrun_outside","Zbadaj otoczenie"},
    {"pc_note_speedrun_outside","Przejdź się ulicą z finału. Powrót do korytarza jest możliwy w dowolnym momencie z menu pauzy."},
    {"pc_note_speedrun_real","Rzeczywisty czas od przejęcia kontroli do finału: uwzględnia pauzy, ekrany ładowania oraz przerywniki filmowe."},
    {"pc_note_speedrun_game","Czas samej rozgrywki: pauza w menu oraz ekrany wczytywania po śmierci gracza nie są wliczane."},
    {"pc_speedrun_best","Rekord życiowy"},
    {"pc_note_speedrun_best","Poprzedni rekord: {1}. Wyniki są zapisywane w plikach speedrun.ini, speedrun_history.txt oraz speedrun_pb.lss (LiveSplit) w folderze użytkownika."},
    {"pc_speedrun_new_best","Nowy rekord życiowy!"},
    {"pc_speedrun_partial","Nie od początku"},
    {"pc_speedrun_start_room","Pokój startowy"},
    {"pc_speedrun_loop","Pętla {1}"},
    {"pc_third_person","Widok zza pleców (eksperymentalny)"},
    {"pc_note_third_person","Funkcja eksperymentalna, nieobecna w oryginale: kamera umieszczona jest za ramieniem postaci. Zbliżenie i przerywniki filmowe tymczasowo przywracają widok z pierwszej osoby; rozgrywka przebiega identycznie."},
    {"pc_extras_start","Włącz"},
    {"pc_photo_title","TRYB FOTOGRAFICZNY"},
    {"pc_photo_section_camera","Kamera"},
    {"pc_photo_section_lens","Obiektyw"},
    {"pc_photo_section_image","Obraz"},
    {"pc_photo_take","Zrób zdjęcie"},
    {"pc_photo_capture","Przechwyć"},
    {"pc_photo_fov","Pole widzenia"},
    {"pc_photo_roll","Przechylenie kamery"},
    {"pc_photo_speed","Prędkość kamery"},
    {"pc_photo_speed_slow","Niska"},
    {"pc_photo_speed_normal","Normalna"},
    {"pc_photo_speed_fast","Wysoka"},
    {"pc_photo_reset","Zresetuj kamerę"},
    {"pc_photo_focus","Odległość ostrzenia"},
    {"pc_photo_aperture","Przysłona"},
    {"pc_photo_exposure","Ekspozycja"},
    {"pc_photo_grading","Korekcja barwna"},
    {"pc_photo_letterbox","Pasy filmowe"},
    {"pc_photo_body","Model postaci"},
    {"pc_photo_flashlight","Latarka"},
    {"pc_photo_shown","Pokaż"},
    {"pc_photo_hidden","Ukryj"},
    {"pc_photo_auto","Auto"},
    {"pc_photo_metres","{value} m"},
    {"pc_photo_saved","Zapisano w Pictures/PT Photos: {file}"},
    {"pc_photo_hint","Strzałki / krzyżak: wybór i zmiana. P / Kwadrat: zdjęcie. H / Trójkąt: ukryj panel. Prawy przycisk myszy: rozejrzyj się. Esc / Kółko: wyjście."},
    {"pc_note_photo_take","Zapisuje aktualny kadr w folderze Pictures/PT Photos. Interfejs trybu fotograficznego nie jest uwieczniany na zdjęciu."},
    {"pc_note_photo_fov","Pionowe pole widzenia wyrażone w stopniach. Mniejsza wartość oznacza większe przybliżenie kadru."},
    {"pc_note_photo_roll","Obraca kamerę w osi widzenia, tworząc tzw. kąt holenderski."},
    {"pc_note_photo_speed","Szybkość poruszania się kamery. Klawisz Shift lub drążek L3 pozwala przyspieszyć ruch."},
    {"pc_note_photo_reset","Przywraca pozycję kamery z chwili aktywacji trybu fotograficznego."},
    {"pc_note_photo_dof","Rozmywa elementy znajdujące się bliżej lub dalej niż ustawiona płaszczyzna ostrości."},
    {"pc_note_photo_focus","Opcja automatyczna ustawia ostrość na obiekcie znajdującym się dokładnie w centrum kadru."},
    {"pc_note_photo_aperture","Niższa wartość przysłony zapewnia silniejsze rozmycie tła. Ustawienie automatyczne zachowuje parametry kamery z gry."},
    {"pc_note_photo_exposure","Rozjaśnia lub przyciemnia kadr w odstępach co pół stopnia ekspozycji (EV)."},
    {"pc_note_photo_grain","Oryginalne ziarno filmowe. Wyłączenie zapewnia idealnie gładki, czysty obraz."},
    {"pc_note_photo_grading","Oryginalna paleta barw. Wyłączenie przywraca neutralną kolorystykę sceny."},
    {"pc_note_photo_letterbox","Kinowe czarne pasy u góry i u dołu ekranu. Zostaną uwiecznione na gotowym zdjęciu."},
    {"pc_note_photo_body","Wyświetla lub ukrywa model postaci gracza."},
    {"pc_note_photo_flashlight","Wyłącza światło latarki podczas komponowania ujęcia."},
    {"pc_extras_stop","Wyłącz"},
    {"pc_note_loop_generating","Generowanie miniatur podglądu... Twój zapis gry zostanie zachowany. Kolejny autozapis nastąpi przy punkcie kontrolnym: po wyjściu z piwnicy lub w ostatniej pętli."},
    {"pc_title","USTAWIENIA PC"},
    {"pc_entry","Ustawienia PC"},
    {"pc_back","Wstecz"},
    {"pc_quit","Wyjdź"},
    {"pc_nav_columns","Tab / L1 / R1: zmiana kolumny"},
    {"pc_quit_confirm","Wyjść z gry?"},
    {"pc_save_no_space","Za mało wolnego miejsca na dysku, aby zapisać stan gry.\nZwolnij miejsce, a następnie zamknij ten komunikat, aby ponowić próbę."},
    {"pc_ok","OK"},
    {"pc_note_quit","Wyjście do pulpitu."},
    {"pc_note_quit_confirm","Naciśnij {accept} ponownie, aby wyjść, lub Wstecz, aby anulować."},
    {"pc_section_display","Ekran"},
    {"pc_section_upscaling","Skalowanie obrazu"},
    {"pc_section_sound","Dźwięk"},
    {"pc_section_controls","Sterowanie"},
    {"pc_section_progress","Postęp"},
    {"pc_section_ray_tracing","Śledzenie promieni"},
    {"pc_section_textures","Tekstury"},
    {"pc_display_mode","Tryb ekranu"},
    {"pc_resolution","Rozdzielczość"},
    {"pc_vsync","Synchronizacja pionowa"},
    {"pc_focus_pause","Pauza w tle"},
    {"pc_focus_mute","Wycisz w tle"},
    {"pc_upscaler","Technologia"},
    {"pc_quality","Tryb jakości"},
    {"pc_sharpness","Ostrość"},
    {"pc_frame_generation","Generowanie klatek"},
    {"pc_volume","Głośność"},
    {"pc_microphone","Mikrofon"},
    {"pc_microphone_test","Test mikrofonu"},
    {"pc_mic_level","Poziom sygnału wejściowego"},
    {"pc_mic_heard","Rozpoznane słowa"},
    {"pc_mic_monitor","Odsłuch mikrofonu"},
    {"pc_mic_no_word","Brak"},
    {"pc_mic_waiting","Oczekiwanie na mikrofon..."},
    {"pc_mic_unavailable","Nie udało się uzyskać dostępu do mikrofonu. Sprawdź uprawnienia systemowe oraz domyślne urządzenie nagrywające."},
    {"pc_mic_say_jack","Powiedz „Jack” do mikrofonu. Ten test nie wpływa na postęp w grze."},
    {"pc_mic_monitor_note","Odsłuch sygnału z mikrofonu. Zalecamy użycie słuchawek, aby uniknąć sprzężenia zwrotnego. Odsłuch wyłączy się po wyjściu z testu."},
    {"pc_mouse","Czułość myszy"},
    {"pc_camera_tilt","Pochylenie kamery"},
    {"pc_vibration","Wibracje"},
    {"pc_dead_zone","Martwa strefa drążka"},
    {"pc_reset","Zresetuj postęp"},
    {"pc_graphics","Grafika"},
    {"pc_graphics_value","Otwórz"},
    {"pc_rt_shadows","Cienie (śledzenie promieni)"},
    {"pc_rt_contact","Cienie kontaktowe"},
    {"pc_shadows","Cienie"},
    {"pc_reflections","Odbicia"},
    {"pc_standard","Standardowe"},
    {"pc_ray_traced","Śledzenie promieni"},
    {"pc_rt_sharp_long","Śledzenie promieni (ostre)"},
    {"pc_rt_soft_long","Śledzenie promieni (miękkie)"},
    {"pc_note_shadows","Od Niskich do Oryginalnych: tradycyjne mapy cieni z pierwowzoru (512, 1024 lub 2048 px). Śledzenie promieni zastępuje je nowym rozwiązaniem: cieniami ze śledzeniem promieni – ostrymi jak w oryginale lub miękkimi, zależnie od wielkości źródła światła."},
    {"pc_note_ao","Standardowe: tradycyjne cieniowanie w przestrzeni ekranu. Śledzenie promieni precyzyjnie zacienia kąty i szczeliny w oparciu o geometrię całej sceny. Opcja nieobecna w oryginale."},
    {"pc_note_reflections","Standardowe: oryginalne odbicia posadzki w przestrzeni ekranu. Śledzenie promieni uwzględnia również geometrię znajdującą się poza kadrem. Funkcja eksperymentalna."},
    {"pc_rt_ao","Okluzja otoczenia"},
    {"pc_anisotropy","Filtrowanie anizotropowe"},
    {"pc_enhanced_textures","Ulepszone tekstury"},
    {"pc_texture_preparing","Przygotowywanie"},
    {"pc_note_texture_tools_missing","Brak wymaganych narzędzi lub modeli dla ulepszonych tekstur. Przywróć folder texture-tools i spróbuj ponownie. Oryginalne tekstury pozostają nienaruszone."},
    {"pc_note_texture_busy","Inny proces gry przygotowuje obecnie pamięć podręczną tekstur. Zaczekaj na zakończenie operacji i spróbuj ponownie."},
    {"pc_note_texture_failed","Nie udało się przetworzyć ulepszonych tekstur; zachowano wersje oryginalne. Sprawdź wolne miejsce na dysku oraz plik pt.log, a następnie ponów próbę."},
    {"pc_note_texture_preparing","Trwa przetwarzanie ulepszonych tekstur. Do czasu zakończenia widoczne są tekstury oryginalne; podmiana nastąpi płynnie bez restartu gry. Wyłączenie opcji przerywa proces."},
    {"pc_note_enhanced_textures","Jednorazowo generuje ostrzejsze tekstury na podstawie plików gry. Obejmuje ściany i postacie (rozdzielczość 4096 px przy co najmniej 10 GB pamięci VRAM, w przeciwnym razie 2048 px). Wyłączenie anuluje zadanie; oryginalne tekstury są stale zachowane."},
    {"pc_rt_sharp","Ostre"},
    {"pc_rt_soft","Miękkie"},
    {"pc_on","Wł."},
    {"pc_off","Wył."},
    {"pc_window","W oknie"},
    {"pc_borderless","Bez ramek"},
    {"pc_fullscreen","Pełny ekran"},
    {"pc_native","Natywna"},
    {"pc_quality_quality","Jakość"},
    {"pc_quality_balanced","Zrównoważony"},
    {"pc_quality_performance","Wydajność"},
    {"pc_quality_ultra","Ultra wydajność"},
    {"pc_quality_custom","Niestandardowe"},
    {"pc_system_default","Domyślne systemu"},
    {"pc_reset_value","Zresetuj"},
    {"pc_reset_confirm","Potwierdź"},
    {"pc_reset_done","Gotowe"},
    {"pc_note_vsync","Działa natychmiastowo. Synchronizuje wyświetlanie klatek z częstotliwością odświeżania monitora, eliminując rozrywanie obrazu."},
    {"pc_note_vsync_off","Działa natychmiastowo. Klatki wyświetlane są natychmiast po wyrenderowaniu: brak limitu odświeżania monitora może powodować rozrywanie obrazu."},
    {"pc_note_restart","Zmiany zaczną obowiązywać po ponownym uruchomieniu gry."},
    {"pc_note_display_mode","Kombinacja klawiszy Alt+Enter pozwala na szybkie przełączanie między oknem a pełnym ekranem."},
    {"pc_note_resolution","Wymiary okna lub rozdzielczość renderowania gry."},
    {"pc_note_resolution_fullscreen","W trybie bez ramek gra dopasowuje się do wybranej rozdzielczości; pełny ekran na wyłączność korzysta z natywnych trybów monitora."},
    {"pc_note_upscaler_off","Wył.: renderowanie w pełnej, natywnej rozdzielczości ekranu, tak jak w oryginale."},
    {"pc_note_render_size","Renderowanie: {1}, wyświetlanie: {2}."},
    {"pc_note_needs_upscaler","Wymaga uprzedniego włączenia technologii skalowania obrazu."},
    {"pc_note_sharpness_fsr","Wyostrzanie zintegrowane bezpośrednio w algorytm FSR. Niezależny filtr Przejrzystość w sekcji Grafika działa z dowolną metodą skalowania."},
    {"pc_note_reset","Czyści postęp i natychmiast restartuje grę. Język oraz preferencje graficzne zostaną zachowane."},
    {"pc_note_reset_confirm","Naciśnij {accept} ponownie, aby bezpowrotnie usunąć zapis gry."},
    {"pc_note_reset_done","Postęp w bieżącej sesji został zresetowany."},
    {"pc_note_camera_tilt","Kamera delikatnie przechyla się w trakcie chodu wraz z ruchem głowy, identycznie jak w pierwowzorze."},
    {"pc_note_voice","Mikrofon rejestruje dźwięk wyłącznie w kluczowych momentach przewidzianych w oryginale."},
    {"pc_note_focus_pause","Otwiera menu pauzy w sytuacji, gdy okno gry traci aktywność."},
    {"pc_note_focus_mute","Całkowicie wycisza dźwięk, dopóki gra pozostaje w tle."},
    {"pc_note_frame_generation_missing","Technologia niedostępna w tej kompilacji gry."},
    {"pc_note_frame_generation","Algorytm AMD FSR 3 generuje i wstawia dodatkową klatkę pomiędzy każdą parą wyrenderowanych klatek."},
    {"pc_note_fsr4_vulkan","AMD udostępnia technologię FSR 4 wyłącznie dla DirectX 12; ta wersja gry działa w oparciu o API Vulkan."},
    {"pc_dlss_model","Model DLSS"},
    {"pc_dlss_model_auto","Auto"},
    {"pc_note_dlss_model","Tryb automatyczny dobiera model zgodnie z zaleceniami NVIDIA: profil Zrównoważony korzysta z modelu K, Wydajność z M, a Ultra wydajność z L. Modele L i M powodują około dwukrotnie wyższy narzut na kartach RTX z serii 20 i 30."},
    {"pc_note_frame_generation_dlss","Funkcja eksperymentalna. Generowanie klatek NVIDIA DLSS tworzy dodatkowe klatki za pomocą jednostek AI. Wymaga ponownego uruchomienia gry."},
    {"pc_note_dlssg_gpu","Generowanie klatek DLSS wymaga karty graficznej z rodziny NVIDIA GeForce RTX z serii 40 lub nowszej."},
    {"pc_note_fsr_fg_gpu","Generowanie klatek FSR 3 wymaga karty graficznej AMD Radeon RX z serii 5000 / NVIDIA GTX z serii 10 lub nowszej."},
    {"pc_note_dlssg_driver","Generowanie klatek DLSS wymaga zainstalowania nowszej wersji sterownika graficznego NVIDIA."},
    {"pc_note_dlssg_hags","Generowanie klatek DLSS wymaga włączenia funkcji planowania procesora GPU z przyspieszeniem sprzętowym (w ustawieniach ekranu systemu Windows)."},
    {"pc_note_dlssg_missing","Generowanie klatek DLSS nie jest dostępne w tej kompilacji gry."},
    {"pc_note_dlssg_failed","Nie udało się zainicjować generowania klatek DLSS; funkcja została wyłączona."},
    {"pc_note_dlssg_restart","Uruchom grę ponownie, aby aktywować generowanie klatek DLSS."},
    {"pc_note_vsync_dlssg","W środowisku Vulkan funkcja generowania klatek DLSS wyklucza działanie synchronizacji pionowej; synchronizacja pionowa stanie się ponownie aktywna po wyłączeniu generowania klatek."},
    {"pc_note_fsr_fg_restart","Uruchom grę ponownie, aby przełączyć technologię generowania klatek z DLSS na FSR 3."},
    {"pc_note_dead_zone","Wartość 0.10 jest domyślnym rozmiarem martwej strefy dla kontrolera DualShock 4."},
    {"pc_note_rt_shadows","Cienie generowane za pomocą śledzenia promieni zamiast map cieni, z zachowaniem ostrości oryginału. Brak w pierwowzorze."},
    {"pc_note_rt_soft","Cienie oparte na śledzeniu promieni z naturalnie zmiękczonymi krawędziami zależnie od rozmiaru źródła światła. Brak w oryginale."},
    {"pc_note_rt_unsupported","Wymaga karty graficznej ze sprzętową obsługą śledzenia promieni w środowisku Vulkan."},
    {"pc_note_graphics","Wybierz predefiniowany profil graficzny lub precyzyjnie dostosuj parametry oświetlenia, cieni i efektów. Rozdzielczość oraz skalowanie konfigurowane są osobno."},
    {"pc_note_rt_contact","Krótkie cienie oparte na śledzeniu promieni, rzucane przez drobne obiekty od każdego punktu światła – w tym tych, które w oryginale nie rzucały cieni."},
    {"pc_note_rt_ao","Okluzja otoczenia oparta na śledzeniu promieni precyzyjnie przyciemnia załamania ścian, kąty oraz przestrzeń pod obiektami w oparciu o całą scenę. Brak w oryginale."},
    {"pc_rt_reflections","Odbicia"},
    {"pc_note_rt_reflections","Posadzka odbija pełną geometrię korytarza, w tym obiekty znajdujące się poza widocznym kadrem. Funkcja eksperymentalna."},
    {"pc_note_anisotropy","Tekstury podłóg i ścian oglądane pod ostrym kątem zachowują ostrość i czystość. Wył.: filtrowanie identyczne z wersją konsolową."},
    {"pc_graphics_quality","Jakość"},
    {"pc_graphics_preset","Profil ustawień"},
    {"pc_preset_low","Niska"},
    {"pc_preset_medium","Średnia"},
    {"pc_preset_original","Oryginalna (PS4)"},
    {"pc_preset_high","Wysoka"},
    {"pc_preset_ultra","Ultra"},
    {"pc_preset_custom","Niestandardowy"},
    {"pc_ray_tracing","Śledzenie promieni"},
    {"pc_clarity","Przejrzystość"},
    {"pc_graphics_advanced","Zaawansowane"},
    {"pc_graphics_lighting","Oświetlenie"},
    {"pc_graphics_effects","Efekty obrazu"},
    {"pc_graphics_image","Obraz"},
    {"pc_lighting_standard","Oświetlenie standardowe"},
    {"pc_shadow_quality","Mapy cieni"},
    {"pc_standard_ao","Okluzja otoczenia"},
    {"pc_standard_reflections","Odbicia w przestrzeni ekranu"},
    {"pc_ray_quality","Jakość promieni"},
    {"pc_ray_balanced","Zrównoważona"},
    {"pc_texture_detail","Szczegółowość tekstur"},
    {"pc_detail_reduced","Obniżona"},
    {"pc_detail_fine","Wysoka"},
    {"pc_dof","Głębia ostrości"},
    {"pc_motion_blur","Rozmycie w ruchu"},
    {"pc_bloom","Rozbłysk światła (bloom)"},
    {"pc_lens_ghosts","Flary obiektywu"},
    {"pc_note_lens_ghosts","Charakterystyczne rozbłyski soczewkowe na całym ekranie przy patrzeniu w stronę żarówek (jak na PS4). Wyłączenie usuwa ten efekt."},
    {"pc_film_grain","Ziarno filmowe"},
    {"pc_note_preset","Wpływa wyłącznie na opcje renderowania; rozdzielczość i skalowanie pozostają bez zmian. Zmiana pojedynczej opcji ustawia profil Niestandardowy. Profil Ultra włącza śledzenie promieni, jeśli karta je obsługuje."},
    {"pc_note_ray_master","Przełącza jednocześnie cienie oparte na śledzeniu promieni, cienie kontaktowe, okluzję otoczenia i odbicia. Dalsza regulacja w zakładce Oświetlenie."},
    {"pc_lens_distortion","Zniekształcenie obiektywu"},
    {"pc_note_lens_distortion","Efekt dystorsji soczewki i aberracja chromatyczna znane z oryginału. Wyłączenie zapewnia prosty, ostry obraz bez zakrzywień na krawędziach."},
    {"pc_note_clarity","Zwiększa wyrazistość krawędzi poprzez adaptacyjny kontrast lokalny w docelowej rozdzielczości. Wartość 0 zachowuje wygląd oryginału."},
    {"pc_note_letterbox","Dodaje kinowe czarne pasy u góry i u dołu ekranu podczas rozgrywki oraz w przerywnikach filmowych. Napisy pozostają w kadrze. Brak w oryginale."},
    {"pc_note_advanced","Szczegółowa konfiguracja parametrów graficznych. Przycisk Wstecz cofa do menu nadrzędnego; po ręcznej korekcie profil zmieni się na Niestandardowy."},
    {"pc_note_shadow_quality","Rozdzielczość tradycyjnych map cieni: 512, 1024 lub oryginalne 2048 px. Włączone cienie ze śledzeniem promieni zastępują ten mechanizm."},
    {"pc_note_standard_ao","Oryginalna okluzja otoczenia renderowana w przestrzeni ekranu (SSAO). Wyłączenie redukuje obciążenie słabszych układów graficznych."},
    {"pc_note_standard_reflections","Oryginalne odbicia posadzki w przestrzeni ekranu (SSR). Włączone odbicia oparte na śledzeniu promieni zastępują tę funkcję."},
    {"pc_note_ray_quality","Zrównoważona: 2 promienie. Wysoka: 4 promienie. Ultra: 8 promieni. Wyższe wartości zapewniają bardziej miękkie cienie i redukują szum śledzenia promieni."},
    {"pc_note_texture_detail","Obniżona: niższa szczegółowość tekstur (agresywniejszy mipmapping). Wysoka: wyraźniejsze detale w oddali, kosztem możliwego migotania krawędzi. Rozdzielczość ekranu pozostaje bez zmian."},
    {"pc_note_dof","Oryginalne rozmycie tła poza punktem ostrości kamery. Wyłączenie sprawia, że cały plan pozostaje ostry."},
    {"pc_note_motion_blur","Rozmycie wywoływane ruchem postaci i gwałtownym obrotem kamery. Wyłączenie zapewnia idealnie klarowny obraz w ruchu."},
    {"pc_note_bloom","Oryginalna poświata wokół jasnych źródeł światła. Wyłączenie usuwa poświatę i nieznacznie zmniejsza obciążenie karty graficznej."},
    {"pc_note_film_grain","Intensywność nałożonego ziarna filmowego. Wył.: krystalicznie czysty obraz; 100%: efekt identyczny jak na konsoli PS4."},
    {"pc_mods","Modyfikacje"},
    {"pc_section_mods","Zainstalowane modyfikacje"},
    {"pc_note_mods","Włączenie lub wyłączenie modyfikacji wymaga ponownego uruchomienia gry. Modyfikacje nie wchodzą w skład oryginalnej gry."},
    {"pc_archive","Muzeum"},
    {"pc_note_archive","Koncepcyjne grafiki, nagrania głosowe, skrawki fotografii, przerywniki filmowe i modele 3D odblokowywane wraz z postępami. Twój zapis gry pozostaje nienaruszony."},
    {"pc_note_extras_archive","Wybór pętli, muzeum, swobodna kamera i tryb fotograficzny."},
    {"pc_archive_sections","Sale"},
    {"pc_archive_images","Obrazy podprogowe"},
    {"pc_archive_voices","Głosy i radio"},
    {"pc_archive_photos","Fragmenty fotografii"},
    {"pc_archive_cutscenes","Przerywniki filmowe"},
    {"pc_archive_models","Modele"},
    {"pc_archive_unused","Materiały niewykorzystane"},
    {"pc_note_archive_images","Błyski podprogowe z ukrytym tekstem, zakłócenia obrazu oraz kadr zza wizjera w drzwiach."},
    {"pc_note_archive_voices","Audycje radiowe i wszystkie linie dialogowe wraz z transkrypcją w wybranym języku napisów."},
    {"pc_note_archive_photos","Podarte skrawki zdjęcia oraz kompletna fotografia, którą tworzą w ramce."},
    {"pc_note_archive_cutscenes","Przerywniki filmowe odtworzone od początku, w pełnej jakości audio i z napisami."},
    {"pc_note_archive_models","Trójwymiarowy model Lisy, postaci oraz rekwizytów z korytarza w neutralnym świetle pokoju startowego."},
    {"pc_note_archive_unused_section","Zawartość z plików gry, która ostatecznie do niej nie trafiła. Odblokowuje się po ukończeniu rozgrywki."},
    {"pc_note_archive_image","Enter / Krzyżyk: pełny ekran."},
    {"pc_note_archive_voice","Enter / Krzyżyk: odtwórz lub wstrzymaj."},
    {"pc_note_archive_photo","Enter / Krzyżyk: pełny ekran."},
    {"pc_note_archive_demo","Enter / Krzyżyk: odtwórz od początku. Esc / Kółko: powrót."},
    {"pc_note_archive_model","Enter / Krzyżyk: oglądaj model. Esc / Kółko: powrót."},
    {"pc_note_archive_unused","Niewykorzystane w grze. Enter / Krzyżyk: oglądaj model."},
    {"pc_note_archive_locked","Zablokowane. Osiągnij ten moment w fabule gry, aby uzyskać dostęp."},
    {"pc_note_archive_playing","Trwa odtwarzanie. Enter / Krzyżyk: zatrzymaj."},
    {"pc_archive_lock","Zablokuj muzeum"},
    {"pc_note_archive_lock","Ponownie blokuje wszystkie eksponaty w muzeum, przywracając stan sprzed rozpoczęcia gry. Zapis gry nie ulegnie zmianie."},
    {"pc_archive_hint","Enter / Krzyżyk / A: otwórz"},
    {"pc_archive_view_hint","W lewo / W prawo: poprzedni / następny element. Esc / Kółko: wstecz."},
    {"pc_archive_demo_hint","Esc / Kółko / Enter / Krzyżyk: zatrzymaj"},
    {"pc_archive_model_hint","WASD / lewy drążek: przesuwanie kamery. Strzałki / prawy drążek: obrót. Spusty: przybliżenie. Esc / Kółko: wstecz."},
    {"pc_archive_sub","Komunikat podprogowy {1}"},
    {"pc_archive_noise","Szum"},
    {"pc_archive_noise_normal","Zniekształcenie szumu"},
    {"pc_archive_peephole_mask","Kadr z wizjera"},
    {"pc_archive_radio_news","Radio: serwis informacyjny"},
    {"pc_archive_radio_news2","Radio: powtórzenie wiadomości"},
    {"pc_archive_radio_voice","Głos w radiu {1}"},
    {"pc_archive_riddle","Zagadka radiowa {1}"},
    {"pc_archive_sermon","Radio: kazanie"},
    {"pc_archive_phone","Rozmowa telefoniczna"},
    {"pc_archive_peephole_voice","Głos zza drzwi"},
    {"pc_archive_bag","Mówiąca torba"},
    {"pc_archive_fetus","Głos płodu {1}"},
    {"pc_archive_photo_lisa","Fragment: Lisa"},
    {"pc_archive_photo_tree","Fragment: drzewo"},
    {"pc_archive_photo_gap","Fragment: szczelina"},
    {"pc_archive_photo_bath","Fragment: łazienka"},
    {"pc_archive_photo_stair","Fragment: schody"},
    {"pc_archive_photo_option","Fragment: menu opcji"},
    {"pc_archive_photo_complete","Kompletna fotografia"},
    {"pc_archive_preface","Prolog"},
    {"pc_archive_awakening","Pierwsze przebudzenie"},
    {"pc_archive_opening","Przebudzenie"},
    {"pc_archive_first_exit","Pierwsze wyjście"},
    {"pc_archive_door","Przejście przez drzwi"},
    {"pc_archive_clock","Północ"},
    {"pc_archive_kill","Atak Lisy"},
    {"pc_archive_ending","Finał"},
    {"pc_archive_teaser","Zwiastun"},
    {"pc_archive_lisa_stand","Lisa: postawa stojąca"},
    {"pc_archive_lisa_walk","Lisa: chód"},
    {"pc_archive_lisa_dash","Szarża Lisy"},
    {"pc_archive_lisa_door","Lisa w drzwiach"},
    {"pc_archive_baby","Płód w umywalce"},
    {"pc_archive_fridge","Podwieszona lodówka"},
    {"pc_archive_bag_model","Papierowa torba"},
    {"pc_archive_lamp","Lampa sufitowa"},
    {"pc_archive_roach","Karaluch"},
    {"pc_archive_flashlight","Latarka"},
    {"pc_archive_radio","Odbiornik radiowy"},
    {"pc_archive_phone_model","Telefon stacjonarny"},
    {"pc_archive_xmark_photo","Fotografia z krzyżykiem"},
    {"pc_archive_clock_model","Budzik cyfrowy"},
    {"pc_archive_man","Mężczyzna"},
    {"pc_archive_bathtub","Wanna z zawartością"},
};
inline std::string_view Menu(std::string_view key) {
    for (const auto& e : kMenu) if (e.key == key) return e.text;
    return {};
}
struct Subtitle { uint32_t key; std::initializer_list<std::string_view> lines; };
inline const Subtitle kSubtitles[] = {
    {0x54E4EFDE,{
        "W cieniu toczącej się w Kongresie debaty nad dostępem do broni,",
        "donosimy o tragedii:|ojciec zamordował żonę i dwójkę dzieci.",
        "Broń użytą do zbrodni kupił w miejscowym sklepie|zaledwie dwa dni wcześniej.",
        "Do tego makabrycznego czynu doszło w niedzielne popołudnie,|gdy cała rodzina była w domu.",
        "Mężczyzna wyciągnął strzelbę z bagażnika|i zabił żonę sprzątającą kuchnię po obiedzie.",
        "Gdy dziesięcioletni syn przybiegł, słysząc strzał,|zastrzelił również i jego.",
        "Sześcioletnia córka ukryła się w łazience,|ale ojciec nakłonił ją do wyjścia, wmawiając, że to tylko zabawa.",
        "Dziewczynka zginęła od strzału w pierś z bliskiej odległości.",
        "Kobieta, postrzelona prosto w brzuch, była w ciąży.",
        "Gdy wezwana przez sąsiadów policja dotarła na miejsce,|zastała sprawcę w aucie, jak gdyby nigdy nic słuchającego radia.",
        "Jak zeznają sąsiedzi, na kilka dni przed tragedią|mężczyzna bez przerwy powtarzał ten sam ciąg cyfr.",
        "Świadkowie twierdzą, że brzmiało to niemal jak opętanie.",
        "W zeszłym miesiącu w tym samym stanie doszło do podobnego morderstwa,|a w grudniu ubiegłego roku",
        "inny ojciec zabił swoich bliskich przy użyciu strzelby i tasaka.",
        "W każdym z tych przypadków sprawcą był ojciec rodziny.",
        "Policja stanowa twierdzi wprawdzie, że te sprawy nie są ze sobą powiązane,",
        "jednak mogą wynikać z przepracowania,|problemów wychowawczych i kryzysu współczesnej rodziny."}},
    {0xB91F5727,{
        "Szedłem i szedłem.",
        "Ciało samo parło do przodu.",
        "Aż zobaczyłem kogoś przed sobą. To byłem ja.",
        "Tyle że to wcale nie byłem ja.",
        "Uważaj.",
        "Za tą szczeliną w drzwiach... jest inny świat.",
        "Ja to tylko ja.",
        "A ty? Jesteś pewien, że jesteś sam?"}},
    {0x72E1954B,{
        "Wylali cię z roboty i zacząłeś pić na umór.",
        "Ona musiała tyrać na kasie w spożywczaku.",
        "I trzymali ją tam tylko dlatego,|że kierownikowi podobało się, jak wygląda w spódnicy.",
        "Pamiętasz to, co?",
        "Równo dziesięć miesięcy temu."}},
    {0x7D33E7DF,{
        "Stary był potwornym nudziarzem.",
        "Codziennie to samo żarcie,|te same łachy,",
        "w kółko te same durne gry...",
        "Taa, cały on.",
        "Aż któregoś dnia po prostu wziął i wyrżnął nas wszystkich!",
        "Nawet sprzątnąć nas z jakimś polotem nie umiał.",
        "Nie żebym narzekał... I tak umierałem z nudów.",
        "Ale wiesz co? Jeszcze tu wrócę.",
        "I wezmę ze sobą nowe zabawki."}},
    {0xFBCD1565,{
        "Pora działać.",
        "To społeczeństwo zgniło do cna.",
        "Mówię do was, uczciwi, ciężko pracujący obywatele,|którym odebrano pracę i zasiłki!",
        "Tak, do ciebie! Dobrze wiesz, co trzeba zrobić!",
        "Nadszedł czas! Zrób to!"}},
    {0xDF405E61,{
        "Zostałeś wybrany."}},
    {0x40D69C3A,{
        "Nie zmieniajcie stacji, dopiero się rozkręcamy."}},
    {0x0AD16A8E,{
        "Nie pij wody z kranu."}},
    {0xC5EB59AA,{
        "Odwróć się.",
        "Mówię do ciebie: spójrz za siebie."}},
    {0x879FF72D,{
        "Po wymordowaniu rodziny ojciec powiesił się w garażu|na wężu ogrodowym."}},
    {0x01E674E7,{
        "204863",
        "204863"}},
    {0x30DE6EF0,{
        "Twój syn..."}},
    {0x4926CF3C,{
        "Odeślij go do aniołków...|...własnymi rękami.",
        "Jeszcze nie jest za późno. Pospiesz się."}},
    {0x7AC3E25E,{
        "Coś ty zrobił?!",
        "Na oczach wszystkich!",
        "Wylądujesz w wiadomościach, ty psycholu!",
        "MORDERCA!"}},
    {0x7980630B,{
        "Po wymordowaniu rodziny ojciec powiesił się w garażu|na pępowinie."}},
    {0xCE86DEBA,{
        "Słyszysz mój głos?|Potrafisz odczytać ten znak?|Będę czekać bez końca, po prostu przyjdź."}},
    {0x3E6F2ED2,{
        "Słyszysz mój głos?|Potrafisz odczytać ten znak?"}},
    {0xD925B7BD,{
        "Słyszysz mój głos?"}},
    {0x4AF4F3D4,{
        "Wybacz mi, Liso.|Mieszka we mnie potwór."}},
    {0x4FA7C4BD,{
        "Słyszę, jak wołają mnie z piekła."}},
    {0xF124B2D3,{
        "Stąd nie ma już ucieczki."}},
    {0x5D5A2A13,{
        "Stary był potwornym nudziarzem.|Codziennie to samo żarcie, te same łachy, w kółko te same durne gry...|Taa, cały on."}},
    {0x3FB2DE6F,{
        "Tak, do ciebie! Dobrze wiesz, co trzeba zrobić!",
        "Nadszedł czas!",
        "Zrób to!"}},
    {0xBF6D9A27,{
        "Nie zmieniajcie stacji, dopiero się rozkręcamy.",
        "Nie pij wody z kranu.",
        "204863",
        "Odwróć się.",
        "Mówię do ciebie: spójrz za siebie.",
        "204863"}},
    {0xC52AE206,{
        "Uważaj. Za tą szczeliną w drzwiach...|jest inny świat."}},
    {0xD62FBBDA,{
        "Ja to tylko ja.|A ty? Jesteś pewien, że jesteś sam?"}},
    {0x99242989,{
        "Ten zwiastun ma charakter interaktywny.|Nie wchodzi w skład właściwej gry."}},
};
}