#pragma once
#include <string_view>

// Brazilian Portuguese (as the game's own) for the port's own menus (PC settings, extras, photo mode, loop browser, notes and prompts) and the added
// languages' names on the option screen. The options screen's other texts and the subtitles are the game's own.
namespace pt::portuguese {
struct Text { std::string_view key, text; };
inline constexpr Text kMenu[] = {
    {"pc_controller_speaker","Altifalante do comando"},
    {"pc_note_controller_speaker","Reproduz os gritos gravados da Lisa nos altifalantes compatíveis dos comandos Sony. No Windows, requer ligação USB; dispositivos não suportados e Bluetooth ficam em silêncio. É independente da resposta háptica e está desativado por predefinição."},
    {"pc_controller_speaker_volume","Volume do altifalante do comando"},
    {"pc_note_controller_speaker_volume","Ajusta apenas o volume do altifalante do comando, em passos de 5%. Não altera o áudio do jogo nem a intensidade háptica do DualSense. Disponível apenas com comandos Sony com fios compatíveis no Windows."},
    {"pc_microphone_trigger_assign","Atribuir {input} ao acionador do microfone"},
    {"pc_note_microphone_trigger","Alternativa opcional ao microfone. O teclado e os dois gatilhos do comando ativam-na apenas enquanto o jogo está a ouvir."},
    {"pc_note_microphone_test","Testa o microfone e o resultado do reconhecimento."},
    {"pc_fps_limit","Limite de fotogramas"},
    {"pc_unlimited","Sem limite"},
    {"pc_note_fps_limit","Limita os fotogramas renderizados. Os menus continuam limitados a 60 FPS. A sincronização vertical pode impor um limite inferior."},
    {"pc_hdr","HDR nativo"},
    {"pc_note_hdr_restart","Aplicado no próximo arranque. Requer HDR ativo num ecrã compatível; caso contrário, é usado SDR."},
    {"pc_surround","Saída surround"},
    {"pc_note_surround","Após reiniciar, usa a disposição 5.1 ou 7.1 da saída. Os dispositivos estéreo continuam em estéreo."},
    {"pc_rumble_profile","Modo de vibração"},
    {"pc_rumble_original","Original"},
    {"pc_rumble_enhanced","Melhorado"},
    {"pc_note_rumble_profile","Original usa apenas a vibração dos motores prevista pelo jogo. Melhorado acrescenta vibração nos gatilhos compatíveis e, em comandos DualSense USB compatíveis no Windows, háptica derivada dos gritos filtrados da Lisa. O controlo principal da vibração desativa ambas. O som do altifalante do comando é independente."},
    {"pc_vr_height","Ajuste de altura"},
    {"pc_note_vr_height","Move o ponto de vista acompanhado para cima ou para baixo sem alterar a posição do jogador no jogo."},
    {"pc_vr_world_scale","Escala do mundo"},
    {"pc_note_vr_world_scale","Ajusta o movimento acompanhado da cabeça, dos olhos e dos comandos entre 50% e 200%. Quanto maior o valor, mais pequeno parece o mundo. Predefinição: 100%."},
    {"pc_photo_focal_length","Distância focal"},
    {"pc_note_photo_focal_length","Distância focal da lente em milímetros. O desfoque usa a mesma lente e o mesmo sensor da câmara."},
    {"pc_photo_aspect","Proporção"},
    {"pc_note_photo_aspect","Recorta a fotografia pelo centro."},
    {"pc_photo_resolution","Resolução da fotografia"},
    {"pc_note_photo_resolution","Nativa guarda os píxeis enquadrados. 4K volta a renderizar a cena com 3840 píxeis no lado maior."},
    {"pc_photo_resolution_native","Nativa"},
    {"pc_photo_resolution_4k","4K"},
    {"pc_photo_filter","Filtro de cor"},
    {"pc_note_photo_filter","Aplica-se apenas à pré-visualização e à fotografia guardada."},
    {"pc_photo_filter_bw","Preto e branco"},
    {"pc_photo_filter_warm","Quente"},
    {"pc_photo_filter_cool","Frio"},
    {"pc_photo_filter_muted","Suave"},
    {"pc_archive_model_hint","WASD / stick esquerdo: deslocar o enquadramento. Setas / stick direito: rodar. Gatilhos: zoom. Esc / Círculo: voltar."},
    {"pc_note_resolution_fullscreen","O modo sem margens usa o tamanho escolhido; o ecrã inteiro exclusivo usa um modo suportado."},
    {"op_sub_turkish","Turco"},
    {"op_sub_chinese","Chinês simplificado"},
    {"op_sub_arabic","Árabe"},
    {"op_sub_russian","Russo"},
    {"op_sub_ukrainian","Ucraniano"},
    {"op_sub_czech","Checo"},
    {"op_sub_polish","Polonês"},
    {"pc_loop_browser","Seleção de loop"},
    {"pc_note_loop_browser_entry","Comece qualquer loop sem substituir seu arquivo salvo."},
    {"pc_loop_choose","Escolha um loop"},
    {"pc_loop_preview","Prévia"},
    {"pc_loop_start_hint","Enter / X / A: iniciar loop"},
    {"pc_loop_f000","Sala inicial: a abertura"},
    {"pc_loop_f010","Loop 1: o rádio"},
    {"pc_loop_f005","Loop 2: a porta da entrada se abre"},
    {"pc_loop_f020","Loop 3: choro no banheiro"},
    {"pc_loop_f030","Loop 4: a porta do banheiro"},
    {"pc_loop_f040","Loop 5: Lisa no fim do corredor"},
    {"pc_loop_f060","Loop 6: o banheiro, a lanterna"},
    {"pc_loop_f050a","Loop 7: Lisa segue você"},
    {"pc_loop_f050b","Loop 8: a foto riscada"},
    {"pc_loop_f070","Loop 9: a janela se quebra"},
    {"pc_loop_f080","Loop 10: a geladeira que sangra"},
    {"pc_loop_f090","Loop 11: HELLO"},
    {"pc_loop_f100","Loop 12: o corredor vermelho"},
    {"pc_loop_f110","Loop 13: o labirinto e o olho mágico"},
    {"pc_loop_f120","Loop 14: 204863, a tela de erro"},
    {"pc_loop_f160","Loop 15: o último loop"},
    {"pc_loop_ending","Cena final e créditos"},
    {"pc_loop_street","Passeio pela rua (após o final)"},
    {"pc_note_loop_opening","Inicia a abertura na sala inicial, como um jogo novo. Seu arquivo salvo é mantido."},
    {"pc_note_loop_hallway","Começa na sala inicial logo antes deste loop, com os enigmas anteriores resolvidos. Atravesse a porta. Seu arquivo salvo é mantido; o salvamento volta no próximo checkpoint."},
    {"pc_note_loop_ending","Mostra a cena final e os créditos e depois oferece o passeio pela rua. Seu arquivo salvo é mantido."},
    {"pc_note_loop_street","Coloca você na rua do final, em primeira pessoa. Saia pelos Extras. Seu arquivo salvo é mantido."},
    {"pc_note_loop_locked","Bloqueado. Termine o jogo uma vez; então cada loop que você alcançou jogando é liberado."},
    {"pc_note_loop_browser_locked","Termine o jogo uma vez para liberar a seleção de loop."},
    {"pc_street_title","A rua"},
    {"pc_street_question","Explorar a rua?"},
    {"pc_street_walk","Sim, andar pela rua"},
    {"pc_credit_version","P.T. PC Port {1} por LoreanXavier"},
    {"pc_update_available","Versão {1} disponível (esta é a {2})"},
    {"pc_credits_by","por LoreanXavier"},
    {"pc_credits_dlss","Este jogo usa NVIDIA DLSS."},
    {"pc_credits_licenses","Os textos completos das licenças estão na pasta licenses, ao lado de pt.exe."},
    {"pc_credits_konami","P.T. pertence à Konami Digital Entertainment e à Kojima Productions."},
    {"pc_credits_fan","Esta versão é um projeto de fã não oficial, sem vínculo com Konami, NVIDIA, AMD ou Intel e sem o endosso delas."},
    {"pc_note_street_walk","Ande pela rua do final em primeira pessoa. Saia pelos Extras."},
    {"pc_street_restart","Não, voltar ao início"},
    {"pc_note_street_restart","Recomeça na sala inicial, como o original faz após os créditos."},
    {"pc_street_leave","Sair da rua"},
    {"pc_note_street_leave","Encerra o passeio e volta à sala inicial."},
    {"pc_street_return","Voltar para a casa"},
    {"pc_street_return_confirm","Voltar para a casa?"},
    {"pc_loop_lock","Bloquear a seleção de loop"},
    {"pc_note_loop_lock","Bloqueia de novo todos os loops, como antes do seu primeiro final. Seu arquivo salvo não muda."},
    {"pc_extras","Extras"},
    {"pc_vr","RV (experimental)"},
    {"pc_note_vr","Jogue com um headset de RV via OpenXR. Experimental: não testado em hardware real."},
    {"pc_vr_mode","Modo RV"},
    {"pc_note_vr_mode","Não testado em hardware real. Precisa de um runtime OpenXR e de um headset. Vale a partir da próxima abertura; sem headset, o jogo abre normalmente."},
    {"pc_vr_flashlight","Lanterna"},
    {"pc_note_vr_flashlight","A lanterna segue a sua cabeça, como no original, ou o controle na sua mão."},
    {"pc_vr_head","Cabeça"},
    {"pc_vr_controller","Controle"},
    {"pc_vr_turn","Giro"},
    {"pc_note_vr_turn","O analógico direito gira em passos ou de forma contínua. Os passos causam menos enjoo."},
    {"pc_vr_snap","Em passos"},
    {"pc_vr_smooth","Contínuo"},
    {"pc_note_extras","Seleção de loop, câmera livre e modo foto."},
    {"pc_freecam","Câmera livre"},
    {"pc_note_freecam","Solta a câmera do jogador (F6). Espaço / Ctrl ou os gatilhos: subir e descer, Shift ou L3: mais rápido. Esc: sair."},
    {"pc_photo_mode","Modo foto"},
    {"pc_note_photo_mode","Pausa o jogo para enquadrar com a câmera livre (F7). P ou Quadrado: salvar em Pictures/PT Photos, H ou Triângulo: ocultar o painel."},
    {"pc_speedrun","Cronômetro de speedrun"},
    {"pc_note_speedrun","Um cronômetro na tela com um parcial a cada loop e uma tela de resultados após os créditos. O tempo real conta tudo; o tempo de jogo deixa de fora pausas e carregamentos. Não existe no original."},
    {"pc_speedrun_real_time","Tempo real"},
    {"pc_speedrun_game_time","Tempo de jogo"},
    {"pc_livesplit","Servidor do LiveSplit"},
    {"pc_note_livesplit","Envia o início, os parciais e o tempo de jogo ao LiveSplit (Control > Start TCP Server, porta {1}). O host e a porta ficam no pt.ini."},
    {"pc_speedrun_results","PARTIDA CONCLUÍDA"},
    {"pc_speedrun_run","Partida"},
    {"pc_speedrun_splits","Parciais"},
    {"pc_speedrun_menu","Voltar ao menu"},
    {"pc_note_speedrun_menu","Recomeça do início como o original após o final, primeiro com a tela de opções. A próxima partida começa quando você retoma o controle."},
    {"pc_speedrun_outside","Explorar lá fora"},
    {"pc_note_speedrun_outside","Ande pela rua do final. Volte para a casa pelo menu de pausa."},
    {"pc_note_speedrun_real","Relógio real desde o controle até o final: pausas, carregamentos e cenas incluídos."},
    {"pc_note_speedrun_game","Só jogo sem pausa: o menu de pausa e os carregamentos após um game over ficam de fora."},
    {"pc_speedrun_best","Recorde pessoal"},
    {"pc_note_speedrun_best","Recorde anterior: {1}. Os recordes ficam em speedrun.ini, speedrun_history.txt e speedrun_pb.lss (LiveSplit) na pasta do usuário."},
    {"pc_speedrun_new_best","Novo recorde!"},
    {"pc_speedrun_partial","Não desde o início"},
    {"pc_speedrun_start_room","Sala inicial"},
    {"pc_speedrun_loop","Loop {1}"},
    {"pc_third_person","Terceira pessoa (experimental)"},
    {"pc_note_third_person","Experimental, não existe no original: a câmera acompanha o jogador por trás do ombro. O zoom e as cenas voltam à primeira pessoa; os eventos acontecem como em primeira pessoa."},
    {"pc_extras_start","Iniciar"},
    {"pc_photo_title","MODO FOTO"},
    {"pc_photo_section_camera","Câmera"},
    {"pc_photo_section_lens","Lente"},
    {"pc_photo_section_image","Imagem"},
    {"pc_photo_take","Tirar foto"},
    {"pc_photo_capture","Capturar"},
    {"pc_photo_fov","Campo de visão"},
    {"pc_photo_roll","Rotação da câmera"},
    {"pc_photo_speed","Velocidade da câmera"},
    {"pc_photo_speed_slow","Lenta"},
    {"pc_photo_speed_normal","Normal"},
    {"pc_photo_speed_fast","Rápida"},
    {"pc_photo_reset","Redefinir câmera"},
    {"pc_photo_focus","Distância de foco"},
    {"pc_photo_aperture","Abertura"},
    {"pc_photo_exposure","Exposição"},
    {"pc_photo_grading","Correção de cor"},
    {"pc_photo_letterbox","Faixas de cinema"},
    {"pc_photo_body","Corpo do jogador"},
    {"pc_photo_flashlight","Lanterna"},
    {"pc_photo_shown","Visível"},
    {"pc_photo_hidden","Oculto"},
    {"pc_photo_auto","Auto"},
    {"pc_photo_metres","{value} m"},
    {"pc_photo_saved","Salva em Pictures/PT Photos: {file}"},
    {"pc_photo_save_failed","Não foi possível guardar a fotografia. Consulte pt.log."},
    {"pc_photo_hint","Setas / botões direcionais: escolher e alterar. P / Quadrado: foto. H / Triângulo: ocultar painel. Botão direito do mouse: olhar. Esc / Círculo: sair."},
    {"pc_note_photo_take","Salva a visão atual em Pictures/PT Photos. O painel nunca aparece na foto."},
    {"pc_note_photo_fov","Campo de visão vertical em graus. Valores menores aproximam a imagem."},
    {"pc_note_photo_roll","Inclina a câmera para o lado, num ângulo holandês."},
    {"pc_note_photo_speed","Velocidade da câmera. Shift ou L3 continuam acelerando."},
    {"pc_note_photo_reset","Leva a câmera de volta para onde o modo foto começou."},
    {"pc_note_photo_dof","Desfoca o que está mais perto ou mais longe que a distância de foco."},
    {"pc_note_photo_focus","Auto foca o que está no centro do quadro."},
    {"pc_note_photo_aperture","Números f menores desfocam mais. Auto mantém a lente do jogo."},
    {"pc_note_photo_exposure","Clareia ou escurece a imagem em passos de meio ponto."},
    {"pc_note_photo_grain","A granulação original. Desativado deixa a imagem mais limpa."},
    {"pc_note_photo_grading","As cores originais. Desativado mostra cores neutras."},
    {"pc_note_photo_letterbox","Faixas pretas de cinema. Elas fazem parte da foto."},
    {"pc_note_photo_body","Mostra ou oculta o corpo do jogador."},
    {"pc_note_photo_flashlight","Apaga a luz da lanterna enquanto o modo foto está ativo."},
    {"pc_extras_stop","Parar"},
    {"pc_note_loop_generating","Gerando prévias... Seu arquivo salvo é mantido. O salvamento volta no próximo checkpoint: ao sair do porão ou ao chegar ao último loop."},
    {"pc_title","CONFIGURAÇÕES DO PC"},
    {"pc_entry","Configurações do PC"},
    {"pc_back","Voltar"},
    {"pc_quit","Sair"},
    {"pc_nav_columns","Tab / L1 / R1: trocar de coluna"},
    {"pc_quit_confirm","Sair?"},
    {"pc_save_no_space","Não há espaço livre suficiente para salvar o jogo.\nLibere espaço e feche esta mensagem para tentar de novo."},
    {"pc_ok","OK"},
    {"pc_note_quit","Sair do jogo."},
    {"pc_note_quit_confirm","Pressione {accept} de novo para sair. Voltar cancela."},
    {"pc_section_display","Tela"},
    {"pc_section_upscaling","Escalonamento"},
    {"pc_section_sound","Som"},
    {"pc_section_controls","Controles"},
    {"pc_section_progress","Progresso"},
    {"pc_section_ray_tracing","Ray tracing"},
    {"pc_section_textures","Texturas"},
    {"pc_display_mode","Modo de tela"},
    {"pc_resolution","Resolução"},
    {"pc_vsync","Sincronização vertical"},
    {"pc_focus_pause","Pausar em segundo plano"},
    {"pc_focus_mute","Sem som em segundo plano"},
    {"pc_upscaler","Método"},
    {"pc_quality","Modo"},
    {"pc_sharpness","Nitidez"},
    {"pc_frame_generation","Geração de quadros"},
    {"pc_volume","Volume"},
    {"pc_microphone","Microfone"},
    {"pc_microphone_enabled","Entrada do microfone"},
    {"pc_note_microphone_enabled","Ativa o microfone para o enigma de voz ou o teste do microfone. O acionador opcional continua a funcionar quando esta opção está desligada."},
    {"pc_mic_disabled","A entrada do microfone está desligada. Ative-a nas definições de som para usar o microfone ou o seu teste."},
    {"pc_mic_permission_pending","A aguardar permissão para o microfone. Escolha Permitir ou Não Permitir no aviso do macOS."},
    {"pc_mic_permission_denied","O acesso ao microfone está bloqueado. Ative P.T. nas Definições do Sistema > Privacidade e Segurança > Microfone, ou use o acionador opcional."},
    {"pc_mic_st_permission","Permissão necessária"},
    {"pc_microphone_test","Teste do microfone"},
    {"pc_mic_level","Nível de entrada"},
    {"pc_mic_heard","Palavras reconhecidas"},
    {"pc_mic_monitor","Ouvir minha voz"},
    {"pc_mic_no_word","Nenhuma ainda"},
    {"pc_mic_waiting","Aguardando o microfone selecionado..."},
    {"pc_mic_unavailable","Não foi possível abrir o microfone selecionado. Verifique as permissões de gravação e o dispositivo escolhido."},
    {"pc_mic_st_loading","Carregando..."},
    {"pc_mic_st_nomic","Sem microfone"},
    {"pc_mic_st_files","Arquivos de voz ausentes"},
    {"pc_mic_st_runtime","Mecanismo de voz falhou"},
    {"pc_mic_st_cpu","CPU não compatível"},
    {"pc_mic_st_model","Modelo de voz falhou"},
    {"pc_mic_st_silent","Sem som"},
    {"pc_mic_err_files","Os arquivos do reconhecimento de voz estão ausentes. Reinstale ou repare o jogo."},
    {"pc_mic_err_runtime","Não foi possível carregar o mecanismo de voz. A causa está em pt.log."},
    {"pc_mic_err_cpu","Este processador não consegue executar o mecanismo de voz."},
    {"pc_mic_err_model","Não foi possível carregar o modelo de voz. A causa está em pt.log."},
    {"pc_mic_err_silent","O microfone está aberto, mas não envia som. Verifique se não está silenciado e se o dispositivo certo está selecionado."},
    {"pc_mic_say_jack","Diga “Jack” no microfone selecionado. Este teste não faz o enigma avançar."},
    {"pc_mic_monitor_note","Você ouve o seu microfone. Use fones de ouvido para evitar microfonia. A escuta para quando você sai deste teste."},
    {"pc_mouse","Sensibilidade do mouse"},
    {"pc_gamepad_sensitivity","Sensibilidade de rotação do controle"},
    {"pc_camera_tilt","Inclinação da câmera"},
    {"pc_vibration","Vibração"},
    {"pc_dead_zone","Zona morta do analógico"},
    {"pc_reset","Reiniciar progresso"},
    {"pc_graphics","Gráficos"},
    {"pc_graphics_value","Abrir"},
    {"pc_rt_shadows","Sombras com ray tracing"},
    {"pc_rt_contact","Sombras de contato"},
    {"pc_shadows","Sombras"},
    {"pc_reflections","Reflexos"},
    {"pc_standard","Padrão"},
    {"pc_ray_traced","Ray tracing"},
    {"pc_rt_sharp_long","Ray tracing, nítidas"},
    {"pc_rt_soft_long","Ray tracing, suaves"},
    {"pc_note_shadows","De Baixo a Original são os mapas de sombra do original (512, 1024 ou 2048 px). O ray tracing os substitui: nítidas como no original ou suaves conforme o tamanho de cada luz."},
    {"pc_note_ao","Padrão é a oclusão em espaço de tela do original. O ray tracing escurece cantos e o espaço sob os objetos a partir da própria cena. Não existe no original."},
    {"pc_note_reflections","Padrão são os reflexos do piso em espaço de tela do original. O ray tracing também reflete o que está fora da tela. Experimental."},
    {"pc_rt_ao","Oclusão de ambiente"},
    {"pc_anisotropy","Filtragem anisotrópica"},
    {"pc_enhanced_textures","Texturas aprimoradas"},
    {"pc_texture_preparing","Preparando"},
    {"pc_note_texture_tools_missing","Faltam as ferramentas ou os arquivos de modelo das texturas aprimoradas. Restaure texture-tools a partir do pacote portátil e tente de novo. As texturas originais são mantidas."},
    {"pc_note_texture_busy","Outra instância do jogo está preparando este cache de texturas. Aguarde terminar e tente de novo. As texturas originais são mantidas."},
    {"pc_note_texture_failed","Falha ao preparar as texturas; as texturas originais são mantidas. Verifique o espaço livre e o pt.log e tente de novo."},
    {"pc_note_texture_preparing","Preparando texturas aprimoradas. Até lá aparecem as originais; depois elas mudam sem reiniciar. Desativado cancela."},
    {"pc_note_enhanced_textures","Gera uma vez texturas de cor mais nítidas a partir dos arquivos do jogo. Inclui paredes e personagens; 4096 px com 10 GB de memória de vídeo, senão 2048. Desativado cancela; as texturas originais continuam disponíveis."},
    {"pc_rt_sharp","Nítidas"},
    {"pc_rt_soft","Suaves"},
    {"pc_on","Ativado"},
    {"pc_off","Desativado"},
    {"pc_window","Janela"},
    {"pc_borderless","Sem bordas"},
    {"pc_fullscreen","Tela cheia"},
    {"pc_native","Nativa"},
    {"pc_quality_quality","Qualidade"},
    {"pc_quality_balanced","Equilibrado"},
    {"pc_quality_performance","Desempenho"},
    {"pc_quality_ultra","Ultradesempenho"},
    {"pc_quality_custom","Personalizado"},
    {"pc_system_default","Padrão do sistema"},
    {"pc_reset_value","Reiniciar"},
    {"pc_reset_confirm","Confirmar"},
    {"pc_reset_done","Pronto"},
    {"pc_note_vsync","Vale na hora. Sincroniza a imagem com a taxa de atualização do monitor."},
    {"pc_note_vsync_off","Aplica-se de imediato. Desligada, cada quadro aparece assim que fica pronto: a taxa não fica presa à frequência do monitor e a imagem pode rasgar."},
    {"pc_note_restart","Vale a partir da próxima inicialização."},
    {"pc_note_display_mode","Alt+Enter também alterna entre janela e tela cheia."},
    {"pc_note_resolution","Tamanho da janela."},
    {"pc_note_resolution_fullscreen","A tela cheia usa a resolução da área de trabalho."},
    {"pc_note_upscaler_off","Desativado renderiza na resolução da tela, como o original."},
    {"pc_note_render_size","Renderizado em {1}, exibido em {2}."},
    {"pc_note_needs_upscaler","Requer um método de escalonamento."},
    {"pc_note_sharpness_fsr","Só o FSR tem nitidez própria. Nitidez da imagem, em Gráficos, funciona com qualquer método."},
    {"pc_note_reset","Reinicia o progresso e recomeça o jogo agora. O idioma e as configurações do PC são mantidos."},
    {"pc_note_reset_confirm","Pressione {accept} de novo para excluir o arquivo salvo."},
    {"pc_note_reset_done","Progresso reiniciado nesta sessão."},
    {"pc_note_camera_tilt","A câmera se inclina com a cabeça, como no original."},
    {"pc_note_voice","O microfone só escuta onde o jogo original escuta."},
    {"pc_note_focus_pause","Abre este menu quando a janela vai para segundo plano."},
    {"pc_note_focus_mute","Silencia o jogo enquanto a janela está em segundo plano."},
    {"pc_note_frame_generation_missing","Não incluído nesta versão."},
    {"pc_note_frame_generation","AMD FSR 3 mostra um quadro gerado entre dois quadros renderizados."},
    {"pc_note_fsr4_vulkan","A AMD publica o FSR 4 apenas para DirectX 12; este jogo usa Vulkan, então o FSR 4 não pode funcionar aqui."},
    {"pc_dlss_model","Modelo DLSS"},
    {"pc_dlss_model_auto","Automático"},
    {"pc_note_dlss_model","Automático segue a escolha da NVIDIA: K até Equilibrado, M em Desempenho, L em Ultradesempenho. L e M custam cerca do dobro em RTX 20 e 30."},
    {"pc_note_frame_generation_dlss","Experimental. O NVIDIA DLSS Frame Generation mostra um quadro gerado entre dois quadros renderizados. Vale a partir da próxima inicialização."},
    {"pc_note_dlssg_gpu","O DLSS Frame Generation requer uma NVIDIA GeForce RTX série 40 ou mais recente."},
    {"pc_note_fsr_fg_gpu","A geração de quadros FSR 3 requer uma AMD Radeon RX série 5000 ou mais recente."},
    {"pc_note_dlssg_driver","O DLSS Frame Generation requer um driver NVIDIA mais recente."},
    {"pc_note_dlssg_hags","O DLSS Frame Generation requer o agendamento de GPU acelerado por hardware (configurações de gráficos do Windows)."},
    {"pc_note_dlssg_missing","O DLSS Frame Generation não está incluído nesta versão."},
    {"pc_note_dlssg_failed","O DLSS Frame Generation não conseguiu iniciar e foi desativado."},
    {"pc_note_dlssg_restart","Reinicie o jogo para iniciar o DLSS Frame Generation."},
    {"pc_note_vsync_dlssg","O DLSS Frame Generation funciona sem V-Sync no Vulkan; a configuração volta a valer quando a geração de quadros está desligada."},
    {"pc_note_fsr_fg_restart","Reinicie o jogo para trocar o DLSS Frame Generation pelo FSR 3."},
    {"pc_note_dead_zone","0.10 é o valor do DualShock 4."},
    {"pc_note_gamepad_sensitivity","Ajusta a velocidade de rotação após a resposta original do analógico. 1 mantém a resposta original."},
    {"pc_note_rt_shadows","Sombras calculadas com ray tracing em vez de mapas de sombra, tão nítidas quanto as do original. Não existe no original."},
    {"pc_note_rt_soft","Sombras com ray tracing e bordas suaves conforme o tamanho de cada luz. Não existe no original."},
    {"pc_note_rt_unsupported","Requer uma GPU com ray tracing Vulkan."},
    {"pc_note_graphics","Escolha uma predefinição ou ajuste iluminação, texturas e efeitos de imagem. Resolução e escalonamento ficam à parte."},
    {"pc_note_rt_contact","Os objetos projetam sombras curtas com ray tracing de cada luz, inclusive das que não projetam sombra no original."},
    {"pc_note_rt_ao","O sombreamento com ray tracing escurece cantos e o espaço sob e atrás dos objetos. Não existe no original."},
    {"pc_rt_reflections","Reflexos"},
    {"pc_note_rt_reflections","O piso reflete a cena além das bordas da tela. Experimental; a aparência pode diferir do original."},
    {"pc_note_anisotropy","Pisos e paredes mais nítidos vistos de lado. Desativado usa a filtragem original."},
    {"pc_graphics_quality","Qualidade"},
    {"pc_graphics_preset","Predefinição"},
    {"pc_preset_low","Baixo"},
    {"pc_preset_medium","Médio"},
    {"pc_preset_original","Original (PS4)"},
    {"pc_preset_high","Alto"},
    {"pc_preset_ultra","Ultra"},
    {"pc_preset_custom","Personalizado"},
    {"pc_ray_tracing","Ray tracing"},
    {"pc_clarity","Nitidez da imagem"},
    {"pc_graphics_advanced","Avançado"},
    {"pc_graphics_lighting","Iluminação"},
    {"pc_graphics_effects","Efeitos de imagem"},
    {"pc_graphics_image","Imagem"},
    {"pc_lighting_standard","Iluminação padrão"},
    {"pc_shadow_quality","Mapas de sombra"},
    {"pc_standard_ao","Oclusão de ambiente"},
    {"pc_standard_reflections","Reflexos em tela"},
    {"pc_ray_quality","Qualidade dos raios"},
    {"pc_ray_balanced","Equilibrado"},
    {"pc_texture_detail","Detalhe das texturas"},
    {"pc_detail_reduced","Reduzido"},
    {"pc_detail_fine","Fino"},
    {"pc_dof","Profundidade de campo"},
    {"pc_motion_blur","Desfoque de movimento"},
    {"pc_bloom","Bloom"},
    {"pc_lens_ghosts","Reflexos do lens flare"},
    {"pc_note_lens_ghosts","Os grandes reflexos do lens flare por toda a tela ao olhar perto de uma lâmpada, como no original (PS4). Desativado os remove."},
    {"pc_film_grain","Granulação"},
    {"pc_note_preset","Muda só os gráficos; mantém resolução e escalonamento. Ajustes manuais mostram Personalizado. Ultra usa ray tracing quando houver suporte."},
    {"pc_note_ray_master","Liga ou desliga juntos sombras com ray tracing, sombras de contato, oclusão de ambiente e reflexos. Cada um separado fica em Iluminação."},
    {"pc_lens_distortion","Efeito de lente"},
    {"pc_note_lens_distortion","A curvatura da lente e as franjas de cor originais. Desativado deixa as bordas mais nítidas e a imagem mais ampla."},
    {"pc_note_clarity","Acrescenta uma nitidez moderada de contraste local na resolução de saída. Zero mantém a imagem original."},
    {"pc_note_letterbox","Faixas pretas acima e abaixo da imagem, no jogo e nas cenas. As legendas ficam dentro da imagem. Não existe no original."},
    {"pc_note_advanced","Ajuste esta categoria. Voltar retorna a Gráficos; mudanças mostram Personalizado."},
    {"pc_note_shadow_quality","Mapas de sombra de 512, 1024 ou 2048 px (original). As sombras com ray tracing os substituem quando ativas. A escala de resolução não muda."},
    {"pc_note_standard_ao","A oclusão de ambiente original em espaço de tela. Desligue para aliviar GPUs mais lentas."},
    {"pc_note_standard_reflections","Os reflexos do piso originais em espaço de tela. Os reflexos com ray tracing os substituem quando ativos."},
    {"pc_note_ray_quality","Equilibrado: 2 raios. Alto: 4 raios. Ultra: 8 raios, para sombras mais suaves e menos ruído na oclusão com ray tracing."},
    {"pc_note_texture_detail","Reduzido usa mipmaps mais grosseiros. Fino mantém mais detalhes à distância; pode cintilar. A resolução de saída não muda."},
    {"pc_note_dof","O desfoque de foco original da câmera. Desativado mantém nítidos as superfícies próximas e o fundo."},
    {"pc_note_motion_blur","O desfoque original ao virar e se mover. Desativado deixa a imagem em movimento mais clara."},
    {"pc_note_bloom","O brilho original das luzes. Desativado reduz o brilho e o custo do pós-processamento."},
    {"pc_note_film_grain","A intensidade da granulação original. Desativado deixa a imagem mais limpa; 100% mantém o efeito original."},
    {"pc_mods","Mods"},
    {"pc_section_mods","Mods instalados"},
    {"pc_note_mods","Ligar ou desligar um mod vale a partir da próxima inicialização. Os mods não fazem parte do jogo original."},
    {"pc_archive","Museu"},
    {"pc_note_archive","As imagens, vozes, pedaços de foto, cenas e modelos do próprio jogo, conforme você os alcança jogando. Seu jogo não é alterado."},
    {"pc_note_extras_archive","Seleção de loop, museu, câmera livre e modo foto."},
    {"pc_archive_sections","Salas"},
    {"pc_archive_images","Imagens subliminares"},
    {"pc_archive_voices","Vozes e rádio"},
    {"pc_archive_photos","Pedaços de foto"},
    {"pc_archive_cutscenes","Cenas"},
    {"pc_archive_models","Modelos"},
    {"pc_archive_unused","Conteúdo não usado"},
    {"pc_note_archive_images","Os textos dos lampejos subliminares, o ruído dos lampejos e a vista pelo olho mágico."},
    {"pc_note_archive_voices","As transmissões de rádio e cada fala, com a transcrição no seu idioma de legendas."},
    {"pc_note_archive_photos","Os pedaços rasgados da fotografia, e a foto que eles formam na moldura."},
    {"pc_note_archive_cutscenes","Cada cena desde o início, com som e legendas."},
    {"pc_note_archive_models","Lisa e as outras figuras e objetos do corredor, sob a luz do quarto inicial."},
    {"pc_note_archive_unused_section","Conteúdo nos arquivos do jogo que o jogo nunca mostra. É liberado quando você termina o jogo."},
    {"pc_note_archive_image","Enter / Xis: ver em tela cheia."},
    {"pc_note_archive_voice","Enter / Xis: tocar ou parar."},
    {"pc_note_archive_photo","Enter / Xis: ver em tela cheia."},
    {"pc_note_archive_demo","Enter / Xis: tocar desde o início. Esc / Círculo para."},
    {"pc_note_archive_model","Enter / Xis: ver o modelo. Esc / Círculo: voltar."},
    {"pc_note_archive_unused","Nunca mostrado no jogo. Enter / Xis: ver o modelo."},
    {"pc_note_archive_locked","Bloqueado. Alcance-o jogando para liberá-lo."},
    {"pc_note_archive_playing","Tocando. Enter / Xis para."},
    {"pc_archive_lock","Bloquear o museu"},
    {"pc_note_archive_lock","Bloqueia de novo cada peça do museu, como antes de jogar. Seu salvamento não é alterado."},
    {"pc_archive_hint","Enter / X / A: abrir"},
    {"pc_archive_view_hint","Esquerda / Direita: anterior / próximo. Esc / Círculo: voltar."},
    {"pc_archive_demo_hint","Esc / Círculo / Enter / Xis: parar"},
    {"pc_archive_model_hint","Setas / analógicos: girar. W / S / gatilhos: mais perto / mais longe. Esc / Círculo: voltar."},
    {"pc_archive_sub","Texto subliminar {1}"},
    {"pc_archive_noise","Ruído"},
    {"pc_archive_noise_normal","Distorção do ruído"},
    {"pc_archive_peephole_mask","A vista pelo olho mágico"},
    {"pc_archive_radio_news","Rádio: o noticiário"},
    {"pc_archive_radio_news2","Rádio: o noticiário de novo"},
    {"pc_archive_radio_voice","Voz do rádio {1}"},
    {"pc_archive_riddle","Charada do rádio {1}"},
    {"pc_archive_sermon","Rádio: o sermão"},
    {"pc_archive_phone","O telefonema"},
    {"pc_archive_peephole_voice","Pelo olho mágico"},
    {"pc_archive_bag","O saco que fala"},
    {"pc_archive_fetus","O feto fala {1}"},
    {"pc_archive_photo_lisa","Pedaço: Lisa"},
    {"pc_archive_photo_tree","Pedaço: a árvore"},
    {"pc_archive_photo_gap","Pedaço: a fresta"},
    {"pc_archive_photo_bath","Pedaço: o banheiro"},
    {"pc_archive_photo_stair","Pedaço: a escada"},
    {"pc_archive_photo_option","Pedaço: a tela de opções"},
    {"pc_archive_photo_complete","A foto completa"},
    {"pc_archive_preface","O prefácio"},
    {"pc_archive_awakening","O primeiro despertar"},
    {"pc_archive_opening","O despertar"},
    {"pc_archive_first_exit","A primeira porta"},
    {"pc_archive_door","Pela porta"},
    {"pc_archive_clock","Meia-noite"},
    {"pc_archive_kill","Pego por Lisa"},
    {"pc_archive_ending","O final"},
    {"pc_archive_teaser","O teaser"},
    {"pc_archive_lisa_stand","Lisa, parada"},
    {"pc_archive_lisa_walk","Lisa, andando"},
    {"pc_archive_lisa_dash","Lisa, avançando"},
    {"pc_archive_lisa_door","Lisa atrás da porta"},
    {"pc_archive_baby","O feto na pia"},
    {"pc_archive_fridge","A geladeira"},
    {"pc_archive_bag_model","O saco de papel"},
    {"pc_archive_lamp","A luminária do teto"},
    {"pc_archive_roach","Barata"},
    {"pc_archive_flashlight","A lanterna"},
    {"pc_archive_radio","O rádio"},
    {"pc_archive_phone_model","O telefone"},
    {"pc_archive_xmark_photo","A foto do X"},
    {"pc_archive_clock_model","O relógio"},
    {"pc_archive_man","O homem"},
    {"pc_archive_bathtub","O corpo na banheira"},
};
inline std::string_view Menu(std::string_view key) {
    for (const auto& e : kMenu) if (e.key == key) return e.text;
    return {};
}
}
