#pragma once
#include <string_view>

// Spanish (Latin American, as the game's own) for the port's own menus (PC settings, extras, photo mode, loop browser, notes and prompts) and the added
// languages' names on the option screen. The options screen's other texts and the subtitles are the game's own.
namespace pt::spanish {
struct Text { std::string_view key, text; };
inline constexpr Text kMenu[] = {
    {"pc_controller_speaker","Altavoz del mando"},
    {"pc_note_controller_speaker","Reproduce los gritos grabados de Lisa por los altavoces compatibles de mandos Sony. En Windows se requiere USB; los dispositivos no compatibles y Bluetooth permanecen en silencio. Es independiente de la respuesta háptica y está desactivado de forma predeterminada."},
    {"pc_controller_speaker_volume","Volumen del altavoz del mando"},
    {"pc_note_controller_speaker_volume","Ajusta solo el volumen del altavoz del mando en pasos del 5 %. No cambia el audio del juego ni la fuerza háptica de DualSense. Solo está disponible con mandos Sony compatibles conectados por cable en Windows."},
    {"pc_microphone_trigger_assign","Asignar {input} al activador del micrófono"},
    {"pc_note_microphone_trigger","Alternativa opcional al micrófono. El teclado y ambos gatillos del mando la activan solo cuando el juego está escuchando."},
    {"pc_note_microphone_test","Prueba el micrófono y el resultado del reconocimiento."},
    {"pc_fps_limit","Límite de fotogramas"},
    {"pc_unlimited","Sin límite"},
    {"pc_note_fps_limit","Limita los fotogramas renderizados. Los menús siguen limitados a 60 FPS. La sincronización vertical puede imponer un límite menor."},
    {"pc_hdr","HDR nativo"},
    {"pc_note_hdr_restart","Se aplica al reiniciar. Requiere HDR activado en una pantalla compatible; de lo contrario, se usa SDR."},
    {"pc_surround","Salida envolvente"},
    {"pc_note_surround","Tras reiniciar, usa la configuración 5.1 o 7.1 del dispositivo de salida. Los dispositivos estéreo siguen en estéreo."},
    {"pc_rumble_profile","Modo de vibración"},
    {"pc_rumble_original","Original"},
    {"pc_rumble_enhanced","Mejorado"},
    {"pc_note_rumble_profile","Original usa solo la vibración de motor prevista por el juego. Mejorado añade vibración en gatillos compatibles y, en mandos DualSense USB compatibles con Windows, háptica basada en los gritos filtrados de Lisa. El ajuste principal de vibración desactiva ambas. El audio del altavoz del mando es independiente."},
    {"pc_vr_height","Ajuste de altura"},
    {"pc_note_vr_height","Mueve el punto de vista seguido hacia arriba o abajo sin cambiar la posición del jugador en el juego."},
    {"pc_vr_world_scale","Escala del mundo"},
    {"pc_note_vr_world_scale","Ajusta el movimiento registrado de la cabeza, los ojos y los mandos entre el 50 % y el 200 %. Cuanto mayor sea el valor, más pequeño parecerá el mundo. Predeterminado: 100 %."},
    {"pc_photo_focal_length","Longitud focal"},
    {"pc_note_photo_focal_length","Longitud focal del objetivo en milímetros. El desenfoque de enfoque usa el mismo objetivo y sensor que la cámara."},
    {"pc_photo_aspect","Relación de aspecto"},
    {"pc_note_photo_aspect","Recorta la foto desde el centro."},
    {"pc_photo_resolution","Resolución de foto"},
    {"pc_note_photo_resolution","Nativa guarda los píxeles encuadrados. 4K vuelve a renderizar la escena con 3840 píxeles en el lado largo."},
    {"pc_photo_resolution_native","Nativa"},
    {"pc_photo_resolution_4k","4K"},
    {"pc_photo_filter","Filtro de color"},
    {"pc_note_photo_filter","Solo afecta a la vista de foto y a la foto guardada."},
    {"pc_photo_filter_bw","Blanco y negro"},
    {"pc_photo_filter_warm","Cálido"},
    {"pc_photo_filter_cool","Frío"},
    {"pc_photo_filter_muted","Desaturado"},
    {"pc_archive_model_hint","WASD / stick izquierdo: desplazar el encuadre. Flechas / stick derecho: girar. Gatillos: zoom. Esc / Círculo: volver."},
    {"pc_note_resolution_fullscreen","El modo sin bordes usa el tamaño elegido; la pantalla completa exclusiva usa un tamaño de pantalla compatible."},
    {"op_sub_turkish","Turco"},
    {"op_sub_chinese","Chino simplificado"},
    {"op_sub_arabic","Árabe"},
    {"op_sub_russian","Ruso"},
    {"op_sub_ukrainian","Ucraniano"},
    {"op_sub_czech","Checo"},
    {"op_sub_polish","Polaco"},
    {"pc_loop_browser","Selector de bucles"},
    {"pc_note_loop_browser_entry","Inicia cualquier bucle sin reemplazar tu partida guardada."},
    {"pc_loop_choose","Elige un bucle"},
    {"pc_loop_preview","Vista previa"},
    {"pc_loop_start_hint","Enter / X / A: iniciar bucle"},
    {"pc_loop_f000","Cuarto de inicio: la apertura"},
    {"pc_loop_f010","Bucle 1: la radio"},
    {"pc_loop_f005","Bucle 2: se abre la puerta del recibidor"},
    {"pc_loop_f020","Bucle 3: llanto en el baño"},
    {"pc_loop_f030","Bucle 4: la puerta del baño"},
    {"pc_loop_f040","Bucle 5: Lisa al fondo del pasillo"},
    {"pc_loop_f060","Bucle 6: el baño, la linterna"},
    {"pc_loop_f050a","Bucle 7: Lisa te sigue"},
    {"pc_loop_f050b","Bucle 8: la foto tachada"},
    {"pc_loop_f070","Bucle 9: se rompe la ventana"},
    {"pc_loop_f080","Bucle 10: el refrigerador que sangra"},
    {"pc_loop_f090","Bucle 11: HELLO"},
    {"pc_loop_f100","Bucle 12: el pasillo rojo"},
    {"pc_loop_f110","Bucle 13: el laberinto y la mirilla"},
    {"pc_loop_f120","Bucle 14: 204863, la pantalla de error"},
    {"pc_loop_f160","Bucle 15: el último bucle"},
    {"pc_loop_ending","Cinemática final y créditos"},
    {"pc_loop_street","Paseo por la calle (tras el final)"},
    {"pc_note_loop_opening","Inicia la apertura en el cuarto de inicio, como una partida nueva. Tu partida guardada se conserva."},
    {"pc_note_loop_hallway","Empieza en el cuarto de inicio justo antes de este bucle, con los acertijos anteriores resueltos. Cruza la puerta. Tu partida guardada se conserva; el guardado se reanuda en el siguiente punto de control."},
    {"pc_note_loop_ending","Reproduce la cinemática final y los créditos, y luego ofrece el paseo por la calle. Tu partida guardada se conserva."},
    {"pc_note_loop_street","Te pone en la calle del final, en primera persona. Sal desde Extras. Tu partida guardada se conserva."},
    {"pc_note_loop_locked","Bloqueado. Termina el juego una vez; luego se abre cada bucle al que llegaste jugando."},
    {"pc_note_loop_browser_locked","Termina el juego una vez para desbloquear el selector de bucles."},
    {"pc_street_title","La calle"},
    {"pc_street_question","¿Explorar la calle?"},
    {"pc_street_walk","Sí, recorrer la calle"},
    {"pc_credit_version","P.T. PC Port {1} por LoreanXavier"},
    {"pc_update_available","Versión {1} disponible (esta es la {2})"},
    {"pc_credits_by","por LoreanXavier"},
    {"pc_credits_dlss","Este juego usa NVIDIA DLSS."},
    {"pc_credits_licenses","Los textos completos de las licencias están en la carpeta licenses, junto a pt.exe."},
    {"pc_credits_konami","P.T. pertenece a Konami Digital Entertainment y Kojima Productions."},
    {"pc_credits_fan","Esta versión es un proyecto no oficial de fans, sin relación con Konami, NVIDIA, AMD ni Intel y sin su respaldo."},
    {"pc_note_street_walk","Recorre en primera persona la calle del final. Sal desde Extras."},
    {"pc_street_restart","No, volver al inicio"},
    {"pc_note_street_restart","Reinicia en el cuarto de inicio, como el original tras los créditos."},
    {"pc_street_leave","Salir de la calle"},
    {"pc_note_street_leave","Termina el paseo y vuelve al cuarto de inicio."},
    {"pc_street_return","Volver a la casa"},
    {"pc_street_return_confirm","¿Volver a la casa?"},
    {"pc_loop_lock","Bloquear el selector de bucles"},
    {"pc_note_loop_lock","Vuelve a bloquear todos los bucles, como antes de tu primer final. Tu partida guardada no cambia."},
    {"pc_extras","Extras"},
    {"pc_vr","RV (experimental)"},
    {"pc_note_vr","Juega con un visor de RV mediante OpenXR. Experimental: no probado en hardware real."},
    {"pc_vr_mode","Modo RV"},
    {"pc_note_vr_mode","No probado en hardware real. Necesita un runtime de OpenXR y un visor. Se aplica en el próximo inicio; sin visor, el juego arranca como siempre."},
    {"pc_vr_flashlight","Linterna"},
    {"pc_note_vr_flashlight","La linterna sigue tu cabeza, como en el original, o el mando que tienes en la mano."},
    {"pc_vr_head","Cabeza"},
    {"pc_vr_controller","Mando"},
    {"pc_vr_turn","Giro"},
    {"pc_note_vr_turn","El stick derecho gira por pasos o de forma continua. Los pasos marean menos."},
    {"pc_vr_snap","Por pasos"},
    {"pc_vr_smooth","Continuo"},
    {"pc_note_extras","Selector de bucles, cámara libre y modo foto."},
    {"pc_freecam","Cámara libre"},
    {"pc_note_freecam","Separa la cámara del jugador (F6). Espacio / Ctrl o los gatillos: subir y bajar, Shift o L3: más rápido. Esc: salir."},
    {"pc_photo_mode","Modo foto"},
    {"pc_note_photo_mode","Pausa el juego para encuadrar con la cámara libre (F7). P o Cuadrado: guardar en Pictures/PT Photos, H o Triángulo: ocultar el panel."},
    {"pc_speedrun","Cronómetro de speedrun"},
    {"pc_note_speedrun","Un cronómetro en pantalla con un parcial en cada bucle y una pantalla de resultados tras los créditos. El tiempo real lo cuenta todo; el tiempo de juego deja fuera pausas y cargas. No está en el original."},
    {"pc_speedrun_real_time","Tiempo real"},
    {"pc_speedrun_game_time","Tiempo de juego"},
    {"pc_livesplit","Servidor de LiveSplit"},
    {"pc_note_livesplit","Envía el inicio, los parciales y el tiempo de juego a LiveSplit (Control > Start TCP Server, puerto {1}). El host y el puerto están en pt.ini."},
    {"pc_speedrun_results","PARTIDA COMPLETADA"},
    {"pc_speedrun_run","Partida"},
    {"pc_speedrun_splits","Parciales"},
    {"pc_speedrun_menu","Volver al menú"},
    {"pc_note_speedrun_menu","Reinicia desde el principio como el original tras el final, primero con la pantalla de opciones. La siguiente partida empieza cuando recuperas el control."},
    {"pc_speedrun_outside","Explorar fuera"},
    {"pc_note_speedrun_outside","Recorre la calle del final. Vuelve a la casa desde el menú de pausa."},
    {"pc_note_speedrun_real","Reloj real desde que tomas el control hasta el final: pausas, cargas y escenas incluidas."},
    {"pc_note_speedrun_game","Solo juego sin pausa: el menú de pausa y las cargas tras un game over quedan fuera."},
    {"pc_speedrun_best","Mejor marca"},
    {"pc_note_speedrun_best","Mejor marca anterior: {1}. Los récords están en speedrun.ini, speedrun_history.txt y speedrun_pb.lss (LiveSplit) en la carpeta del usuario."},
    {"pc_speedrun_new_best","¡Nueva marca!"},
    {"pc_speedrun_partial","No desde el inicio"},
    {"pc_speedrun_start_room","Cuarto de inicio"},
    {"pc_speedrun_loop","Bucle {1}"},
    {"pc_third_person","Tercera persona (experimental)"},
    {"pc_note_third_person","Experimental, no está en el original: la cámara sigue al jugador por encima del hombro. El zoom y las cinemáticas vuelven a primera persona; los sucesos ocurren igual que en primera persona."},
    {"pc_extras_start","Iniciar"},
    {"pc_photo_title","MODO FOTO"},
    {"pc_photo_section_camera","Cámara"},
    {"pc_photo_section_lens","Lente"},
    {"pc_photo_section_image","Imagen"},
    {"pc_photo_take","Tomar foto"},
    {"pc_photo_capture","Capturar"},
    {"pc_photo_fov","Campo de visión"},
    {"pc_photo_roll","Giro de cámara"},
    {"pc_photo_speed","Velocidad de cámara"},
    {"pc_photo_speed_slow","Lenta"},
    {"pc_photo_speed_normal","Normal"},
    {"pc_photo_speed_fast","Rápida"},
    {"pc_photo_reset","Restablecer cámara"},
    {"pc_photo_focus","Distancia de enfoque"},
    {"pc_photo_aperture","Apertura"},
    {"pc_photo_exposure","Exposición"},
    {"pc_photo_grading","Corrección de color"},
    {"pc_photo_letterbox","Barras de cine"},
    {"pc_photo_body","Cuerpo del jugador"},
    {"pc_photo_flashlight","Linterna"},
    {"pc_photo_shown","Visible"},
    {"pc_photo_hidden","Oculto"},
    {"pc_photo_auto","Auto"},
    {"pc_photo_metres","{value} m"},
    {"pc_photo_saved","Guardada en Pictures/PT Photos: {file}"},
    {"pc_photo_save_failed","No se pudo guardar la foto. Consulta pt.log."},
    {"pc_photo_hint","Flechas / botones de dirección: elegir y cambiar. P / Cuadrado: foto. H / Triángulo: ocultar panel. Botón derecho del mouse: mirar. Esc / Círculo: salir."},
    {"pc_note_photo_take","Guarda la vista actual en Pictures/PT Photos. El panel nunca aparece en la foto."},
    {"pc_note_photo_fov","Campo de visión vertical en grados. Los valores bajos acercan la imagen."},
    {"pc_note_photo_roll","Inclina la cámara hacia un lado para un plano holandés."},
    {"pc_note_photo_speed","Qué tan rápido se mueve la cámara. Shift o L3 siguen acelerando."},
    {"pc_note_photo_reset","Devuelve la cámara al lugar donde empezó el modo foto."},
    {"pc_note_photo_dof","Desenfoca lo que está más cerca o más lejos que la distancia de enfoque."},
    {"pc_note_photo_focus","Auto enfoca lo que está en el centro del encuadre."},
    {"pc_note_photo_aperture","Los números f bajos desenfocan más. Auto conserva la lente del juego."},
    {"pc_note_photo_exposure","Aclara u oscurece la imagen en pasos de medio punto."},
    {"pc_note_photo_grain","El grano de película original. Desactivado da una imagen más limpia."},
    {"pc_note_photo_grading","El color original. Desactivado muestra colores neutros."},
    {"pc_note_photo_letterbox","Barras negras de cine. Forman parte de la foto."},
    {"pc_note_photo_body","Muestra u oculta el cuerpo del jugador."},
    {"pc_note_photo_flashlight","Apaga la luz de la linterna mientras dura el modo foto."},
    {"pc_extras_stop","Detener"},
    {"pc_note_loop_generating","Creando vistas previas... Tu partida guardada se conserva. El guardado se reanuda en el siguiente punto de control: al salir del sótano o al llegar al último bucle."},
    {"pc_title","CONFIGURACIÓN DE PC"},
    {"pc_entry","Configuración de PC"},
    {"pc_back","Regresar"},
    {"pc_quit","Salir"},
    {"pc_nav_columns","Tab / L1 / R1: cambiar de columna"},
    {"pc_quit_confirm","¿Salir?"},
    {"pc_save_no_space","No hay suficiente espacio libre para guardar el juego.\nLibera espacio y cierra este mensaje para intentarlo de nuevo."},
    {"pc_ok","Aceptar"},
    {"pc_note_quit","Salir del juego."},
    {"pc_note_quit_confirm","Presiona {accept} otra vez para salir. Regresar cancela."},
    {"pc_section_display","Pantalla"},
    {"pc_section_upscaling","Escalado"},
    {"pc_section_sound","Sonido"},
    {"pc_section_controls","Controles"},
    {"pc_section_progress","Progreso"},
    {"pc_section_ray_tracing","Trazado de rayos"},
    {"pc_section_textures","Texturas"},
    {"pc_display_mode","Modo de pantalla"},
    {"pc_resolution","Resolución"},
    {"pc_vsync","Sincronización vertical"},
    {"pc_focus_pause","Pausa en segundo plano"},
    {"pc_focus_mute","Silencio en segundo plano"},
    {"pc_upscaler","Método"},
    {"pc_quality","Modo"},
    {"pc_sharpness","Nitidez"},
    {"pc_frame_generation","Generación de fotogramas"},
    {"pc_volume","Volumen"},
    {"pc_microphone","Micrófono"},
    {"pc_microphone_test","Prueba de micrófono"},
    {"pc_mic_level","Nivel de entrada"},
    {"pc_mic_heard","Palabras reconocidas"},
    {"pc_mic_monitor","Escuchar mi voz"},
    {"pc_mic_no_word","Ninguna aún"},
    {"pc_mic_waiting","Esperando el micrófono seleccionado..."},
    {"pc_mic_unavailable","No se pudo abrir el micrófono seleccionado. Revisa los permisos de grabación y el dispositivo elegido."},
    {"pc_mic_st_loading","Cargando..."},
    {"pc_mic_st_nomic","Sin micrófono"},
    {"pc_mic_st_files","Faltan archivos de voz"},
    {"pc_mic_st_runtime","Motor de voz fallido"},
    {"pc_mic_st_cpu","CPU no compatible"},
    {"pc_mic_st_model","Modelo de voz fallido"},
    {"pc_mic_st_silent","Sin sonido"},
    {"pc_mic_err_files","Faltan los archivos del reconocimiento de voz. Reinstala o repara el juego."},
    {"pc_mic_err_runtime","No se pudo cargar el motor de voz. La causa está en pt.log."},
    {"pc_mic_err_cpu","Este procesador no puede ejecutar el motor de voz."},
    {"pc_mic_err_model","No se pudo cargar el modelo de voz. La causa está en pt.log."},
    {"pc_mic_err_silent","El micrófono está abierto pero no envía sonido. Comprueba que no esté silenciado y que el dispositivo elegido sea el correcto."},
    {"pc_mic_say_jack","Di «Jack» al micrófono seleccionado. Esta prueba no hace avanzar el acertijo."},
    {"pc_mic_monitor_note","Escuchas tu micrófono. Usa audífonos para evitar el acople. La escucha termina al salir de esta prueba."},
    {"pc_mouse","Sensibilidad del mouse"},
    {"pc_gamepad_sensitivity","Sensibilidad de giro del mando"},
    {"pc_camera_tilt","Inclinación de cámara"},
    {"pc_vibration","Vibración"},
    {"pc_dead_zone","Zona muerta del stick"},
    {"pc_reset","Reiniciar progreso"},
    {"pc_graphics","Gráficos"},
    {"pc_graphics_value","Abrir"},
    {"pc_rt_shadows","Sombras con trazado de rayos"},
    {"pc_rt_contact","Sombras de contacto"},
    {"pc_shadows","Sombras"},
    {"pc_reflections","Reflejos"},
    {"pc_standard","Estándar"},
    {"pc_ray_traced","Trazado de rayos"},
    {"pc_rt_sharp_long","Trazado de rayos, nítidas"},
    {"pc_rt_soft_long","Trazado de rayos, suaves"},
    {"pc_note_shadows","De Bajo a Original son los mapas de sombras del original (512, 1024 o 2048 px). El trazado de rayos los reemplaza: nítidas como el original o suaves según el tamaño de cada luz."},
    {"pc_note_ao","Estándar es la oclusión en espacio de pantalla del original. El trazado de rayos oscurece esquinas y el espacio bajo los objetos a partir de la escena. No está en el original."},
    {"pc_note_reflections","Estándar son los reflejos del piso en espacio de pantalla del original. El trazado de rayos también refleja lo que está fuera de la pantalla. Experimental."},
    {"pc_rt_ao","Oclusión ambiental"},
    {"pc_anisotropy","Filtrado anisotrópico"},
    {"pc_enhanced_textures","Texturas mejoradas"},
    {"pc_texture_preparing","Preparando"},
    {"pc_note_texture_tools_missing","Faltan las herramientas o los archivos de modelo de texturas mejoradas. Restaura texture-tools desde el paquete portátil e inténtalo de nuevo. Las texturas originales se conservan."},
    {"pc_note_texture_busy","Otra instancia del juego está preparando esta caché de texturas. Espera a que termine e inténtalo de nuevo. Las texturas originales se conservan."},
    {"pc_note_texture_failed","Falló la preparación de texturas; las texturas originales se conservan. Revisa el espacio libre en disco y pt.log, e inténtalo de nuevo."},
    {"pc_note_texture_preparing","Preparando texturas mejoradas. Hasta terminar se ven las originales; luego cambian sin reiniciar. Desactivado cancela."},
    {"pc_note_enhanced_textures","Crea una vez texturas de color más nítidas a partir de tus archivos del juego. Incluye paredes y personajes; 4096 px con 10 GB de memoria de vídeo, si no 2048. Desactivado cancela; las texturas originales siguen disponibles."},
    {"pc_rt_sharp","Nítidas"},
    {"pc_rt_soft","Suaves"},
    {"pc_on","Activado"},
    {"pc_off","Desactivado"},
    {"pc_window","Ventana"},
    {"pc_borderless","Sin bordes"},
    {"pc_fullscreen","Pantalla completa"},
    {"pc_native","Nativa"},
    {"pc_quality_quality","Calidad"},
    {"pc_quality_balanced","Equilibrado"},
    {"pc_quality_performance","Rendimiento"},
    {"pc_quality_ultra","Ultra rendimiento"},
    {"pc_quality_custom","Personalizado"},
    {"pc_system_default","Predeterminado del sistema"},
    {"pc_reset_value","Reiniciar"},
    {"pc_reset_confirm","Confirmar"},
    {"pc_reset_done","Listo"},
    {"pc_note_vsync","Se aplica al instante. Sincroniza la imagen con la frecuencia de actualización del monitor."},
    {"pc_note_vsync_off","Se aplica al instante. Desactivada, cada fotograma se muestra en cuanto está listo: la tasa no se limita a la frecuencia del monitor y la imagen puede cortarse."},
    {"pc_note_restart","Se aplica en el próximo inicio."},
    {"pc_note_display_mode","Alt+Enter también alterna entre ventana y pantalla completa."},
    {"pc_note_resolution","Tamaño de la ventana."},
    {"pc_note_resolution_fullscreen","La pantalla completa usa la resolución del escritorio."},
    {"pc_note_upscaler_off","Desactivado renderiza a la resolución de la pantalla, como el original."},
    {"pc_note_render_size","Renderizado a {1}, mostrado a {2}."},
    {"pc_note_needs_upscaler","Requiere un método de escalado."},
    {"pc_note_sharpness_fsr","Solo FSR tiene su propio enfoque. Claridad de imagen, en Gráficos, da nitidez con cualquier método."},
    {"pc_note_reset","Reinicia el progreso y vuelve a empezar el juego ahora. Se conservan el idioma y la configuración de PC."},
    {"pc_note_reset_confirm","Presiona {accept} otra vez para borrar la partida guardada."},
    {"pc_note_reset_done","Progreso reiniciado en esta sesión."},
    {"pc_note_camera_tilt","La cámara se inclina con la cabeza, como en el original."},
    {"pc_note_voice","El micrófono solo escucha donde lo hace el juego original."},
    {"pc_note_focus_pause","Abre este menú cuando la ventana pasa a segundo plano."},
    {"pc_note_focus_mute","Silencia el juego mientras la ventana está en segundo plano."},
    {"pc_note_frame_generation_missing","No está en esta versión."},
    {"pc_note_frame_generation","AMD FSR 3 muestra un fotograma generado entre dos fotogramas renderizados."},
    {"pc_note_fsr4_vulkan","AMD publica FSR 4 solo para DirectX 12; este juego usa Vulkan, así que FSR 4 no puede funcionar aquí."},
    {"pc_dlss_model","Modelo DLSS"},
    {"pc_dlss_model_auto","Automático"},
    {"pc_note_dlss_model","Automático sigue la elección de NVIDIA: K hasta Equilibrado, M en Rendimiento, L en Ultra rendimiento. L y M cuestan casi el doble en RTX 20 y 30."},
    {"pc_note_frame_generation_dlss","Experimental. NVIDIA DLSS Frame Generation muestra un fotograma generado entre dos fotogramas renderizados. Se aplica en el próximo inicio."},
    {"pc_note_dlssg_gpu","DLSS Frame Generation requiere una NVIDIA GeForce RTX serie 40 o posterior."},
    {"pc_note_fsr_fg_gpu","La generación de fotogramas FSR 3 requiere una AMD Radeon RX serie 5000 o posterior."},
    {"pc_note_dlssg_driver","DLSS Frame Generation requiere un controlador de NVIDIA más reciente."},
    {"pc_note_dlssg_hags","DLSS Frame Generation requiere la programación de GPU acelerada por hardware (configuración de gráficos de Windows)."},
    {"pc_note_dlssg_missing","DLSS Frame Generation no está incluido en esta versión."},
    {"pc_note_dlssg_failed","DLSS Frame Generation no pudo iniciarse y se ha desactivado."},
    {"pc_note_dlssg_restart","Reinicia el juego para iniciar DLSS Frame Generation."},
    {"pc_note_vsync_dlssg","DLSS Frame Generation funciona sin sincronización vertical en Vulkan; el ajuste vuelve a aplicarse sin generación de fotogramas."},
    {"pc_note_fsr_fg_restart","Reinicia el juego para cambiar de DLSS Frame Generation a FSR 3."},
    {"pc_note_dead_zone","0.10 es el valor del DualShock 4."},
    {"pc_note_gamepad_sensitivity","Ajusta la velocidad de giro después de la respuesta original del stick. 1 conserva el ajuste original."},
    {"pc_note_rt_shadows","Sombras calculadas con trazado de rayos en lugar de mapas de sombras, tan nítidas como las del original. No está en el original."},
    {"pc_note_rt_soft","Sombras con trazado de rayos y bordes suaves según el tamaño de cada luz. No está en el original."},
    {"pc_note_rt_unsupported","Requiere una GPU con trazado de rayos Vulkan."},
    {"pc_note_graphics","Elige un preajuste o afina la iluminación, las texturas y los efectos de imagen. La resolución y el escalado van aparte."},
    {"pc_note_rt_contact","Los objetos proyectan sombras cortas con trazado de rayos desde cada luz, incluso las que no proyectan sombra en el original."},
    {"pc_note_rt_ao","El sombreado con trazado de rayos oscurece esquinas y el espacio bajo y detrás de los objetos. No está en el original."},
    {"pc_rt_reflections","Reflejos"},
    {"pc_note_rt_reflections","El piso refleja la escena más allá de los bordes de la pantalla. Experimental; el aspecto puede diferir del original."},
    {"pc_note_anisotropy","Pisos y paredes más nítidos vistos en ángulo. Desactivado es el filtrado del original."},
    {"pc_graphics_quality","Calidad"},
    {"pc_graphics_preset","Preajuste"},
    {"pc_preset_low","Bajo"},
    {"pc_preset_medium","Medio"},
    {"pc_preset_original","Original (PS4)"},
    {"pc_preset_high","Alto"},
    {"pc_preset_ultra","Ultra"},
    {"pc_preset_custom","Personalizado"},
    {"pc_ray_tracing","Trazado de rayos"},
    {"pc_clarity","Claridad de imagen"},
    {"pc_graphics_advanced","Avanzado"},
    {"pc_graphics_lighting","Iluminación"},
    {"pc_graphics_effects","Efectos de imagen"},
    {"pc_graphics_image","Imagen"},
    {"pc_lighting_standard","Iluminación estándar"},
    {"pc_shadow_quality","Mapas de sombras"},
    {"pc_standard_ao","Oclusión ambiental"},
    {"pc_standard_reflections","Reflejos en pantalla"},
    {"pc_ray_quality","Calidad de rayos"},
    {"pc_ray_balanced","Equilibrado"},
    {"pc_texture_detail","Detalle de texturas"},
    {"pc_detail_reduced","Reducido"},
    {"pc_detail_fine","Fino"},
    {"pc_dof","Profundidad de campo"},
    {"pc_motion_blur","Desenfoque de movimiento"},
    {"pc_bloom","Resplandor"},
    {"pc_lens_ghosts","Reflejos de destello"},
    {"pc_note_lens_ghosts","Los grandes reflejos del destello de lente por toda la pantalla al mirar cerca de una lámpara, como en el original (PS4). Desactivado los elimina."},
    {"pc_film_grain","Grano de película"},
    {"pc_note_preset","Solo cambia los gráficos; conserva la resolución y el escalado. Un ajuste manual muestra Personalizado. Ultra usa trazado de rayos si hay soporte."},
    {"pc_note_ray_master","Activa o desactiva juntos sombras con trazado de rayos, sombras de contacto, oclusión ambiental y reflejos. Cada uno por separado está en Iluminación."},
    {"pc_lens_distortion","Efecto de lente"},
    {"pc_note_lens_distortion","La curvatura de lente y los bordes de color originales. Desactivado da bordes más nítidos y una imagen más amplia."},
    {"pc_note_clarity","Añade un enfoque moderado de contraste local a la resolución de salida. Cero conserva la imagen original."},
    {"pc_note_letterbox","Barras negras arriba y abajo de la imagen, en el juego y en las cinemáticas. Los subtítulos quedan dentro de la imagen. No está en el original."},
    {"pc_note_advanced","Afina esta categoría. Regresar vuelve a Gráficos; los cambios muestran Personalizado."},
    {"pc_note_shadow_quality","Mapas de sombras de 512, 1024 o 2048 px (original). Las sombras con trazado de rayos los reemplazan si están activas. La escala de resolución no cambia."},
    {"pc_note_standard_ao","La oclusión ambiental original en espacio de pantalla. Desactívala para aligerar GPU más lentas."},
    {"pc_note_standard_reflections","Los reflejos del piso originales en espacio de pantalla. Los reflejos con trazado de rayos los reemplazan si están activos."},
    {"pc_note_ray_quality","Equilibrado: 2 rayos. Alto: 4 rayos. Ultra: 8 rayos, para sombras más suaves y menos ruido en la oclusión con trazado de rayos."},
    {"pc_note_texture_detail","Reducido usa mipmaps más gruesos. Fino conserva más detalle a distancia; puede parpadear. La resolución de salida no cambia."},
    {"pc_note_dof","El desenfoque de cámara original. Desactivado mantiene nítidos las superficies cercanas y el fondo."},
    {"pc_note_motion_blur","El desenfoque original al girar y moverse. Desactivado da una imagen más clara en movimiento."},
    {"pc_note_bloom","El resplandor original de las luces. Desactivado reduce el brillo y el costo del posprocesado."},
    {"pc_note_film_grain","La intensidad del grano de película original. Desactivado da una imagen más limpia; 100 % conserva el efecto original."},
    {"pc_mods","Mods"},
    {"pc_section_mods","Mods instalados"},
    {"pc_note_mods","Activar o desactivar un mod se aplica en el próximo inicio. Los mods no forman parte del juego original."},
    {"pc_archive","Museo"},
    {"pc_note_archive","Las imágenes, voces, trozos de foto, cinemáticas y modelos del propio juego, a medida que los alcanzas jugando. Tu partida no cambia."},
    {"pc_note_extras_archive","Selector de bucles, museo, cámara libre y modo foto."},
    {"pc_archive_sections","Salas"},
    {"pc_archive_images","Imágenes subliminales"},
    {"pc_archive_voices","Voces y radio"},
    {"pc_archive_photos","Trozos de foto"},
    {"pc_archive_cutscenes","Cinemáticas"},
    {"pc_archive_models","Modelos"},
    {"pc_archive_unused","Contenido sin usar"},
    {"pc_note_archive_images","Los textos de los destellos subliminales, el ruido de los destellos y la vista por la mirilla."},
    {"pc_note_archive_voices","Las emisiones de radio y cada frase hablada, con la transcripción en tu idioma de subtítulos."},
    {"pc_note_archive_photos","Los trozos rotos de la fotografía, y la foto que forman en el marco."},
    {"pc_note_archive_cutscenes","Cada cinemática desde su inicio, con su sonido y subtítulos."},
    {"pc_note_archive_models","Lisa y las demás figuras y objetos del pasillo, con la luz de la habitación inicial."},
    {"pc_note_archive_unused_section","Contenido de los archivos del juego que el juego nunca muestra. Se abre al terminar el juego."},
    {"pc_note_archive_image","Enter / Equis: ver a pantalla completa."},
    {"pc_note_archive_voice","Enter / Equis: reproducir o detener."},
    {"pc_note_archive_photo","Enter / Equis: ver a pantalla completa."},
    {"pc_note_archive_demo","Enter / Equis: reproducir desde el inicio. Esc / Círculo la detiene."},
    {"pc_note_archive_model","Enter / Equis: ver el modelo. Esc / Círculo: volver."},
    {"pc_note_archive_unused","Nunca se muestra en el juego. Enter / Equis: ver el modelo."},
    {"pc_note_archive_locked","Bloqueado. Alcánzalo jugando para abrirlo."},
    {"pc_note_archive_playing","Reproduciendo. Enter / Equis lo detiene."},
    {"pc_archive_lock","Bloquear el museo"},
    {"pc_note_archive_lock","Vuelve a bloquear cada pieza del museo, como antes de jugar. Tu partida guardada no cambia."},
    {"pc_archive_hint","Enter / X / A: abrir"},
    {"pc_archive_view_hint","Izquierda / Derecha: anterior / siguiente. Esc / Círculo: volver."},
    {"pc_archive_demo_hint","Esc / Círculo / Enter / Equis: detener"},
    {"pc_archive_model_hint","Flechas / sticks: girar. W / S / gatillos: más cerca / más lejos. Esc / Círculo: volver."},
    {"pc_archive_sub","Texto subliminal {1}"},
    {"pc_archive_noise","Ruido"},
    {"pc_archive_noise_normal","Distorsión del ruido"},
    {"pc_archive_peephole_mask","La vista por la mirilla"},
    {"pc_archive_radio_news","Radio: el noticiario"},
    {"pc_archive_radio_news2","Radio: el noticiario otra vez"},
    {"pc_archive_radio_voice","Voz de la radio {1}"},
    {"pc_archive_riddle","Acertijo de la radio {1}"},
    {"pc_archive_sermon","Radio: el sermón"},
    {"pc_archive_phone","La llamada"},
    {"pc_archive_peephole_voice","Por la mirilla"},
    {"pc_archive_bag","La bolsa que habla"},
    {"pc_archive_fetus","El feto habla {1}"},
    {"pc_archive_photo_lisa","Trozo: Lisa"},
    {"pc_archive_photo_tree","Trozo: el árbol"},
    {"pc_archive_photo_gap","Trozo: la rendija"},
    {"pc_archive_photo_bath","Trozo: el baño"},
    {"pc_archive_photo_stair","Trozo: la escalera"},
    {"pc_archive_photo_option","Trozo: la pantalla de opciones"},
    {"pc_archive_photo_complete","La foto completa"},
    {"pc_archive_preface","El prefacio"},
    {"pc_archive_awakening","El primer despertar"},
    {"pc_archive_opening","El despertar"},
    {"pc_archive_first_exit","La primera puerta"},
    {"pc_archive_door","Por la puerta"},
    {"pc_archive_clock","Medianoche"},
    {"pc_archive_kill","Atrapado por Lisa"},
    {"pc_archive_ending","El final"},
    {"pc_archive_teaser","El teaser"},
    {"pc_archive_lisa_stand","Lisa, de pie"},
    {"pc_archive_lisa_walk","Lisa, caminando"},
    {"pc_archive_lisa_dash","Lisa, abalanzándose"},
    {"pc_archive_lisa_door","Lisa tras la puerta"},
    {"pc_archive_baby","El feto en el lavabo"},
    {"pc_archive_fridge","El refrigerador"},
    {"pc_archive_bag_model","La bolsa de papel"},
    {"pc_archive_lamp","La lámpara del techo"},
    {"pc_archive_roach","Cucaracha"},
    {"pc_archive_flashlight","La linterna"},
    {"pc_archive_radio","La radio"},
    {"pc_archive_phone_model","El teléfono"},
    {"pc_archive_xmark_photo","La foto de la X"},
    {"pc_archive_clock_model","El reloj"},
    {"pc_archive_man","El hombre"},
    {"pc_archive_bathtub","El cuerpo en la bañera"},
};
inline std::string_view Menu(std::string_view key) {
    for (const auto& e : kMenu) if (e.key == key) return e.text;
    return {};
}
}
