#pragma once
#include <cstdint>
#include <initializer_list>
#include <string_view>

namespace pt::turkish {
struct Text { std::string_view key, text; };
inline constexpr Text kMenu[] = {
    {"pc_controller_speaker","Kontrolcü hoparlörü"},
    {"pc_note_controller_speaker","Lisa’nın oyunda kaydedilmiş çığlıklarını desteklenen Sony kontrolcü hoparlörlerinden çalar. Windows’ta USB bağlantısı gerekir; desteklenmeyen aygıtlar ve Bluetooth sessiz kalır. Dokunsal geri bildirimden bağımsızdır ve varsayılan olarak kapalıdır."},
    {"pc_controller_speaker_volume","Kontrolcü hoparlör sesi"},
    {"pc_note_controller_speaker_volume","Yalnızca kontrolcü hoparlörünün sesini %5 adımlarla değiştirir. Oyun sesini veya DualSense dokunsal geri bildirim gücünü etkilemez. Yalnızca Windows’ta desteklenen kablolu Sony kontrolcülerinde kullanılabilir."},
    {"pc_microphone_trigger_assign","{input} tuşunu mikrofon tetikleyicisine ata"},
    {"pc_note_microphone_trigger","Mikrofona isteğe bağlı bir alternatiftir. Klavye ve iki kontrolcü tetiği yalnızca oyun dinlerken etkinleşir."},
    {"pc_note_microphone_test","Mikrofonu ve tanıma sonucunu test eder."},
    {"pc_fps_limit","Kare hızı sınırı"},
    {"pc_unlimited","Sınırsız"},
    {"pc_note_fps_limit","Çizilen kareleri sınırlar. Menüler 60 FPS ile sınırlı kalır. Dikey eşitleme daha düşük bir sınır getirebilir."},
    {"pc_hdr","Yerel HDR"},
    {"pc_note_hdr_restart","Bir sonraki açılışta uygulanır. Uyumlu ekranda HDR açık olmalıdır; aksi halde SDR kullanılır."},
    {"pc_surround","Çevresel ses çıkışı"},
    {"pc_note_surround","Yeniden başlatınca çıkış aygıtının 5.1 veya 7.1 düzenini kullanır. Stereo aygıtlar stereo kalır."},
    {"pc_rumble_profile","Titreşim modu"},
    {"pc_rumble_original","Orijinal"},
    {"pc_rumble_enhanced","Geliştirilmiş"},
    {"pc_note_rumble_profile","Orijinal yalnızca oyunun özgün motor titreşimini kullanır. Geliştirilmiş, desteklenen tetik titreşimini ve Windows'ta desteklenen USB DualSense gamepadlerde Lisa'nın filtrelenmiş çığlıklarından üretilen dokunsal geri bildirimi ekler. Ana titreşim ayarı ikisini de kapatır. Gamepad hoparlör sesi bundan bağımsızdır."},
    {"pc_vr_height","Yükseklik ayarı"},
    {"pc_note_vr_height","Oyuncunun oyun içindeki konumunu değiştirmeden izlenen bakış noktasını yukarı veya aşağı taşır."},
    {"pc_vr_world_scale","Dünya ölçeği"},
    {"pc_note_vr_world_scale","İzlenen baş, göz ve kontrolcü hareketlerini %50 ile %200 arasında ölçekler. Değer yükseldikçe dünya daha küçük hissedilir. Varsayılan: %100."},
    {"pc_photo_focal_length","Odak uzaklığı"},
    {"pc_note_photo_focal_length","Merceğin milimetre cinsinden odak uzaklığı. Odak bulanıklığı kamerayla aynı mercek ve sensörü kullanır."},
    {"pc_photo_aspect","En-boy oranı"},
    {"pc_note_photo_aspect","Fotoğrafı ortadan kırpar."},
    {"pc_photo_resolution","Fotoğraf çözünürlüğü"},
    {"pc_note_photo_resolution","Yerel, kadrajdaki pikselleri kaydeder. 4K, uzun kenarı 3840 piksel olacak şekilde sahneyi yeniden işler."},
    {"pc_photo_resolution_native","Yerel"},
    {"pc_photo_resolution_4k","4K"},
    {"pc_photo_filter","Renk filtresi"},
    {"pc_note_photo_filter","Yalnızca fotoğraf görünümüne ve kaydedilen fotoğrafa uygulanır."},
    {"pc_photo_filter_bw","Siyah beyaz"},
    {"pc_photo_filter_warm","Sıcak"},
    {"pc_photo_filter_cool","Soğuk"},
    {"pc_photo_filter_muted","Soluk"},
    {"pc_archive_model_hint","WASD / sol analog: kadrajı kaydır. Oklar / sağ analog: döndür. Tetikler: yakınlaştır. Esc / Daire: geri."},
    {"pc_note_resolution_fullscreen","Çerçevesiz mod seçilen boyutu kullanır; özel tam ekran desteklenen ekran boyutunu kullanır."},
    {"op_sub_turkish","Türkçe"},{"op_sub_chinese","Çince (basitleştirilmiş)"},{"op_sub_arabic","Arapça"},{"op_sub_russian","Rusça"},{"op_sub_ukrainian","Ukraynaca"},{"op_sub_czech","Çekçe"},{"op_sub_polish","Lehçe"},
    {"op_options","SEÇENEKLER"},{"op_back","Geri"},{"op_brightness_setting","Parlaklık"},
    {"op_britness_tip","Yalnızca soldaki resim görünene kadar parlaklığı ayarlayın."},
    {"op_subtitles_setting","Altyazılar"},{"op_sub_none","Kapalı"},{"op_sub_english","İngilizce"},
    {"op_sub_french","Fransızca"},{"op_sub_german","Almanca"},{"op_sub_spanish","İspanyolca"},
    {"op_sub_japanese","Japonca"},{"op_sub_itlian","İtalyanca"},{"op_sub_portuguese","Portekizce"},
    {"op_camera_setting","Kamera"},{"op_camera_y_axis","Dikey eksen"},{"op_camera_x_axis","Yatay eksen"},
    {"op_camera_normal","Normal"},{"op_camera_reversed","Ters"},
    {"pc_title","PC AYARLARI"},{"pc_entry","PC Ayarları"},{"pc_back","Geri"},{"pc_quit","Çıkış"},
    {"pc_nav_columns","Tab / L1 / R1: sütun değiştir"},{"pc_quit_confirm","Çıkılsın mı?"},
    {"pc_nav_columns","Tab / L1 / R1: sütun değiştir"},{"pc_save_no_space","Oyunu kaydetmek için yeterli boş alan yok.\nYer açın, ardından yeniden denemek için bu mesajı kapatın."},
    {"pc_nav_columns","Tab / L1 / R1: sütun değiştir"},{"pc_ok","Tamam"},
    {"pc_note_quit","Oyundan çık."},{"pc_note_quit_confirm","Çıkmak için {accept} tuşuna tekrar bas. Geri ile iptal et."},
    {"pc_section_display","Ekran"},{"pc_section_upscaling","Görüntü ölçekleme"},{"pc_section_sound","Ses"},
    {"pc_section_controls","Kontroller"},{"pc_section_progress","İlerleme"},{"pc_section_ray_tracing","Işın izleme"},
    {"pc_section_textures","Dokular"},{"pc_display_mode","Ekran modu"},{"pc_resolution","Çözünürlük"},
    {"pc_vsync","Dikey eşitleme"},{"pc_focus_pause","Arka planda duraklat"},{"pc_focus_mute","Arka planda sessize al"},
    {"pc_upscaler","Ölçekleyici"},{"pc_quality","Kalite"},{"pc_sharpness","Keskinlik"},
    {"pc_frame_generation","Kare üretimi"},{"pc_volume","Ses düzeyi"},{"pc_microphone","Mikrofon"},
    {"pc_microphone_test","Mikrofon testi"},{"pc_mic_level","Giriş düzeyi"},{"pc_mic_heard","Algılanan kelimeler"},
    {"pc_mic_monitor","Sesimi dinle"},{"pc_mic_no_word","Henüz yok"},{"pc_mic_waiting","Seçilen mikrofon bekleniyor."},
    {"pc_mic_unavailable","Seçilen mikrofon açılamadı. Kayıt izinlerini ve cihaz seçimini kontrol et."},
    {"pc_mic_st_loading","Yükleniyor..."},
    {"pc_mic_st_nomic","Mikrofon yok"},
    {"pc_mic_st_files","Konuşma dosyaları eksik"},
    {"pc_mic_st_runtime","Konuşma motoru başarısız"},
    {"pc_mic_st_cpu","İşlemci desteklenmiyor"},
    {"pc_mic_st_model","Konuşma modeli başarısız"},
    {"pc_mic_st_silent","Ses yok"},
    {"pc_mic_err_files","Konuşma tanıma dosyaları eksik. Oyunu yeniden kur veya onar."},
    {"pc_mic_err_runtime","Konuşma motoru yüklenemedi. Nedeni pt.log dosyasında."},
    {"pc_mic_err_cpu","Bu işlemci konuşma motorunu çalıştıramıyor."},
    {"pc_mic_err_model","Konuşma modeli yüklenemedi. Nedeni pt.log dosyasında."},
    {"pc_mic_err_silent","Mikrofon açık ama ses göndermiyor. Sessize alınmadığını ve doğru cihazın seçildiğini kontrol et."},
    {"pc_mic_say_jack","Seçilen mikrofona Jack de. Bu test bulmacayı ilerletmez."},
    {"pc_mic_monitor_note","Mikrofonunu dinle. Kulaklık geri beslemeyi önler. Testten çıkınca dinleme durur."},
    {"pc_mouse","Fare hassasiyeti"},{"pc_gamepad_sensitivity","Kontrolcü bakış hassasiyeti"},{"pc_camera_tilt","Kamera eğimi"},{"pc_vibration","Titreşim"},
    {"pc_dead_zone","Analog ölü bölgesi"},{"pc_reset","İlerlemeyi sıfırla"},{"pc_graphics","Grafikler"},
    {"pc_graphics_value","Ayrıntılar"},{"pc_rt_shadows","Işın izlemeli gölgeler"},{"pc_rt_contact","Temas gölgeleri"},
    {"pc_rt_ao","Ortam gölgeleme"},{"pc_anisotropy","Anizotropik filtreleme"},{"pc_enhanced_textures","Geliştirilmiş dokular"},
    {"pc_texture_preparing","Hazırlanıyor"},
    {"pc_note_texture_tools_missing","Geliştirilmiş doku araçları veya model dosyaları eksik. texture-tools klasörünü taşınabilir paketten geri yükleyip yeniden dene. Orijinal dokular korunuyor."},
    {"pc_note_texture_busy","Başka bir oyun oturumu bu doku önbelleğini hazırlıyor. Tamamlanmasını bekleyip yeniden dene. Orijinal dokular korunuyor."},
    {"pc_note_texture_failed","Dokular hazırlanamadı; orijinal dokular korunuyor. Boş disk alanını ve hatanın sebebi için pt.log dosyasını kontrol edip yeniden dene."},
    {"pc_note_texture_preparing","Geliştirilmiş dokular hazırlanıyor. Hazır olana kadar orijinal dokular görünür; ardından yeniden başlatmadan değişir. Kapalı seçeneği hazırlığı iptal eder."},
    {"pc_note_enhanced_textures","Oyun dosyalarından bir kez daha keskin renk dokuları üretir. Duvarlar ve karakterler dahil; 10 GB video belleğinde 4096, altında 2048 piksel. İptal için kapat; orijinal dokular kullanılabilir."},
    {"pc_rt_sharp","Keskin"},{"pc_rt_soft","Yumuşak"},{"pc_on","Açık"},{"pc_off","Kapalı"},
    {"pc_window","Pencere"},{"pc_borderless","Kenarlıksız"},{"pc_fullscreen","Tam ekran"},{"pc_native","Doğal"},
    {"pc_quality_quality","Kalite"},{"pc_quality_balanced","Dengeli"},{"pc_quality_performance","Performans"},
    {"pc_quality_ultra","Üstün performans"},{"pc_quality_custom","Özel"},{"pc_system_default","Sistem varsayılanı"},
    {"pc_reset_value","Sıfırla"},{"pc_reset_confirm","Onayla"},{"pc_reset_done","Tamamlandı"},
    {"pc_note_vsync","Hemen uygulanır. Kare sunumunu ekranın yenileme hızıyla eşitler."},
    {"pc_note_vsync_off","Hemen uygulanır. Kapalıyken her kare hazır olur olmaz gösterilir: kare hızı ekranın yenileme hızına bağlı kalmaz ve görüntüde yırtılma olabilir."},
    {"pc_shadows","Gölgeler"},{"pc_reflections","Yansımalar"},{"pc_standard","Standart"},{"pc_ray_traced","Işın izlemeli"},{"pc_rt_sharp_long","Işın izlemeli, keskin"},{"pc_rt_soft_long","Işın izlemeli, yumuşak"},{"pc_note_shadows","Düşük ile Orijinal arası orijinalin gölge haritalarıdır (512, 1024 veya 2048 px). Işın izlemeli bunların yerini alır: orijinal kadar keskin ya da her ışığın boyutuna göre yumuşak."},{"pc_note_ao","Standart, orijinalin ekran uzayı gölgelemesidir. Işın izlemeli, köşeleri ve nesnelerin altını sahnenin kendisinden karartır. Orijinalde yoktur."},{"pc_note_reflections","Standart, orijinalin ekran uzayı zemin yansımalarıdır. Işın izlemeli ekran dışındakileri de yansıtır. Deneyseldir."},
    {"pc_note_restart","Sonraki açılışta uygulanır."},{"pc_note_display_mode","Alt+Enter da pencere ile tam ekran arasında geçiş yapar."},
    {"pc_note_resolution","Pencere boyutu."},{"pc_note_resolution_fullscreen","Tam ekran masaüstü çözünürlüğünü kullanır."},
    {"pc_note_render_size","Çizim {1}, çıktı {2}."},
    {"pc_note_upscaler_off","Kapalıyken orijinal oyun gibi ekran çözünürlüğünde çizilir."},{"pc_note_needs_upscaler","Bir görüntü ölçekleyici gerekir."},{"pc_note_sharpness_fsr","Yalnızca FSR kendi keskinleştirmesine sahiptir. Grafik sayfasındaki Görüntü netliği her ölçekleyiciyle keskinleştirir."},
    {"pc_note_reset","İlerlemeyi sıfırlar ve oyunu şimdi yeniden başlatır. Dil ve PC ayarları korunur."},
    {"pc_note_reset_confirm","Kaydı silmek için {accept} tuşuna tekrar bas."},
    {"pc_note_reset_done","İlerleme sıfırlandı. Yeni oyun bu oturumda başladı."},
    {"pc_note_camera_tilt","Kamera orijinal oyundaki gibi başla birlikte eğilir."},
    {"pc_note_voice","Mikrofon yalnızca orijinal oyunun dinlediği yerlerde dinler."},
    {"pc_note_focus_pause","Oyun arka plana geçtiğinde bu menüyü açar."},{"pc_note_focus_mute","Oyun arka plandayken sesi kapatır."},
    {"pc_note_frame_generation_missing","Bu build'de bulunmuyor."},
    {"pc_note_frame_generation","AMD FSR 3, çizilen iki kare arasında üretilmiş bir kare gösterir."},
    {"pc_note_fsr4_vulkan","AMD, FSR 4'ü yalnızca DirectX 12 için yayımlıyor; bu oyun Vulkan ile çizildiği için FSR 4 burada çalışamaz."},
    {"pc_dlss_model","DLSS modeli"},
    {"pc_dlss_model_auto","Otomatik"},
    {"pc_note_dlss_model","Otomatik, NVIDIA'nın seçimini izler: Dengeli'ye kadar K, Performans'ta M, Üstün performans'ta L. L ve M, RTX 20 ve 30'da yaklaşık iki kat yük getirir."},
    {"pc_note_frame_generation_dlss","Deneysel. NVIDIA DLSS Frame Generation, çizilen iki kare arasında üretilmiş bir kare gösterir. Bir sonraki açılışta etkinleşir."},
    {"pc_note_dlssg_gpu","DLSS Frame Generation, NVIDIA GeForce RTX 40 serisi veya daha yeni bir ekran kartı gerektirir."},
    {"pc_note_fsr_fg_gpu","FSR 3 kare üretimi, AMD Radeon RX 5000 serisi veya daha yeni bir ekran kartı gerektirir."},
    {"pc_note_dlssg_driver","DLSS Frame Generation daha yeni bir NVIDIA sürücüsü gerektirir."},
    {"pc_note_dlssg_hags","DLSS Frame Generation, donanım hızlandırmalı GPU zamanlamasını gerektirir (Windows grafik ayarları)."},
    {"pc_note_dlssg_missing","DLSS Frame Generation bu build'de bulunmuyor."},
    {"pc_note_dlssg_failed","DLSS Frame Generation başlatılamadı ve kapatıldı."},
    {"pc_note_dlssg_restart","DLSS Frame Generation'ı başlatmak için oyunu yeniden başlatın."},
    {"pc_note_vsync_dlssg","DLSS Frame Generation, Vulkan'da dikey eşitleme olmadan çalışır; kare üretimi kapalıyken ayar yeniden geçerli olur."},
    {"pc_note_fsr_fg_restart","DLSS Frame Generation'dan FSR 3'e geçmek için oyunu yeniden başlatın."},
    {"pc_note_dead_zone","DualShock 4'ün kendi değeri 0,10'dur."},
    {"pc_note_gamepad_sensitivity","Dönüş hızını özgün analog çubuk tepkisinden sonra ayarlar. 1 özgün hızı korur."},
    {"pc_note_rt_shadows","Gölge haritaları yerine sahneye ışın izler; orijinalin keskinliğini korur. Orijinal oyunda yoktur."},
    {"pc_note_rt_soft","Işığın boyutuna göre yumuşak kenarlı ışın izlemeli gölgeler. Orijinal oyunda yoktur."},
    {"pc_note_rt_unsupported","Vulkan ışın izleme destekli bir GPU gerekir."},
    {"pc_note_graphics","Bir grafik profili seç veya aydınlatma, doku ve görüntü efektlerini ayrı ayarla. Çözünürlük ve görüntü ölçekleme bağımsızdır."},
    {"pc_note_rt_contact","Nesneler her ışıktan kısa temas gölgeleri üretir; orijinalin gölgesiz bıraktığı ışıklar da dahildir."},
    {"pc_note_rt_ao","Işın izleme köşeleri ve nesnelerin altını/arkasını karartır. Orijinal oyunda yoktur."},
    {"pc_rt_reflections","Işın izlemeli yansımalar"},
    {"pc_note_rt_reflections","Zemin, ekran dışındaki sahneyi yansıtır. Deneyseldir; görünüm orijinalden farklı olabilir."},
    {"pc_note_anisotropy","Eğik açıdan görülen zemin ve duvarları keskinleştirir. Kapalıyken orijinal filtreleme kullanılır."},
    {"pc_graphics_quality","Kalite"},
    {"pc_graphics_preset","Grafik profili"},
    {"pc_preset_low","Düşük"},
    {"pc_preset_medium","Orta"},
    {"pc_preset_original","Orijinal (PS4)"},
    {"pc_preset_high","Yüksek"},
    {"pc_preset_ultra","Ultra"},
    {"pc_preset_custom","Özel"},
    {"pc_ray_tracing","Işın izleme"},
    {"pc_clarity","Görüntü netliği"},
    {"pc_graphics_advanced","Gelişmiş"},
    {"pc_graphics_lighting","Aydınlatma"},
    {"pc_graphics_effects","Görüntü efektleri"},
    {"pc_graphics_image","Görüntü detayı"},
    {"pc_lighting_standard","Standart aydınlatma"},
    {"pc_shadow_quality","Gölge haritaları"},
    {"pc_standard_ao","Ortam gölgeleme"},
    {"pc_standard_reflections","Ekran yansımaları"},
    {"pc_ray_quality","Işın kalitesi"},
    {"pc_ray_balanced","Dengeli"},
    {"pc_texture_detail","Doku detayı"},
    {"pc_detail_reduced","Azaltılmış"},
    {"pc_detail_fine","İnce"},
    {"pc_dof","Alan derinliği"},
    {"pc_motion_blur","Hareket bulanıklığı"},
    {"pc_bloom","Işık parlaması"},
    {"pc_lens_ghosts","Lens yansımaları"},
    {"pc_note_lens_ghosts","Bir lambanın yakınına bakınca ekranın tamamına yayılan büyük lens parlaması yansımaları, orijinaldeki (PS4) gibi. Kapalıyken çizilmez."},
    {"pc_film_grain","Film grenleri"},
    {"pc_note_preset","Yalnızca grafikleri değiştirir; çözünürlüğü ve ölçekleyiciyi korur. Elle değişiklik yapınca Özel olur. Ultra, destekleniyorsa ışın izleme kullanır."},
    {"pc_note_ray_master","Işın izlemeli gölgeleri, temas gölgelerini, ortam gölgelemeyi ve yansımaları birlikte aç/kapat. Ayrı seçenekler Aydınlatma sayfasındadır."},
    {"pc_lens_distortion","Lens efekti"},
    {"pc_note_lens_distortion","Orijinal kavisli lens ve renk saçılması. Kapalıyken kenarlar daha net, görüntü daha geniştir."},
    {"pc_note_clarity","Çıkış çözünürlüğünde ölçülü yerel kontrast keskinliği ekler. Sıfır, orijinal görüntüyü korur."},{"pc_note_letterbox","Oynanışta ve ara sahnelerde görüntünün üstünde ve altında siyah şeritler. Altyazılar görüntünün içinde kalır. Orijinalde yoktur."},
    {"pc_note_advanced","Bu kategoriyi ayrı ayarla. Geri, Grafikler sayfasına döner. Değişiklikler otomatik olarak Özel profilini gösterir."},
    {"pc_note_shadow_quality","512, 1024 veya orijinal 2048 piksel gölgeler. Işın izleme açılınca haritaların yerini alır. Çözünürlük ölçeği değişmez."},
    {"pc_note_standard_ao","Orijinal ekran tabanlı ortam gölgelemesi. Yavaş GPU için kapatılabilir."},
    {"pc_note_standard_reflections","Orijinal ekran tabanlı zemin yansımaları. Işın izlemeli yansımalar açıksa bunların yerini alır."},
    {"pc_note_ray_quality","Dengeli: 2 ışın. Yüksek: 4 ışın. Ultra: 8 ışın. Gölgelerin ve ortam gölgelemesinin gürültüsünü azaltır."},
    {"pc_note_texture_detail","Azaltılmış, daha kaba doku katmanları kullanır. İnce, uzaktaki detayları korur; titreşim oluşturabilir. Çıkış çözünürlüğü değişmez."},
    {"pc_note_dof","Orijinal kamera odak bulanıklığı. Kapalıyken yakın yüzeyler ve arka plan net kalır."},
    {"pc_note_motion_blur","Dönerken ve yürürken orijinal hareket bulanıklığı. Kapalıyken hareketli görüntü daha nettir."},
    {"pc_note_bloom","Orijinal ışık parlaması. Kapatmak parlamayı ve efekt maliyetini azaltır."},
    {"pc_note_film_grain","Orijinal film greni gücü. Sıfır daha temiz görüntü verir; %100 orijinal efekti korur."},
    {"pc_mods","Modlar"},{"pc_section_mods","Yüklü modlar"},
    {"pc_note_mods","Bir modu açıp kapatmak bir sonraki başlatmada etkili olur. Modlar orijinal oyunun parçası değildir."},
    {"pc_loop_browser","Döngü Tarayıcı"},
    {"pc_note_loop_browser_entry","Kaydını değiştirmeden herhangi bir döngüyü başlat."},
    {"pc_loop_choose","Bir döngü seç"},
    {"pc_loop_preview","Önizleme"},
    {"pc_loop_start_hint","Enter / X / A: başlat"},
    {"pc_loop_f000","Başlangıç odası: açılış"},
    {"pc_loop_f010","Döngü 1: radyo"},
    {"pc_loop_f005","Döngü 2: giriş kapısı açılır"},
    {"pc_loop_f020","Döngü 3: banyoda ağlama"},
    {"pc_loop_f030","Döngü 4: banyo kapısı"},
    {"pc_loop_f040","Döngü 5: koridorun sonunda Lisa"},
    {"pc_loop_f060","Döngü 6: banyo ve el feneri"},
    {"pc_loop_f050a","Döngü 7: Lisa seni takip ediyor"},
    {"pc_loop_f050b","Döngü 8: X işaretli fotoğraf"},
    {"pc_loop_f070","Döngü 9: pencere kırılır"},
    {"pc_loop_f080","Döngü 10: kanayan buzdolabı"},
    {"pc_loop_f090","Döngü 11: HELLO"},
    {"pc_loop_f100","Döngü 12: kırmızı koridor"},
    {"pc_loop_f110","Döngü 13: labirent ve gözetleme deliği"},
    {"pc_loop_f120","Döngü 14: 204863, hata ekranı"},
    {"pc_loop_f160","Döngü 15: son döngü"},
    {"pc_loop_ending","Final sinematiği ve jenerik"},
    {"pc_loop_street","Sokakta yürü (finalden sonra)"},
    {"pc_note_loop_opening","Başlangıç odasındaki açılışı yeni bir oyun gibi başlatır. Kaydın korunur."},
    {"pc_note_loop_hallway","Bu döngüden hemen önce, başlangıç odasında ve önceki bulmacalar çözülmüş olarak başlar. Kapıdan geç. Kaydın korunur; kayıt bir sonraki kontrol noktasında devam eder."},
    {"pc_note_loop_ending","Final sinematiğini ve jeneriği oynatır, ardından sokak yürüyüşünü önerir. Kaydın korunur."},
    {"pc_note_loop_street","Seni finaldeki sokağa birinci şahıs bakışla koyar. Ekstralar'dan çıkabilirsin. Kaydın korunur."},
    {"pc_note_loop_locked","Kilitli. Oyunu bir kez bitir; ardından oynarken ulaştığın her döngü açılır."},
    {"pc_note_loop_browser_locked","Döngü tarayıcıyı açmak için oyunu bir kez bitir."},
    {"pc_street_title","Sokak"},
    {"pc_street_question","Sokağı keşfetmek ister misin?"},
    {"pc_street_walk","Evet, sokakta yürü"},
    {"pc_credit_version","P.T. PC Port {1}, LoreanXavier tarafından"},
    {"pc_update_available","Sürüm {1} mevcut (bu sürüm {2})"},
    {"pc_credits_by","LoreanXavier tarafından"},
    {"pc_credits_dlss","Bu oyun NVIDIA DLSS kullanır."},
    {"pc_credits_licenses","Lisans metinlerinin tamamı pt.exe'nin yanındaki licenses klasöründedir."},
    {"pc_credits_konami","P.T., Konami Digital Entertainment ve Kojima Productions'a aittir."},
    {"pc_credits_fan","Bu port resmi olmayan bir hayran projesidir; Konami, NVIDIA, AMD veya Intel ile bağlantılı değildir ve onlar tarafından onaylanmamıştır."},
    {"pc_note_street_walk","Finaldeki sokakta birinci şahıs bakışla yürü. Ekstralar'dan çıkabilirsin."},
    {"pc_street_restart","Hayır, başa dön"},
    {"pc_note_street_restart","Orijinaldeki gibi, jenerikten sonra başlangıç odasından yeniden başlar."},
    {"pc_street_leave","Sokaktan çık"},
    {"pc_note_street_leave","Sokak yürüyüşünü bitirir ve başlangıç odasına döner."},
    {"pc_street_return","Eve dön"},
    {"pc_street_return_confirm","Eve dönülsün mü?"},
    {"pc_loop_lock","Döngü tarayıcıyı kilitle"},
    {"pc_note_loop_lock","İlk bitirişinden önceki gibi tüm girişleri yeniden kilitler. Kaydın değişmez."},
    {"pc_extras","Ekstralar"},
    {"pc_vr","VR (deneysel)"},
    {"pc_note_vr","OpenXR üzerinden bir VR başlığıyla oyna. Deneysel: gerçek donanımda test edilmedi."},
    {"pc_vr_mode","VR modu"},
    {"pc_note_vr_mode","Gerçek donanımda test edilmedi. Bir OpenXR çalışma ortamı ve başlık gerekir. Bir sonraki açılışta geçerli olur; başlık yoksa oyun her zamanki gibi açılır."},
    {"pc_vr_flashlight","El feneri"},
    {"pc_note_vr_flashlight","El feneri orijinaldeki gibi başını ya da elindeki kumandayı takip eder."},
    {"pc_vr_head","Baş"},
    {"pc_vr_controller","Kumanda"},
    {"pc_vr_turn","Dönüş"},
    {"pc_note_vr_turn","Sağ çubuk adım adım ya da akıcı döndürür. Adımlı dönüş mideyi daha az yorar."},
    {"pc_vr_snap","Adımlı"},
    {"pc_vr_smooth","Akıcı"},
    {"pc_note_extras","Döngü tarayıcı, serbest kamera ve fotoğraf modu."},
    {"pc_freecam","Serbest kamera"},
    {"pc_note_freecam","Kamerayı oyuncudan uzağa uçur (F6). Space / Ctrl veya tetikler yükseltir ve alçaltır, Shift veya L3 hızlandırır. Esc ile biter."},
    {"pc_photo_mode","Fotoğraf modu"},
    {"pc_note_photo_mode","Oyunu duraklat ve serbest kamerayla kareni oluştur (F7). P veya Kare Pictures/PT Photos klasörüne kaydeder, H veya Üçgen paneli gizler."},
    {"pc_speedrun","Speedrun sayacı"},
    {"pc_note_speedrun","Ekranda her döngüde ara süre alan bir sayaç ve jenerikten sonra bir sonuç ekranı. Gerçek süre her şeyi sayar; oyun süresi duraklatmaları ve yüklemeleri saymaz. Orijinalde yoktur."},
    {"pc_speedrun_real_time","Gerçek süre"},
    {"pc_speedrun_game_time","Oyun süresi"},
    {"pc_livesplit","LiveSplit sunucusu"},
    {"pc_note_livesplit","Sayacın başlangıcını, ara sürelerini ve oyun süresini LiveSplit'e gönderir (Control > Start TCP Server, port {1}). Sunucu ve port pt.ini dosyasındadır."},
    {"pc_speedrun_results","KOŞU TAMAMLANDI"},
    {"pc_speedrun_run","Koşu"},
    {"pc_speedrun_splits","Ara süreler"},
    {"pc_speedrun_menu","Menüye dön"},
    {"pc_note_speedrun_menu","Orijinalin sondan sonra yaptığı gibi en baştan başlatır, önce seçenekler ekranı gelir. Sonraki koşu kontrol sende olduğunda başlar."},
    {"pc_speedrun_outside","Dışarıyı keşfet"},
    {"pc_note_speedrun_outside","Sondaki sokakta yürü. Eve duraklatma menüsünden dönebilirsin."},
    {"pc_note_speedrun_real","Kontrolü aldığın andan sona kadar gerçek saat: duraklatmalar, yüklemeler ve ara sahneler dahil."},
    {"pc_note_speedrun_game","Yalnızca duraklatılmamış oyun: duraklatma menüsü ve oyun sonu sonrası yüklemeler sayılmaz."},
    {"pc_speedrun_best","Kişisel rekor"},
    {"pc_note_speedrun_best","Önceki rekor: {1}. Kayıtlar kullanıcı klasöründeki speedrun.ini, speedrun_history.txt ve speedrun_pb.lss (LiveSplit) dosyalarındadır."},
    {"pc_speedrun_new_best","Yeni rekor!"},
    {"pc_speedrun_partial","Baştan değil"},
    {"pc_speedrun_start_room","Başlangıç odası"},
    {"pc_speedrun_loop","Döngü {1}"},
    {"pc_third_person","Üçüncü şahıs (deneysel)"},
    {"pc_note_third_person","Deneysel, orijinalde yok: kamera seni omzunun arkasından takip eder. Yakınlaştırma ve ara sahneler birinci şahsa döner; olaylar birinci şahıstaki gibi gerçekleşir."},
    {"pc_extras_start","Başlat"},
    {"pc_extras_stop","Durdur"},
    {"pc_note_loop_generating","Önizlemeler oluşturuluyor... Kaydın korunur. Kayıt bir sonraki kontrol noktasında devam eder: bodrumdan çıkınca veya son döngüye ulaşınca."},
    {"pc_photo_title","FOTOĞRAF MODU"},
    {"pc_photo_section_camera","Kamera"},
    {"pc_photo_section_lens","Lens"},
    {"pc_photo_section_image","Görüntü"},
    {"pc_photo_take","Fotoğraf çek"},
    {"pc_photo_capture","Çek"},
    {"pc_photo_fov","Görüş alanı"},
    {"pc_photo_roll","Kamera yatışı"},
    {"pc_photo_speed","Kamera hızı"},
    {"pc_photo_speed_slow","Yavaş"},
    {"pc_photo_speed_normal","Normal"},
    {"pc_photo_speed_fast","Hızlı"},
    {"pc_photo_reset","Kamerayı sıfırla"},
    {"pc_photo_focus","Odak mesafesi"},
    {"pc_photo_aperture","Diyafram"},
    {"pc_photo_exposure","Pozlama"},
    {"pc_photo_grading","Renk düzenleme"},
    {"pc_photo_letterbox","Sinema şeritleri"},
    {"pc_photo_body","Oyuncu bedeni"},
    {"pc_photo_flashlight","El feneri"},
    {"pc_photo_shown","Görünür"},
    {"pc_photo_hidden","Gizli"},
    {"pc_photo_auto","Otomatik"},
    {"pc_photo_metres","{value} m"},
    {"pc_photo_saved","Pictures/PT Photos klasörüne kaydedildi: {file}"},
    {"pc_photo_save_failed","Fotoğraf kaydedilemedi. pt.log dosyasına bakın."},
    {"pc_photo_hint","Oklar / Yön tuşları: seç ve değiştir. P / Kare: fotoğraf. H / Üçgen: paneli gizle. Sağ fare: bak. Esc / Daire: çık."},
    {"pc_note_photo_take","Geçerli görüntüyü Pictures/PT Photos klasörüne kaydeder. Panel asla fotoğrafta görünmez."},
    {"pc_note_photo_fov","Derece cinsinden dikey görüş alanı. Düşük değerler yakınlaştırır."},
    {"pc_note_photo_roll","Eğik bir açı için kamerayı yana yatırır."},
    {"pc_note_photo_speed","Kameranın ne kadar hızlı hareket ettiği. Shift veya L3 yine daha hızlıdır."},
    {"pc_note_photo_reset","Kamerayı fotoğraf modunun başladığı yere döndürür."},
    {"pc_note_photo_dof","Odak mesafesinden yakın veya uzak olanları bulanıklaştırır."},
    {"pc_note_photo_focus","Otomatik, karenin ortasındakine odaklanır."},
    {"pc_note_photo_aperture","Düşük f değerleri daha çok bulanıklaştırır. Otomatik, oyunun kendi lensini korur."},
    {"pc_note_photo_exposure","Görüntüyü yarım durak adımlarla aydınlatır veya karartır."},
    {"pc_note_photo_grain","Orijinal film greni. Kapalıyken görüntü daha temizdir."},
    {"pc_note_photo_grading","Orijinal renk görünümü. Kapalıyken doğal renkler gösterilir."},
    {"pc_note_photo_letterbox","Sinematik siyah şeritler. Fotoğrafın bir parçasıdırlar."},
    {"pc_note_photo_body","Oyuncunun bedenini gösterir veya gizler."},
    {"pc_note_photo_flashlight","Fotoğraf modu sürerken el fenerinin ışığını kapatır."},
    {"pc_archive","Müze"},
    {"pc_note_archive","Oyunun kendi görselleri, sesleri, fotoğraf parçaları, ara sahneleri ve modelleri; oynarken ulaştıkça açılır. Oyunun değişmez."},
    {"pc_note_extras_archive","Döngü tarayıcı, müze, serbest kamera ve fotoğraf modu."},
    {"pc_archive_sections","Salonlar"},
    {"pc_archive_images","Bilinçaltı görüntüler"},
    {"pc_archive_voices","Sesler ve radyo"},
    {"pc_archive_photos","Fotoğraf parçaları"},
    {"pc_archive_cutscenes","Ara sahneler"},
    {"pc_archive_models","Modeller"},
    {"pc_archive_unused","Kullanılmayan içerik"},
    {"pc_note_archive_images","Bilinçaltı parlamaların yazıları, parlamaların paraziti ve gözetleme deliğinden görünüş."},
    {"pc_note_archive_voices","Radyo yayınları ve bütün konuşmalar, altyazı dilindeki dökümleriyle."},
    {"pc_note_archive_photos","Fotoğrafın yırtık parçaları ve çerçevede oluşturdukları fotoğraf."},
    {"pc_note_archive_cutscenes","Her ara sahne baştan, sesi ve altyazılarıyla."},
    {"pc_note_archive_models","Lisa ve koridordaki diğer figürler ve eşyalar, başlangıç odasının ışığında."},
    {"pc_note_archive_unused_section","Oyun dosyalarında bulunan ama oyunun hiç göstermediği içerik. Oyunu bitirince açılır."},
    {"pc_note_archive_image","Enter / Çarpı: tam ekran göster."},
    {"pc_note_archive_voice","Enter / Çarpı: oynat veya durdur."},
    {"pc_note_archive_photo","Enter / Çarpı: tam ekran göster."},
    {"pc_note_archive_demo","Enter / Çarpı: baştan oynat. Esc / Daire durdurur."},
    {"pc_note_archive_model","Enter / Çarpı: modeli göster. Esc / Daire: geri."},
    {"pc_note_archive_unused","Oyunda hiç gösterilmez. Enter / Çarpı: modeli göster."},
    {"pc_note_archive_locked","Kilitli. Açmak için oynarken ona ulaş."},
    {"pc_note_archive_playing","Oynatılıyor. Enter / Çarpı durdurur."},
    {"pc_archive_lock","Müzeyi kilitle"},
    {"pc_note_archive_lock","Müzedeki her eseri oynamadan önceki gibi yeniden kilitler. Kaydın değişmez."},
    {"pc_archive_hint","Enter / X / A: aç"},
    {"pc_archive_view_hint","Sol / Sağ: önceki / sonraki. Esc / Daire: geri."},
    {"pc_archive_demo_hint","Esc / Daire / Enter / Çarpı: durdur"},
    {"pc_archive_model_hint","Oklar / analoglar: döndür. W / S / tetikler: yaklaş / uzaklaş. Esc / Daire: geri."},
    {"pc_archive_sub","Bilinçaltı yazı {1}"},
    {"pc_archive_noise","Parazit"},
    {"pc_archive_noise_normal","Parazit bozulması"},
    {"pc_archive_peephole_mask","Gözetleme deliğinden görünüş"},
    {"pc_archive_radio_news","Radyo: haber yayını"},
    {"pc_archive_radio_news2","Radyo: yayın yeniden"},
    {"pc_archive_radio_voice","Radyo sesi {1}"},
    {"pc_archive_riddle","Radyo bilmecesi {1}"},
    {"pc_archive_sermon","Radyo: vaaz"},
    {"pc_archive_phone","Telefon görüşmesi"},
    {"pc_archive_peephole_voice","Gözetleme deliğinden"},
    {"pc_archive_bag","Konuşan torba"},
    {"pc_archive_fetus","Cenin konuşuyor {1}"},
    {"pc_archive_photo_lisa","Parça: Lisa"},
    {"pc_archive_photo_tree","Parça: ağaç"},
    {"pc_archive_photo_gap","Parça: aralık"},
    {"pc_archive_photo_bath","Parça: banyo"},
    {"pc_archive_photo_stair","Parça: merdiven"},
    {"pc_archive_photo_option","Parça: seçenekler ekranı"},
    {"pc_archive_photo_complete","Tamamlanan fotoğraf"},
    {"pc_archive_preface","Önsöz"},
    {"pc_archive_awakening","İlk uyanış"},
    {"pc_archive_opening","Uyanış"},
    {"pc_archive_first_exit","İlk kapı"},
    {"pc_archive_door","Kapıdan geçiş"},
    {"pc_archive_clock","Gece yarısı"},
    {"pc_archive_kill","Lisa'ya yakalanmak"},
    {"pc_archive_ending","Son"},
    {"pc_archive_teaser","Tanıtım"},
    {"pc_archive_lisa_stand","Lisa, ayakta"},
    {"pc_archive_lisa_walk","Lisa, yürürken"},
    {"pc_archive_lisa_dash","Lisa, saldırırken"},
    {"pc_archive_lisa_door","Kapının ardındaki Lisa"},
    {"pc_archive_baby","Lavabodaki cenin"},
    {"pc_archive_fridge","Buzdolabı"},
    {"pc_archive_bag_model","Kâğıt torba"},
    {"pc_archive_lamp","Tavan lambası"},
    {"pc_archive_roach","Hamamböceği"},
    {"pc_archive_flashlight","El feneri"},
    {"pc_archive_radio","Radyo"},
    {"pc_archive_phone_model","Telefon"},
    {"pc_archive_xmark_photo","X işaretli fotoğraf"},
    {"pc_archive_clock_model","Saat"},
    {"pc_archive_man","Adam"},
    {"pc_archive_bathtub","Küvetteki ceset"},
};
inline std::string_view Menu(std::string_view key) {
    for (const auto& e : kMenu) if(e.key==key) return e.text;
    return {};
}
struct Subtitle { uint32_t key; std::initializer_list<std::string_view> lines; };
inline const Subtitle kSubtitles[] = {
    {0x54E4EFDE,{
        "Kongrede silahlanma düzenlemeleriyle ilgili tartışmalar yeniden alevlenirken,",
        "bir kadın ve iki çocuğunun, eşleri ve babaları tarafından|öldürüldüğünü üzülerek bildiriyoruz.",
        "Baba, suçta kullandığı tüfeği iki gün önce|yakındaki silah mağazasından satın almıştı.",
        "Bu vahşi cinayet, aile pazar öğleden sonra|evde bir aradayken işlendi.",
        "O gün baba, arabasının bagajından tüfeği aldı|ve öğle yemeğinden sonra mutfağı temizleyen eşini vurdu.",
        "On yaşındaki oğlu gürültünün nedenini öğrenmeye|geldiğinde baba onu da vurdu.",
        "Altı yaşındaki kızı banyoya saklandı. Ancak haberlere göre,|baba bunun bir oyun olduğunu söyleyerek onu dışarı çıkardı.",
        "Kız çocuğu, göğsünden yakın mesafede tek kurşunla vurulmuş bulundu.",
        "Karnından vurduğu anne o sırada hamileydi.",
        "Komşuların 911'i araması üzerine gelen polis,|babayı arabasında radyo dinlerken buldu.",
        "Komşular, cinayetlerden birkaç gün önce babanın|bir sayı dizisini yüksek sesle tekrarladığını duyduklarını söylüyor.",
        "Sanki tuhaf bir büyü okuyormuş, dediler.",
        "Geçen ay aynı eyalette başka bir aile de vurularak öldürülmüştü.|Geçen yıl aralık ayında da",
        "bir adam, tüfek ve satır kullanarak tüm ailesini öldürmüştü.",
        "Her olayda failler babalardı.",
        "Eyalet polisi, bu aile cinayetlerinin birbiriyle bağlantılı görünmediğini söylüyor.",
        "Yine de sıradan ailelerin karşılaştığı iş, çocuk bakımı ve|diğer toplumsal sorunlarla ilgili daha büyük bir eğilimin parçası olabilirler."}},
    {0xB91F5727,{"Yürüdüm.","Yürümekten başka bir şey yapamıyordum.","Sonra kendi önümde yürüyen kendimi gördüm.",
        "Ama o gerçekten ben değildim.","Dikkat et.","Kapıdaki aralık... ayrı bir gerçeklik.","Tek ben, benim.","Tek senin, sen olduğundan emin misin?"}},
    {0x72E1954B,{"İşten atıldın, sen de kederini içkiye boğdun.","O, bir marketin kasasında yarı zamanlı işe girmek zorunda kaldı.",
        "Maaş alabilmesinin tek nedeni, müdürün|onu etekle beğenmesiydi.","Hatırlıyorsun, değil mi?","Tam on ay önce."}},
    {0x7D33E7DF,{"Babam çok sıkıcıydı.","Her gün aynı tür yemekleri yer,|aynı şekilde giyinir,","aynı tür oyunların başına otururdu...",
        "Evet, işte öyle bir adamdı.","Ama sonra bir gün, gidip hepimizi öldürdü!","Bunu yapış biçiminde bile özgün olamadı.",
        "Şikâyet etmiyorum... Zaten sıkıntıdan ölüyordum.","Ama tahmin et ne olacak? Geri döneceğim,","ve yeni oyuncaklarımı da getireceğim."}},
    {0xFBCD1565,{"Harekete geçme zamanı.","Toplumumuz tepeden tırnağa çürümüş.","Sosyal yardımı kesilen, işi elinden alınan|bütün düzgün insanlara sesleniyorum.",
        "Evet, sana! Ne yapacağını biliyorsun!","Tam zamanı! Yap şunu!"}},
    {0xDF405E61,{"Seçildin."}},{0x40D69C3A,{"Radyonun ayarıyla oynama, daha yeni başlıyoruz."}},
    {0x0AD16A8E,{"Musluk suyuna güvenemezsin."}},
    {0xC5EB59AA,{"Arkana bak.","Arkana bak dedim."}},
    {0x879FF72D,{"Ailesini öldürdükten sonra baba, garajdaki|bir bahçe hortumuyla kendini astı."}},
    {0x01E674E7,{"204863","204863"}},{0x30DE6EF0,{"Oğlun..."}},
    {0x4926CF3C,{"Onu cennete gönder...|...kendi ellerinle.","Hızlı davranırsan henüz çok geç değil."}},
    {0x7AC3E25E,{"Sen... Ne yaptın?!","Herkesin gözünün önünde!","Bunu haberlere vereceğim, psikopat!","KATİL!"}},
    {0x7980630B,{"Ailesini öldürdükten sonra baba, garajdaki|bir göbek kordonuyla kendini astı."}},
    {0xCE86DEBA,{"Sesimi duyabiliyor musun?|Bu işareti okuyabiliyor musun?|Yeter ki bana gel, sonsuza dek beklerim."}},
    {0x3E6F2ED2,{"Sesimi duyabiliyor musun?|Bu işareti okuyabiliyor musun?"}},
    {0xD925B7BD,{"Sesimi duyabiliyor musun?"}},
    {0x4AF4F3D4,{"Beni affet, Lisa|İçimde bir canavar var"}},{0x4FA7C4BD,{"Cehennemden beni çağırdıklarını duyabiliyorum"}},
    {0xF124B2D3,{"Artık geri dönüş yok"}},
    {0x5D5A2A13,{"Babam çok sıkıcıydı.|Her gün aynı tür yemekleri yer, aynı şekilde giyinir, aynı tür oyunların başına otururdu...|Evet, işte öyle bir adamdı."}},
    {0x3FB2DE6F,{"Evet, sana! Ne yapacağını biliyorsun!","Tam zamanı!","Yap şunu!"}},
    {0xBF6D9A27,{"Radyonun ayarıyla oynama, daha yeni başlıyoruz.","Musluk suyuna güvenemezsin.","204863","Arkana bak.","Arkana bak dedim.","204863"}},
    {0xC52AE206,{"Dikkat et. Kapıdaki aralık...|ayrı bir gerçeklik."}},
    {0xD62FBBDA,{"Tek ben, benim.|Tek senin, sen olduğundan emin misin?"}},
    {0x99242989,{"Bu oyun bir ön gösterimdir.|Ana oyunla doğrudan bağlantısı yoktur."}},
};
}
