# Release support is mandatory on Windows; this file is also exercised by the isolated policy tests.
if(DEFINED PT_UPSCALER_POLICY_WINDOWS)
  set(pt_upscaler_policy_windows ${PT_UPSCALER_POLICY_WINDOWS})
else()
  set(pt_upscaler_policy_windows ${WIN32})
endif()

if(NOT pt_upscaler_policy_windows)
  if(PT_REQUIRE_UPSCALERS)
    message(FATAL_ERROR "PT_REQUIRE_UPSCALERS is only valid for Windows releases")
  endif()
  return()
endif()

set(pt_has_release_config FALSE)
if(CMAKE_CONFIGURATION_TYPES)
  foreach(config IN LISTS CMAKE_CONFIGURATION_TYPES)
    if(NOT config STREQUAL "Debug")
      set(pt_has_release_config TRUE)
    endif()
  endforeach()
elseif(NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(pt_has_release_config TRUE)
endif()

if(pt_has_release_config)
  if(NOT PT_UPSCALERS)
    message(FATAL_ERROR "Windows release builds require PT_UPSCALERS=ON; clear the stale PT_UPSCALERS=OFF cache value")
  endif()
  # A stale OFF cache value must not disable the independent SDK completeness check.
  set(PT_REQUIRE_UPSCALERS ON CACHE BOOL "Require all Windows release upscalers" FORCE)
  set(PT_REQUIRE_UPSCALERS ON)
  message(STATUS "PT_REQUIRE_UPSCALERS=ON for this Windows release configuration")
elseif(PT_REQUIRE_UPSCALERS AND NOT PT_UPSCALERS)
  message(FATAL_ERROR "PT_REQUIRE_UPSCALERS requires PT_UPSCALERS=ON")
endif()
