# Apple Silicon builds keep the executable and resources separate in the shipped .app.
if(NOT APPLE)
  return()
endif()
if(NOT CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  message(FATAL_ERROR "The Apple port currently supports macOS only")
endif()
enable_language(OBJCXX)
set(CMAKE_OBJCXX_STANDARD 20)
set(CMAKE_OBJCXX_STANDARD_REQUIRED ON)
find_library(PT_COCOA_FRAMEWORK Cocoa REQUIRED)
find_file(PT_MOLTENVK_LIBRARY NAMES libMoltenVK.dylib
  HINTS "$ENV{VULKAN_SDK}/lib" "$ENV{VULKAN_SDK}/../MoltenVK/dynamic/dylib/macOS")
if(NOT PT_MOLTENVK_LIBRARY)
  message(FATAL_ERROR "Install the macOS Vulkan SDK with MoltenVK, or set PT_MOLTENVK_LIBRARY to libMoltenVK.dylib")
endif()
if(NOT PT_MOLTENVK_LIBRARY MATCHES "[.]dylib$" OR NOT EXISTS "${PT_MOLTENVK_LIBRARY}")
  message(FATAL_ERROR "PT_MOLTENVK_LIBRARY must name an existing libMoltenVK.dylib, not a static library or framework")
endif()
target_compile_definitions(pt_engine PRIVATE PT_MOLTENVK_LIBRARY="${PT_MOLTENVK_LIBRARY}")
foreach(game pt pt_release)
  set_target_properties(${game} PROPERTIES BUILD_RPATH "@executable_path;@executable_path/../Frameworks")
endforeach()
foreach(game pt pt_release)
  add_custom_command(TARGET ${game} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PT_MOLTENVK_LIBRARY}" "$<TARGET_FILE_DIR:${game}>/libMoltenVK.dylib"
    VERBATIM)
endforeach()
add_executable(pt_setup_macos EXCLUDE_FROM_ALL installer/Native/setup_macos.mm
  src/engine/platform/os.cpp)
target_include_directories(pt_setup_macos PRIVATE src installer/Native "${CMAKE_BINARY_DIR}/generated")
add_dependencies(pt_setup_macos pt_version)
target_compile_options(pt_setup_macos PRIVATE $<$<COMPILE_LANGUAGE:OBJCXX>:-fobjc-arc>)
target_link_libraries(pt_setup_macos PRIVATE zlibstatic ${PT_COCOA_FRAMEWORK} Threads::Threads)
