if(NOT DEFINED EXE OR NOT EXISTS "${EXE}" OR NOT DEFINED OUT)
  message(FATAL_ERROR "upscaler manifest needs an existing EXE and an OUT path")
endif()
file(SHA256 "${EXE}" exe_sha256)
foreach(backend FSR DLSS XeSS Streamline)
  if(${backend})
    set(${backend}_json true)
  else()
    set(${backend}_json false)
  endif()
endforeach()
file(WRITE "${OUT}" "{\n  \"sha256\": \"${exe_sha256}\",\n  \"backends\": {\"FSR\": ${FSR_json}, \"DLSS\": ${DLSS_json}, \"XeSS\": ${XeSS_json}, \"Streamline\": ${Streamline_json}}\n}\n")
